/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIE
 */
public class cie_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setNonBlocking(false);
        faw_23.setStyle("windowBackgroundSecondary");
        fey_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setPrefSize(new fsm_1(100.0f, 56));
        faw_24.setStyle("windowHeaderSmallSecondary");
        fea_12.X(faw_24);
        faw_24.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_24.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setExpandable(false);
        faw_25.setPrefSize(new fsm_1(44, 32));
        faw_24.X(faw_25);
        faw_25.guy();
        faw_25.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("windowTitle");
        String string = "%account.chest.compartment.modification%";
        string = string.replace("%account.chest.compartment.modification%", fyw_0.gqw().k("account.chest.compartment.modification", new Object[0]));
        fbv_22.setText(string);
        faw_24.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(44, 32));
        faw_24.X(faw_26);
        faw_26.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setPrefSize(new fsm_1(32, 32));
        fad_12.setStyle("crossTertiary");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        faw_26.X(fad_12);
        fad_12.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 0, 12));
        fad_12.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLP);
        fad_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_24.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_27);
        }
        faw_27.setPrefSize(new fsm_1(440, 390));
        faw_23.X(faw_27);
        faw_27.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_27.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_27.X(faw_28);
        faw_28.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_28.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_27.X(faw_29);
        faw_29.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_29.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_210.setNonBlocking(false);
        faw_29.X(faw_210);
        faw_210.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_210.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_211 = faw_210;
        fys_0 fys_02 = ((fes_2)faw_211).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_210.X(fys_02);
        fys_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 20, 10, 20));
        fys_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_02.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipLight16");
        String string3 = "%account.chest.compartment.name%";
        string3 = string3.replace("%account.chest.compartment.name%", fyw_0.gqw().k("account.chest.compartment.name", new Object[0]));
        fbv_24.setText(string3);
        faw_210.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string4 = "compartmentName";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.abk(16);
        fdu_12.setMaxWidth(238);
        fdu_12.setMinWidth(1);
        fdu_12.setPrefSize(new fsm_1(0, 12));
        fdu_12.setRestrict("[.*&[^<>]]");
        fdu_12.setStyle("defaultTextEditor");
        faw_210.X(fdu_12);
        fdu_12.guy();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq3 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fdu_12.X(fzq3);
        fzq3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(10, 0, 0, 0));
        fzq3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_212.setPrefSize(new fsm_1(100.0f, -2));
        faw_29.X(faw_212);
        faw_212.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(true);
        faw_212.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_213 = faw_212;
        fys_0 fys_03 = ((fes_2)faw_213).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_212.X(fys_03);
        fys_03.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 20, 0, 20));
        fys_03.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_212.X(faw_214);
        faw_214.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHorizontal(false);
        faw_214.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("wipLight16");
        String string5 = "%account.chest.compartment.color%";
        string5 = string5.replace("%account.chest.compartment.color%", fyw_0.gqw().k("account.chest.compartment.color", new Object[0]));
        fbv_25.setText(string5);
        faw_214.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        String string6 = "compartmentColor";
        fdu_1 fdu_14 = new fdu_1();
        fdu_14.aVI();
        fdu_14.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fdu_14);
        }
        fdu_14.setExpandable(false);
        fdu_14.abk(6);
        fdu_14.setMaxWidth(120);
        fdu_14.setMinWidth(120);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.accountChest:onColorType(compartmentColor)");
        fdu_14.setOnKeyType(fmu_22);
        fdu_14.setPrefSize(new fsm_1(0, 12));
        fdu_14.setRestrict("[0-9a-fA-F]+");
        fdu_14.setStyle("defaultTextEditor");
        faw_214.X(fdu_14);
        fdu_14.guy();
        fdu_1 fdu_15 = fdu_14;
        fzq fzq4 = (fzq)((fes_2)fdu_15).getAppearance();
        fzq4.setElementMap(fhs_23);
        fdu_14.X(fzq4);
        fzq4.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(10, 0, 0, 0));
        fzq4.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdu_14.onChildrenAdded();
        faw_214.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.accountChest:resetColor(compartmentColor)");
        fad_13.setOnClick(fmz_13);
        fad_13.setPrefSize(new fsm_1(36, 36));
        fad_13.setStyle("resetSecondarySmall");
        faw_212.X(fad_13);
        fad_13.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLR);
        fad_13.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 8, 0, 0));
        fad_13.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fad_13.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_212.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        String string7 = "colorPreview";
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, faw_215);
        }
        faw_215.setExpandable(false);
        faw_215.setPrefSize(new fsm_1(45, 45));
        faw_215.setStyle("caracsBorder");
        faw_212.X(faw_215);
        faw_215.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLQ);
        faw_215.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        faw_2 faw_216 = faw_215;
        fys_0 fys_04 = ((fes_2)faw_216).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_215.X(fys_04);
        fys_04.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_23);
        fys_04.X(fkk_12);
        fkk_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("color");
        fsj_22.setLocal(true);
        fsj_22.setName("compartmentColorPreview");
        fkk_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setExpandable(false);
        faw_217.setPrefSize(new fsm_1(80.0f, 150));
        faw_217.setStyle("caracsBackground");
        faw_29.X(faw_217);
        faw_217.guy();
        faw_2 faw_218 = faw_217;
        fys_0 fys_05 = ((fes_2)faw_218).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_217.X(fys_05);
        fys_05.guy();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_23);
        fzv8.setInsets(new Insets(20, 20, 20, 20));
        fys_05.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fzt fzt2 = new fzt();
        fzt2.aVI();
        fzt2.setElementMap(fhs_23);
        fzt2.setInsets(new Insets(5, 5, 5, 5));
        fys_05.X(fzt2);
        fzt2.guy();
        fzt2.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string8 = "compartmentColorPicker";
        faq_2 faq_22 = new faq_2();
        faq_22.aVI();
        faq_22.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, faq_22);
        }
        faq_22.setNeedsScissor(true);
        fmr_1 fmr_12 = new fmr_1();
        fmr_12.vw("wakfu.accountChest:pickCompartmentColor(compartmentColor)");
        faq_22.setOnValueChange(fmr_12);
        faw_217.X(faq_22);
        faq_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("value");
        fsj_23.setLocal(true);
        fsj_23.setName("compartmentColorPickerValue");
        faq_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        faq_22.onChildrenAdded();
        faw_217.onChildrenAdded();
        String string9 = "validateButton";
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        if (fhs_23 != null && string9 != null) {
            fhs_23.a(string9, fad_14);
        }
        fad_14.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.accountChest:validateCompartmentModification(compartmentName,compartmentColor)");
        fad_14.setOnClick(fmz_14);
        fad_14.setPrefSize(new fsm_1(138, 36));
        fad_14.setStyle("primaryMedium");
        String string10 = "%validate%";
        string10 = string10.replace("%validate%", fyw_0.gqw().k("validate", new Object[0]));
        fad_14.setText(string10);
        faw_29.X(fad_14);
        fad_14.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLO);
        fad_14.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fad_14.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        fey_22.X(faw_219);
        faw_219.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        faw_219.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        faw_219.onChildrenAdded();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setResizeOnce(true);
        fey_22.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

