/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIH
 */
public class cih_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.setPrefSize(new fsm_1(500, 300));
        fey_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setExpandable(false);
        faw_22.setNonBlocking(false);
        faw_22.setPrefSize(new fsm_1(18, 100));
        faw_22.setStyle("itemInventoryBarBackground");
        fey_22.X(faw_22);
        faw_22.guy();
        frt_2 frt_22 = new frt_2();
        frt_22.aVI();
        faw_22.X(frt_22);
        frt_22.guy();
        frt_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        faw_22.X(fea_12);
        fea_12.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKw);
        fea_12.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frt_2 frt_23 = new frt_2();
        frt_23.aVI();
        fea_12.X(frt_23);
        frt_23.guy();
        frt_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setOrientation(fzu_0.tKC);
        fbv_22.setStyle("bold");
        fbv_22.setText("Editeur de couleur de personnage");
        fea_12.X(fbv_22);
        fbv_22.guy();
        fru_1 fru_13 = fru_1.checkOut();
        fru_13.setElementMap(fhs_23);
        fru_13.setData(fzt_0.tKw);
        fbv_22.X(fru_13);
        fru_13.guy();
        fru_13.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 20, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("closeWindow");
        fea_12.X(fad_12);
        fad_12.guy();
        fru_1 fru_14 = fru_1.checkOut();
        fru_14.setElementMap(fhs_23);
        fru_14.setData(fzt_0.tKx);
        fad_12.X(fru_14);
        fru_14.guy();
        fru_14.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(10, 0, 0, 0));
        fym_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setNonBlocking(false);
        faw_23.setStyle("brownInventoryBackground");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(15, 5, 10, 7));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("whiteTitle");
        fbv_24.setText("\u00c9dition des couleurs");
        faw_25.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_25.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        fad_14.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.adminCharacterEditor:openCharacterColorEditor");
        fad_14.setOnClick(fmz_13);
        fad_14.setText("\u00c9diter les caracs");
        faw_25.X(fad_14);
        fad_14.guy();
        fad_1 fad_15 = fad_14;
        fym_0 fym_03 = (fym_0)((fes_2)fad_15).getAppearance();
        fym_03.setElementMap(fhs_23);
        fad_14.X(fym_03);
        fym_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(2, 10, 2, 10));
        fym_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 10));
        fym_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fym_03.onChildrenAdded();
        fad_14.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_23.X(faw_26);
        faw_26.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLN);
        faw_26.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        faw_26.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("whiteBold");
        fbv_25.setText("Ajouter une Part \u00e0 coloriser ");
        faw_26.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        String string = "comboColor";
        fas_1 fas_12 = new fas_1();
        fas_12.aVI();
        fas_12.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fas_12);
        }
        fas_12.setExpandable(false);
        fas_12.setPrefSize(new fsm_1(150, 15));
        faw_26.X(fas_12);
        fas_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("content");
        fsj_22.setName("adminInactiveColors");
        fas_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fcv_1 fcv_12 = new fcv_1();
        fcv_12.aVI();
        fcv_12.setElementMap(fhs_23);
        fas_12.X(fcv_12);
        fcv_12.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fcv_12.X(fje_22);
        fje_22.guy();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        fje_22.X(faw_27);
        faw_27.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_27.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setNonBlocking(true);
        faw_27.X(fbv_26);
        fbv_26.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        fbv_26.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fbv_26.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_27.onChildrenAdded();
        fje_22.onChildrenAdded();
        fcv_12.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(100.0f, 16));
        fbz_22.setHorizontal(false);
        fas_12.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fbz_22.X(fje_23);
        fje_23.guy();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        fje_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_03 = ((fes_2)faw_29).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_28.X(fys_03);
        fys_03.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 10, 0, 0));
        fys_03.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_28.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setExpandable(false);
        fbv_27.setNonBlocking(true);
        faw_28.X(fbv_27);
        fbv_27.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLO);
        fbv_27.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fsd_13.setField("name");
        fbv_27.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_27.onChildrenAdded();
        faw_28.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_22.onChildrenAdded();
        fas_12.onChildrenAdded();
        fad_1 fad_16 = new fad_1();
        fad_16.aVI();
        fad_16.setElementMap(fhs_23);
        fad_16.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.adminCharacterEditor:activateColor");
        fad_16.setOnClick(fmz_14);
        fad_16.setStyle("smallValid");
        faw_26.X(fad_16);
        fad_16.guy();
        fad_16.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_210.setPrefSize(new fsm_1(0, 7));
        faw_210.setStyle("lineSeparator");
        faw_23.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_210;
        fys_0 fys_04 = ((fes_2)faw_211).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_210.X(fys_04);
        fys_04.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(5, 0, 2, 0));
        fys_04.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_23.X(faw_212);
        faw_212.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        faw_212.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setExpandable(false);
        fcq_22.setPrefSize(new fsm_1(350, 600));
        faw_212.X(fcq_22);
        fcq_22.guy();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        fdf_12.setHorizontal(false);
        fcq_22.X(fdf_12);
        fdf_12.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLN);
        fdf_12.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setName("adminColors");
        fdf_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLL);
        frz_27.setHorizontal(false);
        fdf_12.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fje_2 fje_24 = new fje_2();
        fje_24.aVI();
        fje_24.setElementMap(fhs_23);
        fdf_12.X(fje_24);
        fje_24.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLN);
        fje_24.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_213.setPrefSize(new fsm_1(290, 0));
        fje_24.X(faw_213);
        faw_213.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLL);
        frz_28.setHorizontal(false);
        faw_213.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setExpandable(false);
        faw_213.X(faw_214);
        faw_214.guy();
        String string2 = "color";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, frv_12);
        }
        faw_214.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("value");
        frv_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        frv_12.onChildrenAdded();
        frz_2 frz_29 = frz_2.checkOut();
        frz_29.setAlign(faa_2.tLL);
        frz_29.setHorizontal(false);
        faw_214.X(frz_29);
        frz_29.guy();
        frz_29.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_214.X(faw_215);
        faw_215.guy();
        frz_2 frz_210 = frz_2.checkOut();
        frz_210.setAlign(faa_2.tLN);
        faw_215.X(frz_210);
        frz_210.guy();
        frz_210.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setExpandable(false);
        fbv_28.setStyle("whiteBold");
        faw_215.X(fbv_28);
        fbv_28.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("text");
        fsd_15.setField("name");
        fbv_28.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_28.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_23);
        fbv_29.setExpandable(false);
        fbv_29.setStyle("whiteBold");
        String string3 = "%colon%";
        string3 = string3.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fbv_29.setText(string3);
        faw_215.X(fbv_29);
        fbv_29.guy();
        fbv_29.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setPrefSize(new fsm_1(150, 0));
        fdy_12.setSelectable(true);
        fdy_12.setStyle("whiteBold");
        faw_215.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("text");
        fsd_16.setField("floatString");
        fdy_12.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fdy_12.onChildrenAdded();
        this.R(faw_215);
        this.c(faw_215);
        faw_215.onChildrenAdded();
        this.d(faw_214);
        this.e(faw_214);
        this.F(faw_214);
        faw_214.onChildrenAdded();
        this.G(faw_213);
        faw_213.onChildrenAdded();
        fje_24.onChildrenAdded();
        fdf_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        this.f(faw_212);
        faw_212.onChildrenAdded();
        faw_23.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_22.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        return fde_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.adminCharacterEditor:deleteActiveColor(color)");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("closeWindow");
        faw_22.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(5, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setPrefSize(new fsm_1(50, 0));
        fbv_22.setStyle("whiteBold");
        String string = "%red%";
        string = string.replace("%red%", fyw_0.gqw().k("red", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("whiteBold");
        fbv_23.setText("0");
        faw_23.X(fbv_23);
        fbv_23.guy();
        fbv_23.onChildrenAdded();
        fcz_2 fcz_22 = new fcz_2();
        fcz_22.aVI();
        fcz_22.setElementMap(fhs_22);
        fcz_22.setExpandable(false);
        fcz_22.setHorizontal(true);
        fmp_2 fmp_22 = new fmp_2();
        fmp_22.vw("wakfu.adminCharacterEditor:setFilterRed(color)");
        fcz_22.setOnSliderMove(fmp_22);
        fcz_22.setPrefSize(new fsm_1(100, 0));
        fcz_22.setStyle("volume");
        faw_23.X(fcz_22);
        fcz_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        fsd_12.setField("red");
        fcz_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fcz_2 fcz_23 = fcz_22;
        fys_0 fys_03 = ((fes_2)fcz_23).getAppearance();
        fys_03.setElementMap(fhs_22);
        fcz_22.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 5, 0, 5));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        fcz_22.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("whiteBold");
        fbv_24.setText("100%");
        faw_23.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string2 = "redTextEditor";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.abk(3);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.adminCharacterEditor:setFilterRed(redTextEditor,color)");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setPrefSize(new fsm_1(25, 15));
        fdu_12.setRestrict("[0-9]+");
        faw_23.X(fdu_12);
        fdu_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("red255");
        fdu_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq2 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLP);
        fdu_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdu_1 fdu_14 = fdu_12;
        fzq fzq3 = (fzq)((fes_2)fdu_14).getAppearance();
        fzq3.setElementMap(fhs_22);
        fdu_12.X(fzq3);
        fzq3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 5, 0, 0));
        fzq3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setPrefSize(new fsm_1(50, 0));
        fbv_22.setStyle("whiteBold");
        String string = "%green%";
        string = string.replace("%green%", fyw_0.gqw().k("green", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("whiteBold");
        fbv_23.setText("0");
        faw_23.X(fbv_23);
        fbv_23.guy();
        fbv_23.onChildrenAdded();
        fcz_2 fcz_22 = new fcz_2();
        fcz_22.aVI();
        fcz_22.setElementMap(fhs_22);
        fcz_22.setExpandable(false);
        fcz_22.setHorizontal(true);
        fmp_2 fmp_22 = new fmp_2();
        fmp_22.vw("wakfu.adminCharacterEditor:setFilterGreen(color)");
        fcz_22.setOnSliderMove(fmp_22);
        fcz_22.setPrefSize(new fsm_1(100, 0));
        fcz_22.setStyle("volume");
        faw_23.X(fcz_22);
        fcz_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        fsd_12.setField("green");
        fcz_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fcz_2 fcz_23 = fcz_22;
        fys_0 fys_02 = ((fes_2)fcz_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        fcz_22.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 5));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fcz_22.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("whiteBold");
        fbv_24.setText("100%");
        faw_23.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string2 = "greenTextEditor";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.abk(3);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.adminCharacterEditor:setFilterGreen(greenTextEditor,color)");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setPrefSize(new fsm_1(25, 15));
        fdu_12.setRestrict("[0-9]+");
        faw_23.X(fdu_12);
        fdu_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("green255");
        fdu_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq2 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLP);
        fdu_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdu_1 fdu_14 = fdu_12;
        fzq fzq3 = (fzq)((fes_2)fdu_14).getAppearance();
        fzq3.setElementMap(fhs_22);
        fdu_12.X(fzq3);
        fzq3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 5, 0, 0));
        fzq3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setPrefSize(new fsm_1(50, 0));
        fbv_22.setStyle("whiteBold");
        String string = "%blue%";
        string = string.replace("%blue%", fyw_0.gqw().k("blue", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("whiteBold");
        fbv_23.setText("0");
        faw_23.X(fbv_23);
        fbv_23.guy();
        fbv_23.onChildrenAdded();
        fcz_2 fcz_22 = new fcz_2();
        fcz_22.aVI();
        fcz_22.setElementMap(fhs_22);
        fcz_22.setExpandable(false);
        fcz_22.setHorizontal(true);
        fmp_2 fmp_22 = new fmp_2();
        fmp_22.vw("wakfu.adminCharacterEditor:setFilterBlue(color)");
        fcz_22.setOnSliderMove(fmp_22);
        fcz_22.setPrefSize(new fsm_1(100, 0));
        fcz_22.setStyle("volume");
        faw_23.X(fcz_22);
        fcz_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        fsd_12.setField("blue");
        fcz_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fcz_2 fcz_23 = fcz_22;
        fys_0 fys_02 = ((fes_2)fcz_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        fcz_22.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 5));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fcz_22.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("whiteBold");
        fbv_24.setText("100%");
        faw_23.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string2 = "blueTextEditor";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.abk(3);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.adminCharacterEditor:setFilterBlue(blueTextEditor,color)");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setPrefSize(new fsm_1(25, 15));
        fdu_12.setRestrict("[0-9]+");
        faw_23.X(fdu_12);
        fdu_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("blue255");
        fdu_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq2 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLP);
        fdu_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdu_1 fdu_14 = fdu_12;
        fzq fzq3 = (fzq)((fes_2)fdu_14).getAppearance();
        fzq3.setElementMap(fhs_22);
        fdu_12.X(fzq3);
        fzq3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 5, 0, 0));
        fzq3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(0, 7));
        faw_23.setStyle("lineSeparator");
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(5, 0, 2, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new awx_2(0.0f, 0.0f, 0.0f, 1.0f));
        fkm_12.setInsets(new Insets(0, 1, 0, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.adminCharacterEditor:loadAnmDebugger");
        fad_12.setOnClick(fmz_12);
        fad_12.setText("Anm Debugger");
        faw_25.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.adminCharacterEditor:reloadAnmimation");
        fad_13.setOnClick(fmz_13);
        fad_13.setText("Reload Anm");
        faw_25.X(fad_13);
        fad_13.guy();
        fad_13.onChildrenAdded();
        faw_25.onChildrenAdded();
        String string = "localPlayerDisplay";
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fax_12);
        }
        fax_12.setExpandable(false);
        fax_12.setOffsetY(-200.0f);
        fax_12.setPrefSize(new fsm_1(100, 0));
        fax_12.setScale(2.0f);
        faw_23.X(fax_12);
        fax_12.guy();
        fax_1 fax_13 = fax_12;
        fyk_0 fyk_02 = (fyk_0)((fes_2)fax_13).getAppearance();
        fyk_02.setElementMap(fhs_22);
        fax_12.X(fyk_02);
        fyk_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 30, 0, 0));
        fyk_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fyk_02.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("animatedElement");
        fsj_22.setField("actorDescriptorLibrary");
        fsj_22.setName("localPlayer");
        fax_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("equipment");
        fsj_23.setField("actorEquipment");
        fsj_23.setName("localPlayer");
        fax_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("direction");
        fsj_24.setName("adminAnimDirection");
        fax_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("animName");
        fsj_25.setName("adminAnimName");
        fax_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }
}

