/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cII
 */
public class cii_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPrefSize(new fsm_1(800, 300));
        fey_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setExpandable(false);
        faw_22.setNonBlocking(false);
        faw_22.setPrefSize(new fsm_1(18, 100));
        faw_22.setStyle("itemInventoryBarBackground");
        fey_22.X(faw_22);
        faw_22.guy();
        frt_2 frt_22 = new frt_2();
        frt_22.aVI();
        faw_22.X(frt_22);
        frt_22.guy();
        frt_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        faw_22.X(fea_12);
        fea_12.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKw);
        fea_12.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frt_2 frt_23 = new frt_2();
        frt_23.aVI();
        fea_12.X(frt_23);
        frt_23.guy();
        frt_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setOrientation(fzu_0.tKC);
        fbv_22.setStyle("bold");
        fbv_22.setText("Editeur de personnage");
        fea_12.X(fbv_22);
        fbv_22.guy();
        fru_1 fru_13 = fru_1.checkOut();
        fru_13.setElementMap(fhs_23);
        fru_13.setData(fzt_0.tKw);
        fbv_22.X(fru_13);
        fru_13.guy();
        fru_13.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 20, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("smallDelete");
        fea_12.X(fad_12);
        fad_12.guy();
        fru_1 fru_14 = fru_1.checkOut();
        fru_14.setElementMap(fhs_23);
        fru_14.setData(fzt_0.tKx);
        fad_12.X(fru_14);
        fru_14.guy();
        fru_14.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(10, 0, 0, 0));
        fym_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setNonBlocking(false);
        faw_23.setStyle("brownInventoryBackground");
        fey_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(15, 5, 10, 7));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_25.X(faw_26);
        faw_26.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_26.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("whiteTitle");
        String string = "Niveau du personnage%colon%";
        string = string.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fbv_24.setText(string);
        faw_26.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string2 = "level";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.setPrefSize(new fsm_1(150, 0));
        fdu_12.setRestrict("[0-9]+");
        fdu_12.setStyle("dark");
        faw_26.X(fdu_12);
        fdu_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("level");
        fsj_22.setName("localPlayer");
        fdu_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdu_12.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        fad_14.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.adminCharacterEditor:validLevel");
        fad_14.setOnClick(fmz_13);
        fad_14.setStyle("smallValid");
        faw_26.X(fad_14);
        fad_14.guy();
        fad_14.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_26.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fad_1 fad_15 = new fad_1();
        fad_15.aVI();
        fad_15.setElementMap(fhs_23);
        fad_15.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.adminCharacterEditor:openCharacterColorEditor");
        fad_15.setOnClick(fmz_14);
        fad_15.setText("\u00c9diter les couleurs");
        faw_26.X(fad_15);
        fad_15.guy();
        fad_1 fad_16 = fad_15;
        fym_0 fym_03 = (fym_0)((fes_2)fad_16).getAppearance();
        fym_03.setElementMap(fhs_23);
        fad_15.X(fym_03);
        fym_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(2, 10, 2, 10));
        fym_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 10));
        fym_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fym_03.onChildrenAdded();
        fad_15.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(0, 7));
        faw_27.setStyle("lineSeparator");
        faw_25.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_27.X(fys_03);
        fys_03.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(5, 0, 2, 0));
        fys_03.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_27.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("whiteTitle");
        fbv_25.setText("Sorts (setLevel) :");
        faw_25.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(350, 25));
        fbz_22.setExpandable(false);
        fbz_22.setHorizontal(false);
        fbz_22.setPrefSize(new fsm_1(350, 150));
        faw_25.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setName("spellsList");
        fbz_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string3 = "spell";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        fje_22.X(faw_29);
        faw_29.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_29.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(26, 26));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setPrefSize(new fsm_1(39, 0));
        fbt_12.setScaled(false);
        faw_29.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("texture");
        fsd_13.setField("smallIconUrl");
        fze2.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setPrefSize(new fsm_1(200, 0));
        fbv_26.setStyle("whiteBold");
        faw_29.X(fbv_26);
        fbv_26.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fbv_26.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_26.onChildrenAdded();
        String string4 = "spellLevelEditor";
        fdu_1 fdu_13 = new fdu_1();
        fdu_13.aVI();
        fdu_13.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdu_13);
        }
        fdu_13.setExpandable(false);
        fdu_13.setPrefSize(new fsm_1(50, 0));
        fdu_13.setRestrict("[0-9]+");
        fdu_13.setStyle("dark");
        faw_29.X(fdu_13);
        fdu_13.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("text");
        fsd_15.setField("level");
        fdu_13.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fdu_13.onChildrenAdded();
        fad_1 fad_17 = new fad_1();
        fad_17.aVI();
        fad_17.setElementMap(fhs_23);
        fad_17.setExpandable(false);
        fmz_1 fmz_15 = new fmz_1();
        fmz_15.vw("wakfu.adminCharacterEditor:validSpellLevel(spell,spellLevelEditor)");
        fad_17.setOnClick(fmz_15);
        fad_17.setStyle("smallValid");
        faw_29.X(fad_17);
        fad_17.guy();
        fad_17.onChildrenAdded();
        faw_29.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_210.setPrefSize(new fsm_1(0, 7));
        faw_210.setStyle("lineSeparator");
        faw_25.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_210;
        fys_0 fys_04 = ((fes_2)faw_211).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_210.X(fys_04);
        fys_04.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(5, 0, 2, 0));
        fys_04.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_210.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setExpandable(false);
        fbv_27.setStyle("whiteTitle");
        fbv_27.setText("Skills \u00e0 apprendre :");
        faw_25.X(fbv_27);
        fbv_27.guy();
        fbv_27.onChildrenAdded();
        fbz_2 fbz_23 = new fbz_2();
        fbz_23.aVI();
        fbz_23.setElementMap(fhs_23);
        fbz_23.setCellSize(new fsm_1(350, 25));
        fbz_23.setExpandable(false);
        fbz_23.setHorizontal(false);
        fbz_23.setPrefSize(new fsm_1(350, 100));
        faw_25.X(fbz_23);
        fbz_23.guy();
        fbz_2 fbz_24 = fbz_23;
        fza fza2 = (fza)((fes_2)fbz_24).getAppearance();
        fza2.setElementMap(fhs_23);
        fbz_23.X(fza2);
        fza2.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 0, 10, 0));
        fza2.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fza2.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("content");
        fsj_24.setName("craftSkillsList");
        fbz_23.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fbz_23.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_23);
        fjt_23.X(fjx_13);
        fjx_13.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_23);
        fjx_13.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        String string5 = "skill";
        frv_1 frv_13 = new frv_1();
        frv_13.aVI();
        frv_13.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, frv_13);
        }
        fje_23.X(frv_13);
        frv_13.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("value");
        frv_13.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        frv_13.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        fje_23.X(faw_212);
        faw_212.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_212.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        this.R(faw_212);
        this.c(faw_212);
        faw_212.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_23.onChildrenAdded();
        this.d(faw_25);
        this.e(faw_25);
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.adminCharacterEditor:learnSkill(skill)");
        fad_12.setOnClick(fmz_12);
        faw_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(5, 5, 5, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(26, 26));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setPrefSize(new fsm_1(30, 0));
        fbt_12.setScaled(false);
        faw_23.X(fbt_12);
        fbt_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("style");
        fsd_12.setField("craftIcon");
        fbt_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setNonBlocking(true);
        fbv_22.setPrefSize(new fsm_1(200, 0));
        fbv_22.setStyle("bold");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("name");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("whiteTitle");
        fbv_22.setText("Skills (addXp) :");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setCellSize(new fsm_1(360, 25));
        fbz_22.setExpandable(false);
        fbz_22.setHorizontal(false);
        fbz_22.setPrefSize(new fsm_1(360, 100));
        faw_22.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("craft/allKnownCrafts");
        fsj_22.setName("localPlayer");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjn_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjx_13.setField("isUnknown");
        fjn_22.X(fjx_13);
        fjx_13.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjx_13.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string = "skill";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        fje_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(26, 26));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setPrefSize(new fsm_1(30, 0));
        fbt_12.setScaled(false);
        faw_23.X(fbt_12);
        fbt_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("style");
        fsd_13.setField("craftIcon");
        fbt_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fyY2.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new awx_2(0.2f, 0.2f, 0.2f, 1.0f));
        fkm_12.setInsets(new Insets(1, 1, 1, 1));
        fyY2.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 0, 9));
        fyY2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setPrefSize(new fsm_1(180, 0));
        fbv_22.setStyle("whiteBold");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fbv_22.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setPrefSize(new fsm_1(50, 0));
        fbv_23.setStyle("whiteBold");
        faw_23.X(fbv_23);
        fbv_23.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("levelText");
        fbv_23.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_23.onChildrenAdded();
        String string2 = "skillXpEditor";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.setPrefSize(new fsm_1(50, 0));
        fdu_12.setRestrict("[0-9]+");
        fdu_12.setStyle("dark");
        fdu_12.setText("0");
        faw_23.X(fdu_12);
        fdu_12.guy();
        fdu_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.adminCharacterEditor:addSkillXp(skill,skillXpEditor)");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("smallValid");
        faw_23.X(fad_12);
        fad_12.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("enabled");
        fsd_16.setField("isConceptual");
        fad_12.X(fsd_16);
        fsd_16.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsd_16.X(fjt_23);
        fjt_23.guy();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_22);
        fjt_23.X(fjw_23);
        fjw_23.guy();
        fjw_23.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_16.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        return fbz_22;
    }
}

