/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIK
 */
public class cik_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "equipInventWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tKY);
        frp_13.setInitValue(true);
        frp_13.setSize(new fsm_1(370, 320));
        frp_13.setXOffset(100);
        frp_13.setYOffset(-100);
        fey_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setNonBlocking(false);
        faw_22.setStyle("windowBackgroundSecondary");
        fey_22.X(faw_22);
        faw_22.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(8, 0, 0, 0));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setPrefSize(new fsm_1(360, 310));
        faw_22.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 8, 8));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        fea_12.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setExpandable(false);
        fea_12.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setStyle("wipTitleLight20");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("worldname");
        fsj_22.setName("statistics");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLa);
        fbv_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(24, 24));
        fad_12.setStyle("crossTertiary");
        faw_24.X(fad_12);
        fad_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLc);
        fad_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        fea_12.X(faw_25);
        faw_25.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_25.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(8, 8, 0, 0));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_27.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipLight14Bold");
        fbv_24.setText("Total players : ");
        faw_27.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("wipLight14");
        faw_27.X(fbv_25);
        fbv_25.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("total");
        fsj_23.setName("statistics");
        fbv_25.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_25.X(faw_28);
        faw_28.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        faw_28.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setStyle("wipLight14Bold");
        fbv_26.setText("Total heroes : ");
        faw_28.X(fbv_26);
        fbv_26.guy();
        fbv_26.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setExpandable(false);
        fbv_27.setStyle("wipLight14");
        faw_28.X(fbv_27);
        fbv_27.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("heroes");
        fsj_24.setName("statistics");
        fbv_27.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fbv_27.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setExpandable(false);
        faw_25.X(faw_29);
        faw_29.guy();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLN);
        faw_29.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setExpandable(false);
        fbv_28.setStyle("wipLight14Bold");
        fbv_28.setText("Admins : ");
        faw_29.X(fbv_28);
        fbv_28.guy();
        fbv_28.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_23);
        fbv_29.setExpandable(false);
        fbv_29.setStyle("wipLight14");
        faw_29.X(fbv_29);
        fbv_29.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("admins");
        fsj_25.setName("statistics");
        fbv_29.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fbv_29.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_25.X(faw_210);
        faw_210.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLL);
        frz_28.setHorizontal(false);
        faw_210.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        fbv_2 fbv_210 = new fbv_2();
        fbv_210.aVI();
        fbv_210.setElementMap(fhs_23);
        fbv_210.setExpandable(false);
        fbv_210.setStyle("wipLight14Bold");
        fbv_210.setText("Subscriptions (and heroes) : ");
        faw_210.X(fbv_210);
        fbv_210.guy();
        fbv_210.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("wipLight14");
        faw_210.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("text");
        fsj_26.setField("subscriptions");
        fsj_26.setName("statistics");
        fdy_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_25.X(faw_211);
        faw_211.guy();
        frz_2 frz_29 = frz_2.checkOut();
        frz_29.setAlign(faa_2.tLN);
        faw_211.X(frz_29);
        frz_29.guy();
        frz_29.onChildrenAdded();
        fbv_2 fbv_211 = new fbv_2();
        fbv_211.aVI();
        fbv_211.setElementMap(fhs_23);
        fbv_211.setExpandable(false);
        fbv_211.setStyle("wipLight14Bold");
        fbv_211.setText("Accounts in EquipmentManager : ");
        faw_211.X(fbv_211);
        fbv_211.guy();
        fbv_211.onChildrenAdded();
        fbv_2 fbv_212 = new fbv_2();
        fbv_212.aVI();
        fbv_212.setElementMap(fhs_23);
        fbv_212.setExpandable(false);
        fbv_212.setStyle("wipLight14");
        faw_211.X(fbv_212);
        fbv_212.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("text");
        fsj_27.setField("accountInventories");
        fsj_27.setName("statistics");
        fbv_212.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fbv_212.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_25.X(faw_212);
        faw_212.guy();
        frz_2 frz_210 = frz_2.checkOut();
        frz_210.setAlign(faa_2.tLN);
        faw_212.X(frz_210);
        frz_210.guy();
        frz_210.onChildrenAdded();
        fbv_2 fbv_213 = new fbv_2();
        fbv_213.aVI();
        fbv_213.setElementMap(fhs_23);
        fbv_213.setExpandable(false);
        fbv_213.setStyle("wipLight14Bold");
        fbv_213.setText("Total inventories in EquipmentManager : ");
        faw_212.X(fbv_213);
        fbv_213.guy();
        fbv_213.onChildrenAdded();
        fbv_2 fbv_214 = new fbv_2();
        fbv_214.aVI();
        fbv_214.setElementMap(fhs_23);
        fbv_214.setExpandable(false);
        fbv_214.setStyle("wipLight14");
        faw_212.X(fbv_214);
        fbv_214.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("text");
        fsj_28.setField("characterInventories");
        fsj_28.setName("statistics");
        fbv_214.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fbv_214.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_25.X(faw_213);
        faw_213.guy();
        frz_2 frz_211 = frz_2.checkOut();
        frz_211.setAlign(faa_2.tLN);
        faw_213.X(frz_211);
        frz_211.guy();
        frz_211.onChildrenAdded();
        fbv_2 fbv_215 = new fbv_2();
        fbv_215.aVI();
        fbv_215.setElementMap(fhs_23);
        fbv_215.setExpandable(false);
        fbv_215.setStyle("wipLight14Bold");
        fbv_215.setText("Accounts in GameAccountDataManager : ");
        faw_213.X(fbv_215);
        fbv_215.guy();
        fbv_215.onChildrenAdded();
        fbv_2 fbv_216 = new fbv_2();
        fbv_216.aVI();
        fbv_216.setElementMap(fhs_23);
        fbv_216.setExpandable(false);
        fbv_216.setStyle("wipLight14");
        faw_213.X(fbv_216);
        fbv_216.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("text");
        fsj_29.setField("gamesAccountData");
        fsj_29.setName("statistics");
        fbv_216.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fbv_216.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

