/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIL
 */
public class cil_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "adminTranslatorWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fys_02.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setNonBlocking(false);
        faw_24.setStyle("windowBackgroundRepeated");
        fey_22.X(faw_24);
        faw_24.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_24.X(fea_12);
        fea_12.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setPrefSize(new fsm_1(100.0f, 56));
        faw_25.setStyle("WindowHeaderMedium");
        fea_12.X(faw_25);
        faw_25.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_25.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_26);
        faw_26.guy();
        faw_26.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("windowTitle");
        fbv_22.setText("Admin Text Formatting");
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(44, 32));
        faw_27.setVisible(false);
        faw_25.X(faw_27);
        faw_27.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setPrefSize(new fsm_1(32, 32));
        fad_12.setStyle("unknownTertiary");
        faw_27.X(fad_12);
        fad_12.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 0, 12));
        fad_12.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLP);
        fad_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_28.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_28);
        faw_28.guy();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fad_13.setPrefSize(new fsm_1(32, 32));
        fad_13.setStyle("crossTertiary");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_13.setOnClick(fmz_12);
        faw_28.X(fad_13);
        fad_13.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 12));
        fad_13.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLP);
        fad_13.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_29);
        }
        faw_29.setPrefSize(new fsm_1(640, 584));
        faw_24.X(faw_29);
        faw_29.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_29.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_29.X(faw_210);
        faw_210.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_210.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_29.X(faw_211);
        faw_211.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_211.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_212 = faw_211;
        fys_0 fys_03 = ((fes_2)faw_212).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_211.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(16, 16, 16, 16));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_211.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        String string3 = "textFormatting";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frv_12);
        }
        faw_211.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("value");
        fsj_22.setName("adminTextFormatting");
        frv_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_213.setStyle("ContentContainer1");
        faw_211.X(faw_213);
        faw_213.guy();
        faw_2 faw_214 = faw_213;
        fys_0 fys_04 = ((fes_2)faw_214).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_213.X(fys_04);
        fys_04.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(8, 8, 8, 8));
        fys_04.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        frz_24.setVgap((short)8);
        faw_213.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_213.X(faw_215);
        faw_215.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        frz_25.setHgap((short)4);
        faw_215.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        fad_14.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.adminTextFormatting:clearInputText(textFormatting)");
        fad_14.setOnClick(fmz_13);
        fad_14.setStyle("crossTertiary2");
        faw_215.X(fad_14);
        fad_14.guy();
        fad_1 fad_15 = fad_14;
        fym_0 fym_02 = (fym_0)((fes_2)fad_15).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_14.X(fym_02);
        fym_02.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(4, 0, 0, 0));
        fym_02.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_14.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipTitleLight18");
        fbv_24.setText("Text");
        faw_215.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        faw_215.onChildrenAdded();
        String string4 = "inputTE";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdu_12);
        }
        fdu_12.setMultiline(true);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.adminTextFormatting:onKeyTyped(inputTE,parametersTE,textFormatting)");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setPrefSize(new fsm_1(100.0f, 180));
        fdu_12.setStyle("defaultTextEditor");
        faw_213.X(fdu_12);
        fdu_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("inputText");
        fsj_23.setName("adminTextFormatting");
        fdu_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_216.setStyle("ContentContainer1");
        faw_211.X(faw_216);
        faw_216.guy();
        faw_2 faw_217 = faw_216;
        fys_0 fys_05 = ((fes_2)faw_217).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_216.X(fys_05);
        fys_05.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(8, 8, 8, 8));
        fys_05.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fys_05.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHorizontal(false);
        frz_26.setVgap((short)8);
        faw_216.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setExpandable(false);
        faw_216.X(faw_218);
        faw_218.guy();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLN);
        frz_27.setHgap((short)4);
        faw_218.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fad_1 fad_16 = new fad_1();
        fad_16.aVI();
        fad_16.setElementMap(fhs_23);
        fad_16.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.adminTextFormatting:clearParameters(textFormatting)");
        fad_16.setOnClick(fmz_14);
        fad_16.setStyle("crossTertiary2");
        faw_218.X(fad_16);
        fad_16.guy();
        fad_1 fad_17 = fad_16;
        fym_0 fym_03 = (fym_0)((fes_2)fad_17).getAppearance();
        fym_03.setElementMap(fhs_23);
        fad_16.X(fym_03);
        fym_03.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(4, 0, 0, 0));
        fym_03.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fym_03.onChildrenAdded();
        fad_16.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("wipTitleLight18");
        fbv_25.setText("Parameters (separated by ;, escapable with \\;)");
        faw_218.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        faw_218.onChildrenAdded();
        String string5 = "parametersTE";
        fdu_1 fdu_13 = new fdu_1();
        fdu_13.aVI();
        fdu_13.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fdu_13);
        }
        fdu_13.setMultiline(true);
        fmu_2 fmu_23 = new fmu_2();
        fmu_23.vw("wakfu.adminTextFormatting:onKeyTyped(inputTE,parametersTE,textFormatting)");
        fdu_13.setOnKeyType(fmu_23);
        fdu_13.setPrefSize(new fsm_1(100.0f, 50));
        fdu_13.setStyle("defaultTextEditor");
        faw_216.X(fdu_13);
        fdu_13.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("parameters");
        fsj_24.setName("adminTextFormatting");
        fdu_13.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdu_13.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_219.setExpandable(false);
        faw_219.setStyle("ContentContainer1");
        faw_211.X(faw_219);
        faw_219.guy();
        faw_2 faw_220 = faw_219;
        fys_0 fys_06 = ((fes_2)faw_220).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_219.X(fys_06);
        fys_06.guy();
        fzx fzx6 = new fzx();
        fzx6.aVI();
        fzx6.setElementMap(fhs_23);
        fzx6.setInsets(new Insets(8, 8, 8, 8));
        fys_06.X(fzx6);
        fzx6.guy();
        fzx6.onChildrenAdded();
        fys_06.onChildrenAdded();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLK);
        frz_28.setHorizontal(false);
        frz_28.setVgap((short)8);
        faw_219.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setStyle("wipTitleLight18");
        fbv_26.setText("Result");
        faw_219.X(fbv_26);
        fbv_26.guy();
        fbv_26.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setMultiline(true);
        fdy_12.setPrefSize(new fsm_1(100.0f, 150));
        fdy_12.setStyle("wipLight14");
        faw_219.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLK);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("outputText");
        fsj_25.setName("adminTextFormatting");
        fdy_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_219.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_221 = faw_2.checkOut();
        faw_221.setElementMap(fhs_23);
        fey_22.X(faw_221);
        faw_221.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        faw_221.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        faw_221.onChildrenAdded();
        this.l(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 l(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setResizeOnce(true);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

