/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIM
 */
public class cim_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "adminTranslatorWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fys_02.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setNonBlocking(false);
        faw_24.setStyle("windowBackgroundRepeated");
        fey_22.X(faw_24);
        faw_24.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_24.X(fea_12);
        fea_12.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setPrefSize(new fsm_1(100.0f, 56));
        faw_25.setStyle("WindowHeaderMedium");
        fea_12.X(faw_25);
        faw_25.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_25.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_26);
        faw_26.guy();
        faw_26.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("windowTitle");
        fbv_22.setText("Admin Translator");
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(44, 32));
        faw_27.setVisible(false);
        faw_25.X(faw_27);
        faw_27.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setPrefSize(new fsm_1(32, 32));
        fad_12.setStyle("unknownTertiary");
        faw_27.X(fad_12);
        fad_12.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 0, 12));
        fad_12.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLP);
        fad_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_28.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_28);
        faw_28.guy();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fad_13.setPrefSize(new fsm_1(32, 32));
        fad_13.setStyle("crossTertiary");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_13.setOnClick(fmz_12);
        faw_28.X(fad_13);
        fad_13.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 12));
        fad_13.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLP);
        fad_13.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_29);
        }
        faw_29.setPrefSize(new fsm_1(1040, 744));
        faw_24.X(faw_29);
        faw_29.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_29.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_29.X(faw_210);
        faw_210.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_210.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_29.X(faw_211);
        faw_211.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_211.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_212 = faw_211;
        fys_0 fys_03 = ((fes_2)faw_212).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_211.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(16, 16, 16, 16));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_211.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        String string3 = "translator";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frv_12);
        }
        faw_211.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("value");
        fsj_22.setName("adminTranslator");
        frv_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_213.setPrefSize(new fsm_1(100.0f, 48));
        faw_213.setStyle("ContentContainer1");
        faw_211.X(faw_213);
        faw_213.guy();
        faw_2 faw_214 = faw_213;
        fys_0 fys_04 = ((fes_2)faw_214).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_213.X(fys_04);
        fys_04.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(0, 8, 0, 8));
        fys_04.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        frz_24.setHgap((short)8);
        faw_213.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipLight16");
        fbv_24.setText("Search key (.*)");
        faw_213.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_215.setPrefSize(new fsm_1(250, 32));
        faw_213.X(faw_215);
        faw_215.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_215.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        String string4 = "keySearch";
        fdv_1 fdv_12 = new fdv_1();
        fdv_12.aVI();
        fdv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdv_12);
        }
        fdv_12.setExpandable(false);
        String string5 = "%search%";
        string5 = string5.replace("%search%", fyw_0.gqw().k("search", new Object[0]));
        fdv_12.tX(string5);
        fme_2 fme_22 = new fme_2();
        fme_22.vw("wakfu.adminTranslator:filterTranslationsByKey(translator,keySearch,textSearch)");
        fdv_12.setOnClear(fme_22);
        fmt_2 fmt_22 = new fmt_2();
        fmt_22.vw("wakfu.adminTranslator:filterTranslationsByKey(translator,keySearch,textSearch)");
        fdv_12.setOnKeyRelease(fmt_22);
        fdv_12.setReplaceNullByGhostText(true);
        fdv_12.setStyle("defaultTextEditor");
        fdv_12.setWithClearButton(true);
        faw_215.X(fdv_12);
        fdv_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("keySearch");
        fsj_23.setName("adminTranslator");
        fdv_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdv_12.onChildrenAdded();
        faw_215.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setStyle("wipLightBold16");
        fbv_25.setText("|");
        faw_213.X(fbv_25);
        fbv_25.guy();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq3 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLO);
        fbv_25.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_25.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setExpandable(false);
        fbv_27.setStyle("wipLight16");
        fbv_27.setText("Search text (.*)");
        faw_213.X(fbv_27);
        fbv_27.guy();
        fbv_27.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_216.setPrefSize(new fsm_1(452, 32));
        faw_213.X(faw_216);
        faw_216.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHorizontal(false);
        faw_216.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        String string6 = "textSearch";
        fdv_1 fdv_13 = new fdv_1();
        fdv_13.aVI();
        fdv_13.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fdv_13);
        }
        fdv_13.setExpandable(false);
        String string7 = "%search%";
        string7 = string7.replace("%search%", fyw_0.gqw().k("search", new Object[0]));
        fdv_13.tX(string7);
        fme_2 fme_23 = new fme_2();
        fme_23.vw("wakfu.adminTranslator:filterTranslationsByText(translator,keySearch,textSearch)");
        fdv_13.setOnClear(fme_23);
        fmt_2 fmt_23 = new fmt_2();
        fmt_23.vw("wakfu.adminTranslator:filterTranslationsByText(translator,keySearch,textSearch)");
        fdv_13.setOnKeyRelease(fmt_23);
        fdv_13.setReplaceNullByGhostText(true);
        fdv_13.setStyle("defaultTextEditor");
        fdv_13.setWithClearButton(true);
        faw_216.X(fdv_13);
        fdv_13.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("textSearch");
        fsj_24.setName("adminTranslator");
        fdv_13.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdv_13.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setStyle("ContentContainer1");
        faw_211.X(faw_217);
        faw_217.guy();
        faw_2 faw_218 = faw_217;
        fys_0 fys_05 = ((fes_2)faw_218).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_217.X(fys_05);
        fys_05.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(8, 8, 8, 8));
        fys_05.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fys_05.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLL);
        frz_27.setHorizontal(false);
        frz_27.setVgap((short)8);
        faw_217.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_219.setExpandable(false);
        faw_217.X(faw_219);
        faw_219.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLN);
        faw_219.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setExpandable(false);
        fbv_28.setStyle("wipTitleLight22");
        fbv_28.setText("Results (");
        faw_219.X(fbv_28);
        fbv_28.guy();
        fbv_28.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_23);
        fbv_29.setExpandable(false);
        fbv_29.setStyle("wipTitleLight22");
        faw_219.X(fbv_29);
        fbv_29.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("resultsCount");
        fsj_25.setName("adminTranslator");
        fbv_29.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fbv_29.onChildrenAdded();
        fbv_2 fbv_210 = new fbv_2();
        fbv_210.aVI();
        fbv_210.setElementMap(fhs_23);
        fbv_210.setExpandable(false);
        fbv_210.setStyle("wipTitleLight22");
        fbv_210.setText(")");
        faw_219.X(fbv_210);
        fbv_210.guy();
        fbv_210.onChildrenAdded();
        faw_219.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setInnerWidgetAlign(faa_2.tLK);
        fcq_22.setStyle("defaultScrollContainer");
        faw_217.X(fcq_22);
        fcq_22.guy();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        fdf_12.setExpandable(true);
        fdf_12.setHideContainerWithoutItem(true);
        fdf_12.setHorizontal(false);
        fdf_12.setInnerExpandable(true);
        fdf_12.setStyle("defaultList");
        fcq_22.X(fdf_12);
        fdf_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("content");
        fsj_26.setField("results");
        fsj_26.setName("adminTranslator");
        fdf_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fdf_12.X(fje_22);
        fje_22.guy();
        String string8 = "translation";
        frv_1 frv_13 = new frv_1();
        frv_13.aVI();
        frv_13.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, frv_13);
        }
        fje_22.X(frv_13);
        frv_13.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("value");
        frv_13.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_13.onChildrenAdded();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        fje_22.X(faw_220);
        faw_220.guy();
        this.R(faw_220);
        this.c(faw_220);
        this.d(faw_220);
        faw_220.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_217.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_24.onChildrenAdded();
        this.m(fey_22);
        this.n(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHgap((short)8);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        return null;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setCursorType(fzo_0.tHz);
        faw_23.setExpandable(false);
        faw_23.setNonBlocking(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.adminTranslator:copyTranslationKey(translation)");
        faw_23.setOnClick(fmz_12);
        faw_23.setPrefSize(new fsm_1(360, 100.0f));
        faw_23.setStyle("ContentContainer2");
        faw_22.X(faw_23);
        faw_23.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setEnableAutoZoomShrink(true);
        fbv_22.setExpandable(false);
        fbv_22.setMaxWidth(340);
        fbv_22.setMultiline(true);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("wipLight14");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("key");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(596, 100.0f));
        faw_23.setStyle("ContentContainer2");
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(8, 8, 8, 8));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        frz_22.setVgap((short)8);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        frz_23.setHgap((short)4);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        faw_25.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("texture");
        fsj_22.setField("en");
        fsj_22.setName("flagIcons");
        fze2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setCursorType(fzo_0.tHz);
        fbv_22.setMaxWidth(560);
        fbv_22.setMultiline(true);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.adminTranslator:copyTranslationValue(translation,en)");
        fbv_22.setOnClick(fmz_12);
        fbv_22.setStyle("wipLight12");
        faw_25.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("en");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_23.X(faw_26);
        faw_26.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        frz_24.setHgap((short)4);
        faw_26.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setExpandable(false);
        faw_26.X(fbt_13);
        fbt_13.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fbt_13.X(fze3);
        fze3.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("texture");
        fsj_23.setField("fr");
        fsj_23.setName("flagIcons");
        fze3.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fze3.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setCursorType(fzo_0.tHz);
        fbv_23.setMaxWidth(560);
        fbv_23.setMultiline(true);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.adminTranslator:copyTranslationValue(translation,fr)");
        fbv_23.setOnClick(fmz_13);
        fbv_23.setStyle("wipLight12");
        faw_26.X(fbv_23);
        fbv_23.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("fr");
        fbv_23.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_23.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_23.X(faw_27);
        faw_27.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        frz_25.setHgap((short)4);
        faw_27.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setExpandable(false);
        faw_27.X(fbt_14);
        fbt_14.guy();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_22);
        fbt_14.X(fze4);
        fze4.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("texture");
        fsj_24.setField("es");
        fsj_24.setName("flagIcons");
        fze4.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fze4.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setCursorType(fzo_0.tHz);
        fbv_24.setMaxWidth(560);
        fbv_24.setMultiline(true);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.adminTranslator:copyTranslationValue(translation,es)");
        fbv_24.setOnClick(fmz_14);
        fbv_24.setStyle("wipLight12");
        faw_27.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("es");
        fbv_24.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_23.X(faw_28);
        faw_28.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        frz_26.setHgap((short)4);
        faw_28.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_22);
        fbt_15.setExpandable(false);
        faw_28.X(fbt_15);
        fbt_15.guy();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_22);
        fbt_15.X(fze5);
        fze5.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("texture");
        fsj_25.setField("pt");
        fsj_25.setName("flagIcons");
        fze5.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fze5.onChildrenAdded();
        fbt_15.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setCursorType(fzo_0.tHz);
        fbv_25.setMaxWidth(560);
        fbv_25.setMultiline(true);
        fmz_1 fmz_15 = new fmz_1();
        fmz_15.vw("wakfu.adminTranslator:copyTranslationValue(translation,pt)");
        fbv_25.setOnClick(fmz_15);
        fbv_25.setStyle("wipLight12");
        faw_28.X(fbv_25);
        fbv_25.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("pt");
        fbv_25.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 m(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setResizeOnce(true);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

