/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIP
 */
public class cip_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "artisansListWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_25;
        fys_0 fys_05 = ((fes_2)faw_27).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_25.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 6, 0));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_25.X(faw_28);
        faw_28.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_28.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string2 = "%craft.artisansBook.list.name%";
        string2 = string2.replace("%craft.artisansBook.list.name%", fyw_0.gqw().k("craft.artisansBook.list.name", new Object[0]));
        fbv_22.setText(string2);
        faw_28.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_23.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_06 = ((fes_2)faw_210).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_29.X(fys_06);
        fys_06.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 12, 0, 12));
        fys_06.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_06.onChildrenAdded();
        String string3 = "windowContentContainer";
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, faw_211);
        }
        faw_29.X(faw_211);
        faw_211.guy();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_211.X(faw_212);
        faw_212.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_212.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_213.setStyle("caracs");
        faw_212.X(faw_213);
        faw_213.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_213.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(510, 34));
        fbz_22.setHorizontal(false);
        fbz_22.setPrefSize(new fsm_1(510, 442));
        faw_213.X(fbz_22);
        fbz_22.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fbz_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_23);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        fje_22.X(faw_214);
        faw_214.guy();
        faw_2 faw_215 = faw_214;
        fys_0 fys_07 = ((fes_2)faw_215).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_214.X(fys_07);
        fys_07.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_23);
        fys_07.X(fkk_12);
        fkk_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("color");
        fkk_12.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fjt_23.setElseValue("oddCellColor");
        fjt_23.setValue("evenCellColor");
        fsd_12.X(fjt_23);
        fjt_23.guy();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_23);
        fjy_22.setKey("evenIndex");
        fjt_23.X(fjy_22);
        fjy_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjy_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_12.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fys_07.onChildrenAdded();
        faw_214.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        String string4 = "artisan";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, frv_12);
        }
        faw_213.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("value");
        frv_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        frv_12.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setExpandable(false);
        fcq_22.setHorizontalScrollBarBehaviour(fzi_0.tHc);
        fcq_22.setPageJumpRatio(0.1f);
        faw_213.X(fcq_22);
        fcq_22.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        fcq_22.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        String string5 = "artisanList";
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fdf_12);
        }
        fdf_12.setHorizontal(false);
        fdf_12.setInnerExpandable(false);
        fdf_12.setPrefSize(new fsm_1(500, 85));
        fcq_22.X(fdf_12);
        fdf_12.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLL);
        frz_25.setHorizontal(false);
        fdf_12.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("content");
        fsj_22.setField("currentArtisansPage");
        fsj_22.setLocal(true);
        fsj_22.setName("artisansList");
        fdf_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fdf_12.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fje_23.X(fjt_24);
        fjt_24.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_23);
        fjt_24.X(fjn_22);
        fjn_22.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_23);
        fjn_22.X(fjx_13);
        fjx_13.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_13.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_24.onChildrenAdded();
        String string6 = "artisan";
        frv_1 frv_13 = new frv_1();
        frv_13.aVI();
        frv_13.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, frv_13);
        }
        fje_23.X(frv_13);
        frv_13.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("value");
        frv_13.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        frv_13.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_216.setPrefSize(new fsm_1(100.0f, 34));
        fje_23.X(faw_216);
        faw_216.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        faw_216.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setMaxWidth(150);
        fbv_24.setMinWidth(150);
        fbv_24.setNonBlocking(true);
        fbv_24.setStyle("whiteBold");
        faw_216.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("text");
        fsd_15.setField("name");
        fbv_24.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 10, 0, 0));
        fzq3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setMaxWidth(50);
        fbv_26.setMinWidth(50);
        fbv_26.setNonBlocking(true);
        fbv_26.setStyle("whiteBold");
        faw_216.X(fbv_26);
        fbv_26.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("text");
        fsd_16.setField("jobLevel");
        fbv_26.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq4 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq4.setElementMap(fhs_23);
        fbv_26.X(fzq4);
        fzq4.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 10, 0, 0));
        fzq4.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzq4.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setExpandable(false);
        faw_217.setPrefSize(new fsm_1(200, 34));
        faw_216.X(faw_217);
        faw_217.guy();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_217.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setExpandable(false);
        fbv_28.setMaxWidth(170);
        fbv_28.setMinWidth(50);
        fbv_28.setNonBlocking(true);
        fbv_28.setStyle("whiteBold");
        faw_217.X(fbv_28);
        fbv_28.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_23);
        fsd_17.setAttribute("text");
        fsd_17.setField("fee");
        fbv_28.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        fbv_2 fbv_29 = fbv_28;
        fzq fzq5 = (fzq)((fes_2)fbv_29).getAppearance();
        fzq5.setElementMap(fhs_23);
        fbv_28.X(fzq5);
        fzq5.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 10, 0, 0));
        fzq5.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzq5.onChildrenAdded();
        fbv_28.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("kamas");
        faw_217.X(fbt_12);
        fbt_12.guy();
        fbt_12.onChildrenAdded();
        this.R(faw_217);
        faw_217.onChildrenAdded();
        this.c(faw_216);
        faw_216.onChildrenAdded();
        fje_23.onChildrenAdded();
        this.b(fdf_12);
        fdf_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_213.onChildrenAdded();
        this.e(faw_212);
        faw_212.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.n(fey_22);
        this.q(fey_22);
        this.r(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_22.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        return fde_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_24.setPrefSize(new fsm_1(28, 28));
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 3, 0, 3));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLP);
        faw_24.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_24.X(faw_26);
        faw_26.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_26.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.artisansBook:contactArtisan(artisan)");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(contactArtisanPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("yellowSmall");
        faw_26.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("enabled");
        fsd_12.setField("mpEnabled");
        fad_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(24, 24));
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("mru5");
        faw_26.X(fbt_12);
        fbt_12.guy();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(2, 2, 2, 2));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        String string = "contactArtisanPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_26.X(frx_12);
        frx_12.guy();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setPrefSize(new fsm_1(15, 0));
        faw_27.setStyle("popup");
        frx_12.X(faw_27);
        faw_27.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        String string2 = "%craft.artisansBook.sendMessage%";
        string2 = string2.replace("%craft.artisansBook.sendMessage%", fyw_0.gqw().k("craft.artisansBook.sendMessage", new Object[0]));
        fbv_22.setText(string2);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("visible");
        fsd_13.setField("mpEnabled");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setStyle("PopupInformation");
        String string3 = "%craft.artisansBook.ignored%";
        string3 = string3.replace("%craft.artisansBook.ignored%", fyw_0.gqw().k("craft.artisansBook.ignored", new Object[0]));
        fbv_23.setText(string3);
        faw_27.X(fbv_23);
        fbv_23.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("visible");
        fsd_14.setField("ignored");
        fbv_23.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_23.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setStyle("PopupInformation");
        String string4 = "%craft.artisansBook.itsMe%";
        string4 = string4.replace("%craft.artisansBook.itsMe%", fyw_0.gqw().k("craft.artisansBook.itsMe", new Object[0]));
        fbv_24.setText(string4);
        faw_27.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("visible");
        fsd_15.setField("itsMe");
        fbv_24.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_27.onChildrenAdded();
        frx_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 b(fdf_1 fdf_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fdf_12.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fje_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fys_02.X(fkk_12);
        fkk_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("color");
        fkk_12.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fjt_23.setElseValue("oddCellColor");
        fjt_23.setValue("evenCellColor");
        fsd_12.X(fjt_23);
        fjt_23.guy();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_22);
        fjy_22.setKey("evenIndex");
        fjt_23.X(fjy_22);
        fjy_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjy_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_12.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        frz_22.setHorizontal(true);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        String string = "selectedCraft";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        faw_23.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("value");
        fsj_22.setLocal(true);
        fsj_22.setName("craft");
        frv_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frv_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.artisansBook:previousPageArtisans");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("characterCreationLeftArrow");
        faw_23.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("enabled");
        fsj_23.setField("currentPage");
        fsj_23.setLocal(true);
        fsj_23.setName("artisansList");
        fad_12.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjc_1 fjc_12 = new fjc_1();
        fjc_12.aVI();
        fjc_12.setElementMap(fhs_22);
        fjc_12.setValue("1");
        fjt_22.X(fjc_12);
        fjc_12.guy();
        fjc_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fad_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(200);
        fdy_12.setMinWidth(200);
        fdy_12.setStyle("StyledBoldDark12");
        faw_23.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("currentPageText");
        fsj_24.setLocal(true);
        fsj_24.setName("artisansList");
        fdy_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.artisansBook:nextPageArtisans");
        fad_13.setOnClick(fmz_13);
        fad_13.setStyle("characterCreationRightArrow");
        faw_23.X(fad_13);
        fad_13.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("enabled");
        fsj_25.setField("currentPage");
        fsj_25.setLocal(true);
        fsj_25.setName("artisansList");
        fad_13.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_25.X(fjt_23);
        fjt_23.guy();
        fjr_1 fjr_12 = new fjr_1();
        fjr_12.aVI();
        fjr_12.setElementMap(fhs_22);
        fjt_23.X(fjr_12);
        fjr_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("value");
        fsj_26.setField("totalPages");
        fsj_26.setLocal(true);
        fsj_26.setName("artisansList");
        fjr_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fjr_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "closeArtisansListDialog";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fad_12);
        }
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

