/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIR
 */
public class cir_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setVisible(false);
        faw_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("visible");
        fsj_22.setName("isInGame");
        faw_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_23);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjn_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_23);
        fjn_22.X(fjl_13);
        fjl_13.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("comparedValue");
        fsj_23.setName("isInBattleground");
        fjl_13.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fjl_13.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(-2, -2));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 0, 2));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setExpandable(false);
        faw_24.setPrefSize(new fsm_1(300, 168));
        faw_22.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_24.X(faw_25);
        faw_25.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLa);
        frp_13.setXOffset(-118);
        frp_13.setYOffset(-58);
        faw_25.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_25.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_23);
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu:toggleBattlegroundBarDetail");
        fdd_22.setOnSelectionChange(fmo_12);
        fdd_22.setStyle("CharacteristicsDisplay");
        faw_25.X(fdd_22);
        fdd_22.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fdd_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("selected");
        fsj_24.setName("battlegroundBarDetail");
        fdd_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdd_22.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("DownSortArrow");
        faw_25.X(fbt_12);
        fbt_12.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setName("battlegroundBarDetail");
        fbt_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLm);
        frp_15.setSize(new fsm_1(-2, -2));
        frp_15.setYOffset(7);
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("UpSortArrow");
        faw_25.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLm);
        frp_16.setSize(new fsm_1(-2, -2));
        frp_16.setYOffset(7);
        fbt_13.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("visible");
        fsj_26.setName("battlegroundBarDetail");
        fbt_13.X(fsj_26);
        fsj_26.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsj_26.X(fjt_23);
        fjt_23.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjt_23.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_26.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setNonBlocking(false);
        faw_26.setPrefSize(new fsm_1(0, 0));
        faw_26.setStyle("dungeonWindowDecoration");
        faw_24.X(faw_26);
        faw_26.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tKY);
        frp_17.setXOffset(74);
        frp_17.setYOffset(-60);
        faw_26.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("visible");
        fsj_27.setName("battlegroundBarDetail");
        faw_26.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        String string = "battlegroundBarDetailTextId";
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fdy_12);
        }
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(200);
        fdy_12.setMultiline(true);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("bold");
        faw_26.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("text");
        fsj_28.setName("battlegroundBarDetailText");
        fdy_12.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_23);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(10, 10, 10, 10));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(5, 10, 15, 10));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setNonBlocking(false);
        faw_27.setPrefSize(new fsm_1(300, 58));
        faw_27.setStyle("dungeonWindowDecoration");
        faw_24.X(faw_27);
        faw_27.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tKY);
        faw_27.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLK);
        faw_27.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_27.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(0, 32, 12, 6));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        String string2 = "battlegroundType";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, frv_12);
        }
        faw_27.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("value");
        fsj_29.setField("battlegroundType");
        fsj_29.setName("battlegroundView");
        frv_12.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu:displayBattlegroundExplanation(battlegroundType)");
        faw_29.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(bgTypeDetail)");
        faw_29.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_29.setOnPopupHide(fml_12);
        faw_29.setPrefSize(new fsm_1(46, 0));
        faw_27.X(faw_29);
        faw_29.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_29.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setDisplaySize(new fsm_1(42, 42));
        faw_29.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setAlign(fzw_0.tLg);
        frp_19.setSize(new fsm_1(100.0f, 100.0f));
        fbt_14.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_14.X(fze2);
        fze2.guy();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("texture");
        fsj_210.setField("battlegroundType/iconUrl");
        fsj_210.setName("battlegroundView");
        fze2.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_23);
        fbt_15.setDisplaySize(new fsm_1(46, 46));
        fbt_15.setStyle("spellFrame");
        faw_29.X(fbt_15);
        fbt_15.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_23);
        frp_110.setAlign(fzw_0.tLg);
        frp_110.setSize(new fsm_1(100.0f, 100.0f));
        fbt_15.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        fbt_15.onChildrenAdded();
        String string3 = "bgTypeDetail";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLQ);
        frx_12.setHotSpotPosition(faa_2.tLK);
        faw_29.X(frx_12);
        frx_12.guy();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setPrefSize(new fsm_1(10, 0));
        faw_210.setStyle("popup");
        frx_12.X(faw_210);
        faw_210.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_210.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        fdy_14.setExpandable(false);
        fdy_14.setMaxWidth(330);
        fdy_14.setMinWidth(330);
        fdy_14.setMultiline(true);
        fdy_14.setNonBlocking(true);
        fdy_14.setStyle("whiteTitle");
        faw_210.X(fdy_14);
        fdy_14.guy();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_23);
        fsj_211.setAttribute("text");
        fsj_211.setField("battlegroundType/name");
        fsj_211.setName("battlegroundView");
        fdy_14.X(fsj_211);
        fsj_211.guy();
        fsj_211.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        fde_12.setPrefSize(new fsm_1(0, 4));
        faw_210.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_23);
        fdy_15.setExpandable(false);
        fdy_15.setMaxWidth(330);
        fdy_15.setMinWidth(330);
        fdy_15.setMultiline(true);
        fdy_15.setNonBlocking(true);
        fdy_15.setStyle("white");
        faw_210.X(fdy_15);
        fdy_15.guy();
        fsj_2 fsj_212 = fsj_2.checkOut();
        fsj_212.setElementMap(fhs_23);
        fsj_212.setAttribute("text");
        fsj_212.setField("battlegroundType/desc");
        fsj_212.setName("battlegroundView");
        fdy_15.X(fsj_212);
        fsj_212.guy();
        fsj_212.onChildrenAdded();
        fdy_15.onChildrenAdded();
        faw_210.onChildrenAdded();
        frx_12.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_211.setPrefSize(new fsm_1(167, 0));
        faw_211.setStyle("popup");
        faw_27.X(faw_211);
        faw_211.guy();
        faw_2 faw_212 = faw_211;
        fys_0 fys_04 = ((fes_2)faw_212).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_211.X(fys_04);
        fys_04.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(4, 0, 12, 0));
        fys_04.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_04.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        faw_211.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_23);
        fbt_16.setDisplaySize(new fsm_1(48, 48));
        fbt_16.setNonBlocking(true);
        fbt_16.setStyle("pvpDecorator");
        faw_211.X(fbt_16);
        fbt_16.guy();
        frp_1 frp_111 = new frp_1();
        frp_111.aVI();
        frp_111.setElementMap(fhs_23);
        frp_111.setAlign(fzw_0.tLg);
        fbt_16.X(frp_111);
        frp_111.guy();
        frp_111.onChildrenAdded();
        fbt_16.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_211.X(faw_213);
        faw_213.guy();
        frp_1 frp_112 = new frp_1();
        frp_112.aVI();
        frp_112.setElementMap(fhs_23);
        frp_112.setAlign(fzw_0.tLg);
        frp_112.setSize(new fsm_1(100.0f, 100.0f));
        faw_213.X(frp_112);
        frp_112.guy();
        frp_112.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_213.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_213.X(faw_214);
        faw_214.guy();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_23);
        fdy_16.setExpandable(false);
        fdy_16.setMaxWidth(60);
        fdy_16.setMinWidth(50);
        fdy_16.setNonBlocking(true);
        fdy_16.setStyle("whiteTitle");
        faw_214.X(fdy_16);
        fdy_16.guy();
        this.e(fdy_16);
        this.f(fdy_16);
        fdy_16.onChildrenAdded();
        this.d(faw_214);
        this.e(faw_214);
        faw_214.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_27.onChildrenAdded();
        this.F(faw_24);
        this.G(faw_24);
        faw_24.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 e(fdy_1 fdy_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("defenseTeam/score");
        fsj_22.setName("battlegroundView");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 f(fdy_1 fdy_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("battlegroundDefenseTeamScoreColor"));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        return fzq2;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_22.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        return fde_12;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(60);
        fdy_12.setMinWidth(50);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("whiteTitle");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("attackTeam/score");
        fsj_22.setName("battlegroundView");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("battlegroundAttackTeamScoreColor"));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(180, 16));
        frp_12.setXOffset(5);
        frp_12.setYOffset(-41);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_24.X(faw_25);
        faw_25.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_25.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(16, 16));
        fbz_22.setExpandable(false);
        fbz_22.setIdealSizeMaxRows(1);
        fbz_22.setIdealSizeMinRows(1);
        fbz_22.setNonBlocking(false);
        faw_25.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("defenseTeam/nationsList");
        fsj_22.setName("battlegroundView");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(16, 16));
        fje_22.X(faw_26);
        faw_26.guy();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(14, 14));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(nationPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        faw_26.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("flagIconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        String string = "nationPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLN);
        frx_12.setHotSpotPosition(faa_2.tLP);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setStyle("popup");
        frx_12.X(faw_27);
        faw_27.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_27.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setMaxWidth(200);
        fbv_22.setMinWidth(100);
        fbv_22.setMultiline(true);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("whiteBold");
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_2 fbv_24 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(2, 0, 6, 0));
        fzq3.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("name");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_24.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_24.X(faw_28);
        faw_28.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLP);
        faw_28.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbz_2 fbz_23 = new fbz_2();
        fbz_23.aVI();
        fbz_23.setElementMap(fhs_22);
        fbz_23.setAutoIdealSize(true);
        fbz_23.setCellSize(new fsm_1(16, 16));
        fbz_23.setExpandable(false);
        fbz_23.setIdealSizeMaxRows(1);
        fbz_23.setIdealSizeMinRows(1);
        fbz_23.setNonBlocking(false);
        faw_28.X(fbz_23);
        fbz_23.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("content");
        fsj_23.setField("attackTeam/nationsList");
        fsj_23.setName("battlegroundView");
        fbz_23.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fbz_23.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjt_23.X(fjx_13);
        fjx_13.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjx_13.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setExpandable(false);
        faw_29.setPrefSize(new fsm_1(16, 16));
        fje_23.X(faw_29);
        faw_29.guy();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setDisplaySize(new fsm_1(14, 14));
        fbt_13.setExpandable(false);
        fbt_13.setNonBlocking(false);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(nationPopup)");
        fbt_13.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fbt_13.setOnPopupHide(fml_13);
        faw_29.X(fbt_13);
        fbt_13.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fbt_13.X(fze3);
        fze3.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("texture");
        fsd_14.setField("flagIconUrl");
        fze3.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fze3.onChildrenAdded();
        String string2 = "nationPopup";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_13);
        }
        frx_13.setAlign(faa_2.tLN);
        frx_13.setHotSpotPosition(faa_2.tLP);
        fbt_13.X(frx_13);
        frx_13.guy();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_210.setStyle("popup");
        frx_13.X(faw_210);
        faw_210.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_210.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setMaxWidth(200);
        fbv_25.setMinWidth(100);
        fbv_25.setMultiline(true);
        fbv_25.setNonBlocking(true);
        fbv_25.setStyle("whiteBold");
        faw_210.X(fbv_25);
        fbv_25.guy();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq4 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlignment(faa_2.tLO);
        fbv_25.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_2 fbv_27 = fbv_25;
        fzq fzq5 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq5.setElementMap(fhs_22);
        fbv_25.X(fzq5);
        fzq5.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(2, 0, 6, 0));
        fzq5.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq5.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("name");
        fbv_25.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_210.onChildrenAdded();
        frx_13.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_29.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_23.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(80);
        fdy_12.setMinWidth(80);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("StyledDark12");
        faw_22.X(fdy_12);
        fdy_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(128);
        frp_12.setYOffset(-18);
        fdy_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("battlegroundRemainingTime");
        fsj_22.setName("battlegroundView");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }
}

