/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cIZ
 */
public class ciz_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_23.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_04.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_04.onChildrenAdded();
        String string = "windowContentContainer";
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_27);
        }
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLL);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        frz_23.setUseLegacyVGapBehaviour(true);
        frz_23.setVgap((short)3);
        faw_27.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_27.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 9));
        fys_05.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_05.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLP);
        faw_28.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        String string2 = "hour";
        fdy_2 fdy_22 = new fdy_2();
        fdy_22.aVI();
        fdy_22.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fdy_22);
        }
        fdy_22.setDisplayFormat("%02d");
        fdy_22.setExpandable(false);
        fdy_22.setMaxBound(23);
        fdy_22.setMinBound(0);
        fdy_22.setPrefSize(new fsm_1(35, 0));
        fdy_22.setValue(12);
        faw_28.X(fdy_22);
        fdy_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("value");
        fsj_22.setField("hour");
        fsj_22.setName("calendar.editable");
        fdy_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("bold");
        fbv_22.setText("H");
        faw_28.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 2, 0, 2));
        fzq2.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        String string3 = "minutes";
        fdy_2 fdy_23 = new fdy_2();
        fdy_23.aVI();
        fdy_23.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fdy_23);
        }
        fdy_23.setDisplayFormat("%02d");
        fdy_23.setExpandable(false);
        fdy_23.setMaxBound(59);
        fdy_23.setMinBound(0);
        fdy_23.setPrefSize(new fsm_1(35, 0));
        fdy_23.setValue(0);
        faw_28.X(fdy_23);
        fdy_23.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("value");
        fsj_23.setField("minute");
        fsj_23.setName("calendar.editable");
        fdy_23.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_23.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_27.X(faw_210);
        faw_210.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLP);
        faw_210.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fas_1 fas_12 = new fas_1();
        fas_12.aVI();
        fas_12.setElementMap(fhs_23);
        fas_12.setExpandable(false);
        fmv_2 fmv_22 = new fmv_2();
        fmv_22.vw("wakfu.eventsCalendar:changeEditableCurrentMonth");
        fas_12.setOnListSelectionChange(fmv_22);
        fas_12.setPrefSize(new fsm_1(100, 15));
        faw_210.X(fas_12);
        fas_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("content");
        fsj_24.setField("monthesList");
        fsj_24.setName("calendar.editable");
        fas_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("selectedValue");
        fsj_25.setField("selectedMonth");
        fsj_25.setName("calendar.editable");
        fas_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fcv_1 fcv_12 = new fcv_1();
        fcv_12.aVI();
        fcv_12.setElementMap(fhs_23);
        fas_12.X(fcv_12);
        fcv_12.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fcv_12.X(fje_22);
        fje_22.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setNonBlocking(true);
        fje_22.X(fbv_24);
        fbv_24.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLO);
        fbv_24.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("description");
        fbv_24.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fcv_12.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(100.0f, 16));
        fbz_22.setHorizontal(false);
        fas_12.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fbz_22.X(fje_23);
        fje_23.guy();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setNonBlocking(true);
        fje_23.X(fbv_25);
        fbv_25.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fsd_13.setField("description");
        fbv_25.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq3 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_25.X(fzq3);
        fzq3.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 10, 0, 0));
        fzq3.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_25.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_22.onChildrenAdded();
        fas_12.onChildrenAdded();
        fas_1 fas_13 = new fas_1();
        fas_13.aVI();
        fas_13.setElementMap(fhs_23);
        fas_13.setExpandable(false);
        fmv_2 fmv_23 = new fmv_2();
        fmv_23.vw("wakfu.eventsCalendar:changeEditableCurrentYear");
        fas_13.setOnListSelectionChange(fmv_23);
        fas_13.setPrefSize(new fsm_1(50, 15));
        faw_210.X(fas_13);
        fas_13.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("content");
        fsj_26.setField("yearsList");
        fsj_26.setName("calendar.editable");
        fas_13.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("selectedValue");
        fsj_27.setField("selectedYear");
        fsj_27.setName("calendar.editable");
        fas_13.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fcv_1 fcv_13 = new fcv_1();
        fcv_13.aVI();
        fcv_13.setElementMap(fhs_23);
        fas_13.X(fcv_13);
        fcv_13.guy();
        fje_2 fje_24 = new fje_2();
        fje_24.aVI();
        fje_24.setElementMap(fhs_23);
        fcv_13.X(fje_24);
        fje_24.guy();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setNonBlocking(true);
        fje_24.X(fbv_27);
        fbv_27.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLO);
        fbv_27.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("text");
        fbv_27.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_27.onChildrenAdded();
        fje_24.onChildrenAdded();
        fcv_13.onChildrenAdded();
        fbz_2 fbz_23 = new fbz_2();
        fbz_23.aVI();
        fbz_23.setElementMap(fhs_23);
        fbz_23.setCellSize(new fsm_1(100.0f, 16));
        fbz_23.setHorizontal(false);
        fas_13.X(fbz_23);
        fbz_23.guy();
        fje_2 fje_25 = new fje_2();
        fje_25.aVI();
        fje_25.setElementMap(fhs_23);
        fbz_23.X(fje_25);
        fje_25.guy();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setNonBlocking(true);
        fje_25.X(fbv_28);
        fbv_28.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("text");
        fbv_28.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_2 fbv_29 = fbv_28;
        fzq fzq4 = (fzq)((fes_2)fbv_29).getAppearance();
        fzq4.setElementMap(fhs_23);
        fbv_28.X(fzq4);
        fzq4.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 10, 0, 0));
        fzq4.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzq4.onChildrenAdded();
        fbv_28.onChildrenAdded();
        fje_25.onChildrenAdded();
        fbz_23.onChildrenAdded();
        fas_13.onChildrenAdded();
        faw_210.onChildrenAdded();
        String string4 = "calendar";
        fak_2 fak_22 = new fak_2();
        fak_22.aVI();
        fak_22.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fak_22);
        }
        fak_22.setCellSize(new fsm_1(22, 22));
        fak_22.setExpandable(false);
        fak_22.setStyle("small");
        faw_27.X(fak_22);
        fak_22.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("calendar");
        fsj_28.setField("calendar");
        fsj_28.setName("calendar.editable");
        fak_22.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        frb_1 frb_17 = new frb_1();
        frb_17.aVI();
        frb_17.setElementMap(fhs_23);
        frb_17.setAlign(faa_2.tLO);
        fak_22.X(frb_17);
        frb_17.guy();
        frb_17.onChildrenAdded();
        fje_2 fje_26 = new fje_2();
        fje_26.aVI();
        fje_26.setElementMap(fhs_23);
        fak_22.X(fje_26);
        fje_26.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setStyle("flat");
        fje_26.X(fad_12);
        fad_12.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        fad_12.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fad_12.onChildrenAdded();
        fje_26.onChildrenAdded();
        fak_22.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setClickSoundId(600002);
        fad_13.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:selectDate(calendar,hour,minutes)");
        fad_13.setOnClick(fmz_12);
        fad_13.setStyle("flat");
        String string5 = "%ok%";
        string5 = string5.replace("%ok%", fyw_0.gqw().k("ok", new Object[0]));
        fad_13.setText(string5);
        faw_27.X(fad_13);
        fad_13.guy();
        fad_1 fad_14 = fad_13;
        fym_0 fym_02 = (fym_0)((fes_2)fad_14).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_13.X(fym_02);
        fym_02.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 10, 3, 10));
        fym_02.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fym_02.onChildrenAdded();
        frb_1 frb_18 = new frb_1();
        frb_18.aVI();
        frb_18.setElementMap(fhs_23);
        frb_18.setAlign(faa_2.tLO);
        fad_13.X(frb_18);
        frb_18.guy();
        frb_18.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.l(fey_22);
        this.D(fey_22);
        this.C(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 l(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 D(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:closeCalendar");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 C(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

