/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cJA
 */
public class cja_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "consoleDialog";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setNonBlocking(true);
        fey_22.setPrefSize(new fsm_1(100, 100));
        fey_22.setSize(new fsm_1(300, 300));
        fey_22.setStyle("console");
        fey_22.setX(100);
        fey_22.setY(100);
        fey_22.guy();
        frt_2 frt_22 = new frt_2();
        frt_22.aVI();
        fey_22.X(frt_22);
        frt_22.guy();
        frt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKw);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frt_2 frt_23 = new frt_2();
        frt_23.aVI();
        faw_22.X(frt_23);
        frt_23.guy();
        frt_23.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fma_2 fma_22 = new fma_2();
        fma_22.vw("xulor:toggleVisible(windowContentContainer)");
        fea_12.setOnDoubleClick(fma_22);
        fea_12.setThemeElementName("titleBar");
        fea_12.setThemeElementParentType("window");
        faw_22.X(fea_12);
        fea_12.guy();
        fru_1 fru_13 = fru_1.checkOut();
        fru_13.setElementMap(fhs_23);
        fru_13.setData(fzt_0.tKA);
        fea_12.X(fru_13);
        fru_13.guy();
        fru_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        fea_12.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setStyle("smallDelete");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fea_12.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setOrientation(fzu_0.tKC);
        fbv_22.setThemeElementName("label");
        fbv_22.setThemeElementParentType("window");
        String string2 = "%dialog.console.title%";
        string2 = string2.replace("%dialog.console.title%", fyw_0.gqw().k("dialog.console.title", new Object[0]));
        fbv_22.setText(string2);
        fea_12.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string3 = "windowContentContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, faw_23);
        }
        faw_23.setThemeElementName("content");
        faw_23.setThemeElementParentType("window");
        faw_22.X(faw_23);
        faw_23.guy();
        fru_1 fru_14 = fru_1.checkOut();
        fru_14.setElementMap(fhs_23);
        fru_14.setData(fzt_0.tKw);
        faw_23.X(fru_14);
        fru_14.guy();
        fru_14.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frt_2 frt_24 = new frt_2();
        frt_24.aVI();
        faw_24.X(frt_24);
        frt_24.guy();
        frt_24.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setHorizontalScrollBarBehaviour(fzi_0.tHc);
        fcq_22.setNonBlocking(true);
        fcq_22.setVerticalScrollBarPosition(0.0f);
        faw_24.X(fcq_22);
        fcq_22.guy();
        fru_1 fru_15 = fru_1.checkOut();
        fru_15.setElementMap(fhs_23);
        fru_15.setData(fzt_0.tKw);
        fcq_22.X(fru_15);
        fru_15.guy();
        fru_15.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setEnableShrinking(false);
        fdy_12.setSelectable(true);
        fdy_12.setStyle("DefaultWhite");
        fdy_12.setUseParentMaxWidth(true);
        fcq_22.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("logs");
        fsj_22.setName("adminConsole");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_23);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("ConsoleInput");
        faw_24.X(faw_25);
        faw_25.guy();
        fru_1 fru_16 = fru_1.checkOut();
        fru_16.setElementMap(fhs_23);
        fru_16.setData(fzt_0.tKy);
        faw_25.X(fru_16);
        fru_16.guy();
        fru_16.onChildrenAdded();
        frt_2 frt_25 = new frt_2();
        frt_25.aVI();
        faw_25.X(frt_25);
        frt_25.guy();
        frt_25.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_23);
        faw_25.X(fbv_23);
        fbv_23.guy();
        fru_1 fru_17 = fru_1.checkOut();
        fru_17.setElementMap(fhs_23);
        fru_17.setData(fzt_0.tKA);
        fbv_23.X(fru_17);
        fru_17.guy();
        fru_17.onChildrenAdded();
        fbv_2 fbv_24 = fbv_23;
        fzq fzq3 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_23.X(fzq3);
        fzq3.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 2, 0, 2));
        fzq3.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("prompt");
        fsj_23.setName("adminConsole");
        fbv_23.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbv_23.onChildrenAdded();
        String string4 = "input";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdu_12);
        }
        fdu_12.setAutoHorizontalScrolled(true);
        fdu_12.setFocused(true);
        fms_2 fms_22 = new fms_2();
        fms_22.vw("wakfu.adminConsole:processInputKeyEvent(input)");
        fdu_12.setOnKeyPress(fms_22);
        fdu_12.setStyle("dark");
        faw_25.X(fdu_12);
        fdu_12.guy();
        fru_1 fru_18 = fru_1.checkOut();
        fru_18.setElementMap(fhs_23);
        fru_18.setData(fzt_0.tKw);
        fdu_12.X(fru_18);
        fru_18.guy();
        fru_18.onChildrenAdded();
        fdu_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.adminConsole:clear");
        fad_13.setOnClick(fmz_13);
        fad_13.setStyle("small");
        String string5 = "%clear%";
        string5 = string5.replace("%clear%", fyw_0.gqw().k("clear", new Object[0]));
        fad_13.setText(string5);
        faw_25.X(fad_13);
        fad_13.guy();
        fad_1 fad_14 = fad_13;
        fym_0 fym_02 = (fym_0)((fes_2)fad_14).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_13.X(fym_02);
        fym_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 20));
        fym_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fym_02.onChildrenAdded();
        fru_1 fru_19 = fru_1.checkOut();
        fru_19.setElementMap(fhs_23);
        fru_19.setData(fzt_0.tKz);
        fad_13.X(fru_19);
        fru_19.guy();
        fru_19.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_24.onChildrenAdded();
        fed_2 fed_22 = new fed_2();
        fed_22.aVI();
        fed_22.setElementMap(fhs_23);
        fed_22.setPointAlign(faa_2.tLS);
        faw_23.X(fed_22);
        fed_22.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLo);
        fed_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        fed_22.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fad_1 fad_15 = new fad_1();
        fad_15.aVI();
        fad_15.setElementMap(fhs_23);
        fad_15.setExpandable(false);
        fad_15.setNonBlocking(true);
        fad_15.setStyle("Yellow");
        fed_22.X(fad_15);
        fad_15.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fad_15.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fad_1 fad_16 = fad_15;
        fym_0 fym_03 = (fym_0)((fes_2)fad_16).getAppearance();
        fym_03.setElementMap(fhs_23);
        fad_15.X(fym_03);
        fym_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(2, 2, 2, 3));
        fym_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fym_03.onChildrenAdded();
        fad_15.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("multidirectionnalCross");
        fed_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fed_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_22.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setInitValue(true);
        frp_16.setSize(new fsm_1(600, 300));
        fey_22.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

