/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cJd
 */
public class cjd_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(250, 200));
        frp_12.setXOffset(630);
        frp_12.setYOffset(-135);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setStyle("windowBackgroundSecondary");
        fey_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(12, 12, 12, 12));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        frz_22.setVgap((short)8);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setCursorType(fzo_0.tHO);
        fea_12.setExpandable(false);
        faw_22.X(fea_12);
        fea_12.guy();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        fea_12.X(faw_24);
        faw_24.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLL);
        faw_24.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHgap((short)8);
        faw_24.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setPrefSize(new fsm_1(18, 18));
        fbt_12.setStyle("palettePrimaryLight");
        faw_24.X(fbt_12);
        fbt_12.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        fbt_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setEnableAutoZoomShrink(true);
        fbv_22.setMaxWidth(170);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("wipGold14Bordered");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setName("characterCreation.colorizablePartDescription");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(24, 24));
        fad_12.setStyle("crossTertiary");
        faw_24.X(fad_12);
        fad_12.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLO);
        fad_12.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string = "characterCreationPicker";
        faq_2 faq_22 = new faq_2();
        faq_22.aVI();
        faq_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faq_22);
        }
        faq_22.setNeedsScissor(true);
        fmr_1 fmr_12 = new fmr_1();
        fmr_12.vw("wakfu.characterCreation:onColorPicked");
        faq_22.setOnValueChange(fmr_12);
        faw_22.X(faq_22);
        faq_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("value");
        fsj_23.setName("characterCreation.colorPickerValue");
        faq_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("enabled");
        fsj_24.setName("characterCreation.enableColorChange");
        faq_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        faq_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setExpandable(false);
        faw_22.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_25.X(faw_26);
        faw_26.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_26.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setStyle("ColorSelectionBackground");
        faw_26.X(faw_27);
        faw_27.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_27.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_27.X(fys_03);
        fys_03.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_23);
        fkk_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.75f));
        fys_03.X(fkk_12);
        fkk_12.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("color");
        fsj_25.setName("characterCreation.colorPickerValue");
        fkk_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(4, 4, 4, 4));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setExpandable(false);
        faw_29.setNonBlocking(false);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.characterCreation:onMouseEnterPart($anmPart$)");
        faw_29.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.characterCreation:onMouseExitPart($anmPart$)");
        faw_29.setOnMouseExit(fmf_22);
        faw_29.setPrefSize(new fsm_1(130, 26));
        faw_29.setStyle("newTextEditor");
        faw_26.X(faw_29);
        faw_29.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_210.setPrefSize(new fsm_1(28, 28));
        faw_29.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_210;
        fys_0 fys_04 = ((fes_2)faw_211).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_210.X(fys_04);
        fys_04.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 4, 0, 0));
        fys_04.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_04.onChildrenAdded();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLP);
        faw_210.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fcu_1 fcu_12 = new fcu_1();
        fcu_12.aVI();
        fcu_12.setElementMap(fhs_23);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.characterCreation:openColorPicker");
        fcu_12.setOnClick(fmz_13);
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu.characterCreation:onColorizablePartSelected");
        fcu_12.setOnSelectionChange(fmo_12);
        fcu_12.setStyle("coloredSquare");
        faw_210.X(fcu_12);
        fcu_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("modulationColor");
        fsj_26.setName("characterCreation.colorPickerValue");
        fcu_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fcu_1 fcu_13 = fcu_12;
        fzk fzk2 = (fzk)((fes_2)fcu_13).getAppearance();
        fzk2.setElementMap(fhs_23);
        fcu_12.X(fzk2);
        fzk2.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 0, 0, 6));
        fzk2.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzk2.onChildrenAdded();
        fcu_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipLightGray14");
        fbv_24.setText("#");
        faw_29.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string2 = "colorPickerTextEditor";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fdu_12);
        }
        fdu_12.abk(6);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.characterCreation:onColorType(colorPickerTextEditor)");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setPrefSize(new fsm_1(64, 0));
        fdu_12.setRestrict("[0-9a-fA-F]+");
        fdu_12.setSelectOnFocus(true);
        fdu_12.setStyle("invisibleTextEditorGray14");
        faw_29.X(fdu_12);
        fdu_12.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("text");
        fsj_27.setName("characterCreation.colorPickerHexValue");
        fdu_12.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("enabled");
        fsj_28.setName("characterCreation.enableColorChange");
        fdu_12.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("editable");
        fsj_29.setName("characterCreation.enableColorChange");
        fdu_12.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fdu_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.characterCreation:cancelColor");
        fad_13.setOnClick(fmz_14);
        fad_13.setStyle("resetArrow");
        faw_29.X(fad_13);
        fad_13.guy();
        fad_1 fad_14 = fad_13;
        fym_0 fym_02 = (fym_0)((fes_2)fad_14).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_13.X(fym_02);
        fym_02.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 0, 0, 4));
        fym_02.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_26.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_25.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fad_1 fad_15 = new fad_1();
        fad_15.aVI();
        fad_15.setElementMap(fhs_23);
        fad_15.setExpandable(false);
        fmz_1 fmz_15 = new fmz_1();
        fmz_15.vw("wakfu.characterCreation:randomColor");
        fad_15.setOnClick(fmz_15);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(randomColorPopup)");
        fad_15.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_15.setOnPopupHide(fml_12);
        fad_15.setPrefSize(new fsm_1(36, 36));
        fad_15.setStyle("randomTertiary");
        faw_25.X(fad_15);
        fad_15.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLO);
        fad_15.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("enabled");
        fsj_210.setName("characterCreation.enableColorChange");
        fad_15.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        String string3 = "randomColorPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLR);
        frx_12.setHotSpotPosition(faa_2.tLL);
        fad_15.X(frx_12);
        frx_12.guy();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setPrefSize(new fsm_1(10, 0));
        faw_212.setStyle("popup");
        frx_12.X(faw_212);
        faw_212.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKA);
        faw_212.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setStyle("PopupInformation");
        String string4 = "%characterCreation.random.color%";
        string4 = string4.replace("%characterCreation.random.color%", fyw_0.gqw().k("characterCreation.random.color", new Object[0]));
        fbv_25.setText(string4);
        faw_212.X(fbv_25);
        fbv_25.guy();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq3 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fbv_25.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_212.onChildrenAdded();
        frx_12.onChildrenAdded();
        fad_15.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_22.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

