/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cJE
 */
public class cje_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fys_02.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setNonBlocking(false);
        faw_24.setStyle("windowBackgroundSecondary");
        fey_22.X(faw_24);
        faw_24.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_24.X(fea_12);
        fea_12.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setPrefSize(new fsm_1(100.0f, 48));
        faw_25.setStyle("WindowHeaderSmallSecondary");
        fea_12.X(faw_25);
        faw_25.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_25.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_26);
        faw_26.guy();
        faw_26.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setEnableAutoZoomShrink(true);
        fbv_22.setMaxWidth(270);
        fbv_22.setMinWidth(100);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("windowTitle");
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("actionText");
        fsj_22.setName("cosmeticPresetEdition");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_27);
        faw_27.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setPrefSize(new fsm_1(32, 32));
        fad_12.setStyle("crossTertiary");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        faw_27.X(fad_12);
        fad_12.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 0, 12));
        fad_12.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLP);
        fad_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string = "windowContentContainer";
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_28);
        }
        faw_28.setPrefSize(new fsm_1(360, 150));
        faw_24.X(faw_28);
        faw_28.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_28.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_28.X(faw_29);
        faw_29.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_28.X(faw_210);
        faw_210.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_210.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_211 = faw_210;
        fys_0 fys_03 = ((fes_2)faw_211).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_210.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(12, 10, 12, 10));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        String string2 = "editionView";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, frv_12);
        }
        faw_210.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("value");
        fsj_23.setName("cosmeticPresetEdition");
        frv_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_210.X(faw_212);
        faw_212.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_212.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_212.X(faw_213);
        faw_213.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        frz_24.setVgap((short)12);
        faw_213.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setExpandable(false);
        faw_213.X(faw_214);
        faw_214.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        frz_25.setVgap((short)8);
        faw_214.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setStyle("wipLight16");
        String string3 = "%name%";
        string3 = string3.replace("%name%", fyw_0.gqw().k("name", new Object[0]));
        fbv_24.setText(string3);
        faw_214.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string4 = "presetNameTE";
        fdv_1 fdv_12 = new fdv_1();
        fdv_12.aVI();
        fdv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdv_12);
        }
        fdv_12.setFocusable(true);
        fdv_12.setFocused(true);
        fdv_12.setMaxCharacters(20);
        fmn_1 fmn_12 = new fmn_1();
        fmn_12.vw("wakfu.cosmeticPresets:validatePresetName(presetNameTE,editionView)");
        fdv_12.setOnSearch(fmn_12);
        fdv_12.setSearchOnPressEnter(true);
        fdv_12.setSelectOnFocus(true);
        fdv_12.setStyle("defaultTextEditor");
        fdv_12.setWithClearButton(true);
        faw_214.X(fdv_12);
        fdv_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("defaultName");
        fsj_24.setName("cosmeticPresetEdition");
        fdv_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdv_12.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_213.X(faw_215);
        faw_215.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setField("displayIcons");
        fsj_25.setName("cosmeticPresetEdition");
        faw_215.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHorizontal(false);
        frz_26.setVgap((short)8);
        faw_215.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setStyle("wipLight16");
        String string5 = "%icon%";
        string5 = string5.replace("%icon%", fyw_0.gqw().k("icon", new Object[0]));
        fbv_25.setText(string5);
        faw_215.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_216.setPrefSize(new fsm_1(100.0f, 100.0f));
        faw_216.setStyle("ContentContainer1");
        faw_215.X(faw_216);
        faw_216.guy();
        faw_2 faw_217 = faw_216;
        fys_0 fys_04 = ((fes_2)faw_217).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_216.X(fys_04);
        fys_04.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(6, 13, 6, 6));
        fys_04.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_04.onChildrenAdded();
        String string6 = "iconList";
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fbz_22);
        }
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(63, 63));
        fbz_22.setHideContainerWithoutItem(true);
        fbz_22.setIdealSizeMaxColumns(5);
        fbz_22.setIdealSizeMaxRows(3);
        fbz_22.setIdealSizeMinColumns(5);
        fbz_22.setIdealSizeMinRows(1);
        fbz_22.setScrollBar(true);
        fbz_22.setStyle("equipmentList");
        faw_216.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("content");
        fsj_26.setField("icons");
        fsj_26.setName("cosmeticPresetEdition");
        fbz_22.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("selectedValue");
        fsj_27.setField("selectedIcon");
        fsj_27.setName("cosmeticPresetEdition");
        fbz_22.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        String string7 = "iconSelection";
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fje_22);
        }
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.cosmeticPresets:selectIconInEditDialog(editionView)");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setStyle("equipmentSlot");
        fje_22.X(faw_218);
        faw_218.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_218.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_218.X(faw_219);
        faw_219.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        faw_219.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        faw_219.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(56, 56));
        fbt_12.setNonBlocking(true);
        faw_219.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        fbt_12.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("texture");
        fsd_12.setField("iconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setDisplaySize(new fsm_1(66, 66));
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("selectorBorder");
        fbt_13.setVisible(false);
        faw_219.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLg);
        fbt_13.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("visible");
        fbt_13.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsd_13.X(fjt_23);
        fjt_23.guy();
        fjx_2 fjx_22 = new fjx_2();
        fjx_22.aVI();
        fjx_22.setElementMap(fhs_23);
        fjx_22.setValue("selected");
        fjx_22.setWidgetId("iconSelection");
        fjt_23.X(fjx_22);
        fjx_22.guy();
        fjx_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_13.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_219.onChildrenAdded();
        faw_218.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        faw_220.setExpandable(false);
        faw_212.X(faw_220);
        faw_220.guy();
        faw_2 faw_221 = faw_220;
        fys_0 fys_05 = ((fes_2)faw_221).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_220.X(fys_05);
        fys_05.guy();
        this.d(fys_05);
        fys_05.onChildrenAdded();
        this.c(faw_220);
        this.d(faw_220);
        this.e(faw_220);
        faw_220.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_24.onChildrenAdded();
        this.n(fey_22);
        this.q(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 d(fys_0 fys_02) {
        fhs_2 fhs_22 = this.nei.peek();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(12, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        return fzv2;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHgap((short)12);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        return null;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(160, 52));
        fad_12.setStyle("secondaryLarge");
        String string = "%cancel%";
        string = string.replace("%cancel%", fyw_0.gqw().k("cancel", new Object[0]));
        fad_12.setText(string);
        faw_22.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.cosmeticPresets:validatePresetName(presetNameTE,editionView)");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(160, 52));
        fad_12.setStyle("primaryLarge");
        faw_22.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("actionText");
        fsj_22.setName("cosmeticPresetEdition");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setResizeOnce(true);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

