/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cJm
 */
public class cjm_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        feq_1 feq_12 = new feq_1();
        feq_12.aVI();
        feq_12.setElementMap(fhs_23);
        feq_12.setAlign(faa_2.tLL);
        feq_12.setNonBlocking(true);
        feq_12.setPack(true);
        feq_12.setXOffset(0);
        feq_12.setYOffset(0);
        feq_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setNonBlocking(true);
        feq_12.X(faw_22);
        faw_22.guy();
        frz_2 frz_22 = frz_2.checkOut();
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setNonBlocking(true);
        faw_23.setPrefSize(new fsm_1(14, 18));
        faw_23.setStyle("characterBookBar");
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(8, 0, 7, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("visible");
        fsj_22.setField("slots");
        fsj_22.setLocal(true);
        fsj_22.setName("collectInProgress");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_23);
        fjt_22.X(fja_12);
        fja_12.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_23);
        fjv_12.setValue("0");
        fja_12.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fcb_1 fcb_12 = new fcb_1();
        fcb_12.aVI();
        fcb_12.setElementMap(fhs_23);
        fcb_12.setNonBlocking(true);
        fcb_12.setStyle("CollectNumberCharacters");
        faw_23.X(fcb_12);
        fcb_12.guy();
        fcb_1 fcb_13 = fcb_12;
        fys_0 fys_03 = ((fes_2)fcb_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fcb_12.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 2, 0, 0));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("repeatNumber");
        fsj_23.setField("slots");
        fsj_23.setLocal(true);
        fsj_23.setName("collectInProgress");
        fcb_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fcb_12.onChildrenAdded();
        fcb_1 fcb_14 = new fcb_1();
        fcb_14.aVI();
        fcb_14.setElementMap(fhs_23);
        fcb_14.setNonBlocking(true);
        fcb_14.setPrefSize(new fsm_1(10, 18));
        fcb_14.setStyle("waitOthers");
        faw_23.X(fcb_14);
        fcb_14.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("visible");
        fsj_24.setField("wait");
        fsj_24.setLocal(true);
        fsj_24.setName("collectInProgress");
        fcb_14.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsj_24.X(fjt_23);
        fjt_23.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjt_23.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("repeatNumber");
        fsj_25.setField("drawNumber");
        fsj_25.setLocal(true);
        fsj_25.setName("collectInProgress");
        fcb_14.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fcb_14.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setNonBlocking(true);
        faw_25.setPrefSize(new fsm_1(120, 40));
        faw_22.X(faw_25);
        faw_25.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_25.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setNonBlocking(true);
        faw_26.setPrefSize(new fsm_1(100, 40));
        faw_26.setStyle("ProgressBarCollect");
        faw_25.X(faw_26);
        faw_26.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(120, 40));
        frp_12.setX(0);
        frp_12.setY(0);
        faw_26.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setNonBlocking(true);
        faw_27.setPrefSize(new fsm_1(16, 16));
        faw_25.X(faw_27);
        faw_27.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(16, 16));
        frp_13.setX(9);
        frp_13.setY(11);
        faw_27.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(16, 16));
        fbt_12.setNonBlocking(true);
        fbt_12.setScaled(true);
        faw_27.X(fbt_12);
        fbt_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("style");
        fsj_26.setField("iconskill");
        fsj_26.setLocal(true);
        fsj_26.setName("collectInProgress");
        fbt_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_25.X(faw_28);
        faw_28.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(82, 40));
        frp_14.setX(27);
        frp_14.setY(0);
        faw_28.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_29 = faw_28;
        fys_0 fys_04 = ((fes_2)faw_29).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_28.X(fys_04);
        fys_04.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 5, 0, 0));
        fys_04.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_04.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_28.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        String string = "progressBarWait";
        fce_2 fce_22 = new fce_2();
        fce_22.aVI();
        fce_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fce_22);
        }
        fce_22.setNonBlocking(true);
        fce_22.setStyle("XP2");
        faw_28.X(fce_22);
        fce_22.guy();
        fce_2 fce_23 = fce_22;
        fzg fzg2 = (fzg)((fes_2)fce_23).getAppearance();
        fzg2.setElementMap(fhs_23);
        fce_22.X(fzg2);
        fzg2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(1, 1, 1, 1));
        fzg2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("errorColor"));
        fyp_02.setName("progressBar");
        fzg2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzg2.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("visible");
        fsj_27.setField("wait");
        fsj_27.setLocal(true);
        fsj_27.setName("collectInProgress");
        fce_22.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 15));
        frp_15.setYOffset(-1);
        fce_22.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fce_22.onChildrenAdded();
        String string2 = "progressBar";
        fce_2 fce_24 = new fce_2();
        fce_24.aVI();
        fce_24.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fce_24);
        }
        fce_24.setNonBlocking(true);
        fce_24.setStyle("XP2");
        faw_28.X(fce_24);
        fce_24.guy();
        fce_2 fce_25 = fce_24;
        fzg fzg3 = (fzg)((fes_2)fce_25).getAppearance();
        fzg3.setElementMap(fhs_23);
        fce_24.X(fzg3);
        fzg3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(1, 1, 1, 1));
        fzg3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzg3.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("visible");
        fsj_28.setField("wait");
        fsj_28.setLocal(true);
        fsj_28.setName("collectInProgress");
        fce_24.X(fsj_28);
        fsj_28.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fsj_28.X(fjt_24);
        fjt_24.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjt_24.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_28.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(100.0f, 15));
        frp_16.setYOffset(-1);
        fce_24.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fce_24.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setNonBlocking(true);
        faw_210.setStyle("ProgressBar");
        faw_28.X(faw_210);
        faw_210.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setSize(new fsm_1(100.0f, 15));
        frp_17.setYOffset(-1);
        faw_210.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_22.onChildrenAdded();
        feq_12.onChildrenAdded();
        return feq_12;
    }
}

