/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cJP
 */
public class cjp_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "craftTableWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setName("craftTableName");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_211.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_211.X(faw_212);
        faw_212.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_212.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(64, 64));
        fbt_12.setExpandable(false);
        faw_212.X(fbt_12);
        fbt_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("style");
        fsj_23.setField("craftBigIcon");
        fsj_23.setLocal(true);
        fsj_23.setName("craft");
        fbt_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_212.X(faw_213);
        faw_213.guy();
        faw_2 faw_214 = faw_213;
        fys_0 fys_06 = ((fes_2)faw_214).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_213.X(fys_06);
        fys_06.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 5, 0, 0));
        fys_06.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_06.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLL);
        frz_26.setHorizontal(false);
        faw_213.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setMaxWidth(235);
        fbv_24.setPrefSize(new fsm_1(235, 0));
        fbv_24.setStyle("title");
        faw_213.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlignment(faa_2.tLN);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 3, 0, 0));
        fzq3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("mecanicDarkBlueColor"));
        fzq3.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("name");
        fsj_24.setLocal(true);
        fsj_24.setName("craft");
        fbv_24.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_215.setStyle("white");
        faw_213.X(faw_215);
        faw_215.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_215.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_216 = faw_215;
        fys_0 fys_07 = ((fes_2)faw_216).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_215.X(fys_07);
        fys_07.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(5, 6, 5, 6));
        fys_07.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_07.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setField("isInnate");
        fsj_25.setLocal(true);
        fsj_25.setName("craft");
        faw_215.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_25.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fce_2 fce_22 = new fce_2();
        fce_22.aVI();
        fce_22.setElementMap(fhs_23);
        fce_22.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(xpPopup)");
        fce_22.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fce_22.setOnPopupHide(fml_12);
        fce_22.setStyle("XP2Wakfu");
        fce_22.setTweenDuration(1000L);
        fce_22.setUseDecreaseProgressTween(false);
        faw_215.X(fce_22);
        fce_22.guy();
        String string3 = "xpPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fce_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setPrefSize(new fsm_1(10, 0));
        faw_217.setStyle("popup");
        frx_12.X(faw_217);
        faw_217.guy();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setStyle("PopupInformation");
        faw_217.X(fbv_26);
        fbv_26.guy();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq4 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlignment(faa_2.tLN);
        fbv_26.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("text");
        fsj_26.setField("xpRatio");
        fsj_26.setLocal(true);
        fsj_26.setName("craft");
        fbv_26.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_217.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 14));
        frp_14.setXOffset(1);
        fce_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("initialValue");
        fsj_27.setField("nextXpPercentageInit");
        fsj_27.setLocal(true);
        fsj_27.setName("craft");
        fce_22.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("value");
        fsj_28.setField("nextXpPercentage");
        fsj_28.setLocal(true);
        fsj_28.setName("craft");
        fce_22.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("visible");
        fsj_29.setField("nextXpPercentage");
        fsj_29.setLocal(true);
        fsj_29.setName("craft");
        fce_22.X(fsj_29);
        fsj_29.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsj_29.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjt_23.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_29.onChildrenAdded();
        fce_22.onChildrenAdded();
        fce_2 fce_23 = new fce_2();
        fce_23.aVI();
        fce_23.setElementMap(fhs_23);
        fce_23.setNonBlocking(true);
        fce_23.setStyle("XP2");
        fce_23.setTweenDuration(1000L);
        fce_23.setUseDecreaseProgressTween(false);
        faw_215.X(fce_23);
        fce_23.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 14));
        frp_15.setXOffset(1);
        fce_23.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("value");
        fsj_210.setField("currentXpPercentage");
        fsj_210.setLocal(true);
        fsj_210.setName("craft");
        fce_23.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fce_23.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setPrefSize(new fsm_1(0, 11));
        faw_218.setStyle("ProgressBar");
        faw_215.X(faw_218);
        faw_218.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(100.0f, 14));
        faw_218.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        faw_218.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setExpandable(false);
        fbv_28.setNonBlocking(true);
        fbv_28.setStyle("bold");
        faw_215.X(fbv_28);
        fbv_28.guy();
        fbv_2 fbv_29 = fbv_28;
        fzq fzq5 = (fzq)((fes_2)fbv_29).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlignment(faa_2.tLO);
        fbv_28.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setYOffset(1);
        fbv_28.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_23);
        fsj_211.setAttribute("text");
        fsj_211.setField("levelText");
        fsj_211.setLocal(true);
        fsj_211.setName("craft");
        fbv_28.X(fsj_211);
        fsj_211.guy();
        fsj_211.onChildrenAdded();
        fbv_28.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_219.setExpandable(false);
        faw_212.X(faw_219);
        faw_219.guy();
        fsj_2 fsj_212 = fsj_2.checkOut();
        fsj_212.setElementMap(fhs_23);
        fsj_212.setAttribute("visible");
        fsj_212.setField("hasBook");
        fsj_212.setLocal(true);
        fsj_212.setName("craft");
        faw_219.X(fsj_212);
        fsj_212.guy();
        fsj_212.onChildrenAdded();
        this.R(faw_219);
        this.c(faw_219);
        this.d(faw_219);
        this.e(faw_219);
        faw_219.onChildrenAdded();
        faw_212.onChildrenAdded();
        this.F(faw_211);
        this.h(faw_211);
        faw_211.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.k(fey_22);
        this.o(fey_22);
        this.p(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        return null;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(2, 15, 2, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        return fys_02;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.crafts:openLinkedBook");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descCraftBookButton)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        faw_22.X(fad_12);
        fad_12.guy();
        String string = "descCraftBookButton";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_23.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMinWidth(150);
        fdy_12.setStyle("white");
        String string2 = "%desc.openCraftInfos%";
        string2 = string2.replace("%desc.openCraftInfos%", fyw_0.gqw().k("desc.openCraftInfos", new Object[0]));
        fdy_12.setText(string2);
        faw_23.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(42, 42));
        fbt_12.setNonBlocking(true);
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 5, 0, 5));
        fyY2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fyY2.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("texture");
        fsj_22.setField("bookIconUrl");
        fsj_22.setLocal(true);
        fsj_22.setName("craft");
        fze2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setStyle("caracs");
        faw_23.X(faw_25);
        faw_25.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_25.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_03 = ((fes_2)faw_26).getAppearance();
        fys_03.setElementMap(fhs_22);
        fys_03.setModulationColor(new fhl_2("gray90Color"));
        faw_25.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(29, 0, 0, 0));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_25.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_22);
        fcq_22.setExpandable(false);
        fcq_22.setPrefSize(new fsm_1(375, 300));
        faw_23.X(fcq_22);
        fcq_22.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        frp_13.setXOffset(3);
        fcq_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fcq_2 fcq_23 = fcq_22;
        fys_0 fys_04 = ((fes_2)fcq_23).getAppearance();
        fys_04.setElementMap(fhs_22);
        fcq_22.X(fys_04);
        fys_04.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(36, 5, 5, 0));
        fys_04.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_04.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(40, 40));
        fbz_22.setHorizontal(false);
        fbz_22.setIdealSizeMaxColumns(9);
        fbz_22.setIdealSizeMinColumns(9);
        fbz_22.setScrollBarBehaviour(fzi_0.tHc);
        fbz_22.setSelectionTogglable(false);
        fcq_22.X(fbz_22);
        fbz_22.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        fbz_22.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("bags/allItemsView/bagInventory");
        fsj_22.setName("localPlayer");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("enableDND");
        fsj_23.setName("craftRunning");
        fbz_22.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmk_1 fmk_12 = new fmk_1();
        fmk_12.vw("wakfu.craftTable:dropIngredient");
        fje_22.setOnDrop(fmk_12);
        fml_2 fml_22 = new fml_2();
        fml_22.vw("wakfu.craftTable:inventoryDropOutItem");
        fje_22.setOnDropOut(fml_22);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.craftTable:openItemDetailWindow(craftTableWindow)");
        fje_22.setOnItemClick(fmo_22);
        fmp_1 fmp_12 = new fmp_1();
        fmp_12.vw("wakfu.craftTable:addIngredient");
        fje_22.setOnItemDoubleClick(fmp_12);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_22.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_23.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        String string = "currentItem";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        fje_22.X(faw_27);
        faw_27.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_27.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        String string2 = "itemContainer";
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, faw_28);
        }
        faw_28.setNonBlocking(false);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.craftTable:changeItemBackground(currentItem,itemPopup)");
        faw_28.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.craftTable:changeItemBackground(currentItem,itemPopup)");
        faw_28.setOnMouseExit(fmf_22);
        faw_27.X(faw_28);
        faw_28.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(43, 43));
        faw_28.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        String string3 = "itemPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_28.X(frx_12);
        frx_12.guy();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setPrefSize(new fsm_1(10, 0));
        faw_29.setStyle("popup");
        frx_12.X(faw_29);
        faw_29.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_29.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("visible");
        fsd_13.setField("name");
        faw_29.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fsd_13.X(fjt_24);
        fjt_24.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjt_24.X(fja_12);
        fja_12.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjv_12.setValue("");
        fja_12.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_29.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("PopupInformation");
        faw_29.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fbv_22.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("PopupInformation");
        faw_29.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlignment(faa_2.tLN);
        fdy_12.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("gray80Color", 0.8f));
        fzq3.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("visible");
        fsd_15.setField("craftMovable");
        fdy_12.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fsd_15.X(fjt_25);
        fjt_25.guy();
        fjg_2 fjg_22 = new fjg_2();
        fjg_22.aVI();
        fjg_22.setElementMap(fhs_22);
        fjt_25.X(fjg_22);
        fjg_22.guy();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_22);
        fjg_22.X(fjw_23);
        fjw_23.guy();
        fjw_23.onChildrenAdded();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjg_22.X(fjl_12);
        fjl_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("comparedValue");
        fsj_24.setName("craftRunning");
        fjl_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fjl_12.onChildrenAdded();
        fjg_22.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsd_15.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("craftRequirement");
        fdy_12.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setExpandable(false);
        fdy_14.setStyle("PopupInformation");
        String string4 = "%doubleClickToAddOne%";
        string4 = string4.replace("%doubleClickToAddOne%", fyw_0.gqw().k("doubleClickToAddOne", new Object[0]));
        fdy_14.setText(string4);
        faw_29.X(fdy_14);
        fdy_14.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("visible");
        fsd_17.setField("craftMovable");
        fdy_14.X(fsd_17);
        fsd_17.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_22);
        fsd_17.X(fjt_26);
        fjt_26.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_26.X(fjn_22);
        fjn_22.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_22);
        fjn_22.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjw_2 fjw_24 = new fjw_2();
        fjw_24.aVI();
        fjw_24.setElementMap(fhs_22);
        fjn_22.X(fjw_24);
        fjw_24.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("comparedValue");
        fsj_25.setName("craftRunning");
        fjw_24.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fjw_24.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_26.onChildrenAdded();
        fsd_17.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq4 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlignment(faa_2.tLN);
        fdy_14.X(fzq4);
        fzq4.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new fhl_2("gray80Color", 0.8f));
        fzq4.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_29.onChildrenAdded();
        frx_12.onChildrenAdded();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_22);
        fsd_18.setAttribute("style");
        fsd_18.setField("usedInCurrentRecipe");
        faw_28.X(fsd_18);
        fsd_18.guy();
        fjt_2 fjt_27 = new fjt_2();
        fjt_27.aVI();
        fjt_27.setElementMap(fhs_22);
        fjt_27.setElseValue("itemBackground");
        fjt_27.setValue("itemSetSelectedBackground");
        fsd_18.X(fjt_27);
        fjt_27.guy();
        fjl_1 fjl_14 = new fjl_1();
        fjl_14.aVI();
        fjl_14.setElementMap(fhs_22);
        fjt_27.X(fjl_14);
        fjl_14.guy();
        fjl_14.onChildrenAdded();
        fjt_27.onChildrenAdded();
        fsd_18.onChildrenAdded();
        fbd_1 fbd_12 = new fbd_1();
        fbd_12.aVI();
        fbd_12.setElementMap(fhs_22);
        fmh_1 fmh_12 = new fmh_1();
        fmh_12.vw("wakfu.craftTable:inventoryDragItem(currentItem)");
        fbd_12.setOnDrag(fmh_12);
        fmk_1 fmk_13 = new fmk_1();
        fmk_13.vw("wakfu.craftTable:inventoryDropOutItem");
        fbd_12.setOnDrop(fmk_13);
        faw_28.X(fbd_12);
        fbd_12.guy();
        fsd_1 fsd_19 = new fsd_1();
        fsd_19.aVI();
        fsd_19.setElementMap(fhs_22);
        fsd_19.setAttribute("dragEnabled");
        fsd_19.setField("craftMovable");
        fbd_12.X(fsd_19);
        fsd_19.guy();
        fjt_2 fjt_28 = new fjt_2();
        fjt_28.aVI();
        fjt_28.setElementMap(fhs_22);
        fsd_19.X(fjt_28);
        fjt_28.guy();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_22);
        fjt_28.X(fjn_23);
        fjn_23.guy();
        fjl_1 fjl_15 = new fjl_1();
        fjl_15.aVI();
        fjl_15.setElementMap(fhs_22);
        fjn_23.X(fjl_15);
        fjl_15.guy();
        fjl_15.onChildrenAdded();
        fjw_2 fjw_25 = new fjw_2();
        fjw_25.aVI();
        fjw_25.setElementMap(fhs_22);
        fjn_23.X(fjw_25);
        fjw_25.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("comparedValue");
        fsj_26.setName("craftRunning");
        fjw_25.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fjw_25.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjt_28.onChildrenAdded();
        fsd_19.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fbd_12.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(38, 38));
        fbt_12.setNonBlocking(true);
        fbd_12.X(fbt_12);
        fbt_12.guy();
        this.r(fbt_12);
        this.s(fbt_12);
        fbt_12.onChildrenAdded();
        this.g(fbd_12);
        this.f(fbd_12);
        fbd_12.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_27.onChildrenAdded();
        fje_22.onChildrenAdded();
        this.u(fbz_22);
        fbz_22.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 r(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 s(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("iconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 g(fbd_1 fbd_12) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fbd_12.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(40, 40));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("craftMovable");
        faw_22.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsd_12.X(fjt_22);
        fjt_22.guy();
        fjg_2 fjg_22 = new fjg_2();
        fjg_22.aVI();
        fjg_22.setElementMap(fhs_22);
        fjt_22.X(fjg_22);
        fjg_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjg_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjg_22.X(fjl_12);
        fjl_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("comparedValue");
        fsj_22.setName("craftRunning");
        fjl_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fjl_12.onChildrenAdded();
        fjg_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_12.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.3f));
        fys_02.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 f(fbd_1 fbd_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("White10Bordered");
        fbd_12.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("quantity");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsd_12.X(fjt_22);
        fjt_22.guy();
        fjp_1 fjp_12 = new fjp_1();
        fjp_12.aVI();
        fjp_12.setElementMap(fhs_22);
        fjp_12.setValue("1");
        fjt_22.X(fjp_12);
        fjp_12.guy();
        fjp_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 6, 6, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("quantity");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 u(fbz_2 fbz_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmk_1 fmk_12 = new fmk_1();
        fmk_12.vw("wakfu.craftTable:dropIngredient");
        fje_22.setOnDrop(fmk_12);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fje_22.X(faw_22);
        faw_22.guy();
        fbd_1 fbd_12 = new fbd_1();
        fbd_12.aVI();
        fbd_12.setElementMap(fhs_22);
        fbd_12.setDragEnabled(false);
        fmk_1 fmk_13 = new fmk_1();
        fmk_13.vw("wakfu.craftTable:inventoryDropOutItem");
        fbd_12.setOnDrop(fmk_13);
        faw_22.X(fbd_12);
        fbd_12.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fbd_12.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        String string = "itemBackgroundContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setStyle("itemBackground");
        fbd_12.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(43, 43));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        fbd_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 h(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(0, 90));
        faw_23.setStyle("white");
        faw_22.X(faw_23);
        faw_23.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(7, 12, 7, 12));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_23.X(faw_25);
        faw_25.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tKY);
        faw_25.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        String string = "ingredientList";
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fbz_22);
        }
        fbz_22.setCellSize(new fsm_1(45, 45));
        fbz_22.setPrefSize(new fsm_1(180, 90));
        faw_25.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setName("recipeIngredientStack");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("enableDND");
        fsj_23.setName("craftRunning");
        fbz_22.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjn_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fml_2 fml_22 = new fml_2();
        fml_22.vw("wakfu.craftTable:itemDropOut");
        fje_22.setOnDropOut(fml_22);
        fmp_1 fmp_12 = new fmp_1();
        fmp_12.vw("wakfu.craftTable:removeIngredient");
        fje_22.setOnItemDoubleClick(fmp_12);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_22.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_23.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        fje_22.X(faw_26);
        faw_26.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_26.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setNonBlocking(false);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.craftTable:changeItemBackground()");
        faw_27.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.craftTable:changeItemBackground()");
        faw_27.setOnMouseExit(fmf_22);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descIngredient)");
        faw_27.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_27.setOnPopupHide(fml_12);
        faw_27.setStyle("itemBackground");
        faw_26.X(faw_27);
        faw_27.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        faw_27.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        String string2 = "descIngredient";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_27.X(frx_12);
        frx_12.guy();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setPrefSize(new fsm_1(10, 0));
        faw_28.setStyle("popup");
        frx_12.X(faw_28);
        faw_28.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_28.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_28.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("white");
        faw_28.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setExpandable(false);
        fdy_14.setStyle("white");
        String string3 = "(%desc.missingIngredient%)";
        string3 = string3.replace("%desc.missingIngredient%", fyw_0.gqw().k("desc.missingIngredient", new Object[0]));
        fdy_14.setText(string3);
        faw_28.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLN);
        fdy_14.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("visible");
        fsd_13.setField("isPossessed");
        fdy_14.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fsd_13.X(fjt_24);
        fjt_24.guy();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_22);
        fjt_24.X(fjw_23);
        fjw_23.guy();
        fjw_23.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_13.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        fdy_16.setExpandable(false);
        fdy_16.setStyle("PopupInformation");
        String string4 = "%doubleClickToRemoveOne%";
        string4 = string4.replace("%doubleClickToRemoveOne%", fyw_0.gqw().k("doubleClickToRemoveOne", new Object[0]));
        fdy_16.setText(string4);
        faw_28.X(fdy_16);
        fdy_16.guy();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq4 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlignment(faa_2.tLN);
        fdy_16.X(fzq4);
        fzq4.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("gray80Color", 0.8f));
        fzq4.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_28.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbd_1 fbd_12 = new fbd_1();
        fbd_12.aVI();
        fbd_12.setElementMap(fhs_22);
        fmk_1 fmk_12 = new fmk_1();
        fmk_12.vw("wakfu.craftTable:dropItem");
        fbd_12.setOnDrop(fmk_12);
        faw_27.X(fbd_12);
        fbd_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("dropEnabled");
        fsj_24.setName("craftRunning");
        fbd_12.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fsj_24.X(fjt_25);
        fjt_25.guy();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_22);
        fjt_25.X(fjn_23);
        fjn_23.guy();
        fjw_2 fjw_24 = new fjw_2();
        fjw_24.aVI();
        fjw_24.setElementMap(fhs_22);
        fjn_23.X(fjw_24);
        fjw_24.guy();
        fjw_24.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        fbd_12.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(41, 41));
        fbt_12.setNonBlocking(true);
        fbd_12.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("texture");
        fsd_14.setField("iconUrl");
        fze2.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("White10Bordered");
        fbd_12.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLo);
        fbv_22.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq5 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq5.setElementMap(fhs_22);
        fbv_22.X(fzq5);
        fzq5.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 4, 4));
        fzq5.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq5.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("quantity");
        fbv_22.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbd_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_26.onChildrenAdded();
        fje_22.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fbz_22.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_22);
        fje_23.X(fjt_26);
        fjt_26.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjt_26.X(fjx_13);
        fjx_13.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_13.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_26.onChildrenAdded();
        String string5 = "ingredientBackgroundContainer";
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        if (fhs_22 != null && string5 != null) {
            fhs_22.a(string5, faw_29);
        }
        faw_29.setStyle("itemBackground");
        fje_23.X(faw_29);
        faw_29.guy();
        fbd_1 fbd_13 = new fbd_1();
        fbd_13.aVI();
        fbd_13.setElementMap(fhs_22);
        fbd_13.setDragEnabled(false);
        fmk_1 fmk_13 = new fmk_1();
        fmk_13.vw("wakfu.craftTable:dropItem");
        fbd_13.setOnDrop(fmk_13);
        faw_29.X(fbd_13);
        fbd_13.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("dropEnabled");
        fsj_25.setName("craftRunning");
        fbd_13.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_27 = new fjt_2();
        fjt_27.aVI();
        fjt_27.setElementMap(fhs_22);
        fsj_25.X(fjt_27);
        fjt_27.guy();
        fjn_2 fjn_24 = new fjn_2();
        fjn_24.aVI();
        fjn_24.setElementMap(fhs_22);
        fjt_27.X(fjn_24);
        fjn_24.guy();
        fjw_2 fjw_25 = new fjw_2();
        fjw_25.aVI();
        fjw_25.setElementMap(fhs_22);
        fjn_24.X(fjw_25);
        fjw_25.guy();
        fjw_25.onChildrenAdded();
        fjn_24.onChildrenAdded();
        fjt_27.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fbd_13.onChildrenAdded();
        faw_29.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_23.X(faw_210);
        faw_210.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLc);
        frp_16.setXOffset(-10);
        frp_16.setYOffset(-3);
        faw_210.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        faw_210.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        String string6 = "nbCraftText";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string6 != null) {
            fhs_22.a(string6, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.setMaxCharacters(4);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.craftTable:setCurrentCraftNumber(nbCraftText)");
        fdu_12.setOnKeyType(fmu_22);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(nbAutoPopup)");
        fdu_12.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fdu_12.setOnPopupHide(fml_13);
        fdu_12.setPrefSize(new fsm_1(30, 0));
        fdu_12.setRestrict("[0-9]+");
        faw_210.X(fdu_12);
        fdu_12.guy();
        fru_1 fru_13 = fru_1.checkOut();
        fru_13.setElementMap(fhs_22);
        fru_13.setData(fzt_0.tKw);
        fdu_12.X(fru_13);
        fru_13.guy();
        fru_13.onChildrenAdded();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq6 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq6.setElementMap(fhs_22);
        fzq6.setAlign(faa_2.tLP);
        fdu_12.X(fzq6);
        fzq6.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 2, 0, 1));
        fzq6.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq6.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("editable");
        fsj_26.setName("recipeIngredientStack");
        fdu_12.X(fsj_26);
        fsj_26.guy();
        fjt_2 fjt_28 = new fjt_2();
        fjt_28.aVI();
        fjt_28.setElementMap(fhs_22);
        fsj_26.X(fjt_28);
        fjt_28.guy();
        this.p(fjt_28);
        fjt_28.onChildrenAdded();
        fsj_26.onChildrenAdded();
        this.d(fdu_12);
        this.e(fdu_12);
        fdu_12.onChildrenAdded();
        this.j(faw_210);
        faw_210.onChildrenAdded();
        this.L(faw_23);
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 p(fjt_2 fjt_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjn_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_22);
        fjn_22.X(fjn_23);
        fjn_23.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjn_23.X(fjw_22);
        fjw_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("comparedValue");
        fsj_22.setName("craftRunning");
        fjw_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fjw_22.onChildrenAdded();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjn_23.X(fjd_13);
        fjd_13.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("comparedValue");
        fsj_23.setName("selectedRecipe");
        fjd_13.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fjd_13.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjn_22.onChildrenAdded();
        return fjn_22;
    }

    public fhi_2 d(fdu_1 fdu_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setName("currentCraftNb");
        fdu_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 e(fdu_1 fdu_12) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "nbAutoPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fdu_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("White11");
        String string2 = "%desc.nbAutoLaunch%";
        string2 = string2.replace("%desc.nbAutoLaunch%", fyw_0.gqw().k("desc.nbAutoLaunch", new Object[0]));
        fdy_12.setText(string2);
        faw_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 j(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.craftTable:setCurrentCraftMaxNumber");
        fad_12.setOnClick(fmz_12);
        String string = "%max%";
        string = string.replace("%max%", fyw_0.gqw().k("max", new Object[0]));
        fad_12.setText(string);
        faw_22.X(fad_12);
        fad_12.guy();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 2, 0, 0));
        fym_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fym_02.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("enabled");
        fsj_22.setName("recipeIngredientStack");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjn_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjn_22.X(fjw_22);
        fjw_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("comparedValue");
        fsj_23.setName("craftRunning");
        fjw_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fjw_22.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 L(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(140, 120));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLo);
        frp_12.setXOffset(-5);
        frp_12.setYOffset(-30);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLo);
        frp_13.setSize(new fsm_1(68, 68));
        frp_13.setXOffset(-11);
        frp_13.setYOffset(11);
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_24.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fce_2 fce_22 = new fce_2();
        fce_22.aVI();
        fce_22.setElementMap(fhs_22);
        fce_22.setDisplayType(fcf_2.tYc);
        fce_22.setStyle("XP2");
        fce_22.setUseIncreaseProgressTween(false);
        fce_22.setValue(1.0f);
        faw_24.X(fce_22);
        fce_22.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(72, 72));
        fce_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fce_2 fce_23 = fce_22;
        fzg fzg2 = (fzg)((fes_2)fce_23).getAppearance();
        fzg2.setElementMap(fhs_22);
        fce_22.X(fzg2);
        fzg2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("craftBackgroundProgressBarColor"));
        fyp_02.setName("progressBar");
        fzg2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzg2.onChildrenAdded();
        fce_22.onChildrenAdded();
        String string = "progressBar";
        fce_2 fce_24 = new fce_2();
        fce_24.aVI();
        fce_24.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fce_24);
        }
        fce_24.setDisplayType(fcf_2.tYc);
        fce_24.setStyle("XP2");
        fce_24.setUseDecreaseProgressTween(false);
        faw_24.X(fce_24);
        fce_24.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(72, 72));
        fce_24.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fce_2 fce_25 = fce_24;
        fzg fzg3 = (fzg)((fes_2)fce_25).getAppearance();
        fzg3.setElementMap(fhs_22);
        fce_24.X(fzg3);
        fzg3.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new fhl_2("craftActionProgressBarColor"));
        fyp_03.setName("progressBar");
        fzg3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzg3.onChildrenAdded();
        fce_24.onChildrenAdded();
        faw_24.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("CraftControlBackground");
        faw_23.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLo);
        frp_16.setSize(new fsm_1(-2, -2));
        frp_16.setXOffset(3);
        frp_16.setYOffset(-3);
        fbt_12.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_22);
        frp_17.setAlign(fzw_0.tKY);
        frp_17.setXOffset(6);
        frp_17.setYOffset(-7);
        faw_25.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_25.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("selectedRecipe");
        faw_25.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjt_22.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(itemMysteryPopup)");
        faw_26.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_26.setOnPopupHide(fml_12);
        faw_26.setPrefSize(new fsm_1(47, 47));
        faw_26.setStyle("itemMystery");
        faw_25.X(faw_26);
        faw_26.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_22);
        frp_18.setSize(new fsm_1(100.0f, 100.0f));
        faw_26.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        String string2 = "itemMysteryPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_26.X(frx_12);
        frx_12.guy();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setPrefSize(new fsm_1(10, 0));
        faw_27.setStyle("popup");
        frx_12.X(faw_27);
        faw_27.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_27.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMultiline(true);
        fdy_12.setStyle("White11");
        String string3 = "%desc.itemMystery%";
        string3 = string3.replace("%desc.itemMystery%", fyw_0.gqw().k("desc.itemMystery", new Object[0]));
        fdy_12.setText(string3);
        faw_27.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        frx_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_28.setVisible(false);
        faw_23.X(faw_28);
        faw_28.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_22);
        frp_19.setAlign(fzw_0.tKY);
        frp_19.setXOffset(5);
        frp_19.setYOffset(-8);
        faw_28.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        fro_15.setAdaptToContentSize(true);
        faw_28.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setName("selectedRecipe");
        faw_28.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_23.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_23.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_23.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setPrefSize(new fsm_1(47, 47));
        faw_29.setStyle("itemBackground");
        faw_28.X(faw_29);
        faw_29.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_22);
        frp_110.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        faw_29.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setDisplaySize(new fsm_1(47, 47));
        fbt_13.setNonBlocking(true);
        faw_28.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_111 = new frp_1();
        frp_111.aVI();
        frp_111.setElementMap(fhs_22);
        frp_111.setAlign(fzw_0.tLg);
        frp_111.setSize(new fsm_1(-2, -2));
        fbt_13.X(frp_111);
        frp_111.guy();
        frp_111.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_13.X(fze2);
        fze2.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("texture");
        fsj_24.setField("iconUrl");
        fsj_24.setName("selectedRecipe");
        fze2.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_23.X(faw_210);
        faw_210.guy();
        frp_1 frp_112 = new frp_1();
        frp_112.aVI();
        frp_112.setElementMap(fhs_22);
        frp_112.setAlign(fzw_0.tLo);
        frp_112.setXOffset(-8);
        frp_112.setYOffset(8);
        faw_210.X(frp_112);
        frp_112.guy();
        frp_112.onChildrenAdded();
        fro_1 fro_16 = new fro_1();
        fro_16.aVI();
        fro_16.setAdaptToContentSize(true);
        faw_210.X(fro_16);
        fro_16.guy();
        fro_16.onChildrenAdded();
        String string4 = "startButton";
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        if (fhs_22 != null && string4 != null) {
            fhs_22.a(string4, fdd_22);
        }
        fdd_22.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.craftTable:startCraft(progressBar)");
        fdd_22.setOnClick(fmz_12);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(startButtonPopup)");
        fdd_22.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fdd_22.setOnPopupHide(fml_13);
        fdd_22.setStyle("StartCraft");
        faw_210.X(fdd_22);
        fdd_22.guy();
        frp_1 frp_113 = new frp_1();
        frp_113.aVI();
        frp_113.setElementMap(fhs_22);
        frp_113.setAlign(fzw_0.tLg);
        fdd_22.X(frp_113);
        frp_113.guy();
        frp_113.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("enabled");
        fsj_25.setName("currentCraftNb");
        fdd_22.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fsj_25.X(fjt_24);
        fjt_24.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjt_24.X(fja_12);
        fja_12.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjv_12.setValue("0");
        fja_12.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("selected");
        fsj_26.setName("craftRunning");
        fdd_22.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        String string5 = "startButtonPopup";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_22);
        if (fhs_22 != null && string5 != null) {
            fhs_22.a(string5, frx_13);
        }
        frx_13.setAlign(faa_2.tLL);
        frx_13.setHotSpotPosition(faa_2.tLR);
        fdd_22.X(frx_13);
        frx_13.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setPrefSize(new fsm_1(10, 0));
        faw_211.setStyle("popup");
        frx_13.X(faw_211);
        faw_211.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_211.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        faw_211.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setExpandable(false);
        fdy_14.setStyle("White11");
        faw_211.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlignment(faa_2.tLN);
        fdy_14.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("text");
        fsj_27.setName("craftRunning");
        fdy_14.X(fsj_27);
        fsj_27.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        String string6 = "%desc.startCraft%";
        string6 = string6.replace("%desc.startCraft%", fyw_0.gqw().k("desc.startCraft", new Object[0]));
        fjt_25.setElseValue(string6);
        String string7 = "%desc.cancel%";
        string7 = string7.replace("%desc.cancel%", fyw_0.gqw().k("desc.cancel", new Object[0]));
        fjt_25.setValue(string7);
        fsj_27.X(fjt_25);
        fjt_25.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_25.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsj_27.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        fdy_16.setExpandable(false);
        fdy_16.setStyle("White11");
        String string8 = " (%critere.false%)";
        string8 = string8.replace("%critere.false%", fyw_0.gqw().k("critere.false", new Object[0]));
        fdy_16.setText(string8);
        faw_211.X(fdy_16);
        fdy_16.guy();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq4 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlignment(faa_2.tLN);
        fdy_16.X(fzq4);
        fzq4.guy();
        fyp_0 fyp_04 = fyp_0.checkOut();
        fyp_04.setElementMap(fhs_22);
        fyp_04.setColor(new fhl_2("redColor"));
        fzq4.X(fyp_04);
        fyp_04.guy();
        fyp_04.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_22);
        fsj_28.setAttribute("visible");
        fsj_28.setName("currentCraftNb");
        fdy_16.X(fsj_28);
        fsj_28.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_22);
        fsj_28.X(fjt_26);
        fjt_26.guy();
        fjv_1 fjv_13 = new fjv_1();
        fjv_13.aVI();
        fjv_13.setElementMap(fhs_22);
        fjv_13.setValue("0");
        fjt_26.X(fjv_13);
        fjv_13.guy();
        fjv_13.onChildrenAdded();
        fjt_26.onChildrenAdded();
        fsj_28.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_211.onChildrenAdded();
        frx_13.onChildrenAdded();
        fdd_22.onChildrenAdded();
        this.M(faw_210);
        faw_210.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 M(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("craftRunning");
        fbt_12.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("texture");
        fsj_23.setField("buttonIconUrl");
        fsj_23.setLocal(true);
        fsj_23.setName("craft");
        fze2.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("modulationColor");
        fsj_24.setName("currentCraftNb");
        fyY2.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fjt_23.setElseValue("1,1,1,0.5");
        fjt_23.setValue("1,1,1,1");
        fsj_24.X(fjt_23);
        fjt_23.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjt_23.X(fja_12);
        fja_12.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjv_12.setValue("0");
        fja_12.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 k(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 o(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "closeCraftTableDialog";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fad_12);
        }
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 p(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

