/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cJS
 */
public class cjs_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        fbv_22.setText("Debug Anm");
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_210.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        String string2 = "type";
        fry_1 fry_12 = new fry_1();
        fry_12.aVI();
        fry_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, (fhv_1)fry_12);
        }
        faw_211.X(fry_12);
        fry_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("value");
        fsj_22.setField("type");
        fsj_22.setName("debug.anm");
        fry_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fry_12.onChildrenAdded();
        fcu_1 fcu_12 = new fcu_1();
        fcu_12.aVI();
        fcu_12.setElementMap(fhs_23);
        fcu_12.setEnabled(true);
        fcu_12.setGroupId("type");
        fmi_2 fmi_22 = new fmi_2();
        fmi_22.vw("wakfu.debugAnm:setType(players)");
        fcu_12.setOnMouseRelease(fmi_22);
        fcu_12.setText("player");
        fcu_12.setValue("players");
        faw_211.X(fcu_12);
        fcu_12.guy();
        fcu_1 fcu_13 = fcu_12;
        fzk fzk2 = (fzk)((fes_2)fcu_13).getAppearance();
        fzk2.setElementMap(fhs_23);
        fcu_12.X(fzk2);
        fzk2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 2, 0, 2));
        fzk2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzk2.onChildrenAdded();
        fcu_12.onChildrenAdded();
        fcu_1 fcu_14 = new fcu_1();
        fcu_14.aVI();
        fcu_14.setElementMap(fhs_23);
        fcu_14.setEnabled(true);
        fcu_14.setGroupId("type");
        fmi_2 fmi_23 = new fmi_2();
        fmi_23.vw("wakfu.debugAnm:setType(npcs)");
        fcu_14.setOnMouseRelease(fmi_23);
        fcu_14.setText("monstre");
        fcu_14.setValue("npcs");
        faw_211.X(fcu_14);
        fcu_14.guy();
        fcu_1 fcu_15 = fcu_14;
        fzk fzk3 = (fzk)((fes_2)fcu_15).getAppearance();
        fzk3.setElementMap(fhs_23);
        fcu_14.X(fzk3);
        fzk3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 2, 0, 2));
        fzk3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzk3.onChildrenAdded();
        fcu_14.onChildrenAdded();
        fcu_1 fcu_16 = new fcu_1();
        fcu_16.aVI();
        fcu_16.setElementMap(fhs_23);
        fcu_16.setEnabled(true);
        fcu_16.setGroupId("type");
        fmi_2 fmi_24 = new fmi_2();
        fmi_24.vw("wakfu.debugAnm:setType(pets)");
        fcu_16.setOnMouseRelease(fmi_24);
        fcu_16.setText("pets");
        fcu_16.setValue("pets");
        faw_211.X(fcu_16);
        fcu_16.guy();
        fcu_1 fcu_17 = fcu_16;
        fzk fzk4 = (fzk)((fes_2)fcu_17).getAppearance();
        fzk4.setElementMap(fhs_23);
        fcu_16.X(fzk4);
        fzk4.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 2, 0, 2));
        fzk4.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzk4.onChildrenAdded();
        fcu_16.onChildrenAdded();
        fcu_1 fcu_18 = new fcu_1();
        fcu_18.aVI();
        fcu_18.setElementMap(fhs_23);
        fcu_18.setEnabled(true);
        fcu_18.setGroupId("type");
        fmi_2 fmi_25 = new fmi_2();
        fmi_25.vw("wakfu.debugAnm:setType(interactives)");
        fcu_18.setOnMouseRelease(fmi_25);
        fcu_18.setText("interactif");
        fcu_18.setValue("interactives");
        faw_211.X(fcu_18);
        fcu_18.guy();
        fcu_1 fcu_19 = fcu_18;
        fzk fzk5 = (fzk)((fes_2)fcu_19).getAppearance();
        fzk5.setElementMap(fhs_23);
        fcu_18.X(fzk5);
        fzk5.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 2, 0, 2));
        fzk5.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzk5.onChildrenAdded();
        fcu_18.onChildrenAdded();
        fcu_1 fcu_110 = new fcu_1();
        fcu_110.aVI();
        fcu_110.setElementMap(fhs_23);
        fcu_110.setEnabled(true);
        fcu_110.setGroupId("type");
        fmi_2 fmi_26 = new fmi_2();
        fmi_26.vw("wakfu.debugAnm:setType(dynamics)");
        fcu_110.setOnMouseRelease(fmi_26);
        fcu_110.setText("dynamique");
        fcu_110.setValue("dynamics");
        faw_211.X(fcu_110);
        fcu_110.guy();
        fcu_1 fcu_111 = fcu_110;
        fzk fzk6 = (fzk)((fes_2)fcu_111).getAppearance();
        fzk6.setElementMap(fhs_23);
        fcu_110.X(fzk6);
        fzk6.guy();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_23);
        fzv8.setInsets(new Insets(0, 2, 0, 2));
        fzk6.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fzk6.onChildrenAdded();
        fcu_110.onChildrenAdded();
        fcu_1 fcu_112 = new fcu_1();
        fcu_112.aVI();
        fcu_112.setElementMap(fhs_23);
        fcu_112.setEnabled(true);
        fcu_112.setGroupId("type");
        fmi_2 fmi_27 = new fmi_2();
        fmi_27.vw("wakfu.debugAnm:setType(resources)");
        fcu_112.setOnMouseRelease(fmi_27);
        fcu_112.setText("ressources");
        fcu_112.setValue("resources");
        faw_211.X(fcu_112);
        fcu_112.guy();
        fcu_1 fcu_113 = fcu_112;
        fzk fzk7 = (fzk)((fes_2)fcu_113).getAppearance();
        fzk7.setElementMap(fhs_23);
        fcu_112.X(fzk7);
        fzk7.guy();
        fzv fzv9 = fzv.checkOut();
        fzv9.setElementMap(fhs_23);
        fzv9.setInsets(new Insets(0, 2, 0, 2));
        fzk7.X(fzv9);
        fzv9.guy();
        fzv9.onChildrenAdded();
        fzk7.onChildrenAdded();
        fcu_112.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_210.X(faw_212);
        faw_212.guy();
        String string3 = "gfxId";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fdu_12);
        }
        faw_212.X(fdu_12);
        fdu_12.guy();
        fdu_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.debugAnm:setSkin(gfxId)");
        fad_12.setOnClick(fmz_12);
        fad_12.setText("set skin");
        faw_212.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        faw_212.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.debugAnm:updateLinkageList");
        fad_13.setOnClick(fmz_13);
        fad_13.setText("Mettre \u00e0 jour les linkages");
        faw_210.X(fad_13);
        fad_13.guy();
        fad_13.onChildrenAdded();
        fas_1 fas_12 = new fas_1();
        fas_12.aVI();
        fas_12.setElementMap(fhs_23);
        fas_12.setExpandable(false);
        fmv_2 fmv_22 = new fmv_2();
        fmv_22.vw("wakfu.debugAnm:selectionChanged");
        fas_12.setOnListSelectionChange(fmv_22);
        fas_12.setPrefSize(new fsm_1(200, 15));
        faw_210.X(fas_12);
        fas_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setField("linkages");
        fsj_23.setName("debug.anm");
        fas_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("selectedValue");
        fsj_24.setField("selectedLinkage");
        fsj_24.setName("debug.anm");
        fas_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fcv_1 fcv_12 = new fcv_1();
        fcv_12.aVI();
        fcv_12.setElementMap(fhs_23);
        fas_12.X(fcv_12);
        fcv_12.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fcv_12.X(fje_22);
        fje_22.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setNonBlocking(true);
        fje_22.X(fbv_24);
        fbv_24.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        fbv_24.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fbv_24.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fcv_12.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(100.0f, 16));
        fbz_22.setHorizontal(false);
        fas_12.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fbz_22.X(fje_23);
        fje_23.guy();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setNonBlocking(true);
        fje_23.X(fbv_25);
        fbv_25.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fbv_25.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq3 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_25.X(fzq3);
        fzq3.guy();
        fzv fzv10 = fzv.checkOut();
        fzv10.setElementMap(fhs_23);
        fzv10.setInsets(new Insets(0, 10, 0, 0));
        fzq3.X(fzv10);
        fzv10.guy();
        fzv10.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_25.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_22.onChildrenAdded();
        fas_12.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.debugAnm:play");
        fad_14.setOnClick(fmz_14);
        fad_14.setText("Play");
        faw_210.X(fad_14);
        fad_14.guy();
        fad_14.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        fey_22.X(faw_213);
        faw_213.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_213.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_213.onChildrenAdded();
        fad_1 fad_15 = new fad_1();
        fad_15.aVI();
        fad_15.setElementMap(fhs_23);
        fad_15.setExpandable(false);
        fad_15.setStyle("close");
        fmz_1 fmz_15 = new fmz_1();
        fmz_15.vw("unloadDialog");
        fad_15.setOnClick(fmz_15);
        fey_22.X(fad_15);
        fad_15.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLc);
        frp_15.setSize(new fsm_1(-2, -2));
        frp_15.setXOffset(-18);
        frp_15.setYOffset(-12);
        fad_15.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fad_15.onChildrenAdded();
        this.l(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 l(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

