/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cJT
 */
public class cjt_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "dimensionalBagWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setNonBlocking(true);
        fdy_12.setPrefSize(new fsm_1(0, 18));
        fdy_12.setStyle("StyledBold16White");
        String string2 = "%dimensionalBag.appearance%";
        string2 = string2.replace("%dimensionalBag.appearance%", fyw_0.gqw().k("dimensionalBag.appearance", new Object[0]));
        fdy_12.setText(string2);
        faw_25.X(fdy_12);
        fdy_12.guy();
        fdy_12.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_23.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_05 = ((fes_2)faw_28).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_27.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string3 = "windowContentContainer";
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, faw_29);
        }
        faw_27.X(faw_29);
        faw_29.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_29.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setPrefSize(new fsm_1(0, 130));
        faw_29.X(faw_210);
        faw_210.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_210.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_210.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setStyle("dimensionalBagAppearanceManagerBackground");
        faw_210.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLm);
        frp_14.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_23);
        fax_12.setAnimName("AnimStatique_1");
        fax_12.setDirection(3);
        fax_12.setNonBlocking(true);
        fax_12.setOffsetX(0.0f);
        fax_12.setOffsetY(-15.0f);
        fax_12.setScale(1.0f);
        faw_210.X(fax_12);
        fax_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        fax_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("animatedElement");
        fsj_22.setField("actorDescriptorLibrary");
        fsj_22.setName("dimensionalBag.selected.appearance");
        fax_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_29.X(faw_211);
        faw_211.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setClickSoundId(600015);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.appearanceManager:previous");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("characterCreationLeftArrow");
        faw_211.X(fad_12);
        fad_12.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLL);
        fad_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(3, 0, 0, 0));
        fym_02.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setPrefSize(new fsm_1(0, 50));
        faw_211.X(faw_212);
        faw_212.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_212.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_23);
        fdy_13.setMaxWidth(100);
        fdy_13.setMinWidth(100);
        fdy_13.setStyle("styledBold12");
        faw_212.X(fdy_13);
        fdy_13.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("name");
        fsj_23.setName("dimensionalBag.selected.appearance");
        fdy_13.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq2 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLO);
        fdy_13.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_13.onChildrenAdded();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_23);
        fdy_15.setExpandable(false);
        fdy_15.setStyle("styledBold12");
        faw_212.X(fdy_15);
        fdy_15.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setLocal(true);
        fsj_24.setName("currentPage");
        fdy_15.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_1 fdy_16 = fdy_15;
        fzq fzq3 = (fzq)((fes_2)fdy_16).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLO);
        fdy_15.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fdy_15.onChildrenAdded();
        faw_212.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        fad_14.setClickSoundId(600014);
        fad_14.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.appearanceManager:next");
        fad_14.setOnClick(fmz_13);
        fad_14.setStyle("characterCreationRightArrow");
        faw_211.X(fad_14);
        fad_14.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLL);
        fad_14.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fad_14.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        fey_22.X(faw_213);
        faw_213.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        faw_213.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        faw_213.onChildrenAdded();
        fad_1 fad_15 = new fad_1();
        fad_15.aVI();
        fad_15.setElementMap(fhs_23);
        fad_15.setExpandable(false);
        fad_15.setStyle("close");
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("unloadDialog");
        fad_15.setOnClick(fmz_14);
        fey_22.X(fad_15);
        fad_15.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLc);
        frp_17.setSize(new fsm_1(-2, -2));
        frp_17.setXOffset(-18);
        frp_17.setYOffset(-12);
        fad_15.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fad_15.onChildrenAdded();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLg);
        frp_18.setInitValue(true);
        frp_18.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

