/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKb
 */
public class ckb_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "mapWindow";
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_22);
        }
        faw_22.setNonBlocking(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.dragoMap:click");
        faw_22.setOnClick(fmz_12);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_23);
        fkk_12.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.7f));
        fys_02.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_22.X(faw_24);
        faw_24.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_24.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(-2, -2));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_24.X(faw_25);
        faw_25.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_25.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(-2, -2));
        faw_25.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_03 = ((fes_2)faw_26).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_25.X(fys_03);
        fys_03.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(100, 50, 100, 50));
        fys_03.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_03.onChildrenAdded();
        String string2 = "map";
        fbh_2 fbh_22 = new fbh_2();
        fbh_22.aVI();
        fbh_22.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fbh_22);
        }
        fbh_22.setExpandable(false);
        fbh_22.setIsoMap(true);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.dragoMap:onMapItemClick");
        fbh_22.setOnItemClick(fmo_22);
        fmq_1 fmq_12 = new fmq_1();
        fmq_12.vw("wakfu.dragoMap:onMapItemOut");
        fbh_22.setOnItemOut(fmq_12);
        fmr_2 fmr_22 = new fmr_2();
        fmr_22.vw("wakfu.dragoMap:onMapItemOver");
        fbh_22.setOnItemOver(fmr_22);
        fmw_2 fmw_22 = new fmw_2();
        fmw_22.vw("wakfu.dragoMap:onMapClick(map)");
        fbh_22.setOnMapClick(fmw_22);
        fmx_2 fmx_22 = new fmx_2();
        fmx_22.vw("wakfu.controlCenter:adminTP");
        fbh_22.setOnMapDoubleClick(fmx_22);
        fmy_1 fmy_12 = new fmy_1();
        fmy_12.vw("wakfu.dragoMap:onMapMove");
        fbh_22.setOnMapMove(fmy_12);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.dragoMap:onMouseEnter");
        fbh_22.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.dragoMap:onMouseExit");
        fbh_22.setOnMouseExit(fmf_22);
        fmh_2 fmh_22 = new fmh_2();
        fmh_22.vw("wakfu.dragoMap:onMousePress");
        fbh_22.setOnMousePress(fmh_22);
        fmi_2 fmi_22 = new fmi_2();
        fmi_22.vw("wakfu.dragoMap:onMouseRelease");
        fbh_22.setOnMouseRelease(fmi_22);
        fbh_22.setTooltipHotPoint(ahc.cvB);
        faw_25.X(fbh_22);
        fbh_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("mapPath");
        fsj_22.setField("map");
        fsj_22.setName("map");
        fbh_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("mapId");
        fsj_23.setField("mapId");
        fsj_23.setName("map");
        fbh_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("content");
        fsj_24.setField("landmarks/points");
        fsj_24.setName("map");
        fbh_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("compassContent");
        fsj_25.setField("landmarks/compass");
        fsj_25.setName("map");
        fbh_22.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("knownMaps");
        fsj_26.setField("availableMapsCoords");
        fsj_26.setName("map");
        fbh_22.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(-2, -2));
        fbh_22.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbh_2 fbh_23 = fbh_22;
        fzb fzb2 = (fzb)((fes_2)fbh_23).getAppearance();
        fzb2.setElementMap(fhs_23);
        fzb2.setShape(fzz_0.tGo);
        fbh_22.X(fzb2);
        fzb2.guy();
        fzb2.onChildrenAdded();
        fbh_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setNonBlocking(false);
        faw_27.setStyle("windowBackgroundSecondary");
        faw_22.X(faw_27);
        faw_27.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tKY);
        frp_16.setSize(new fsm_1(540, 150));
        frp_16.setXOffset(8);
        frp_16.setYOffset(-8);
        faw_27.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        faw_27.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setStyle("ornament1NE");
        faw_27.X(faw_28);
        faw_28.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tKY);
        frp_17.setSize(new fsm_1(516, 126));
        frp_17.setXOffset(12);
        frp_17.setYOffset(-12);
        faw_28.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_27.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_04 = ((fes_2)faw_210).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_29.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(12, 12, 12, 12));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        frz_22.setHgap((short)12);
        faw_29.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_211.setPrefSize(new fsm_1(120, 120));
        faw_29.X(faw_211);
        faw_211.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLN);
        faw_211.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fro_1 fro_16 = new fro_1();
        fro_16.aVI();
        faw_211.X(fro_16);
        fro_16.guy();
        fro_16.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(protectorDescPopup)");
        faw_212.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_212.setOnPopupHide(fml_12);
        faw_212.setStyle("protectorNeutralBackgroundScalable");
        faw_211.X(faw_212);
        faw_212.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setSize(new fsm_1(120, 120));
        faw_212.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fro_1 fro_17 = new fro_1();
        fro_17.aVI();
        faw_212.X(fro_17);
        fro_17.guy();
        fro_17.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setNeedsScissor(true);
        faw_212.X(faw_213);
        faw_213.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_23);
        frp_110.setAlign(fzw_0.tLg);
        frp_110.setSize(new fsm_1(108, 106));
        faw_213.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_23);
        fax_12.setAnimName("AnimStatique-Neutre");
        fax_12.setDirection(1);
        fax_12.setOffsetX(1.0f);
        fax_12.setOffsetY(-10.0f);
        fax_12.setScale(1.8f);
        faw_213.X(fax_12);
        fax_12.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("animatedElement");
        fsj_27.setField("animation");
        fsj_27.setName("protector");
        fax_12.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("animName");
        fsj_28.setField("animName");
        fsj_28.setName("protector");
        fax_12.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_213.onChildrenAdded();
        String string3 = "protectorDescPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLR);
        frx_12.setHotSpotPosition(faa_2.tLL);
        faw_212.X(frx_12);
        frx_12.guy();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setPrefSize(new fsm_1(10, 0));
        faw_214.setStyle("popup");
        frx_12.X(faw_214);
        faw_214.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setStyle("White11");
        faw_214.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("text");
        fsj_29.setField("currentProtectorDescription");
        fsj_29.setName("map");
        fdy_12.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_214.onChildrenAdded();
        frx_12.onChildrenAdded();
        faw_212.onChildrenAdded();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("visible");
        fsj_210.setField("currentProtector");
        fsj_210.setName("protector");
        faw_211.X(fsj_210);
        fsj_210.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_210.X(fjt_22);
        fjt_22.guy();
        fjg_2 fjg_22 = new fjg_2();
        fjg_22.aVI();
        fjg_22.setElementMap(fhs_23);
        fjt_22.X(fjg_22);
        fjg_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjg_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjg_22.X(fjl_12);
        fjl_12.guy();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_23);
        fsj_211.setAttribute("comparedValue");
        fsj_211.setField("isStatic");
        fsj_211.setName("protector");
        fjl_12.X(fsj_211);
        fsj_211.guy();
        fsj_211.onChildrenAdded();
        fjl_12.onChildrenAdded();
        fjg_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_210.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_29.X(faw_215);
        faw_215.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_215.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipTitleLight20");
        faw_215.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_212 = fsj_2.checkOut();
        fsj_212.setElementMap(fhs_23);
        fsj_212.setAttribute("visible");
        fsj_212.setField("currentTerritoryName");
        fsj_212.setName("map");
        fbv_22.X(fsj_212);
        fsj_212.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsj_212.X(fjt_23);
        fjt_23.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_23);
        fjt_23.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_212.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLO);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_213 = fsj_2.checkOut();
        fsj_213.setElementMap(fhs_23);
        fsj_213.setAttribute("text");
        fsj_213.setField("currentMapName");
        fsj_213.setName("map");
        fbv_22.X(fsj_213);
        fsj_213.guy();
        fsj_213.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipTitleLight20");
        faw_215.X(fbv_24);
        fbv_24.guy();
        fsj_2 fsj_214 = fsj_2.checkOut();
        fsj_214.setElementMap(fhs_23);
        fsj_214.setAttribute("visible");
        fsj_214.setField("currentTerritoryName");
        fsj_214.setName("map");
        fbv_24.X(fsj_214);
        fsj_214.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fsj_214.X(fjt_24);
        fjt_24.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_23);
        fjt_24.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_214.onChildrenAdded();
        this.i(fbv_24);
        this.j(fbv_24);
        fbv_24.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_27.onChildrenAdded();
        this.d(faw_22);
        this.e(faw_22);
        this.F(faw_22);
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 i(fbv_2 fbv_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        return fzq2;
    }

    public fhi_2 j(fbv_2 fbv_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("currentTerritoryName");
        fsj_22.setName("map");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(false);
        faw_23.setStyle("windowBackgroundSecondary");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setXOffset(-8);
        frp_12.setYOffset(-8);
        frp_12.setSize(new fsm_1(180, 60));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(12, 12, 12, 12));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLP);
        frz_22.setHgap((short)8);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        String string = "filterDrawer";
        fbg_2 fbg_22 = new fbg_2();
        fbg_22.aVI();
        fbg_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fbg_22);
        }
        fbg_22.setCloseOnClick(false);
        fbg_22.setExpandable(false);
        faw_24.X(fbg_22);
        fbg_22.guy();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setThemeElementName("staticContainer");
        fbg_22.X(faw_26);
        faw_26.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("switchDrawer(filterDrawer)");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(108, 36));
        fad_12.setStyle("secondaryMedium");
        String string2 = "%chat.filters%";
        string2 = string2.replace("%chat.filters%", fyw_0.gqw().k("chat.filters", new Object[0]));
        fad_12.setText(string2);
        faw_26.X(fad_12);
        fad_12.guy();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(0, 0, 0, 0));
        fym_02.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setStyle("windowBackgroundSecondary");
        faw_27.setThemeElementName("popupContainer");
        fbg_22.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_27.X(fys_03);
        fys_03.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_22);
        fzx4.setInsets(new Insets(8, 8, 8, 8));
        fys_03.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(10, 0, 0, 0));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_27.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_27.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_04 = ((fes_2)faw_210).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_29.X(fys_04);
        fys_04.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(-1, 0, 0, 0));
        fys_04.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        frz_24.setHgap((short)4);
        faw_29.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        String string3 = "allFiltersCB";
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, fdd_22);
        }
        fdd_22.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.dragoMap:toggleAllFilters(allFiltersCB)");
        fdd_22.setOnClick(fmz_13);
        fdd_22.setPrefSize(new fsm_1(250, 28));
        fdd_22.setStyle("eyeTertiary");
        faw_29.X(fdd_22);
        fdd_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("selected");
        fsj_22.setField("noFilterSelected");
        fsj_22.setName("landMark.filters");
        fdd_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("noFilterSelected");
        fsj_23.setName("landMark.filters");
        fdd_22.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        String string4 = "%map.hide.all.filters%";
        string4 = string4.replace("%map.hide.all.filters%", fyw_0.gqw().k("map.hide.all.filters", new Object[0]));
        fjt_23.setElseValue(string4);
        String string5 = "%map.display.all.filters%";
        string5 = string5.replace("%map.display.all.filters%", fyw_0.gqw().k("map.display.all.filters", new Object[0]));
        fjt_23.setValue(string5);
        fsj_23.X(fjt_23);
        fjt_23.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_23.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fdd_22.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_211.setPrefSize(new fsm_1(250, 0));
        faw_27.X(faw_211);
        faw_211.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_211.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_211.X(faw_212);
        faw_212.guy();
        faw_2 faw_213 = faw_212;
        fys_0 fys_05 = ((fes_2)faw_213).getAppearance();
        fys_05.setElementMap(fhs_22);
        faw_212.X(fys_05);
        fys_05.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.15f));
        fkm_12.setInsets(new Insets(0, 0, 2, 0));
        fys_05.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_05.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_22);
        faw_211.X(faw_214);
        faw_214.guy();
        faw_2 faw_215 = faw_214;
        fys_0 fys_06 = ((fes_2)faw_215).getAppearance();
        fys_06.setElementMap(fhs_22);
        faw_214.X(fys_06);
        fys_06.guy();
        fkm_1 fkm_13 = new fkm_1();
        fkm_13.aVI();
        fkm_13.setElementMap(fhs_22);
        fkm_13.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.3f));
        fkm_13.setInsets(new Insets(2, 0, 0, 0));
        fys_06.X(fkm_13);
        fkm_13.guy();
        fkm_13.onChildrenAdded();
        fys_06.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_211.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(250, 36));
        fbz_22.setHideContainerWithoutItem(true);
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMinColumns(1);
        faw_27.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("content");
        fsj_24.setField("typeFilterList");
        fsj_24.setName("landMark.filters");
        fbz_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        String string6 = "typeFilter";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string6 != null) {
            fhs_22.a(string6, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        fsd_12.setField("id");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_22);
        fje_22.X(faw_216);
        faw_216.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        frz_26.setHgap((short)4);
        faw_216.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fdd_2 fdd_23 = new fdd_2();
        fdd_23.aVI();
        fdd_23.setElementMap(fhs_22);
        fdd_23.setExpandable(false);
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu.dragoMap:setTypeFilter(typeFilter)");
        fdd_23.setOnSelectionChange(fmo_12);
        fdd_23.setPrefSize(new fsm_1(36, 36));
        faw_216.X(fdd_23);
        fdd_23.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("selected");
        fsd_13.setField("selected");
        fdd_23.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("style");
        fsd_14.setField("style");
        fdd_23.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fdd_23.onChildrenAdded();
        fdd_2 fdd_24 = new fdd_2();
        fdd_24.aVI();
        fdd_24.setElementMap(fhs_22);
        fdd_24.setExpandable(false);
        fmo_1 fmo_13 = new fmo_1();
        fmo_13.vw("wakfu.dragoMap:setTypeFilter(typeFilter)");
        fdd_24.setOnSelectionChange(fmo_13);
        fdd_24.setStyle("defaultCheckbox");
        faw_216.X(fdd_24);
        fdd_24.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("selected");
        fsd_15.setField("selected");
        fdd_24.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("name");
        fdd_24.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fdd_24.onChildrenAdded();
        faw_216.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_22);
        faw_27.X(faw_217);
        faw_217.guy();
        faw_2 faw_218 = faw_217;
        fys_0 fys_07 = ((fes_2)faw_218).getAppearance();
        fys_07.setElementMap(fhs_22);
        faw_217.X(fys_07);
        fys_07.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(-9, 0, 0, 0));
        fys_07.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_07.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLN);
        frz_27.setHgap((short)4);
        faw_217.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fdd_2 fdd_25 = new fdd_2();
        fdd_25.aVI();
        fdd_25.setElementMap(fhs_22);
        fdd_25.setExpandable(false);
        fmo_1 fmo_14 = new fmo_1();
        fmo_14.vw("wakfu.dragoMap:setDisplayTerritories");
        fdd_25.setOnSelectionChange(fmo_14);
        fdd_25.setPrefSize(new fsm_1(36, 36));
        fdd_25.setStyle("filterTerritory");
        faw_217.X(fdd_25);
        fdd_25.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("selected");
        fsj_25.setField("displayTerritories");
        fsj_25.setName("map");
        fdd_25.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fdd_25.onChildrenAdded();
        fdd_2 fdd_26 = new fdd_2();
        fdd_26.aVI();
        fdd_26.setElementMap(fhs_22);
        fdd_26.setExpandable(false);
        fmo_1 fmo_15 = new fmo_1();
        fmo_15.vw("wakfu.dragoMap:setDisplayTerritories");
        fdd_26.setOnSelectionChange(fmo_15);
        fdd_26.setStyle("defaultCheckbox");
        String string7 = "%map.territories%";
        string7 = string7.replace("%map.territories%", fyw_0.gqw().k("map.territories", new Object[0]));
        fdd_26.setText(string7);
        faw_217.X(fdd_26);
        fdd_26.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("selected");
        fsj_26.setField("displayTerritories");
        fsj_26.setName("map");
        fdd_26.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fdd_26.onChildrenAdded();
        faw_217.onChildrenAdded();
        faw_27.onChildrenAdded();
        fbg_22.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_22);
        fad_14.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("unloadDialog");
        fad_14.setOnClick(fmz_14);
        fad_14.setPrefSize(new fsm_1(36, 36));
        fad_14.setStyle("closeCrossNegativeSmall");
        faw_24.X(fad_14);
        fad_14.guy();
        fad_14.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(false);
        faw_23.setStyle("windowBackgroundSecondary");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        frp_12.setSize(new fsm_1(120, 180));
        frp_12.setXOffset(8);
        frp_12.setYOffset(8);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("displayTerritories");
        fsj_22.setName("gamePreferences");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(8, 12, 12, 12));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        frz_22.setVgap((short)8);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipTitleLight16");
        String string = "%map.key%";
        string = string.replace("%map.key%", fyw_0.gqw().k("map.key", new Object[0]));
        fbv_22.setText(string);
        faw_24.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 4, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_2 fbv_24 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLO);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_24.X(faw_26);
        faw_26.guy();
        faw_2 faw_27 = faw_26;
        fys_0 fys_03 = ((fes_2)faw_27).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_26.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 2, 0));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_28.setPrefSize(new fsm_1(32, 6));
        faw_28.setStyle("backgroundPopupLight");
        faw_26.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_28.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_04 = ((fes_2)faw_210).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_29.X(fys_04);
        fys_04.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(2, 2, 2, 2));
        fys_04.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new awx_2(0.0f, 0.0f, 0.0f, 1.0f));
        fkm_12.setInsets(new Insets(1, 1, 1, 1));
        fys_04.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new fhl_2("amaknaTerritoryMapColor"));
        fys_04.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_28.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setStyle("wipLight12");
        String string2 = "%nation.short.30%";
        string2 = string2.replace("%nation.short.30%", fyw_0.gqw().k("nation.short.30", new Object[0]));
        fbv_25.setText(string2);
        faw_26.X(fbv_25);
        fbv_25.guy();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq4 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq4.setElementMap(fhs_22);
        fbv_25.X(fzq4);
        fzq4.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(0, 3, 0, 0));
        fzq4.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq4.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_24.X(faw_211);
        faw_211.guy();
        faw_2 faw_212 = faw_211;
        fys_0 fys_05 = ((fes_2)faw_212).getAppearance();
        fys_05.setElementMap(fhs_22);
        faw_211.X(fys_05);
        fys_05.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_22);
        fzv6.setInsets(new Insets(0, 0, 2, 0));
        fys_05.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_05.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_22);
        faw_213.setExpandable(false);
        faw_213.setPrefSize(new fsm_1(32, 6));
        faw_213.setStyle("backgroundPopupLight");
        faw_211.X(faw_213);
        faw_213.guy();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_22);
        faw_213.X(faw_214);
        faw_214.guy();
        faw_2 faw_215 = faw_214;
        fys_0 fys_06 = ((fes_2)faw_215).getAppearance();
        fys_06.setElementMap(fhs_22);
        faw_214.X(fys_06);
        fys_06.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_22);
        fzv7.setInsets(new Insets(2, 2, 2, 2));
        fys_06.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fkm_1 fkm_13 = new fkm_1();
        fkm_13.aVI();
        fkm_13.setElementMap(fhs_22);
        fkm_13.setColor(new awx_2(0.0f, 0.0f, 0.0f, 1.0f));
        fkm_13.setInsets(new Insets(1, 1, 1, 1));
        fys_06.X(fkm_13);
        fkm_13.guy();
        fkm_13.onChildrenAdded();
        fkk_1 fkk_13 = new fkk_1();
        fkk_13.aVI();
        fkk_13.setElementMap(fhs_22);
        fkk_13.setColor(new fhl_2("bontaTerritoryMapColor"));
        fys_06.X(fkk_13);
        fkk_13.guy();
        fkk_13.onChildrenAdded();
        fys_06.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_213.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_22);
        fbv_27.setStyle("wipLight12");
        String string3 = "%nation.short.31%";
        string3 = string3.replace("%nation.short.31%", fyw_0.gqw().k("nation.short.31", new Object[0]));
        fbv_27.setText(string3);
        faw_211.X(fbv_27);
        fbv_27.guy();
        fbv_2 fbv_28 = fbv_27;
        fzq fzq5 = (fzq)((fes_2)fbv_28).getAppearance();
        fzq5.setElementMap(fhs_22);
        fbv_27.X(fzq5);
        fzq5.guy();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_22);
        fzv8.setInsets(new Insets(0, 3, 0, 0));
        fzq5.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fzq5.onChildrenAdded();
        fbv_27.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_22);
        faw_216.setExpandable(false);
        faw_24.X(faw_216);
        faw_216.guy();
        faw_2 faw_217 = faw_216;
        fys_0 fys_07 = ((fes_2)faw_217).getAppearance();
        fys_07.setElementMap(fhs_22);
        faw_216.X(fys_07);
        fys_07.guy();
        fzv fzv9 = fzv.checkOut();
        fzv9.setElementMap(fhs_22);
        fzv9.setInsets(new Insets(0, 0, 2, 0));
        fys_07.X(fzv9);
        fzv9.guy();
        fzv9.onChildrenAdded();
        fys_07.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_22);
        faw_218.setExpandable(false);
        faw_218.setPrefSize(new fsm_1(32, 6));
        faw_218.setStyle("backgroundPopupLight");
        faw_216.X(faw_218);
        faw_218.guy();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_22);
        faw_218.X(faw_219);
        faw_219.guy();
        faw_2 faw_220 = faw_219;
        fys_0 fys_08 = ((fes_2)faw_220).getAppearance();
        fys_08.setElementMap(fhs_22);
        faw_219.X(fys_08);
        fys_08.guy();
        fzv fzv10 = fzv.checkOut();
        fzv10.setElementMap(fhs_22);
        fzv10.setInsets(new Insets(2, 2, 2, 2));
        fys_08.X(fzv10);
        fzv10.guy();
        fzv10.onChildrenAdded();
        fkm_1 fkm_14 = new fkm_1();
        fkm_14.aVI();
        fkm_14.setElementMap(fhs_22);
        fkm_14.setColor(new awx_2(0.0f, 0.0f, 0.0f, 1.0f));
        fkm_14.setInsets(new Insets(1, 1, 1, 1));
        fys_08.X(fkm_14);
        fkm_14.guy();
        fkm_14.onChildrenAdded();
        fkk_1 fkk_14 = new fkk_1();
        fkk_14.aVI();
        fkk_14.setElementMap(fhs_22);
        fkk_14.setColor(new fhl_2("brakmarTerritoryMapColor"));
        fys_08.X(fkk_14);
        fkk_14.guy();
        fkk_14.onChildrenAdded();
        fys_08.onChildrenAdded();
        faw_219.onChildrenAdded();
        faw_218.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_22);
        fbv_29.setStyle("wipLight12");
        String string4 = "%nation.short.32%";
        string4 = string4.replace("%nation.short.32%", fyw_0.gqw().k("nation.short.32", new Object[0]));
        fbv_29.setText(string4);
        faw_216.X(fbv_29);
        fbv_29.guy();
        fbv_2 fbv_210 = fbv_29;
        fzq fzq6 = (fzq)((fes_2)fbv_210).getAppearance();
        fzq6.setElementMap(fhs_22);
        fbv_29.X(fzq6);
        fzq6.guy();
        fzv fzv11 = fzv.checkOut();
        fzv11.setElementMap(fhs_22);
        fzv11.setInsets(new Insets(0, 3, 0, 0));
        fzq6.X(fzv11);
        fzv11.guy();
        fzv11.onChildrenAdded();
        fzq6.onChildrenAdded();
        fbv_29.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_2 faw_221 = faw_2.checkOut();
        faw_221.setElementMap(fhs_22);
        faw_221.setExpandable(false);
        faw_24.X(faw_221);
        faw_221.guy();
        faw_2 faw_222 = faw_221;
        fys_0 fys_09 = ((fes_2)faw_222).getAppearance();
        fys_09.setElementMap(fhs_22);
        faw_221.X(fys_09);
        fys_09.guy();
        fzv fzv12 = fzv.checkOut();
        fzv12.setElementMap(fhs_22);
        fzv12.setInsets(new Insets(0, 0, 2, 0));
        fys_09.X(fzv12);
        fzv12.guy();
        fzv12.onChildrenAdded();
        fys_09.onChildrenAdded();
        faw_2 faw_223 = faw_2.checkOut();
        faw_223.setElementMap(fhs_22);
        faw_223.setExpandable(false);
        faw_223.setPrefSize(new fsm_1(32, 6));
        faw_223.setStyle("backgroundPopupLight");
        faw_221.X(faw_223);
        faw_223.guy();
        faw_2 faw_224 = faw_2.checkOut();
        faw_224.setElementMap(fhs_22);
        faw_223.X(faw_224);
        faw_224.guy();
        faw_2 faw_225 = faw_224;
        fys_0 fys_010 = ((fes_2)faw_225).getAppearance();
        fys_010.setElementMap(fhs_22);
        faw_224.X(fys_010);
        fys_010.guy();
        fzv fzv13 = fzv.checkOut();
        fzv13.setElementMap(fhs_22);
        fzv13.setInsets(new Insets(2, 2, 2, 2));
        fys_010.X(fzv13);
        fzv13.guy();
        fzv13.onChildrenAdded();
        fkm_1 fkm_15 = new fkm_1();
        fkm_15.aVI();
        fkm_15.setElementMap(fhs_22);
        fkm_15.setColor(new awx_2(0.0f, 0.0f, 0.0f, 1.0f));
        fkm_15.setInsets(new Insets(1, 1, 1, 1));
        fys_010.X(fkm_15);
        fkm_15.guy();
        fkm_15.onChildrenAdded();
        fkk_1 fkk_15 = new fkk_1();
        fkk_15.aVI();
        fkk_15.setElementMap(fhs_22);
        fkk_15.setColor(new fhl_2("sufokiaTerritoryMapColor"));
        fys_010.X(fkk_15);
        fkk_15.guy();
        fkk_15.onChildrenAdded();
        fys_010.onChildrenAdded();
        faw_224.onChildrenAdded();
        faw_223.onChildrenAdded();
        fbv_2 fbv_211 = new fbv_2();
        fbv_211.aVI();
        fbv_211.setElementMap(fhs_22);
        fbv_211.setStyle("wipLight12");
        String string5 = "%nation.short.33%";
        string5 = string5.replace("%nation.short.33%", fyw_0.gqw().k("nation.short.33", new Object[0]));
        fbv_211.setText(string5);
        faw_221.X(fbv_211);
        fbv_211.guy();
        fbv_2 fbv_212 = fbv_211;
        fzq fzq7 = (fzq)((fes_2)fbv_212).getAppearance();
        fzq7.setElementMap(fhs_22);
        fbv_211.X(fzq7);
        fzq7.guy();
        fzv fzv14 = fzv.checkOut();
        fzv14.setElementMap(fhs_22);
        fzv14.setInsets(new Insets(0, 3, 0, 0));
        fzq7.X(fzv14);
        fzv14.guy();
        fzv14.onChildrenAdded();
        fzq7.onChildrenAdded();
        fbv_211.onChildrenAdded();
        faw_221.onChildrenAdded();
        faw_2 faw_226 = faw_2.checkOut();
        faw_226.setElementMap(fhs_22);
        faw_226.setExpandable(false);
        faw_24.X(faw_226);
        faw_226.guy();
        faw_2 faw_227 = faw_226;
        fys_0 fys_011 = ((fes_2)faw_227).getAppearance();
        fys_011.setElementMap(fhs_22);
        faw_226.X(fys_011);
        fys_011.guy();
        fzv fzv15 = fzv.checkOut();
        fzv15.setElementMap(fhs_22);
        fzv15.setInsets(new Insets(0, 0, 2, 0));
        fys_011.X(fzv15);
        fzv15.guy();
        fzv15.onChildrenAdded();
        fys_011.onChildrenAdded();
        faw_2 faw_228 = faw_2.checkOut();
        faw_228.setElementMap(fhs_22);
        faw_228.setExpandable(false);
        faw_228.setPrefSize(new fsm_1(32, 6));
        faw_228.setStyle("backgroundPopupLight");
        faw_226.X(faw_228);
        faw_228.guy();
        faw_2 faw_229 = faw_2.checkOut();
        faw_229.setElementMap(fhs_22);
        faw_228.X(faw_229);
        faw_229.guy();
        faw_2 faw_230 = faw_229;
        fys_0 fys_012 = ((fes_2)faw_230).getAppearance();
        fys_012.setElementMap(fhs_22);
        faw_229.X(fys_012);
        fys_012.guy();
        fzv fzv16 = fzv.checkOut();
        fzv16.setElementMap(fhs_22);
        fzv16.setInsets(new Insets(2, 2, 2, 2));
        fys_012.X(fzv16);
        fzv16.guy();
        fzv16.onChildrenAdded();
        fkm_1 fkm_16 = new fkm_1();
        fkm_16.aVI();
        fkm_16.setElementMap(fhs_22);
        fkm_16.setColor(new awx_2(0.0f, 0.0f, 0.0f, 1.0f));
        fkm_16.setInsets(new Insets(1, 1, 1, 1));
        fys_012.X(fkm_16);
        fkm_16.guy();
        fkm_16.onChildrenAdded();
        fkk_1 fkk_16 = new fkk_1();
        fkk_16.aVI();
        fkk_16.setElementMap(fhs_22);
        fkk_16.setColor(new fhl_2("neutralTerritoryMapColor"));
        fys_012.X(fkk_16);
        fkk_16.guy();
        fkk_16.onChildrenAdded();
        fys_012.onChildrenAdded();
        faw_229.onChildrenAdded();
        faw_228.onChildrenAdded();
        fbv_2 fbv_213 = new fbv_2();
        fbv_213.aVI();
        fbv_213.setElementMap(fhs_22);
        fbv_213.setStyle("wipLight12");
        String string6 = "%nation.short.0%";
        string6 = string6.replace("%nation.short.0%", fyw_0.gqw().k("nation.short.0", new Object[0]));
        fbv_213.setText(string6);
        faw_226.X(fbv_213);
        fbv_213.guy();
        fbv_2 fbv_214 = fbv_213;
        fzq fzq8 = (fzq)((fes_2)fbv_214).getAppearance();
        fzq8.setElementMap(fhs_22);
        fbv_213.X(fzq8);
        fzq8.guy();
        fzv fzv17 = fzv.checkOut();
        fzv17.setElementMap(fhs_22);
        fzv17.setInsets(new Insets(0, 3, 0, 0));
        fzq8.X(fzv17);
        fzv17.guy();
        fzv17.onChildrenAdded();
        fzq8.onChildrenAdded();
        fbv_213.onChildrenAdded();
        faw_226.onChildrenAdded();
        faw_24.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)4);
        faw_23.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLo);
        frp_12.setXOffset(-8);
        frp_12.setYOffset(8);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLP);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipLight16Bold");
        String string = "%map.position%%colon%";
        string = string.replace("%map.position%", fyw_0.gqw().k("map.position", new Object[0]));
        string = string.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 10, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipLight16Bold");
        faw_23.X(fbv_24);
        fbv_24.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("displayedPosition");
        fsj_22.setName("map");
        fbv_24.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }
}

