/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKC
 */
public class ckc_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "collectMachineWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string2 = "%chat.contactList%";
        string2 = string2.replace("%chat.contactList%", fyw_0.gqw().k("chat.contactList", new Object[0]));
        fbv_22.setText(string2);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("name");
        fsj_22.setName("collectMachine");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string3 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        faw_2 faw_212 = faw_211;
        fys_0 fys_06 = ((fes_2)faw_212).getAppearance();
        fys_06.setElementMap(fhs_23);
        fys_06.setModulationColor(new awx_2(0.9f, 0.9f, 0.9f, 1.0f));
        faw_211.X(fys_06);
        fys_06.guy();
        fys_06.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_211.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_211.X(faw_213);
        faw_213.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_213.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        String string4 = "localMoney";
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, faw_214);
        }
        faw_214.setExpandable(false);
        faw_213.X(faw_214);
        faw_214.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLP);
        faw_214.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_214.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setPrefSize(new fsm_1(120, 31));
        faw_215.setStyle("characterSheetAptitudePoints");
        faw_214.X(faw_215);
        faw_215.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        frp_14.setYOffset(2);
        faw_215.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_214.X(faw_216);
        faw_216.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        faw_216.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_217 = faw_216;
        fys_0 fys_07 = ((fes_2)faw_217).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_216.X(fys_07);
        fys_07.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 10));
        fys_07.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_07.onChildrenAdded();
        String string5 = "money";
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fbv_24);
        }
        fbv_24.setExpandable(false);
        fbv_24.setPrefSize(new fsm_1(75, 0));
        fbv_24.setStyle("smallTitle");
        faw_216.X(fbv_24);
        fbv_24.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("kama");
        fsj_23.setName("collectMachine");
        fbv_24.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlignment(faa_2.tLP);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 0, 2, 5));
        fzq3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setExpandable(false);
        fbt_12.setStyle("kamas");
        faw_216.X(fbt_12);
        fbt_12.guy();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_23);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 0, 2, 0));
        fyY2.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_213.X(faw_218);
        faw_218.guy();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setHorizontal(false);
        faw_218.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.collectMachine:takeKamas");
        fad_12.setOnClick(fmz_12);
        String string6 = "%takeKamas%";
        string6 = string6.replace("%takeKamas%", fyw_0.gqw().k("takeKamas", new Object[0]));
        fad_12.setText(string6);
        faw_218.X(fad_12);
        fad_12.guy();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 0, 0, 5));
        fym_02.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_218.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_213.X(faw_219);
        faw_219.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setHorizontal(false);
        faw_219.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        fad_14.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.collectMachine:giveKamas");
        fad_14.setOnClick(fmz_13);
        String string7 = "%giveKamas%";
        string7 = string7.replace("%giveKamas%", fyw_0.gqw().k("giveKamas", new Object[0]));
        fad_14.setText(string7);
        faw_219.X(fad_14);
        fad_14.guy();
        fad_1 fad_15 = fad_14;
        fym_0 fym_03 = (fym_0)((fes_2)fad_15).getAppearance();
        fym_03.setElementMap(fhs_23);
        fad_14.X(fym_03);
        fym_03.guy();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_23);
        fzv8.setInsets(new Insets(0, 0, 0, 5));
        fym_03.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fym_03.onChildrenAdded();
        fad_14.onChildrenAdded();
        faw_219.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        faw_220.setExpandable(false);
        faw_220.setStyle("white");
        faw_211.X(faw_220);
        faw_220.guy();
        faw_2 faw_221 = faw_220;
        fys_0 fys_08 = ((fes_2)faw_221).getAppearance();
        fys_08.setElementMap(fhs_23);
        fys_08.setModulationColor(new awx_2(0.73f, 0.77f, 0.79f, 1.0f));
        faw_220.X(fys_08);
        fys_08.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(10, 10, 10, 10));
        fys_08.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_08.onChildrenAdded();
        String string8 = "itemList";
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, fbz_22);
        }
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(40, 40));
        fbz_22.setHorizontal(false);
        fbz_22.setIdealSizeMaxColumns(8);
        fbz_22.setIdealSizeMaxRows(5);
        fbz_22.setIdealSizeMinColumns(8);
        fbz_22.setIdealSizeMinRows(5);
        fbz_22.setSelectionTogglable(false);
        faw_220.X(fbz_22);
        fbz_22.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLN);
        fbz_22.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("content");
        fsj_24.setField("content");
        fsj_24.setName("collectMachine");
        fbz_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.inventory:openItemDetailWindow(collectMachineWindow)");
        fje_22.setOnItemClick(fmo_22);
        fmp_1 fmp_12 = new fmp_1();
        fmp_12.vw("wakfu.collectMachine:onItemDoubleClick");
        fje_22.setOnItemDoubleClick(fmp_12);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string9 = "currentItem";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string9 != null) {
            fhs_23.a(string9, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_222 = faw_2.checkOut();
        faw_222.setElementMap(fhs_23);
        fje_22.X(faw_222);
        faw_222.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_222.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        String string10 = "itemContainer";
        faw_2 faw_223 = faw_2.checkOut();
        faw_223.setElementMap(fhs_23);
        if (fhs_23 != null && string10 != null) {
            fhs_23.a(string10, faw_223);
        }
        faw_223.setNonBlocking(false);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.collectMachine:changeItemBackground(currentItem,collectMachineWindow,itemPopup)");
        faw_223.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.collectMachine:changeItemBackground(currentItem,collectMachineWindow,itemPopup)");
        faw_223.setOnMouseExit(fmf_22);
        faw_222.X(faw_223);
        faw_223.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(43, 43));
        faw_223.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        this.R(faw_223);
        this.c(faw_223);
        this.d(faw_223);
        faw_223.onChildrenAdded();
        faw_222.onChildrenAdded();
        fje_22.onChildrenAdded();
        this.E(fbz_22);
        this.a(fbz_22);
        fbz_22.onChildrenAdded();
        faw_220.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.q(fey_22);
        this.r(fey_22);
        this.N(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "itemPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_23.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("whiteBold");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("style");
        fsd_12.setField("backgroundStyle");
        faw_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        return fsd_12;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbd_1 fbd_12 = new fbd_1();
        fbd_12.aVI();
        fbd_12.setElementMap(fhs_22);
        fmh_1 fmh_12 = new fmh_1();
        fmh_12.vw("wakfu.collectMachine:dragItem");
        fbd_12.setOnDrag(fmh_12);
        fmk_1 fmk_12 = new fmk_1();
        fmk_12.vw("wakfu.collectMachine:dropItem");
        fbd_12.setOnDrop(fmk_12);
        faw_22.X(fbd_12);
        fbd_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("dragEnabled");
        fsd_12.setField("movable");
        fbd_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fbd_12.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(38, 38));
        fbt_12.setNonBlocking(true);
        fbd_12.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("texture");
        fsd_13.setField("iconUrl");
        fze2.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        fbd_12.X(faw_23);
        faw_23.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(40, 40));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("visible");
        fsd_14.setField("movable");
        faw_23.X(fsd_14);
        fsd_14.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsd_14.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_14.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.3f));
        fys_02.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("White10Bordered");
        fbd_12.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("visible");
        fsd_15.setField("quantity");
        fbv_22.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsd_15.X(fjt_23);
        fjt_23.guy();
        fjp_1 fjp_12 = new fjp_1();
        fjp_12.aVI();
        fjp_12.setElementMap(fhs_22);
        fjp_12.setValue("1");
        fjt_23.X(fjp_12);
        fjp_12.guy();
        fjp_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_15.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLk);
        fbv_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 6, 6, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("quantity");
        fbv_22.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbd_12.onChildrenAdded();
        return fbd_12;
    }

    public fhi_2 E(fbz_2 fbz_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjn_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_22);
        fjy_22.setKey("tableIndex");
        fjn_22.X(fjy_22);
        fjy_22.guy();
        fjr_1 fjr_12 = new fjr_1();
        fjr_12.aVI();
        fjr_12.setElementMap(fhs_22);
        fjy_22.X(fjr_12);
        fjr_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("value");
        fsj_22.setField("freeBagSlotsSize");
        fsj_22.setName("collectMachine");
        fjr_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fjr_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fje_22.X(faw_22);
        faw_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        String string = "itemBackgroundContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setStyle("itemBackground");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(43, 43));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbd_1 fbd_12 = new fbd_1();
        fbd_12.aVI();
        fbd_12.setElementMap(fhs_22);
        fmk_1 fmk_12 = new fmk_1();
        fmk_12.vw("wakfu.collectMachine:dropItem");
        fbd_12.setOnDrop(fmk_12);
        faw_23.X(fbd_12);
        fbd_12.guy();
        fbd_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 a(fbz_2 fbz_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjn_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_22);
        fjy_22.setKey("tableIndex");
        fjn_22.X(fjy_22);
        fjy_22.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjy_22.X(fja_12);
        fja_12.guy();
        fjr_1 fjr_12 = new fjr_1();
        fjr_12.aVI();
        fjr_12.setElementMap(fhs_22);
        fja_12.X(fjr_12);
        fjr_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("value");
        fsj_22.setField("freeBagSlotsSize");
        fsj_22.setName("collectMachine");
        fjr_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fjr_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fje_22.X(faw_22);
        faw_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        String string = "itemBackgroundContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setStyle("itemBackground");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(43, 43));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        fys_02.setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 0.1f));
        faw_23.X(fys_02);
        fys_02.guy();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 N(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setResizeOnce(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

