/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKL
 */
public class ckl_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "guidePopup";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("BLUEWINDOW");
        fey_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        fea_12.setPrefSize(new fsm_1(100.0f, 50));
        fea_12.setEnabled(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_02 = ((fes_2)fea_13).getAppearance();
        fys_02.setElementMap(fhs_23);
        fea_12.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(-4, -30, 0, -30));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzt fzt2 = new fzt();
        fzt2.aVI();
        fzt2.setElementMap(fhs_23);
        fzt2.setInsets(new Insets(0, 15, 0, 15));
        fys_02.X(fzt2);
        fzt2.guy();
        fzt2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setPrefSize(new fsm_1(100.0f, 50));
        faw_24.setStyle("BLUEWINDOWHEADER");
        fea_12.X(faw_24);
        faw_24.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(false);
        faw_24.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_24.X(faw_25);
        faw_25.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLa);
        frp_14.setSize(new fsm_1(100.0f, 42));
        faw_25.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_25.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(40, 40));
        faw_26.setStyle("BLUEWINDOWTITLEBACKGROUND");
        faw_25.X(faw_26);
        faw_26.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLf);
        frp_15.setXOffset(20);
        faw_26.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_27 = faw_26;
        fys_0 fys_03 = ((fes_2)faw_27).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_26.X(fys_03);
        fys_03.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(2, 2, 2, 2));
        fys_03.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_03.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(26, 26));
        faw_26.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("texture");
        fsj_22.setField("icon");
        fsj_22.setLocal(true);
        fsj_22.setName("guideViewPopup");
        fze2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_28.setPrefSize(new fsm_1(100, 37));
        faw_28.setStyle("BLUEWINDOWTITLEBACKGROUND");
        faw_25.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_04 = ((fes_2)faw_29).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_28.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(0, 20, 0, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        faw_28.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(adminGuidePopup)");
        fbv_22.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbv_22.setOnPopupHide(fml_12);
        fbv_22.setStyle("STYLEDBOLD16WHITE");
        faw_28.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("title");
        fsj_23.setLocal(true);
        fsj_23.setName("guideViewPopup");
        fbv_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        String string2 = "adminGuidePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLR);
        frx_12.setHotSpotPosition(faa_2.tLL);
        fbv_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setPrefSize(new fsm_1(10, 0));
        faw_210.setStyle("popup");
        frx_12.X(faw_210);
        faw_210.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("visible");
        fsj_24.setName("isAdmin");
        faw_210.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setMaxWidth(200);
        fdy_12.setMultiline(true);
        fdy_12.setStyle("11");
        faw_210.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("adminGuideInfo");
        fsj_25.setLocal(true);
        fsj_25.setName("guideViewPopup");
        fdy_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fdy_12.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("defaultLightColor"));
        fzq3.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_25.X(faw_211);
        faw_211.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLh);
        faw_211.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_24.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_23.X(faw_212);
        faw_212.guy();
        faw_2 faw_213 = faw_212;
        fys_0 fys_05 = ((fes_2)faw_213).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_212.X(fys_05);
        fys_05.guy();
        fys_05.onChildrenAdded();
        String string3 = "windowContentContainer";
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, faw_214);
        }
        faw_212.X(faw_214);
        faw_214.guy();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_214.X(faw_215);
        faw_215.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        frz_23.setHorizontal(false);
        faw_215.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        String string4 = "guideView";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, frv_12);
        }
        faw_215.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("value");
        fsj_26.setLocal(true);
        fsj_26.setName("guideViewPopup");
        frv_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_215.X(faw_216);
        faw_216.guy();
        faw_2 faw_217 = faw_216;
        fys_0 fys_06 = ((fes_2)faw_217).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_216.X(fys_06);
        fys_06.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(5, 5, 5, 5));
        fys_06.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_06.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        faw_216.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setStyle("BLUEWINDOWCONTENT");
        faw_216.X(faw_218);
        faw_218.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLg);
        frp_18.setSize(new fsm_1(642, 517));
        faw_218.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fro_1 fro_16 = new fro_1();
        fro_16.aVI();
        faw_218.X(fro_16);
        fro_16.guy();
        fro_16.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setDisplaySize(new fsm_1(588, 340));
        fbt_13.setExpandable(false);
        fbt_13.setKeepAspectRatio(true);
        faw_218.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setAlign(fzw_0.tLa);
        frp_19.setSize(new fsm_1(594, 346));
        fbt_13.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fbt_13.X(fze3);
        fze3.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("texture");
        fsj_27.setField("illustration");
        fsj_27.setLocal(true);
        fsj_27.setName("guideViewPopup");
        fze3.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fze3.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_218.X(faw_219);
        faw_219.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_23);
        frp_110.setAlign(fzw_0.tLa);
        frp_110.setSize(new fsm_1(594, 346));
        faw_219.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        faw_220.setNonBlocking(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.guidePopup:previousPage(guideView)");
        faw_220.setOnClick(fmz_12);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.guidePopup:setLeftArrowVisible(guideView,leftGuideArrow)");
        faw_220.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.guidePopup:setLeftArrowInvisible(guideView,leftGuideArrow)");
        faw_220.setOnMouseExit(fmf_22);
        faw_220.setPrefSize(new fsm_1(250, 100.0f));
        faw_219.X(faw_220);
        faw_220.guy();
        faw_2 faw_221 = faw_220;
        fys_0 fys_07 = ((fes_2)faw_221).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_220.X(fys_07);
        fys_07.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(4, 4, 4, 4));
        fys_07.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_07.onChildrenAdded();
        String string5 = "leftGuideArrow";
        faw_2 faw_222 = faw_2.checkOut();
        faw_222.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, faw_222);
        }
        faw_222.setExpandable(false);
        faw_222.setNonBlocking(true);
        faw_222.setPrefSize(new fsm_1(36, 100.0f));
        faw_222.setVisible(false);
        faw_220.X(faw_222);
        faw_222.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_222.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_223 = faw_2.checkOut();
        faw_223.setElementMap(fhs_23);
        faw_223.setStyle("LeftShadowBorder");
        faw_222.X(faw_223);
        faw_223.guy();
        faw_223.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setDisplaySize(new fsm_1(36, 36));
        fbt_14.setExpandable(false);
        fbt_14.setStyle("LeftShadowBorderArrow");
        faw_222.X(fbt_14);
        fbt_14.guy();
        fbt_14.onChildrenAdded();
        faw_2 faw_224 = faw_2.checkOut();
        faw_224.setElementMap(fhs_23);
        faw_224.setStyle("LeftShadowBorder");
        faw_222.X(faw_224);
        faw_224.guy();
        faw_224.onChildrenAdded();
        faw_222.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_220.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        faw_220.onChildrenAdded();
        fde_1 fde_13 = new fde_1();
        fde_13.aVI();
        fde_13.setElementMap(fhs_23);
        faw_219.X(fde_13);
        fde_13.guy();
        fde_13.onChildrenAdded();
        faw_2 faw_225 = faw_2.checkOut();
        faw_225.setElementMap(fhs_23);
        faw_225.setNonBlocking(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.guidePopup:nextPage(guideView)");
        faw_225.setOnClick(fmz_13);
        fme_1 fme_13 = new fme_1();
        fme_13.vw("wakfu.guidePopup:setRightArrowVisible(guideView,rightGuideArrow)");
        faw_225.setOnMouseEnter(fme_13);
        fmf_2 fmf_23 = new fmf_2();
        fmf_23.vw("wakfu.guidePopup:setRightArrowInvisible(guideView,rightGuideArrow)");
        faw_225.setOnMouseExit(fmf_23);
        faw_225.setPrefSize(new fsm_1(250, 100.0f));
        faw_219.X(faw_225);
        faw_225.guy();
        this.R(faw_225);
        this.c(faw_225);
        this.d(faw_225);
        faw_225.onChildrenAdded();
        faw_219.onChildrenAdded();
        this.e(faw_218);
        this.F(faw_218);
        faw_218.onChildrenAdded();
        faw_216.onChildrenAdded();
        this.G(faw_215);
        faw_215.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.r(fey_22);
        this.N(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(4, 4, 4, 4));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        return fys_02;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_22.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        return fde_12;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "rightGuideArrow";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setExpandable(false);
        faw_23.setNonBlocking(true);
        faw_23.setPrefSize(new fsm_1(36, 100.0f));
        faw_23.setVisible(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setStyle("RightShadowBorder");
        faw_23.X(faw_24);
        faw_24.guy();
        faw_24.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(36, 36));
        fbt_12.setExpandable(false);
        fbt_12.setStyle("RightShadowBorderArrow");
        faw_23.X(fbt_12);
        fbt_12.guy();
        fbt_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setStyle("RightShadowBorder");
        faw_23.X(faw_25);
        faw_25.guy();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("BLUEWINDOWIMAGEFRAME");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(594, 346));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("BLUEWINDOWTEXTFRAME");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(598, 120));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(6, 10, 6, 10));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(585);
        fdy_12.setMultiline(true);
        fdy_12.setStyle("DefaultBold12White");
        faw_23.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLK);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("description");
        fsj_22.setLocal(true);
        fsj_22.setName("guideViewPopup");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(100.0f, 28));
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 0, 4, 0));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_23.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_25.setPrefSize(new fsm_1(200, 31));
        faw_23.X(faw_25);
        faw_25.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("hasManyPages");
        fsj_22.setLocal(true);
        fsj_22.setName("guideViewPopup");
        faw_25.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_03 = ((fes_2)faw_26).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_25.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(-3, 0, 0, 0));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_25.X(faw_27);
        faw_27.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setField("hasPreviousPage");
        fsj_23.setLocal(true);
        fsj_23.setName("guideViewPopup");
        faw_27.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_27.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.guidePopup:previousPage(guideView)");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("BlueWindowLeftArrowButton");
        String string = "%desc.mru.previous%";
        string = string.replace("%desc.mru.previous%", fyw_0.gqw().k("desc.mru.previous", new Object[0]));
        fad_12.setText(string);
        faw_27.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("enabled");
        fsj_24.setField("hasPreviousPage");
        fsj_24.setLocal(true);
        fsj_24.setName("guideViewPopup");
        fad_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(150, 31));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fde_1 fde_13 = new fde_1();
        fde_13.aVI();
        fde_13.setElementMap(fhs_22);
        faw_23.X(fde_13);
        fde_13.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("visible");
        fsj_25.setField("hasManyPages");
        fsj_25.setLocal(true);
        fsj_25.setName("guideViewPopup");
        fde_13.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fde_13.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("defaultBold14White");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 20, 0, 20));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("visible");
        fsj_26.setField("hasManyPages");
        fsj_26.setLocal(true);
        fsj_26.setName("guideViewPopup");
        fbv_22.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("text");
        fsj_27.setField("pageNumber");
        fsj_27.setLocal(true);
        fsj_27.setName("guideViewPopup");
        fbv_22.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fde_1 fde_14 = new fde_1();
        fde_14.aVI();
        fde_14.setElementMap(fhs_22);
        faw_23.X(fde_14);
        fde_14.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_22);
        fsj_28.setAttribute("visible");
        fsj_28.setField("hasManyPages");
        fsj_28.setLocal(true);
        fsj_28.setName("guideViewPopup");
        fde_14.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fde_14.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_28.setPrefSize(new fsm_1(200, 31));
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_04 = ((fes_2)faw_29).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_28.X(fys_04);
        fys_04.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(-3, 0, 0, 0));
        fys_04.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_28.X(faw_210);
        faw_210.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_22);
        fsj_29.setAttribute("visible");
        fsj_29.setField("hasNextPage");
        fsj_29.setLocal(true);
        fsj_29.setName("guideViewPopup");
        faw_210.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_210.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.guidePopup:nextPage(guideView)");
        fad_13.setOnClick(fmz_13);
        fad_13.setStyle("BlueWindowRightArrowButton");
        String string2 = "%desc.mru.next%";
        string2 = string2.replace("%desc.mru.next%", fyw_0.gqw().k("desc.mru.next", new Object[0]));
        fad_13.setText(string2);
        faw_210.X(fad_13);
        fad_13.guy();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_22);
        fsj_210.setAttribute("enabled");
        fsj_210.setField("hasNextPage");
        fsj_210.setLocal(true);
        fsj_210.setName("guideViewPopup");
        fad_13.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(150, 31));
        fad_13.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_28.X(faw_211);
        faw_211.guy();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_22);
        fsj_211.setAttribute("visible");
        fsj_211.setField("hasNextPage");
        fsj_211.setLocal(true);
        fsj_211.setName("guideViewPopup");
        faw_211.X(fsj_211);
        fsj_211.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_211.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_211.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_211.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_22);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.guidePopup:close");
        fad_14.setOnClick(fmz_14);
        fad_14.setStyle("BlueWindowNoArrowButton");
        String string3 = "%close%";
        string3 = string3.replace("%close%", fyw_0.gqw().k("close", new Object[0]));
        fad_14.setText(string3);
        faw_211.X(fad_14);
        fad_14.guy();
        fsj_2 fsj_212 = fsj_2.checkOut();
        fsj_212.setElementMap(fhs_22);
        fsj_212.setAttribute("enabled");
        fsj_212.setLocal(true);
        fsj_212.setName("guidePopupIsClosable");
        fad_14.X(fsj_212);
        fsj_212.guy();
        fsj_212.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(150, 31));
        fad_14.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fad_14.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_28.onChildrenAdded();
        fde_1 fde_15 = new fde_1();
        fde_15.aVI();
        fde_15.setElementMap(fhs_22);
        faw_23.X(fde_15);
        fde_15.guy();
        fde_15.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 N(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(664, 612));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

