/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKN
 */
public class ckn_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        String string = "background";
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fbt_12);
        }
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(450, 612));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("texture");
        fsj_22.setName("dungeonLadderBackgroundImage");
        fze2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        faw_23.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(10, 25, 25, 25));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_24.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_24.X(faw_26);
        faw_26.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_26.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setStyle("SplashTitle");
        faw_26.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        fbt_13.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_26.X(faw_27);
        faw_27.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        faw_27.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_27.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setStyle("TitleDecoratorLeft");
        faw_27.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLf);
        fbt_14.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_23);
        fbt_15.setStyle("TitleDecoratorRight");
        faw_27.X(fbt_15);
        fbt_15.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLh);
        fbt_15.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fbt_15.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setMaxWidth(300);
        fdy_12.setStyle("StyledBold16Dark");
        String string2 = "%guild.ladder%";
        string2 = string2.replace("%guild.ladder%", fyw_0.gqw().k("guild.ladder", new Object[0]));
        fdy_12.setText(string2);
        faw_27.X(fdy_12);
        fdy_12.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setAlign(fzw_0.tLg);
        frp_19.setSize(new fsm_1(100.0f, -2));
        frp_19.setYOffset(12);
        fdy_12.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 50, 0, 50));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_26.onChildrenAdded();
        String string3 = "ladderTable";
        fdq_1 fdq_12 = new fdq_1();
        fdq_12.aVI();
        fdq_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fdq_12);
        }
        fdq_12.setCellHeight(45);
        fdq_12.setExpandable(false);
        fdq_12.setMaxRows(9);
        fdq_12.setMinRows(9);
        fdq_12.setSelectionable(false);
        fdq_12.setStyle("dark");
        faw_24.X(fdq_12);
        fdq_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLL);
        fdq_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setField("currentList");
        fsj_23.setName("guildLadder");
        fdq_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fgm_2 fgm_22 = new fgm_2();
        fgm_22.aVI();
        fgm_22.setElementMap(fhs_23);
        fgm_22.setCellWidth(70);
        fgm_22.setColumnId("rank");
        String string4 = "%rank%";
        string4 = string4.replace("%rank%", fyw_0.gqw().k("rank", new Object[0]));
        fgm_22.setName(string4);
        fgm_22.setSortable(false);
        fdq_12.X(fgm_22);
        fgm_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fgm_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_28.setNonBlocking(false);
        faw_28.setPrefSize(new fsm_1(70, 0));
        fje_22.X(faw_28);
        faw_28.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLO);
        faw_28.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setEnableAutoZoomShrink(true);
        fbv_22.setExpandable(false);
        fbv_22.setMaxWidth(60);
        fbv_22.setMinWidth(20);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("blackBold");
        faw_28.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("rank");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 3, 0, 0));
        fzq3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_28.onChildrenAdded();
        fje_22.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fgm_22.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_23);
        fjt_23.X(fjx_13);
        fjx_13.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_23);
        fjx_13.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setPrefSize(new fsm_1(40, 0));
        fje_23.X(faw_29);
        faw_29.guy();
        faw_29.onChildrenAdded();
        fje_23.onChildrenAdded();
        fgm_22.onChildrenAdded();
        fgm_2 fgm_23 = new fgm_2();
        fgm_23.aVI();
        fgm_23.setElementMap(fhs_23);
        fgm_23.setCellWidth(175);
        fgm_23.setColumnId("name");
        String string5 = "%guild.name%";
        string5 = string5.replace("%guild.name%", fyw_0.gqw().k("guild.name", new Object[0]));
        fgm_23.setName(string5);
        fgm_23.setSortable(false);
        fdq_12.X(fgm_23);
        fgm_23.guy();
        fje_2 fje_24 = new fje_2();
        fje_24.aVI();
        fje_24.setElementMap(fhs_23);
        fgm_23.X(fje_24);
        fje_24.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fje_24.X(fjt_24);
        fjt_24.guy();
        fjx_1 fjx_14 = new fjx_1();
        fjx_14.aVI();
        fjx_14.setElementMap(fhs_23);
        fjt_24.X(fjx_14);
        fjx_14.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_23);
        fjx_14.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_14.onChildrenAdded();
        fjt_24.onChildrenAdded();
        String string6 = "zone";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, frv_12);
        }
        fje_24.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("value");
        frv_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descriptionPopup)");
        faw_210.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_210.setOnPopupHide(fml_12);
        faw_210.setPrefSize(new fsm_1(0, 40));
        fje_24.X(faw_210);
        faw_210.guy();
        String string7 = "descriptionPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_210.X(frx_12);
        frx_12.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setPrefSize(new fsm_1(10, 0));
        faw_211.setStyle("popup");
        frx_12.X(faw_211);
        faw_211.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLL);
        frz_25.setHorizontal(false);
        faw_211.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("visible");
        fsd_14.setField("description");
        faw_211.X(fsd_14);
        fsd_14.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_23);
        fsd_14.X(fjt_25);
        fjt_25.guy();
        fjd_1 fjd_14 = new fjd_1();
        fjd_14.aVI();
        fjd_14.setElementMap(fhs_23);
        fjt_25.X(fjd_14);
        fjd_14.guy();
        fjd_14.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsd_14.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_211.X(faw_212);
        faw_212.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLL);
        frz_26.setHorizontal(false);
        faw_212.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("PopupInformation");
        String string8 = "%description%%colon%";
        string8 = string8.replace("%description%", fyw_0.gqw().k("description", new Object[0]));
        string8 = string8.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fbv_24.setText(string8);
        faw_212.X(fbv_24);
        fbv_24.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLN);
        fbv_24.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        fdy_14.setMinWidth(300);
        fdy_14.setMultiline(true);
        fdy_14.setStyle("PopupInformation");
        faw_212.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq4 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlignment(faa_2.tLN);
        fdy_14.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("text");
        fsd_15.setField("description");
        fdy_14.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_211.onChildrenAdded();
        frx_12.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLN);
        faw_210.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        faw_2 faw_213 = faw_210;
        fys_0 fys_03 = ((fes_2)faw_213).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_210.X(fys_03);
        fys_03.guy();
        this.d(fys_03);
        this.f(fys_03);
        fys_03.onChildrenAdded();
        this.d(faw_210);
        this.e(faw_210);
        faw_210.onChildrenAdded();
        fje_24.onChildrenAdded();
        this.a(fgm_23);
        fgm_23.onChildrenAdded();
        this.a(fdq_12);
        this.b(fdq_12);
        fdq_12.onChildrenAdded();
        this.g(faw_24);
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.H(faw_22);
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 d(fys_0 fys_02) {
        fhs_2 fhs_22 = this.nei.peek();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new fhl_2("scrollFleshColor", 0.8f));
        fkm_12.setInsets(new Insets(0, 1, 0, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        return fkm_12;
    }

    public fhi_2 f(fys_0 fys_02) {
        fhs_2 fhs_22 = this.nei.peek();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 1, 0, 0));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        return fzx2;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setNeedsScissor(true);
        faw_22.X(faw_23);
        faw_23.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setNeedsScissor(true);
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(35, 36));
        faw_24.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(36, 36));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        faw_24.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("blazon");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setEnableAutoZoomShrink(true);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(140);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("blackBold");
        faw_23.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 a(fgm_2 fgm_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fgm_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(175, 0));
        fje_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new fhl_2("scrollFleshColor", 0.8f));
        fkm_12.setInsets(new Insets(0, 1, 0, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 a(fdq_1 fdq_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fgm_2 fgm_22 = new fgm_2();
        fgm_22.aVI();
        fgm_22.setElementMap(fhs_22);
        fgm_22.setCellWidth(50);
        fgm_22.setColumnId("level");
        String string = "%level%";
        string = string.replace("%level%", fyw_0.gqw().k("level", new Object[0]));
        fgm_22.setName(string);
        fdq_12.X(fgm_22);
        fgm_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fgm_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setExpandable(false);
        faw_22.setNonBlocking(false);
        faw_22.setPrefSize(new fsm_1(50, 0));
        fje_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new fhl_2("scrollFleshColor", 0.8f));
        fkm_12.setInsets(new Insets(0, 1, 0, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setEnableAutoZoomShrink(true);
        fbv_22.setExpandable(false);
        fbv_22.setMaxWidth(30);
        fbv_22.setMinWidth(30);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("blackBold");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("level");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 3, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fgm_22.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjt_23.X(fjx_13);
        fjx_13.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_13.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setPrefSize(new fsm_1(40, 0));
        fje_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_03 = ((fes_2)faw_25).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_24.X(fys_03);
        fys_03.guy();
        fkm_1 fkm_13 = new fkm_1();
        fkm_13.aVI();
        fkm_13.setElementMap(fhs_22);
        fkm_13.setColor(new fhl_2("scrollFleshColor", 0.8f));
        fkm_13.setInsets(new Insets(0, 1, 0, 0));
        fys_03.X(fkm_13);
        fkm_13.guy();
        fkm_13.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_24.onChildrenAdded();
        fje_23.onChildrenAdded();
        fgm_22.onChildrenAdded();
        return fgm_22;
    }

    public fhi_2 b(fdq_1 fdq_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fgm_2 fgm_22 = new fgm_2();
        fgm_22.aVI();
        fgm_22.setElementMap(fhs_22);
        fgm_22.setCellWidth(105);
        fgm_22.setColumnId("guildPoints");
        String string = "%guild.guildPoints%";
        string = string.replace("%guild.guildPoints%", fyw_0.gqw().k("guild.guildPoints", new Object[0]));
        fgm_22.setName(string);
        fdq_12.X(fgm_22);
        fgm_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fgm_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setExpandable(false);
        faw_22.setNonBlocking(false);
        faw_22.setPrefSize(new fsm_1(105, 0));
        fje_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new fhl_2("scrollFleshColor", 0.8f));
        fkm_12.setInsets(new Insets(0, 1, 0, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setEnableAutoZoomShrink(true);
        fbv_22.setExpandable(false);
        fbv_22.setMaxWidth(70);
        fbv_22.setMinWidth(70);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("blackBold");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("guildPoints");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 3, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fgm_22.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjt_23.X(fjx_13);
        fjx_13.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_13.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setPrefSize(new fsm_1(70, 0));
        fje_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_03 = ((fes_2)faw_25).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_24.X(fys_03);
        fys_03.guy();
        fkm_1 fkm_13 = new fkm_1();
        fkm_13.aVI();
        fkm_13.setElementMap(fhs_22);
        fkm_13.setColor(new fhl_2("scrollFleshColor", 0.8f));
        fkm_13.setInsets(new Insets(0, 1, 0, 0));
        fys_03.X(fkm_13);
        fkm_13.guy();
        fkm_13.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_24.onChildrenAdded();
        fje_23.onChildrenAdded();
        fgm_22.onChildrenAdded();
        return fgm_22;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.guildLadder:previousPage");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("CharacterCreationLeftArrow");
        faw_23.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("enabled");
        fsj_22.setField("currentPage");
        fsj_22.setName("guildLadder");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjt_22.X(fja_12);
        fja_12.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjv_12.setValue("1");
        fja_12.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fad_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_23.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("StyledBold16Dark");
        faw_25.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("currentPage");
        fsj_23.setName("guildLadder");
        fdy_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_22);
        fdy_13.setExpandable(false);
        fdy_13.setStyle("StyledBold16Dark");
        fdy_13.setText("/");
        faw_25.X(fdy_13);
        fdy_13.guy();
        fdy_13.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setExpandable(false);
        fdy_14.setStyle("StyledBold16Dark");
        faw_25.X(fdy_14);
        fdy_14.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("totalPage");
        fsj_24.setName("guildLadder");
        fdy_14.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_25.onChildrenAdded();
        fde_1 fde_13 = new fde_1();
        fde_13.aVI();
        fde_13.setElementMap(fhs_22);
        faw_23.X(fde_13);
        fde_13.guy();
        fde_13.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.guildLadder:nextPage");
        fad_13.setOnClick(fmz_13);
        fad_13.setStyle("CharacterCreationRightArrow");
        faw_23.X(fad_13);
        fad_13.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("enabled");
        fsj_25.setField("currentPage");
        fsj_25.setName("guildLadder");
        fad_13.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_25.X(fjt_23);
        fjt_23.guy();
        fja_1 fja_13 = new fja_1();
        fja_13.aVI();
        fja_13.setElementMap(fhs_22);
        fjt_23.X(fja_13);
        fja_13.guy();
        fjv_1 fjv_13 = new fjv_1();
        fjv_13.aVI();
        fjv_13.setElementMap(fhs_22);
        fja_13.X(fjv_13);
        fjv_13.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("value");
        fsj_26.setField("totalPage");
        fsj_26.setName("guildLadder");
        fjv_13.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fjv_13.onChildrenAdded();
        fja_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 H(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "closeButton";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fad_12);
        }
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("backgroundDisplayClose");
        faw_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(10, 0, 0, 20));
        fym_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }
}

