/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKP
 */
public class ckp_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_23.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_04.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_04.onChildrenAdded();
        String string = "windowContentContainer";
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_27);
        }
        faw_25.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_27.X(faw_28);
        faw_28.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_28.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setExpandable(false);
        faw_28.X(faw_29);
        faw_29.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_29.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("visible");
        fsj_22.setName("isEditingGuildDescs");
        faw_29.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_29.X(faw_210);
        faw_210.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("visible");
        fsj_23.setField("hasRightToEditGuildDescription");
        fsj_23.setName("guild");
        faw_210.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLL);
        frz_25.setHorizontal(false);
        faw_210.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_211.setStyle("titleBar");
        faw_210.X(faw_211);
        faw_211.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setExpandable(false);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("whiteTitle");
        String string2 = "%guild.description%";
        string2 = string2.replace("%guild.description%", fyw_0.gqw().k("guild.description", new Object[0]));
        fbv_22.setText(string2);
        faw_211.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLL);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_212.setStyle("ShortcutRowBackgroundFull");
        faw_210.X(faw_212);
        faw_212.guy();
        faw_2 faw_213 = faw_212;
        fys_0 fys_05 = ((fes_2)faw_213).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_212.X(fys_05);
        fys_05.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 3, 3, 3));
        fys_05.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(2, 2, 5, 2));
        fys_05.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_05.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLN);
        faw_212.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        faw_212.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        String string3 = "guildDescription";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.abk(200);
        fdu_12.setMultiline(true);
        fms_2 fms_22 = new fms_2();
        fms_22.vw("wakfu.guildManagement:onKeyEvent(applyDescription)");
        fdu_12.setOnKeyPress(fms_22);
        fdu_12.setPrefSize(new fsm_1(300, 100));
        fdu_12.setRestrict("[.*&[^<>]]");
        fdu_12.setStyle("withoutBorder");
        faw_212.X(fdu_12);
        fdu_12.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLL);
        fdu_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("guildDescription");
        fsj_24.setName("guild");
        fdu_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_212.onChildrenAdded();
        String string4 = "applyDescription";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fad_12);
        }
        fad_12.setEnabled(false);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.guildManagement:applyGuildDescription(guildDescription)");
        fad_12.setOnClick(fmz_12);
        String string5 = "%apply%";
        string5 = string5.replace("%apply%", fyw_0.gqw().k("apply", new Object[0]));
        fad_12.setText(string5);
        faw_210.X(fad_12);
        fad_12.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLP);
        fad_12.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_12.X(fym_02);
        fym_02.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(0, 5, 0, 5));
        fym_02.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(5, 0, 0, 5));
        fym_02.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setExpandable(false);
        faw_29.X(faw_214);
        faw_214.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setField("hasRightToEditGuildMessage");
        fsj_25.setName("guild");
        faw_214.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_25.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_23);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjn_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_23);
        fjn_22.X(fjl_13);
        fjl_13.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("comparedValue");
        fsj_26.setField("hasRightToEditGuildDescription");
        fsj_26.setName("guild");
        fjl_13.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fjl_13.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_25.onChildrenAdded();
        faw_2 faw_215 = faw_214;
        fys_0 fys_06 = ((fes_2)faw_215).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_214.X(fys_06);
        fys_06.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(10, 0, 0, 0));
        fys_06.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_06.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_29.X(faw_216);
        faw_216.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("visible");
        fsj_27.setField("hasRightToEditGuildMessage");
        fsj_27.setName("guild");
        faw_216.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLL);
        frz_27.setHorizontal(false);
        faw_216.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setExpandable(false);
        faw_217.setStyle("titleBar");
        faw_216.X(faw_217);
        faw_217.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setNonBlocking(true);
        fbv_24.setStyle("whiteTitle");
        String string6 = "%guild.message%";
        string6 = string6.replace("%guild.message%", fyw_0.gqw().k("guild.message", new Object[0]));
        fbv_24.setText(string6);
        faw_217.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLL);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_217.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setExpandable(false);
        faw_218.setStyle("ShortcutRowBackgroundFull");
        faw_216.X(faw_218);
        faw_218.guy();
        faw_2 faw_219 = faw_218;
        fys_0 fys_07 = ((fes_2)faw_219).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_218.X(fys_07);
        fys_07.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(3, 3, 3, 3));
        fys_07.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(2, 2, 5, 2));
        fys_07.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fys_07.onChildrenAdded();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLN);
        faw_218.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLN);
        faw_218.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        String string7 = "guildMessage";
        fdu_1 fdu_13 = new fdu_1();
        fdu_13.aVI();
        fdu_13.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fdu_13);
        }
        fdu_13.setExpandable(false);
        fdu_13.abk(200);
        fdu_13.setMultiline(true);
        fms_2 fms_23 = new fms_2();
        fms_23.vw("wakfu.guildManagement:onKeyEvent(applyMessage)");
        fdu_13.setOnKeyPress(fms_23);
        fdu_13.setPrefSize(new fsm_1(300, 100));
        fdu_13.setStyle("withoutBorder");
        faw_218.X(fdu_13);
        fdu_13.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("text");
        fsj_28.setField("guildMessage");
        fsj_28.setName("guild");
        fdu_13.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLL);
        fdu_13.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fdu_13.onChildrenAdded();
        faw_218.onChildrenAdded();
        String string8 = "applyMessage";
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, fad_14);
        }
        fad_14.setEnabled(false);
        fad_14.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.guildManagement:applyGuildMessage(guildMessage)");
        fad_14.setOnClick(fmz_13);
        String string9 = "%apply%";
        string9 = string9.replace("%apply%", fyw_0.gqw().k("apply", new Object[0]));
        fad_14.setText(string9);
        faw_216.X(fad_14);
        fad_14.guy();
        frb_1 frb_17 = new frb_1();
        frb_17.aVI();
        frb_17.setElementMap(fhs_23);
        frb_17.setAlign(faa_2.tLP);
        fad_14.X(frb_17);
        frb_17.guy();
        frb_17.onChildrenAdded();
        fad_1 fad_15 = fad_14;
        fym_0 fym_03 = (fym_0)((fes_2)fad_15).getAppearance();
        fym_03.setElementMap(fhs_23);
        fad_14.X(fym_03);
        fym_03.guy();
        fzx fzx6 = new fzx();
        fzx6.aVI();
        fzx6.setElementMap(fhs_23);
        fzx6.setInsets(new Insets(0, 5, 0, 5));
        fym_03.X(fzx6);
        fzx6.guy();
        fzx6.onChildrenAdded();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_23);
        fzv8.setInsets(new Insets(5, 0, 0, 5));
        fym_03.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fym_03.onChildrenAdded();
        fad_14.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_29.onChildrenAdded();
        this.R(faw_28);
        faw_28.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.D(fey_22);
        this.C(fey_22);
        this.m(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("isEditingGuildDescs");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(10, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_24.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setStyle("titleBar");
        faw_24.X(faw_26);
        faw_26.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("whiteTitle");
        String string = "%guild.personalNote%";
        string = string.replace("%guild.personalNote%", fyw_0.gqw().k("guild.personalNote", new Object[0]));
        fbv_22.setText(string);
        faw_26.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLL);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setExpandable(false);
        faw_27.setStyle("ShortcutRowBackgroundFull");
        faw_24.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_27.X(fys_03);
        fys_03.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(3, 3, 3, 3));
        fys_03.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(2, 2, 5, 2));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_27.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        String string2 = "guildPersonalMessage";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.abk(200);
        fdu_12.setMultiline(true);
        fms_2 fms_22 = new fms_2();
        fms_22.vw("wakfu.guildManagement:onKeyEvent(applyPersonalMessage)");
        fdu_12.setOnKeyPress(fms_22);
        fdu_12.setPrefSize(new fsm_1(200, 50));
        fdu_12.setRestrict("[.*&[^<>]]");
        fdu_12.setStyle("withoutBorder");
        faw_27.X(fdu_12);
        fdu_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("guildMessage");
        fsj_23.setName("selectedGuildRank");
        fdu_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLL);
        fdu_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        String string3 = "applyPersonalMessage";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, fad_12);
        }
        fad_12.setEnabled(false);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.guildManagement:applyGuildMessage(guildPersonalMessage)");
        fad_12.setOnClick(fmz_12);
        String string4 = "%apply%";
        string4 = string4.replace("%apply%", fyw_0.gqw().k("apply", new Object[0]));
        fad_12.setText(string4);
        faw_24.X(fad_12);
        fad_12.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_22);
        frb_14.setAlign(faa_2.tLP);
        fad_12.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(0, 5, 0, 5));
        fym_02.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(5, 0, 0, 5));
        fym_02.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 D(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 C(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 m(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setResizeOnce(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

