/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKq
 */
public class ckq_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string = "%eventsCalendar.create.title%";
        string = string.replace("%eventsCalendar.create.title%", fyw_0.gqw().k("eventsCalendar.create.title", new Object[0]));
        fbv_22.setText(string);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_210.setPrefSize(new fsm_1(350, 0));
        faw_28.X(faw_210);
        faw_210.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        frz_24.setUseLegacyVGapBehaviour(true);
        frz_24.setVgap((short)3);
        faw_210.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_210.X(faw_211);
        faw_211.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_211.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("bold");
        String string3 = "%eventsCalendar.eventTitle%";
        string3 = string3.replace("%eventsCalendar.eventTitle%", fyw_0.gqw().k("eventsCalendar.eventTitle", new Object[0]));
        fbv_24.setText(string3);
        faw_211.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        String string4 = "title";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdu_12);
        }
        fdu_12.abk(50);
        faw_211.X(fdu_12);
        fdu_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("title");
        fsj_22.setName("calendar.event.editable");
        fdu_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_210.X(faw_212);
        faw_212.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHorizontal(false);
        faw_212.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("bold");
        String string5 = "%description%";
        string5 = string5.replace("%description%", fyw_0.gqw().k("description", new Object[0]));
        fbv_25.setText(string5);
        faw_212.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setStyle("textEditor");
        faw_212.X(faw_213);
        faw_213.guy();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setHorizontalScrollBarBehaviour(fzi_0.tHc);
        fcq_22.setPrefSize(new fsm_1(180, 55));
        fcq_22.setVerticalScrollBarBehaviour(fzi_0.tHb);
        faw_213.X(fcq_22);
        fcq_22.guy();
        String string6 = "description";
        fdu_1 fdu_13 = new fdu_1();
        fdu_13.aVI();
        fdu_13.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fdu_13);
        }
        fdu_13.setEnableShrinking(false);
        fdu_13.setExpandable(false);
        fdu_13.setMultiline(true);
        fdu_13.setStyle("withoutBorder");
        fcq_22.X(fdu_13);
        fdu_13.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("description");
        fsj_23.setName("calendar.event.editable");
        fdu_13.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("maxChars");
        fsj_24.setName("calendar.event.desc.maxChars");
        fdu_13.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdu_13.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_210.X(faw_214);
        faw_214.guy();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLN);
        faw_214.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setStyle("bold");
        String string7 = "%eventsCalendar.startDate%";
        string7 = string7.replace("%eventsCalendar.startDate%", fyw_0.gqw().k("eventsCalendar.startDate", new Object[0]));
        fbv_26.setText(string7);
        faw_214.X(fbv_26);
        fbv_26.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        fbv_26.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq3 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_26.X(fzq3);
        fzq3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 10));
        fzq3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_26.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        faw_214.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLO);
        fdy_12.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("startDateDesc");
        fsj_25.setName("calendar.event.editable");
        fdy_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_214.X(faw_215);
        faw_215.guy();
        faw_2 faw_216 = faw_215;
        fys_0 fys_06 = ((fes_2)faw_216).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_215.X(fys_06);
        fys_06.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 3, 0, 0));
        fys_06.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_06.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_215.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        String string8 = "start";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, fad_12);
        }
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:selectStartDate");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descSelectStartDatePopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("flat");
        faw_215.X(fad_12);
        fad_12.guy();
        String string9 = "descSelectStartDatePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string9 != null) {
            fhs_23.a(string9, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setPrefSize(new fsm_1(10, 0));
        faw_217.setStyle("popup");
        frx_12.X(faw_217);
        faw_217.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKw);
        faw_217.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setStyle("PopupInformation");
        String string10 = "%eventsCalendar.selectStartDate%";
        string10 = string10.replace("%eventsCalendar.selectStartDate%", fyw_0.gqw().k("eventsCalendar.selectStartDate", new Object[0]));
        fbv_28.setText(string10);
        faw_217.X(fbv_28);
        fbv_28.guy();
        fbv_2 fbv_29 = fbv_28;
        fzq fzq4 = (fzq)((fes_2)fbv_29).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlignment(faa_2.tLN);
        fbv_28.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_28.onChildrenAdded();
        faw_217.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fad_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("calendarIcon");
        faw_215.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_23);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(5, 5, 5, 5));
        fyY2.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_210.X(faw_218);
        faw_218.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLN);
        faw_218.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        fbv_2 fbv_210 = new fbv_2();
        fbv_210.aVI();
        fbv_210.setElementMap(fhs_23);
        fbv_210.setExpandable(false);
        fbv_210.setStyle("bold");
        String string11 = "%eventsCalendar.endDate%";
        string11 = string11.replace("%eventsCalendar.endDate%", fyw_0.gqw().k("eventsCalendar.endDate", new Object[0]));
        fbv_210.setText(string11);
        faw_218.X(fbv_210);
        fbv_210.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLO);
        fbv_210.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fbv_2 fbv_211 = fbv_210;
        fzq fzq5 = (fzq)((fes_2)fbv_211).getAppearance();
        fzq5.setElementMap(fhs_23);
        fbv_210.X(fzq5);
        fzq5.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 0, 0, 10));
        fzq5.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzq5.onChildrenAdded();
        fbv_210.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_23);
        fdy_13.setExpandable(false);
        faw_218.X(fdy_13);
        fdy_13.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLO);
        fdy_13.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        this.e(fdy_13);
        fdy_13.onChildrenAdded();
        this.c(faw_218);
        faw_218.onChildrenAdded();
        this.d(faw_210);
        this.e(faw_210);
        this.F(faw_210);
        this.G(faw_210);
        this.f(faw_210);
        this.g(faw_210);
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.O(fey_22);
        this.P(fey_22);
        this.t(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 e(fdy_1 fdy_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("endDateDesc");
        fsj_22.setName("calendar.event.editable");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 3, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        String string = "end";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fad_12);
        }
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:selectEndDate");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descSelectStartEndPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("flat");
        faw_23.X(fad_12);
        fad_12.guy();
        String string2 = "descSelectStartEndPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setPrefSize(new fsm_1(10, 0));
        faw_25.setStyle("popup");
        frx_12.X(faw_25);
        faw_25.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_25.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        String string3 = "%eventsCalendar.selectEndDate%";
        string3 = string3.replace("%eventsCalendar.selectEndDate%", fyw_0.gqw().k("eventsCalendar.selectEndDate", new Object[0]));
        fbv_22.setText(string3);
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("calendarIcon");
        faw_23.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(5, 5, 5, 5));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(50, 1));
        faw_23.setStyle("lineSeparator2");
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(5, 20, 5, 20));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        String string = "eventType";
        fry_1 fry_12 = new fry_1();
        fry_12.aVI();
        fry_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, (fhv_1)fry_12);
        }
        faw_23.X(fry_12);
        fry_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("value");
        fsj_22.setField("selectedType/value");
        fsj_22.setName("calendar.event.editable");
        fry_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fry_12.onChildrenAdded();
        fcu_1 fcu_12 = new fcu_1();
        fcu_12.aVI();
        fcu_12.setElementMap(fhs_22);
        fcu_12.setGroupId("eventType");
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu.eventsCalendar:setEventType");
        fcu_12.setOnSelectionChange(fmo_12);
        String string2 = "%calendar.event.type.1%";
        string2 = string2.replace("%calendar.event.type.1%", fyw_0.gqw().k("calendar.event.type.1", new Object[0]));
        fcu_12.setText(string2);
        fcu_12.setValue("1");
        faw_23.X(fcu_12);
        fcu_12.guy();
        fcu_12.onChildrenAdded();
        fcu_1 fcu_13 = new fcu_1();
        fcu_13.aVI();
        fcu_13.setElementMap(fhs_22);
        fcu_13.setGroupId("eventType");
        fmo_1 fmo_13 = new fmo_1();
        fmo_13.vw("wakfu.eventsCalendar:setEventType");
        fcu_13.setOnSelectionChange(fmo_13);
        String string3 = "%calendar.event.type.2%";
        string3 = string3.replace("%calendar.event.type.2%", fyw_0.gqw().k("calendar.event.type.2", new Object[0]));
        fcu_13.setText(string3);
        fcu_13.setValue("2");
        faw_23.X(fcu_13);
        fcu_13.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setField("hasGuild");
        fsj_23.setName("localPlayer");
        fcu_13.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fcu_13.onChildrenAdded();
        fcu_1 fcu_14 = new fcu_1();
        fcu_14.aVI();
        fcu_14.setElementMap(fhs_22);
        fcu_14.setGroupId("eventType");
        fmo_1 fmo_14 = new fmo_1();
        fmo_14.vw("wakfu.eventsCalendar:setEventType");
        fcu_14.setOnSelectionChange(fmo_14);
        String string4 = "%calendar.event.type.3%";
        string4 = string4.replace("%calendar.event.type.3%", fyw_0.gqw().k("calendar.event.type.3", new Object[0]));
        fcu_14.setText(string4);
        fcu_14.setValue("3");
        faw_23.X(fcu_14);
        fcu_14.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("visible");
        fsj_24.setName("isAdmin");
        fcu_14.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fcu_14.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu.eventsCalendar:setParticipantsLimited");
        fdd_22.setOnSelectionChange(fmo_12);
        String string = "%eventsCalendar.limitParticipants%";
        string = string.replace("%eventsCalendar.limitParticipants%", fyw_0.gqw().k("eventsCalendar.limitParticipants", new Object[0]));
        fdd_22.setText(string);
        faw_22.X(fdd_22);
        fdd_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("selected");
        fsj_22.setField("areParticipantsLimited");
        fsj_22.setName("calendar.event.editable");
        fdd_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setField("canEditParticipantsLimit");
        fsj_23.setName("calendar.event.editable");
        fdd_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdd_22.onChildrenAdded();
        return fdd_22;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        String string = "numRegisteredContainer";
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_24);
        }
        faw_24.setExpandable(false);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(2, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("areParticipantsLimited");
        fsj_22.setName("calendar.event.editable");
        faw_24.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        faw_24.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("bold");
        String string2 = "%eventsCalendar.eventMaxRegistered%";
        string2 = string2.replace("%eventsCalendar.eventMaxRegistered%", fyw_0.gqw().k("eventsCalendar.eventMaxRegistered", new Object[0]));
        fbv_22.setText(string2);
        faw_24.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 0, 10));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        String string3 = "maxRegistrations";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, fdu_12);
        }
        fdu_12.setExpandable(false);
        fdu_12.abk(2);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.eventsCalendar:changeMaxRegistrations");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setPrefSize(new fsm_1(15, 0));
        fdu_12.setRestrict("[0-9]");
        fdu_12.setSelectOnFocus(true);
        faw_24.X(fdu_12);
        fdu_12.guy();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq3 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLP);
        fdu_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        fdu_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("maxRegistrations");
        fsj_23.setName("calendar.event.editable");
        fdu_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("editable");
        fsj_24.setName("calendar.event.editable.isOwner");
        fdu_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        String string4 = "numParticipantsContainer";
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        if (fhs_22 != null && string4 != null) {
            fhs_22.a(string4, faw_26);
        }
        faw_26.setExpandable(false);
        faw_23.X(faw_26);
        faw_26.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("visible");
        fsj_25.setField("areParticipantsLimited");
        fsj_25.setName("calendar.event.editable");
        faw_26.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_26.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("bold");
        String string5 = "%eventsCalendar.eventMaxParticipants%";
        string5 = string5.replace("%eventsCalendar.eventMaxParticipants%", fyw_0.gqw().k("eventsCalendar.eventMaxParticipants", new Object[0]));
        fbv_24.setText(string5);
        faw_26.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq4 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq4.setElementMap(fhs_22);
        fbv_24.X(fzq4);
        fzq4.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 0, 0, 10));
        fzq4.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq4.onChildrenAdded();
        fbv_24.onChildrenAdded();
        String string6 = "maxParticipants";
        fdu_1 fdu_14 = new fdu_1();
        fdu_14.aVI();
        fdu_14.setElementMap(fhs_22);
        if (fhs_22 != null && string6 != null) {
            fhs_22.a(string6, fdu_14);
        }
        fdu_14.setExpandable(false);
        fdu_14.abk(2);
        fmu_2 fmu_23 = new fmu_2();
        fmu_23.vw("wakfu.eventsCalendar:changeMaxParticipants");
        fdu_14.setOnKeyType(fmu_23);
        fdu_14.setPrefSize(new fsm_1(15, 0));
        fdu_14.setRestrict("[0-9]");
        fdu_14.setSelectOnFocus(true);
        faw_26.X(fdu_14);
        fdu_14.guy();
        fdu_1 fdu_15 = fdu_14;
        fzq fzq5 = (fzq)((fes_2)fdu_15).getAppearance();
        fzq5.setElementMap(fhs_22);
        fzq5.setAlign(faa_2.tLP);
        fdu_14.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLN);
        fdu_14.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("text");
        fsj_26.setField("maxParticipants");
        fsj_26.setName("calendar.event.editable");
        fdu_14.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fdu_14.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(50, 1));
        faw_23.setStyle("lineSeparator2");
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(5, 20, 5, 20));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:createEvent(title,description,maxParticipants,maxRegistrations)");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("flat");
        String string = "%eventsCalendar.create.action%";
        string = string.replace("%eventsCalendar.create.action%", fyw_0.gqw().k("eventsCalendar.create.action", new Object[0]));
        fad_12.setText(string);
        faw_22.X(fad_12);
        fad_12.guy();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(3, 0, 0, 0));
        fym_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(3, 10, 3, 10));
        fym_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fym_02.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fad_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 O(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 P(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:closeCreateEventDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 t(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

