/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKr
 */
public class ckr_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string = "%eventsCalendar.title%";
        string = string.replace("%eventsCalendar.title%", fyw_0.gqw().k("eventsCalendar.title", new Object[0]));
        fbv_22.setText(string);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_210.setPrefSize(new fsm_1(0, 0));
        faw_28.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_211.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_211.X(faw_212);
        faw_212.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLL);
        faw_212.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_212.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_212.X(faw_213);
        faw_213.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLP);
        faw_213.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fas_1 fas_12 = new fas_1();
        fas_12.aVI();
        fas_12.setElementMap(fhs_23);
        fas_12.setExpandable(false);
        fmv_2 fmv_22 = new fmv_2();
        fmv_22.vw("wakfu.eventsCalendar:changeCurrentMonth");
        fas_12.setOnListSelectionChange(fmv_22);
        fas_12.setPrefSize(new fsm_1(100, 15));
        faw_213.X(fas_12);
        fas_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("content");
        fsj_22.setField("calendar/monthesList");
        fsj_22.setName("eventsCalendar");
        fas_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("selectedValue");
        fsj_23.setField("calendar/selectedMonth");
        fsj_23.setName("eventsCalendar");
        fas_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fcv_1 fcv_12 = new fcv_1();
        fcv_12.aVI();
        fcv_12.setElementMap(fhs_23);
        fas_12.X(fcv_12);
        fcv_12.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fcv_12.X(fje_22);
        fje_22.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setNonBlocking(true);
        fje_22.X(fbv_24);
        fbv_24.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLO);
        fbv_24.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("description");
        fbv_24.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fcv_12.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(100.0f, 16));
        fbz_22.setHorizontal(false);
        fas_12.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fbz_22.X(fje_23);
        fje_23.guy();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setNonBlocking(true);
        fje_23.X(fbv_25);
        fbv_25.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fsd_13.setField("description");
        fbv_25.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq3 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_25.X(fzq3);
        fzq3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 10, 0, 0));
        fzq3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_25.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_22.onChildrenAdded();
        fas_12.onChildrenAdded();
        fas_1 fas_13 = new fas_1();
        fas_13.aVI();
        fas_13.setElementMap(fhs_23);
        fas_13.setExpandable(false);
        fmv_2 fmv_23 = new fmv_2();
        fmv_23.vw("wakfu.eventsCalendar:changeCurrentYear");
        fas_13.setOnListSelectionChange(fmv_23);
        fas_13.setPrefSize(new fsm_1(50, 15));
        faw_213.X(fas_13);
        fas_13.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("content");
        fsj_24.setField("calendar/yearsList");
        fsj_24.setName("eventsCalendar");
        fas_13.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("selectedValue");
        fsj_25.setField("calendar/selectedYear");
        fsj_25.setName("eventsCalendar");
        fas_13.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fcv_1 fcv_13 = new fcv_1();
        fcv_13.aVI();
        fcv_13.setElementMap(fhs_23);
        fas_13.X(fcv_13);
        fcv_13.guy();
        fje_2 fje_24 = new fje_2();
        fje_24.aVI();
        fje_24.setElementMap(fhs_23);
        fcv_13.X(fje_24);
        fje_24.guy();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setNonBlocking(true);
        fje_24.X(fbv_27);
        fbv_27.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLO);
        fbv_27.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("text");
        fbv_27.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_27.onChildrenAdded();
        fje_24.onChildrenAdded();
        fcv_13.onChildrenAdded();
        fbz_2 fbz_23 = new fbz_2();
        fbz_23.aVI();
        fbz_23.setElementMap(fhs_23);
        fbz_23.setCellSize(new fsm_1(100.0f, 16));
        fbz_23.setHorizontal(false);
        fas_13.X(fbz_23);
        fbz_23.guy();
        fje_2 fje_25 = new fje_2();
        fje_25.aVI();
        fje_25.setElementMap(fhs_23);
        fbz_23.X(fje_25);
        fje_25.guy();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setNonBlocking(true);
        fje_25.X(fbv_28);
        fbv_28.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("text");
        fbv_28.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_2 fbv_29 = fbv_28;
        fzq fzq4 = (fzq)((fes_2)fbv_29).getAppearance();
        fzq4.setElementMap(fhs_23);
        fbv_28.X(fzq4);
        fzq4.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 10, 0, 0));
        fzq4.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq4.onChildrenAdded();
        fbv_28.onChildrenAdded();
        fje_25.onChildrenAdded();
        fbz_23.onChildrenAdded();
        fas_13.onChildrenAdded();
        faw_213.onChildrenAdded();
        String string3 = "calendar";
        fak_2 fak_22 = new fak_2();
        fak_22.aVI();
        fak_22.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fak_22);
        }
        fak_22.setCellSize(new fsm_1(100, 95));
        fak_22.setDateMargin(new Insets(0, 0, 5, 6));
        fak_22.setExpandable(false);
        faw_212.X(fak_22);
        fak_22.guy();
        fje_2 fje_26 = new fje_2();
        fje_26.aVI();
        fje_26.setElementMap(fhs_23);
        fak_22.X(fje_26);
        fje_26.guy();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setStyle("caracs");
        fje_26.X(faw_214);
        faw_214.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_214.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_214.X(faw_215);
        faw_215.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_215.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        faw_215.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbz_2 fbz_24 = new fbz_2();
        fbz_24.aVI();
        fbz_24.setElementMap(fhs_23);
        fbz_24.setAutoIdealSize(true);
        fbz_24.setCellSize(new fsm_1(21, 21));
        fbz_24.setExpandable(false);
        fbz_24.setHorizontal(false);
        fbz_24.setIdealSizeMaxColumns(4);
        fbz_24.setIdealSizeMinColumns(0);
        fbz_24.setMaxSize(new fsm_1(84, 63));
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.eventsCalendar:openEditEventDialog");
        fbz_24.setOnItemClick(fmo_22);
        fmq_1 fmq_12 = new fmq_1();
        fmq_12.vw("wakfu.eventsCalendar:hideEventDescriptionPopup(eventDescriptionPopup)");
        fbz_24.setOnItemOut(fmq_12);
        fmr_2 fmr_22 = new fmr_2();
        fmr_22.vw("wakfu.eventsCalendar:displayEventDescriptionPopup(eventDescriptionPopup)");
        fbz_24.setOnItemOver(fmr_22);
        fbz_24.setShrinkable(true);
        faw_215.X(fbz_24);
        fbz_24.guy();
        frb_1 frb_17 = new frb_1();
        frb_17.aVI();
        frb_17.setElementMap(fhs_23);
        frb_17.setAlign(faa_2.tLL);
        fbz_24.X(frb_17);
        frb_17.guy();
        frb_17.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("content");
        fbz_24.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fje_2 fje_27 = new fje_2();
        fje_27.aVI();
        fje_27.setElementMap(fhs_23);
        fbz_24.X(fje_27);
        fje_27.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_27.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        fje_27.X(faw_216);
        faw_216.guy();
        this.R(faw_216);
        this.c(faw_216);
        this.d(faw_216);
        faw_216.onChildrenAdded();
        fje_27.onChildrenAdded();
        fbz_24.onChildrenAdded();
        faw_215.onChildrenAdded();
        this.e(faw_214);
        faw_214.onChildrenAdded();
        fje_26.onChildrenAdded();
        fak_22.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.n(fey_22);
        this.q(fey_22);
        this.r(fey_22);
        this.N(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        return null;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setPrefSize(new fsm_1(18, 18));
        fad_12.setStyle("flat");
        faw_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(16, 16));
        fbt_12.setNonBlocking(true);
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("iconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:openCreateEventDialog");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descCreateEventPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("add");
        faw_22.X(fad_12);
        fad_12.guy();
        String string = "descCreateEventPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_23.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        String string2 = "%eventsCalendar.create.title%";
        string2 = string2.replace("%eventsCalendar.create.title%", fyw_0.gqw().k("eventsCalendar.create.title", new Object[0]));
        fbv_22.setText(string2);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.eventsCalendar:closeDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 N(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "eventDescriptionPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        fey_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(300, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMinWidth(180);
        fdy_12.setStyle("bigTitle");
        faw_23.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        fdy_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("title");
        fsj_22.setName("calendar.event.detail");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_23.X(faw_24);
        faw_24.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setField("areParticipantsLimited");
        fsj_23.setName("calendar.event.detail");
        faw_24.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setStyle("singleCharacterIcon");
        faw_24.X(fbt_12);
        fbt_12.guy();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("11Light");
        faw_24.X(fbv_22);
        fbv_22.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLN);
        fbv_22.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("numParticipantsDesc");
        fsj_24.setName("calendar.event.detail");
        fbv_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("visible");
        fsj_25.setField("areParticipantsLimited");
        fsj_25.setName("calendar.event.detail");
        faw_25.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setStyle("tripleCharacterIcon");
        faw_25.X(fbt_13);
        fbt_13.guy();
        fbt_13.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("11Light");
        faw_25.X(fbv_23);
        fbv_23.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_22);
        frb_14.setAlign(faa_2.tLN);
        fbv_23.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("text");
        fsj_26.setField("numRegistrationsDesc");
        fsj_26.setName("calendar.event.detail");
        fbv_23.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fbv_23.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(50, 1));
        faw_26.setStyle("lineSeparator2");
        faw_22.X(faw_26);
        faw_26.guy();
        faw_2 faw_27 = faw_26;
        fys_0 fys_02 = ((fes_2)faw_27).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_26.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(5, 20, 5, 20));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_22.X(faw_28);
        faw_28.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_28.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("11BoldLight");
        String string2 = "%description%";
        string2 = string2.replace("%description%", fyw_0.gqw().k("description", new Object[0]));
        fbv_24.setText(string2);
        faw_28.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_22);
        fdy_13.setExpandable(false);
        fdy_13.setMinWidth(280);
        fdy_13.setStyle("White11");
        faw_28.X(fdy_13);
        fdy_13.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_22);
        frb_15.setAlign(faa_2.tLN);
        fdy_13.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq2 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_13.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("text");
        fsj_27.setField("description");
        fsj_27.setName("calendar.event.detail");
        fdy_13.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fdy_13.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_22.X(faw_29);
        faw_29.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_22);
        fsj_28.setAttribute("visible");
        fsj_28.setField("startDateDesc");
        fsj_28.setName("calendar.event.detail");
        faw_29.X(fsj_28);
        fsj_28.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_28.X(fjt_22);
        fjt_22.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjt_22.X(fja_12);
        fja_12.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjv_12.setValue("");
        fja_12.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_28.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_29.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_210 = faw_29;
        fys_0 fys_03 = ((fes_2)faw_210).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_29.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(5, 0, 0, 0));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("11BoldLight");
        String string3 = "%eventsCalendar.startDate%";
        string3 = string3.replace("%eventsCalendar.startDate%", fyw_0.gqw().k("eventsCalendar.startDate", new Object[0]));
        fbv_25.setText(string3);
        faw_29.X(fbv_25);
        fbv_25.guy();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq3 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_25.X(fzq3);
        fzq3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(0, 0, 0, 5));
        fzq3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_25.onChildrenAdded();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_22);
        fdy_15.setExpandable(false);
        fdy_15.setMinWidth(180);
        fdy_15.setStyle("White11");
        faw_29.X(fdy_15);
        fdy_15.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_22);
        frb_16.setAlign(faa_2.tLN);
        fdy_15.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_22);
        fsj_29.setAttribute("text");
        fsj_29.setField("startDateDesc");
        fsj_29.setName("calendar.event.detail");
        fdy_15.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fdy_15.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_22.X(faw_211);
        faw_211.guy();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_22);
        fsj_210.setAttribute("visible");
        fsj_210.setField("endDateDesc");
        fsj_210.setName("calendar.event.detail");
        faw_211.X(fsj_210);
        fsj_210.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_210.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_23.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_210.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_211.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_212 = faw_211;
        fys_0 fys_04 = ((fes_2)faw_212).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_211.X(fys_04);
        fys_04.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_22);
        fzv6.setInsets(new Insets(5, 0, 0, 0));
        fys_04.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_04.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_22);
        fbv_27.setExpandable(false);
        fbv_27.setStyle("11BoldLight");
        String string4 = "%eventsCalendar.endDate%";
        string4 = string4.replace("%eventsCalendar.endDate%", fyw_0.gqw().k("eventsCalendar.endDate", new Object[0]));
        fbv_27.setText(string4);
        faw_211.X(fbv_27);
        fbv_27.guy();
        fbv_2 fbv_28 = fbv_27;
        fzq fzq4 = (fzq)((fes_2)fbv_28).getAppearance();
        fzq4.setElementMap(fhs_22);
        fbv_27.X(fzq4);
        fzq4.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_22);
        fzv7.setInsets(new Insets(0, 0, 0, 5));
        fzq4.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzq4.onChildrenAdded();
        fbv_27.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        fdy_16.setExpandable(false);
        fdy_16.setMinWidth(180);
        fdy_16.setStyle("White11");
        faw_211.X(fdy_16);
        fdy_16.guy();
        frb_1 frb_17 = new frb_1();
        frb_17.aVI();
        frb_17.setElementMap(fhs_22);
        frb_17.setAlign(faa_2.tLN);
        fdy_16.X(frb_17);
        frb_17.guy();
        frb_17.onChildrenAdded();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_22);
        fsj_211.setAttribute("text");
        fsj_211.setField("endDateDesc");
        fsj_211.setName("calendar.event.detail");
        fdy_16.X(fsj_211);
        fsj_211.guy();
        fsj_211.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }
}

