/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKS
 */
public class cks_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string = "%haven.world.entrance.title%";
        string = string.replace("%haven.world.entrance.title%", fyw_0.gqw().k("haven.world.entrance.title", new Object[0]));
        fbv_22.setText(string);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 5));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(false);
        faw_210.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLf);
        frp_14.setSize(new fsm_1(300, 100.0f));
        faw_211.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_211.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_211.X(faw_212);
        faw_212.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLa);
        frp_15.setSize(new fsm_1(100.0f, 70));
        faw_212.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLO);
        frz_24.setHorizontal(false);
        faw_212.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_212.X(faw_213);
        faw_213.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLL);
        faw_213.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        faw_2 faw_214 = faw_213;
        fys_0 fys_06 = ((fes_2)faw_214).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_213.X(fys_06);
        fys_06.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(5, 0, 0, 0));
        fys_06.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_06.onChildrenAdded();
        String string3 = "customNameFilter";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fdu_12);
        }
        fdu_12.setAutoHorizontalScrolled(true);
        String string4 = "%guild.name%";
        string4 = string4.replace("%guild.name%", fyw_0.gqw().k("guild.name", new Object[0]));
        fdu_12.tX(string4);
        fdu_12.abk(30);
        fdu_12.setMinWidth(240);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.havenWorldEntrance:validNameFilter(customNameFilter)");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setSelectOnFocus(true);
        faw_213.X(fdu_12);
        fdu_12.guy();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq3 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fdu_12.X(fzq3);
        fzq3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(5, 5, 5, 5));
        fzq3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_213.X(faw_215);
        faw_215.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_215.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_215.X(faw_216);
        faw_216.guy();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(20, 20));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(openFilterPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        fbt_12.setStyle("LOCK");
        faw_216.X(fbt_12);
        fbt_12.guy();
        String string5 = "openFilterPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setPrefSize(new fsm_1(10, 0));
        faw_217.setStyle("popup");
        frx_12.X(faw_217);
        faw_217.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setStyle("PopupInformation");
        String string6 = "%desc.havenWorld.openedFilter%";
        string6 = string6.replace("%desc.havenWorld.openedFilter%", fyw_0.gqw().k("desc.havenWorld.openedFilter", new Object[0]));
        fbv_24.setText(string6);
        faw_217.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq4 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlignment(faa_2.tLN);
        fbv_24.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_217.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_23);
        fdd_22.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.havenWorldEntrance:checkOpenedFilter");
        fdd_22.setOnClick(fmz_12);
        fdd_22.setSelected(true);
        fdd_22.setStyle("filter");
        faw_216.X(fdd_22);
        fdd_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("selected");
        fsj_22.setField("isOpenedFilter");
        fsj_22.setLocal(true);
        fsj_22.setName("havenWorldListView");
        fdd_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdd_22.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setExpandable(false);
        faw_215.X(faw_218);
        faw_218.guy();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setDisplaySize(new fsm_1(20, 20));
        fbt_13.setExpandable(false);
        fbt_13.setNonBlocking(false);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(guildFilterPopup)");
        fbt_13.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fbt_13.setOnPopupHide(fml_13);
        fbt_13.setStyle("NEWGUILD");
        faw_218.X(fbt_13);
        fbt_13.guy();
        String string7 = "guildFilterPopup";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, frx_13);
        }
        frx_13.setAlign(faa_2.tLL);
        frx_13.setHotSpotPosition(faa_2.tLR);
        fbt_13.X(frx_13);
        frx_13.guy();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_219.setPrefSize(new fsm_1(10, 0));
        faw_219.setStyle("popup");
        frx_13.X(faw_219);
        faw_219.guy();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setStyle("PopupInformation");
        String string8 = "%desc.havenWorld.guildFilter%";
        string8 = string8.replace("%desc.havenWorld.guildFilter%", fyw_0.gqw().k("desc.havenWorld.guildFilter", new Object[0]));
        fbv_26.setText(string8);
        faw_219.X(fbv_26);
        fbv_26.guy();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq5 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlignment(faa_2.tLN);
        fbv_26.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_219.onChildrenAdded();
        frx_13.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fdd_2 fdd_23 = new fdd_2();
        fdd_23.aVI();
        fdd_23.setElementMap(fhs_23);
        fdd_23.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.havenWorldEntrance:checkGuildFilter");
        fdd_23.setOnClick(fmz_13);
        fdd_23.setSelected(true);
        fdd_23.setStyle("filter");
        faw_218.X(fdd_23);
        fdd_23.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("selected");
        fsj_23.setField("isGuildFilter");
        fsj_23.setLocal(true);
        fsj_23.setName("havenWorldListView");
        fdd_23.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdd_23.onChildrenAdded();
        faw_218.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        faw_220.setNonBlocking(true);
        faw_212.X(faw_220);
        faw_220.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLO);
        faw_220.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setEnabled(false);
        fad_12.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.havenWorldEntrance:firstPage()");
        fad_12.setOnClick(fmz_14);
        fad_12.setStyle("pagingAllLeft");
        faw_220.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("enabled");
        fsj_24.setField("hasPreviousPage");
        fsj_24.setName("havenWorldViewList");
        fad_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fad_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setEnabled(false);
        fad_13.setExpandable(false);
        fmz_1 fmz_15 = new fmz_1();
        fmz_15.vw("wakfu.havenWorldEntrance:previousPage()");
        fad_13.setOnClick(fmz_15);
        fad_13.setStyle("pagingOneLeft");
        faw_220.X(fad_13);
        fad_13.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("enabled");
        fsj_25.setField("hasPreviousPage");
        fsj_25.setName("havenWorldViewList");
        fad_13.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fad_13.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setPrefSize(new fsm_1(120, 0));
        fdy_12.setStyle("titleNameBold12");
        String string9 = "%marketBoard.noResults%";
        string9 = string9.replace("%marketBoard.noResults%", fyw_0.gqw().k("marketBoard.noResults", new Object[0]));
        fdy_12.setText(string9);
        faw_220.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("text");
        fsj_26.setField("currentPageText");
        fsj_26.setName("havenWorldViewList");
        fdy_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq6 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq6.setElementMap(fhs_23);
        fzq6.setAlign(faa_2.tLO);
        fdy_12.X(fzq6);
        fzq6.guy();
        fzq6.onChildrenAdded();
        fdy_12.onChildrenAdded();
        this.R(faw_220);
        this.c(faw_220);
        faw_220.onChildrenAdded();
        faw_212.onChildrenAdded();
        this.d(faw_211);
        this.e(faw_211);
        faw_211.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.n(fey_22);
        this.q(fey_22);
        this.r(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setEnabled(false);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.havenWorldEntrance:nextPage()");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("pagingOneRight");
        faw_22.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("enabled");
        fsj_22.setField("hasNextPage");
        fsj_22.setName("havenWorldViewList");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setEnabled(false);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.havenWorldEntrance:lastPage()");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("pagingAllRight");
        faw_22.X(fad_12);
        fad_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("enabled");
        fsd_12.setField("hasNextPage");
        fad_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("enabled");
        fsj_22.setField("hasNextPage");
        fsj_22.setName("havenWorldViewList");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(100.0f, 460));
        frp_12.setYOffset(40);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 8, 0, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(285, 50));
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMinColumns(1);
        fbz_22.setScrollBarBehaviour(fzi_0.tHc);
        faw_23.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("filteredList");
        fsj_22.setName("havenWorldViewList");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.havenWorldEntrance:selectHavenWorld");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setStyle("caracs");
        fje_22.X(faw_25);
        faw_25.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("style");
        fsj_23.setLocal(true);
        fsj_23.setName("selectedHavenWorld");
        faw_25.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fjt_23.setElseValue("caracs");
        fjt_23.setValue("caracsBlue");
        fsj_23.X(fjt_23);
        fjt_23.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjt_23.X(fjv_12);
        fjv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        fjv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fjv_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_23.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_25.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        frz_22.setHorizontal(true);
        faw_25.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(32, 32));
        faw_25.X(faw_26);
        faw_26.guy();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(32, 32));
        faw_26.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("texture");
        fsd_13.setField("guildBlazon");
        fze2.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setNonBlocking(false);
        faw_25.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_27.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 10, 0, 3));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(200);
        fdy_12.setMultiline(true);
        fdy_12.setNonBlocking(false);
        fdy_12.setStyle("titleNameBold10");
        faw_27.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fdy_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_27.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setDisplaySize(new fsm_1(20, 20));
        fbt_13.setExpandable(false);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("NEWGUILD");
        faw_27.X(fbt_13);
        fbt_13.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("visible");
        fsd_15.setField("isGuildOnly");
        fbt_13.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setExpandable(false);
        faw_29.setPrefSize(new fsm_1(20, 20));
        faw_27.X(faw_29);
        faw_29.guy();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setDisplaySize(new fsm_1(20, 20));
        fbt_14.setExpandable(false);
        fbt_14.setNonBlocking(true);
        fbt_14.setStyle("LOCK");
        faw_29.X(fbt_14);
        fbt_14.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("visible");
        fsd_16.setField("isOpen");
        fbt_14.X(fsd_16);
        fsd_16.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fsd_16.X(fjt_24);
        fjt_24.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_24.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_16.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(100.0f, 30));
        frp_12.setYOffset(10);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setPrefSize(new fsm_1(110, 30));
        faw_24.setVisible(false);
        faw_23.X(faw_24);
        faw_24.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("canEnter");
        fsj_22.setName("basicHavenWorld");
        faw_24.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.havenWorldEntrance:enterHavenWorld");
        fad_12.setOnClick(fmz_12);
        faw_24.X(fad_12);
        fad_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(110, 30));
        fad_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("titleNameBold12");
        String string = "%door.enter%";
        string = string.replace("%door.enter%", fyw_0.gqw().k("door.enter", new Object[0]));
        fdy_12.setText(string);
        faw_24.X(fdy_12);
        fdy_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(110, 30));
        fdy_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setPrefSize(new fsm_1(110, 30));
        faw_25.setVisible(false);
        faw_23.X(faw_25);
        faw_25.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setField("canOpen");
        fsj_23.setName("basicHavenWorld");
        faw_25.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_25.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.havenWorldEntrance:openHavenWorld");
        fad_13.setOnClick(fmz_13);
        faw_25.X(fad_13);
        fad_13.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(110, 30));
        fad_13.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fad_13.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setNonBlocking(true);
        fdy_14.setStyle("titleNameBold12");
        String string2 = "%havenWorld.open%";
        string2 = string2.replace("%havenWorld.open%", fyw_0.gqw().k("havenWorld.open", new Object[0]));
        fdy_14.setText(string2);
        faw_25.X(fdy_14);
        fdy_14.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(110, 30));
        fdy_14.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLO);
        fdy_14.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setResizeOnce(true);
        frp_12.setSize(new fsm_1(340, 620));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

