/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cKU
 */
public class cku_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setNonBlocking(false);
        faw_23.setStyle("windowBackgroundSecondary");
        fey_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setPrefSize(new fsm_1(100.0f, 56));
        faw_24.setStyle("windowHeaderSmallSecondary");
        fea_12.X(faw_24);
        faw_24.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_24.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setExpandable(false);
        faw_25.setPrefSize(new fsm_1(44, 32));
        faw_24.X(faw_25);
        faw_25.guy();
        faw_25.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("windowTitle");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("isDirectionToOther");
        fsj_22.setName("heroBuildCopyBuildView");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        String string = "%build.copy.from%";
        string = string.replace("%build.copy.from%", fyw_0.gqw().k("build.copy.from", new Object[0]));
        fjt_22.setElseValue(string);
        String string2 = "%build.copy.to%";
        string2 = string2.replace("%build.copy.to%", fyw_0.gqw().k("build.copy.to", new Object[0]));
        fjt_22.setValue(string2);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjt_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        String string3 = "levelTooHighPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbv_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setPrefSize(new fsm_1(10, 0));
        faw_26.setStyle("popup");
        frx_12.X(faw_26);
        faw_26.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("PopupInformation");
        faw_26.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlignment(faa_2.tLN);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("isDirectionToOther");
        fsj_23.setName("heroBuildCopyBuildView");
        fbv_24.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        String string4 = "%build.copy.from.invalid.level%";
        string4 = string4.replace("%build.copy.from.invalid.level%", fyw_0.gqw().k("build.copy.from.invalid.level", new Object[0]));
        fjt_23.setElseValue(string4);
        String string5 = "%build.copy.to.invalid.level%";
        string5 = string5.replace("%build.copy.to.invalid.level%", fyw_0.gqw().k("build.copy.to.invalid.level", new Object[0]));
        fjt_23.setValue(string5);
        fsj_23.X(fjt_23);
        fjt_23.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_23);
        fjt_23.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_26.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(44, 32));
        faw_24.X(faw_27);
        faw_27.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setPrefSize(new fsm_1(32, 32));
        fad_12.setStyle("crossTertiary");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        faw_27.X(fad_12);
        fad_12.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 0, 12));
        fad_12.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLP);
        fad_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_24.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string6 = "windowContentContainer";
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, faw_28);
        }
        faw_28.setPrefSize(new fsm_1(600, 700));
        faw_23.X(faw_28);
        faw_28.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_28.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_28.X(faw_29);
        faw_29.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_28.X(faw_210);
        faw_210.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_210.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_211 = faw_210;
        fys_0 fys_02 = ((fes_2)faw_211).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_210.X(fys_02);
        fys_02.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(8, 16, 16, 16));
        fys_02.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setPrefSize(new fsm_1(100.0f, 100.0f));
        faw_210.X(faw_212);
        faw_212.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_212.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_212.X(faw_213);
        faw_213.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_213.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setExpandable(false);
        faw_213.X(faw_214);
        faw_214.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_214.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setStyle("wipLight16");
        String string7 = "%copy%%colon%";
        string7 = string7.replace("%copy%", fyw_0.gqw().k("copy", new Object[0]));
        string7 = string7.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fbv_26.setText(string7);
        faw_214.X(fbv_26);
        fbv_26.guy();
        fbv_26.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_214.X(faw_215);
        faw_215.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHgap((short)12);
        faw_215.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(12, 0, 0, 0));
        faw_215.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        String string8 = "copyEquipmentsCb";
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, fdd_22);
        }
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu.heroBuild:changePartsToCopy(copyEquipmentsCb,copySpellsCb,copyAptitudesCb)");
        fdd_22.setOnSelectionChange(fmo_12);
        fdd_22.setStyle("defaultCheckboxWithBG");
        String string9 = "%equipments%";
        string9 = string9.replace("%equipments%", fyw_0.gqw().k("equipments", new Object[0]));
        fdd_22.setText(string9);
        faw_215.X(fdd_22);
        fdd_22.guy();
        fdd_22.onChildrenAdded();
        String string10 = "copySpellsCb";
        fdd_2 fdd_23 = new fdd_2();
        fdd_23.aVI();
        fdd_23.setElementMap(fhs_23);
        if (fhs_23 != null && string10 != null) {
            fhs_23.a(string10, fdd_23);
        }
        fmo_1 fmo_13 = new fmo_1();
        fmo_13.vw("wakfu.heroBuild:changePartsToCopy(copyEquipmentsCb,copySpellsCb,copyAptitudesCb)");
        fdd_23.setOnSelectionChange(fmo_13);
        fdd_23.setStyle("defaultCheckboxWithBG");
        String string11 = "%spells%";
        string11 = string11.replace("%spells%", fyw_0.gqw().k("spells", new Object[0]));
        fdd_23.setText(string11);
        faw_215.X(fdd_23);
        fdd_23.guy();
        fdd_23.onChildrenAdded();
        String string12 = "copyAptitudesCb";
        fdd_2 fdd_24 = new fdd_2();
        fdd_24.aVI();
        fdd_24.setElementMap(fhs_23);
        if (fhs_23 != null && string12 != null) {
            fhs_23.a(string12, fdd_24);
        }
        fmo_1 fmo_14 = new fmo_1();
        fmo_14.vw("wakfu.heroBuild:changePartsToCopy(copyEquipmentsCb,copySpellsCb,copyAptitudesCb)");
        fdd_24.setOnSelectionChange(fmo_14);
        fdd_24.setStyle("defaultCheckboxWithBG");
        String string13 = "%abilities%";
        string13 = string13.replace("%abilities%", fyw_0.gqw().k("abilities", new Object[0]));
        fdd_24.setText(string13);
        faw_215.X(fdd_24);
        fdd_24.guy();
        fdd_24.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setPrefSize(new fsm_1(100.0f, 100.0f));
        faw_213.X(faw_216);
        faw_216.guy();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setHorizontal(false);
        frz_27.setVgap((short)12);
        faw_216.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(12, 0, 0, 0));
        faw_216.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setExpandable(false);
        fbv_27.setStyle("wipLight16");
        faw_216.X(fbv_27);
        fbv_27.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("isDirectionToOther");
        fsj_24.setName("heroBuildCopyBuildView");
        fbv_27.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        String string14 = "%build.from%%colon%";
        string14 = string14.replace("%build.from%", fyw_0.gqw().k("build.from", new Object[0]));
        string14 = string14.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fjt_24.setElseValue(string14);
        String string15 = "%build.to%%colon%";
        string15 = string15.replace("%build.to%", fyw_0.gqw().k("build.to", new Object[0]));
        string15 = string15.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fjt_24.setValue(string15);
        fsj_24.X(fjt_24);
        fjt_24.guy();
        fjl_1 fjl_14 = new fjl_1();
        fjl_14.aVI();
        fjl_14.setElementMap(fhs_23);
        fjt_24.X(fjl_14);
        fjl_14.guy();
        fjl_14.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fbv_27.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setExpandable(false);
        faw_216.X(faw_217);
        faw_217.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setHgap((short)8);
        faw_217.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        String string16 = "buildForCopySearchTE";
        fdv_1 fdv_12 = new fdv_1();
        fdv_12.aVI();
        fdv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string16 != null) {
            fhs_23.a(string16, fdv_12);
        }
        String string17 = "%search%";
        string17 = string17.replace("%search%", fyw_0.gqw().k("search", new Object[0]));
        fdv_12.tX(string17);
        fme_2 fme_22 = new fme_2();
        fme_22.vw("wakfu.heroBuild:searchBuildsForCopy(buildForCopySearchTE)");
        fdv_12.setOnClear(fme_22);
        fmt_2 fmt_22 = new fmt_2();
        fmt_22.vw("wakfu.heroBuild:searchBuildsForCopy(buildForCopySearchTE)");
        fdv_12.setOnKeyRelease(fmt_22);
        fdv_12.setStyle("defaultTextEditor");
        fdv_12.setWithClearButton(true);
        fdv_12.setWithSearchButton(true);
        faw_217.X(fdv_12);
        fdv_12.guy();
        fdv_12.onChildrenAdded();
        faw_217.onChildrenAdded();
        String string18 = "filterLevel";
        fdd_2 fdd_25 = new fdd_2();
        fdd_25.aVI();
        fdd_25.setElementMap(fhs_23);
        if (fhs_23 != null && string18 != null) {
            fhs_23.a(string18, fdd_25);
        }
        fdd_25.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.heroBuild:filterBuildsForCopyListBySameLevel(filterLevel)");
        fdd_25.setOnClick(fmz_13);
        fdd_25.setStyle("defaultCheckboxWithBG");
        String string19 = "%build.display.same.level.only%";
        string19 = string19.replace("%build.display.same.level.only%", fyw_0.gqw().k("build.display.same.level.only", new Object[0]));
        fdd_25.setText(string19);
        faw_216.X(fdd_25);
        fdd_25.guy();
        fdd_25.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setPrefSize(new fsm_1(100.0f, 100.0f));
        faw_218.setStyle("ContentContainer1");
        faw_216.X(faw_218);
        faw_218.guy();
        faw_2 faw_219 = faw_218;
        fys_0 fys_03 = ((fes_2)faw_219).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_218.X(fys_03);
        fys_03.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(12, 12, 12, 4));
        fys_03.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_29 = frz_2.checkOut();
        frz_29.setAlign(faa_2.tLN);
        faw_218.X(frz_29);
        frz_29.guy();
        frz_29.onChildrenAdded();
        String string20 = "buildsList";
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        if (fhs_23 != null && string20 != null) {
            fhs_23.a(string20, fbz_22);
        }
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(270, 64));
        fbz_22.setExpandable(false);
        fbz_22.setHideContainerWithoutItem(true);
        fbz_22.setIdealSizeMaxColumns(2);
        fbz_22.setIdealSizeMaxRows(0);
        fbz_22.setIdealSizeMinColumns(2);
        fbz_22.setKeepOffset(true);
        fmv_2 fmv_22 = new fmv_2();
        fmv_22.vw("wakfu.heroBuild:selectBuildForCopy");
        fbz_22.setOnListSelectionChange(fmv_22);
        fbz_22.setPrefSize(new fsm_1(100.0f, 100.0f));
        fbz_22.setScrollBar(true);
        fbz_22.setScrollBarBehaviour(fzi_0.tHa);
        fbz_22.setStyle("buildsTile");
        faw_218.X(fbz_22);
        fbz_22.guy();
        this.f(fbz_22);
        this.g(fbz_22);
        fbz_22.onChildrenAdded();
        faw_218.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_213.onChildrenAdded();
        this.d(faw_212);
        this.e(faw_212);
        this.F(faw_212);
        faw_212.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.q(fey_22);
        this.r(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 f(fbz_2 fbz_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("buildSheetList");
        fsj_22.setName("heroBuildCopyBuildView");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 g(fbz_2 fbz_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "buildItemContainer";
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fje_22);
        }
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjn_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string2 = "buildSheet";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 8, 8));
        fje_22.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        String string3 = "buildsListItemContainer";
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, faw_22);
        }
        fje_22.X(faw_22);
        faw_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setNonBlocking(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_24.setPrefSize(new fsm_1(48, 48));
        faw_23.X(faw_24);
        faw_24.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_24.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(44, 44));
        faw_24.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("texture");
        fsd_13.setField("iconUrl");
        fze2.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setDisplaySize(new fsm_1(48, 48));
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("oldRarityDisabledBorder");
        faw_24.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        fbt_13.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("modulationColor");
        fsd_14.setField("isRealLevel");
        fbt_13.X(fsd_14);
        fsd_14.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fjt_23.setElseValue("1,1,1,1");
        fjt_23.setValue("0.3,0.3,0.3,0.5");
        fsd_14.X(fjt_23);
        fjt_23.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_23.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_14.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_25.setNonBlocking(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        frz_22.setHorizontal(false);
        faw_25.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_02 = ((fes_2)faw_26).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_25.X(fys_02);
        fys_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 8, 0, 0));
        fys_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setExpandable(false);
        faw_27.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popupIfReduced(buildNamePopup,buildNameLabel)");
        faw_27.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_27.setOnPopupHide(fml_12);
        faw_25.X(faw_27);
        faw_27.guy();
        String string4 = "buildNamePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string4 != null) {
            fhs_22.a(string4, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_27.X(frx_12);
        frx_12.guy();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setPrefSize(new fsm_1(10, 0));
        faw_28.setStyle("popup");
        frx_12.X(faw_28);
        faw_28.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("PopupInformation");
        faw_28.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("sheetName");
        fbv_22.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_28.onChildrenAdded();
        frx_12.onChildrenAdded();
        String string5 = "buildNameLabel";
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        if (fhs_22 != null && string5 != null) {
            fhs_22.a(string5, fbv_24);
        }
        fbv_24.setEnableAutoZoomShrink(true);
        fbv_24.setMaxWidth(180);
        fbv_24.setMinWidth(180);
        fbv_24.setNonBlocking(true);
        fbv_24.setStyle("wipLight16");
        faw_27.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("sheetName");
        fbv_24.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("style");
        fsd_17.setField("hasInvalidSheet");
        fbv_24.X(fsd_17);
        fsd_17.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fjt_24.setElseValue("wipLight16");
        fjt_24.setValue("wipRedBold16");
        fsd_17.X(fjt_24);
        fjt_24.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_22);
        fjt_24.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_17.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_24.X(fzq3);
        fzq3.guy();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_22);
        fsd_18.setAttribute("modulationColor");
        fsd_18.setField("isRealLevel");
        fzq3.X(fsd_18);
        fsd_18.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fjt_25.setElseValue("1,1,1,1");
        fjt_25.setValue("1,1,1,0.4");
        fsd_18.X(fjt_25);
        fjt_25.guy();
        fjl_1 fjl_14 = new fjl_1();
        fjl_14.aVI();
        fjl_14.setElementMap(fhs_22);
        fjt_25.X(fjl_14);
        fjl_14.guy();
        fjl_14.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsd_18.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setExpandable(false);
        faw_29.setNonBlocking(false);
        faw_25.X(faw_29);
        faw_29.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        faw_29.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("wipLightGray16");
        faw_29.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_19 = new fsd_1();
        fsd_19.aVI();
        fsd_19.setElementMap(fhs_22);
        fsd_19.setAttribute("text");
        fsd_19.setField("level");
        fdy_12.X(fsd_19);
        fsd_19.guy();
        fsd_19.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        String string6 = "warningLevelTooHigh";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        if (fhs_22 != null && string6 != null) {
            fhs_22.a(string6, faw_210);
        }
        faw_210.setExpandable(false);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(levelTooHighPopup,warningLevelTooHigh)");
        faw_210.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        faw_210.setOnPopupHide(fml_13);
        faw_22.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_210;
        fys_0 fys_03 = ((fes_2)faw_211).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_210.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(8, 0, 0, 8));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLc);
        faw_210.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fsd_1 fsd_110 = new fsd_1();
        fsd_110.aVI();
        fsd_110.setElementMap(fhs_22);
        fsd_110.setAttribute("visible");
        fsd_110.setField("isLevelTooHigh");
        faw_210.X(fsd_110);
        fsd_110.guy();
        fsd_110.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setDisplaySize(new fsm_1(20, 20));
        fbt_14.setExpandable(false);
        fbt_14.setStyle("warningIcon");
        faw_210.X(fbt_14);
        fbt_14.guy();
        fbt_1 fbt_15 = fbt_14;
        fyY fyY2 = (fyY)((fes_2)fbt_15).getAppearance();
        fyY2.setElementMap(fhs_22);
        ((fys_0)fyY2).setModulationColor(new fhl_2("warningIconColor"));
        fbt_14.X(fyY2);
        fyY2.guy();
        fyY2.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.1f));
        fkm_12.setInsets(new Insets(0, 0, 1, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(12, 0, 12, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "autoCleanBuild";
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fdd_22);
        }
        fdd_22.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.heroBuild:toggleAutoCleanBuildOnCopy(autoCleanBuild)");
        fdd_22.setOnClick(fmz_12);
        fdd_22.setStyle("defaultCheckboxWithBG");
        String string2 = "%build.auto.clean.builds%";
        string2 = string2.replace("%build.auto.clean.builds%", fyw_0.gqw().k("build.auto.clean.builds", new Object[0]));
        fdd_22.setText(string2);
        faw_22.X(fdd_22);
        fdd_22.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 12, 0));
        fdd_22.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fdd_22.onChildrenAdded();
        return fdd_22;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(100.0f, 0));
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHgap((short)16);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLR);
        faw_23.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(260, 52));
        fad_12.setStyle("secondaryLarge");
        String string = "%cancel%";
        string = string.replace("%cancel%", fyw_0.gqw().k("cancel", new Object[0]));
        fad_12.setText(string);
        faw_23.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.heroBuild:copyBuild");
        fad_13.setOnClick(fmz_13);
        fad_13.setPrefSize(new fsm_1(260, 52));
        fad_13.setStyle("primaryLarge");
        String string2 = "%copy%";
        string2 = string2.replace("%copy%", fyw_0.gqw().k("copy", new Object[0]));
        fad_13.setText(string2);
        faw_23.X(fad_13);
        fad_13.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("enabled");
        fsj_22.setField("canCopyBuild");
        fsj_22.setName("heroBuildCopyBuildView");
        fad_13.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setResizeOnce(true);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

