/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cLi
 */
public class cli_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        chj_2 chj_22 = new chj_2();
        chj_22.aVI();
        chj_22.setElementMap(fhs_23);
        chj_22.setNonBlocking(false);
        chj_22.setPrefSize(new fsm_1(150, 20));
        chj_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        chj_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPrefSize(new fsm_1(150, 90));
        fey_22.setStyle("new");
        chj_22.X(fey_22);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(16, 23, 16, 23));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setThemeElementName("image");
        fbt_12.setThemeElementParentType("interactiveBubble");
        faw_22.X(fbt_12);
        fbt_12.guy();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_23);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 12, 0, 0));
        fyY2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setExpandable(false);
        faw_22.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_03 = ((fes_2)faw_25).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_24.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(3, 5, 0, 12));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_24.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(300);
        fdy_12.setMinWidth(300);
        fdy_12.setThemeElementName("text");
        fdy_12.setThemeElementParentType("interactiveBubble");
        faw_24.X(fdy_12);
        fdy_12.guy();
        fdy_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_24.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_24.X(faw_26);
        faw_26.guy();
        faw_2 faw_27 = faw_26;
        fys_0 fys_04 = ((fes_2)faw_27).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_26.X(fys_04);
        fys_04.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 5, 0));
        fys_04.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_26.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setThemeElementName("buttonContainer");
        faw_28.setThemeElementParentType("interactiveBubble");
        faw_26.X(faw_28);
        faw_28.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLO);
        frz_25.setHgap((short)5);
        faw_28.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_28.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setStyle("small");
        String string = "%leftClick.continue%";
        string = string.replace("%leftClick.continue%", fyw_0.gqw().k("leftClick.continue", new Object[0]));
        fbv_22.setText(string);
        fbv_22.setThemeElementName("clickLabel");
        fbv_22.setThemeElementParentType("interactiveBubble");
        fbv_22.setVisible(false);
        faw_26.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new awx_2(0.5f, 0.5f, 0.5f, 1.0f));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_22.onChildrenAdded();
        fey_22.onChildrenAdded();
        chj_22.onChildrenAdded();
        return chj_22;
    }
}

