/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cLn
 */
public class cln_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "mainContainer";
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_22);
        }
        faw_22.setNonBlocking(true);
        faw_22.guy();
        String string2 = "mainLayout";
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, frp_12);
        }
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setYOffset(150);
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLk);
        frp_13.setXOffset(-30);
        frp_13.setYOffset(-62);
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setStyle("DialogBackground");
        faw_23.X(fbt_12);
        fbt_12.guy();
        fbt_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_22.X(faw_24);
        faw_24.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLo);
        frp_14.setSize(new fsm_1(399, -2));
        frp_14.setXOffset(-101);
        frp_14.setYOffset(20);
        faw_24.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setExpandable(false);
        fbt_13.setStyle("DialogTop");
        faw_24.X(fbt_13);
        fbt_13.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLP);
        fbt_13.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbt_1 fbt_14 = fbt_13;
        fyY fyY2 = (fyY)((fes_2)fbt_14).getAppearance();
        fyY2.setElementMap(fhs_23);
        fbt_13.X(fyY2);
        fyY2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 1, 0, 0));
        fyY2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setExpandable(false);
        faw_25.setPrefSize(new fsm_1(0, 215));
        faw_24.X(faw_25);
        faw_25.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_25.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setStyle("tiledScroll2");
        faw_25.X(faw_26);
        faw_26.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLa);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        frp_15.setYOffset(15);
        faw_26.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_25.X(faw_27);
        faw_27.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        faw_27.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_27.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_28 = faw_27;
        fys_0 fys_02 = ((fes_2)faw_28).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_27.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 15, 0, 15));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setExpandable(false);
        faw_27.X(faw_29);
        faw_29.guy();
        String string3 = "textView";
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fdy_12);
        }
        fdy_12.setDisplayCharDelay(20L);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(320);
        fdy_12.setMinWidth(320);
        fdy_12.setStyle("DefaultDark14");
        faw_29.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        fdy_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_23);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 15, 0));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("currentText");
        fsj_22.setName("currentDialog");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_29.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_27.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        String string4 = "answerList";
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fdf_12);
        }
        fdf_12.setExpandable(false);
        fdf_12.setHorizontal(false);
        fdf_12.setInnerExpandable(false);
        fdf_12.setPrefSize(new fsm_1(300, 0));
        faw_27.X(fdf_12);
        fdf_12.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLN);
        fdf_12.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fdf_1 fdf_13 = fdf_12;
        fza fza2 = (fza)((fes_2)fdf_13).getAppearance();
        fza2.setElementMap(fhs_23);
        fdf_12.X(fza2);
        fza2.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(0, 5, 0, 5));
        fza2.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fza2.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        fdf_12.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setField("currentChoices");
        fsj_23.setName("currentDialog");
        fdf_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fdf_12.X(fje_22);
        fje_22.guy();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        fje_22.X(faw_210);
        faw_210.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("visible");
        fsd_12.setField("visible");
        faw_210.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        String string5 = "choice";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, frv_12);
        }
        faw_210.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("value");
        frv_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_211 = faw_210;
        fys_0 fys_03 = ((fes_2)faw_211).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_210.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(2, 2, 2, 0));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_210.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.interactiveDialog:selectChoice(choice)");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("Yellow");
        faw_210.X(fad_12);
        fad_12.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLf);
        frp_17.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fad_12.onChildrenAdded();
        String string6 = "text";
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fdy_14);
        }
        fdy_14.setExpandable(false);
        fdy_14.setMaxWidth(324);
        fdy_14.setMinWidth(324);
        fdy_14.setNonBlocking(true);
        fdy_14.setStyle("DarkBold11");
        faw_210.X(fdy_14);
        fdy_14.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLf);
        frp_18.setSize(new fsm_1(100.0f, 100.0f));
        fdy_14.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fdy_14.X(fzq3);
        fzq3.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(7, 9, 7, 7));
        fzq3.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 0, 0, 16));
        fzq3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("text");
        fsd_14.setField("text");
        fdy_14.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("visible");
        fsd_15.setField("iconUrl");
        fdy_14.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsd_15.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_15.onChildrenAdded();
        fdy_14.onChildrenAdded();
        String string7 = "text";
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fdy_16);
        }
        fdy_16.setExpandable(false);
        fdy_16.setMaxWidth(340);
        fdy_16.setMinWidth(340);
        fdy_16.setNonBlocking(true);
        fdy_16.setStyle("DarkBold11");
        faw_210.X(fdy_16);
        fdy_16.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setAlign(fzw_0.tLf);
        frp_19.setSize(new fsm_1(100.0f, 100.0f));
        fdy_16.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq4 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLN);
        fdy_16.X(fzq4);
        fzq4.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(7, 9, 7, 7));
        fzq4.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("text");
        fsd_16.setField("text");
        fdy_16.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_23);
        fsd_17.setAttribute("visible");
        fsd_17.setField("iconUrl");
        fdy_16.X(fsd_17);
        fsd_17.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsd_17.X(fjt_23);
        fjt_23.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_23);
        fjt_23.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_17.onChildrenAdded();
        fdy_16.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_23);
        fbt_15.setDisplaySize(new fsm_1(22, 22));
        fbt_15.setNonBlocking(true);
        faw_210.X(fbt_15);
        fbt_15.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_23);
        frp_110.setAlign(fzw_0.tLh);
        frp_110.setSize(new fsm_1(22, 22));
        frp_110.setXOffset(-10);
        fbt_15.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_23);
        fsd_18.setAttribute("visible");
        fsd_18.setField("iconUrl");
        fbt_15.X(fsd_18);
        fsd_18.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fsd_18.X(fjt_24);
        fjt_24.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_23);
        fjt_24.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_18.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_15.X(fze2);
        fze2.guy();
        fsd_1 fsd_19 = new fsd_1();
        fsd_19.aVI();
        fsd_19.setElementMap(fhs_23);
        fsd_19.setAttribute("texture");
        fsd_19.setField("iconUrl");
        fze2.X(fsd_19);
        fsd_19.guy();
        fsd_19.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_15.onChildrenAdded();
        faw_210.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_24.onChildrenAdded();
        this.R(faw_22);
        this.c(faw_22);
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(260, 380));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        frp_12.setXOffset(0);
        frp_12.setYOffset(35);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLP);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(256, 256));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        faw_23.X(fbt_12);
        fbt_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLR);
        fbt_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("texture");
        fsj_22.setField("speakerIconUrl");
        fsj_22.setName("currentDialog");
        fze2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(namePopup,1)");
        faw_23.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_23.setOnPopupHide(fml_12);
        faw_23.setPrefSize(new fsm_1(150, 26));
        faw_23.setStyle("dialogBackgroundTitle");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        frp_12.setXOffset(61);
        frp_12.setYOffset(8);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(180);
        fdy_12.setMinWidth(180);
        fdy_12.setMultiline(true);
        fdy_12.setStyle("title");
        faw_23.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(4, 13, 4, 13));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("speakerName");
        fsj_22.setName("currentDialog");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }
}

