/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cLw
 */
public class clw_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string = "%jukebox.title%";
        string = string.replace("%jukebox.title%", fyw_0.gqw().k("jukebox.title", new Object[0]));
        fbv_22.setText(string);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_210.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_211.setPrefSize(new fsm_1(-2, 30));
        faw_211.setStyle("caracs");
        faw_210.X(faw_211);
        faw_211.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_211.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_211.X(faw_212);
        faw_212.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLf);
        frp_14.setSize(new fsm_1(-2, -2));
        faw_212.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setStyle("bold");
        String string3 = "%jukebox.currentMusic%";
        string3 = string3.replace("%jukebox.currentMusic%", fyw_0.gqw().k("jukebox.currentMusic", new Object[0]));
        fbv_24.setText(string3);
        faw_212.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        faw_212.X(fbv_25);
        fbv_25.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("currentMusicName");
        fsj_22.setLocal(true);
        fsj_22.setName("jukebox");
        fbv_25.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_211.X(faw_213);
        faw_213.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLh);
        frp_15.setSize(new fsm_1(-2, -2));
        faw_213.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.jukebox:dropMusic");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(dropMusicPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setPrefSize(new fsm_1(20, 20));
        faw_213.X(fad_12);
        fad_12.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fad_12.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(20, 20));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("cancel");
        fad_12.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(20, 20));
        frp_16.setYOffset(-1);
        fbt_12.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbt_12.onChildrenAdded();
        String string4 = "dropMusicPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setPrefSize(new fsm_1(10, 0));
        faw_214.setStyle("popup");
        frx_12.X(faw_214);
        faw_214.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKA);
        faw_214.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setStyle("PopupInformation");
        String string5 = "%jukebox.dropMusic%";
        string5 = string5.replace("%jukebox.dropMusic%", fyw_0.gqw().k("jukebox.dropMusic", new Object[0]));
        fbv_26.setText(string5);
        faw_214.X(fbv_26);
        fbv_26.guy();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq3 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fbv_26.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_214.onChildrenAdded();
        frx_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.jukebox:randomMusic");
        fad_13.setOnClick(fmz_13);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(randomMusicPopup)");
        fad_13.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fad_13.setOnPopupHide(fml_13);
        fad_13.setPrefSize(new fsm_1(20, 20));
        faw_213.X(fad_13);
        fad_13.guy();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        fad_13.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setExpandable(false);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("RandomSquare");
        fad_13.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setYOffset(-1);
        fbt_13.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fbt_13.onChildrenAdded();
        String string6 = "randomMusicPopup";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, frx_13);
        }
        frx_13.setAlign(faa_2.tLL);
        frx_13.setHotSpotPosition(faa_2.tLR);
        fad_13.X(frx_13);
        frx_13.guy();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setPrefSize(new fsm_1(10, 0));
        faw_215.setStyle("popup");
        frx_13.X(faw_215);
        faw_215.guy();
        fru_1 fru_13 = fru_1.checkOut();
        fru_13.setElementMap(fhs_23);
        fru_13.setData(fzt_0.tKA);
        faw_215.X(fru_13);
        fru_13.guy();
        fru_13.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setStyle("PopupInformation");
        String string7 = "%jukebox.randomMusic%";
        string7 = string7.replace("%jukebox.randomMusic%", fyw_0.gqw().k("jukebox.randomMusic", new Object[0]));
        fbv_28.setText(string7);
        faw_215.X(fbv_28);
        fbv_28.guy();
        fbv_2 fbv_29 = fbv_28;
        fzq fzq4 = (fzq)((fes_2)fbv_29).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLN);
        fbv_28.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_28.onChildrenAdded();
        faw_215.onChildrenAdded();
        frx_13.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_210.X(faw_216);
        faw_216.guy();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setExpandable(false);
        faw_217.setNonBlocking(false);
        faw_217.setPrefSize(new fsm_1(280, 330));
        faw_217.setStyle("caracs");
        faw_216.X(faw_217);
        faw_217.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLK);
        faw_217.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_217.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        fdu_12.setExpandable(false);
        fdu_12.setFocused(true);
        String string8 = "%search%";
        string8 = string8.replace("%search%", fyw_0.gqw().k("search", new Object[0]));
        fdu_12.tX(string8);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.jukebox:onInstanceSearch");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setPrefSize(new fsm_1(100.0f, 20));
        fdu_12.setStyle("TITLEDTEXTBLUE");
        faw_217.X(fdu_12);
        fdu_12.guy();
        fdu_12.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(100.0f, 24));
        fbz_22.setExpandable(false);
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMaxRows(10);
        fbz_22.setIdealSizeMinColumns(1);
        fbz_22.setIdealSizeMinRows(10);
        fbz_22.setPrefSize(new fsm_1(100.0f, 300));
        fbz_22.setScrollBarBehaviour(fzi_0.tHb);
        faw_217.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setField("instances");
        fsj_23.setLocal(true);
        fsj_23.setName("jukebox");
        fbz_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("selectedValue");
        fsj_24.setField("instance");
        fsj_24.setLocal(true);
        fsj_24.setName("jukebox");
        fbz_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.jukebox:pickInstance");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.jukebox:overList(overContainer)");
        faw_218.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.jukebox:outList(overContainer)");
        faw_218.setOnMouseExit(fmf_22);
        fje_22.X(faw_218);
        faw_218.guy();
        fro_1 fro_16 = new fro_1();
        fro_16.aVI();
        faw_218.X(fro_16);
        fro_16.guy();
        fro_16.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_218.X(faw_219);
        faw_219.guy();
        this.R(faw_219);
        this.c(faw_219);
        this.d(faw_219);
        faw_219.onChildrenAdded();
        this.e(faw_218);
        faw_218.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_217.onChildrenAdded();
        this.F(faw_216);
        this.G(faw_216);
        this.I(faw_216);
        faw_216.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.t(fey_22);
        this.u(fey_22);
        this.v(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fys_02.X(fkk_12);
        fkk_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("color");
        fkk_12.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fjt_22.setElseValue("oddCellColor");
        fjt_22.setValue("evenCellColor");
        fsd_12.X(fjt_22);
        fjt_22.guy();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_22);
        fjy_22.setKey("evenIndex");
        fjt_22.X(fjy_22);
        fjy_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjy_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_12.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        return fys_02;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        faw_22.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("style");
        fsj_22.setField("instance");
        fsj_22.setLocal(true);
        fsj_22.setName("jukebox");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fjt_22.setElseValue("white");
        fjt_22.setValue("whiteBold");
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjt_22.X(fjv_12);
        fjv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        fjv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fjv_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("instance");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "overContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setVisible(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.05f));
        fys_02.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_22.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        return fde_12;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setNonBlocking(false);
        faw_23.setPrefSize(new fsm_1(320, 342));
        faw_22.X(faw_23);
        faw_23.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("instance");
        fsj_22.setLocal(true);
        fsj_22.setName("jukebox");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLM);
        faw_23.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_24.setPrefSize(new fsm_1(300, 100));
        faw_24.setStyle("caracs");
        faw_23.X(faw_24);
        faw_24.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLL);
        faw_24.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setCellSize(new fsm_1(300, 24));
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMinColumns(1);
        fbz_22.setScrollBarBehaviour(fzi_0.tHb);
        fbz_22.setSelectionTogglable(false);
        faw_24.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("content");
        fsj_23.setField("instance/zones");
        fsj_23.setLocal(true);
        fsj_23.setName("jukebox");
        fbz_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("selectedValue");
        fsj_24.setField("playlist");
        fsj_24.setLocal(true);
        fsj_24.setName("jukebox");
        fbz_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.jukebox:pickAmbienceZone");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_22.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_23.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjx_12.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.jukebox:overList(overContainer)");
        faw_25.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.jukebox:outList(overContainer)");
        faw_25.setOnMouseExit(fmf_22);
        fje_22.X(faw_25);
        faw_25.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_25.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_25.X(faw_26);
        faw_26.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_26.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_27 = faw_26;
        fys_0 fys_02 = ((fes_2)faw_27).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_26.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fys_02.X(fkk_12);
        fkk_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("color");
        fkk_12.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fjt_24.setElseValue("oddCellColor");
        fjt_24.setValue("evenCellColor");
        fsd_12.X(fjt_24);
        fjt_24.guy();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_22);
        fjy_22.setKey("evenIndex");
        fjt_24.X(fjy_22);
        fjy_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjy_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_12.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        faw_26.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("style");
        fsj_25.setField("playlist");
        fsj_25.setLocal(true);
        fsj_25.setName("jukebox");
        fbv_22.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fjt_25.setElseValue("white");
        fjt_25.setValue("whiteBold");
        fsj_25.X(fjt_25);
        fjt_25.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjt_25.X(fjv_12);
        fjv_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("value");
        fjv_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fjv_12.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("ambienceZoneName");
        fbv_22.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_26.onChildrenAdded();
        String string = "overContainer";
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_28);
        }
        faw_28.setVisible(false);
        faw_25.X(faw_28);
        faw_28.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_28.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        faw_2 faw_29 = faw_28;
        fys_0 fys_03 = ((fes_2)faw_29).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_28.X(fys_03);
        fys_03.guy();
        fkk_1 fkk_13 = new fkk_1();
        fkk_13.aVI();
        fkk_13.setElementMap(fhs_22);
        fkk_13.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.05f));
        fys_03.X(fkk_13);
        fkk_13.guy();
        fkk_13.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_25.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_210.setStyle("caracs");
        faw_23.X(faw_210);
        faw_210.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_210.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_211 = faw_210;
        fys_0 fys_04 = ((fes_2)faw_211).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_210.X(fys_04);
        fys_04.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 5, 0, 0));
        fys_04.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_210.X(faw_212);
        faw_212.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_212.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setStyle("titleNameBold");
        String string2 = "%jukebox.dayMusic%";
        string2 = string2.replace("%jukebox.dayMusic%", fyw_0.gqw().k("jukebox.dayMusic", new Object[0]));
        fbv_24.setText(string2);
        faw_212.X(fbv_24);
        fbv_24.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLf);
        frp_14.setSize(new fsm_1(180, 20));
        fbv_24.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_22);
        faw_212.X(faw_213);
        faw_213.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLf);
        frp_15.setSize(new fsm_1(140, 20));
        frp_15.setXOffset(180);
        faw_213.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbz_2 fbz_23 = new fbz_2();
        fbz_23.aVI();
        fbz_23.setElementMap(fhs_22);
        fbz_23.setCellSize(new fsm_1(20, 20));
        fbz_23.setHorizontal(true);
        fbz_23.setIdealSizeMaxRows(1);
        fbz_23.setIdealSizeMinRows(1);
        fbz_23.setScrollBarBehaviour(fzi_0.tHc);
        fbz_23.setSelectionTogglable(false);
        faw_213.X(fbz_23);
        fbz_23.guy();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fmo_2 fmo_23 = new fmo_2();
        fmo_23.vw("wakfu.jukebox:pickMusic");
        fje_23.setOnItemClick(fmo_23);
        fbz_23.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_22);
        fje_23.X(fjt_26);
        fjt_26.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjt_26.X(fjx_13);
        fjx_13.guy();
        fjd_1 fjd_14 = new fjd_1();
        fjd_14.aVI();
        fjd_14.setElementMap(fhs_22);
        fjx_13.X(fjd_14);
        fjd_14.guy();
        fjd_14.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_26.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setDisplaySize(new fsm_1(20, 20));
        fad_12.setStyle("BIGPLAYVIDEO");
        fje_23.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fje_23.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("content");
        fsj_26.setField("playlist/dayMusics");
        fsj_26.setLocal(true);
        fsj_26.setName("jukebox");
        fbz_23.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fbz_23.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_22);
        faw_210.X(faw_214);
        faw_214.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_214.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setStyle("titleNameBold");
        String string3 = "%jukebox.nightMusic%";
        string3 = string3.replace("%jukebox.nightMusic%", fyw_0.gqw().k("jukebox.nightMusic", new Object[0]));
        fbv_25.setText(string3);
        faw_214.X(fbv_25);
        fbv_25.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLf);
        frp_16.setSize(new fsm_1(180, 20));
        fbv_25.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_22);
        faw_214.X(faw_215);
        faw_215.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_22);
        frp_17.setAlign(fzw_0.tLf);
        frp_17.setSize(new fsm_1(140, 20));
        frp_17.setXOffset(180);
        faw_215.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fbz_2 fbz_24 = new fbz_2();
        fbz_24.aVI();
        fbz_24.setElementMap(fhs_22);
        fbz_24.setCellSize(new fsm_1(20, 20));
        fbz_24.setHorizontal(true);
        fbz_24.setIdealSizeMaxRows(1);
        fbz_24.setIdealSizeMinRows(1);
        fbz_24.setScrollBarBehaviour(fzi_0.tHc);
        fbz_24.setSelectionTogglable(false);
        faw_215.X(fbz_24);
        fbz_24.guy();
        fje_2 fje_24 = new fje_2();
        fje_24.aVI();
        fje_24.setElementMap(fhs_22);
        fmo_2 fmo_24 = new fmo_2();
        fmo_24.vw("wakfu.jukebox:pickMusic");
        fje_24.setOnItemClick(fmo_24);
        fbz_24.X(fje_24);
        fje_24.guy();
        fjt_2 fjt_27 = new fjt_2();
        fjt_27.aVI();
        fjt_27.setElementMap(fhs_22);
        fje_24.X(fjt_27);
        fjt_27.guy();
        fjx_1 fjx_14 = new fjx_1();
        fjx_14.aVI();
        fjx_14.setElementMap(fhs_22);
        fjt_27.X(fjx_14);
        fjx_14.guy();
        fjd_1 fjd_15 = new fjd_1();
        fjd_15.aVI();
        fjd_15.setElementMap(fhs_22);
        fjx_14.X(fjd_15);
        fjd_15.guy();
        fjd_15.onChildrenAdded();
        fjx_14.onChildrenAdded();
        fjt_27.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setDisplaySize(new fsm_1(20, 20));
        fad_13.setStyle("BIGPLAYVIDEO");
        fje_24.X(fad_13);
        fad_13.guy();
        fad_13.onChildrenAdded();
        fje_24.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("content");
        fsj_27.setField("playlist/nightMusics");
        fsj_27.setLocal(true);
        fsj_27.setName("jukebox");
        fbz_24.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fbz_24.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_22);
        faw_210.X(faw_216);
        faw_216.guy();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        faw_216.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_22);
        fbv_26.setStyle("titleNameBold");
        String string4 = "%jukebox.fightMusic%";
        string4 = string4.replace("%jukebox.fightMusic%", fyw_0.gqw().k("jukebox.fightMusic", new Object[0]));
        fbv_26.setText(string4);
        faw_216.X(fbv_26);
        fbv_26.guy();
        this.y(fbv_26);
        fbv_26.onChildrenAdded();
        this.g(faw_216);
        faw_216.onChildrenAdded();
        this.H(faw_210);
        faw_210.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 y(fbv_2 fbv_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setSize(new fsm_1(180, 20));
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setSize(new fsm_1(140, 20));
        frp_12.setXOffset(180);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setCellSize(new fsm_1(20, 20));
        fbz_22.setHorizontal(true);
        fbz_22.setIdealSizeMaxRows(1);
        fbz_22.setIdealSizeMinRows(1);
        fbz_22.setScrollBarBehaviour(fzi_0.tHc);
        fbz_22.setSelectionTogglable(false);
        faw_23.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.jukebox:pickMusic");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setDisplaySize(new fsm_1(20, 20));
        fad_12.setStyle("BIGPLAYVIDEO");
        fje_22.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fje_22.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("playlist/fightMusics");
        fsj_22.setLocal(true);
        fsj_22.setName("jukebox");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 H(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("titleNameBold");
        String string = "%jukebox.bossMusic%";
        string = string.replace("%jukebox.bossMusic%", fyw_0.gqw().k("jukebox.bossMusic", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setSize(new fsm_1(180, 20));
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLf);
        frp_13.setSize(new fsm_1(140, 20));
        frp_13.setXOffset(180);
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setCellSize(new fsm_1(20, 20));
        fbz_22.setHorizontal(true);
        fbz_22.setIdealSizeMaxRows(1);
        fbz_22.setIdealSizeMinRows(1);
        fbz_22.setScrollBarBehaviour(fzi_0.tHc);
        fbz_22.setSelectionTogglable(false);
        faw_24.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.jukebox:pickMusic");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setDisplaySize(new fsm_1(20, 20));
        fad_12.setStyle("BIGPLAYVIDEO");
        fje_22.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fje_22.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("playlist/bossMusics");
        fsj_22.setLocal(true);
        fsj_22.setName("jukebox");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 I(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(320, 0));
        faw_22.X(faw_23);
        faw_23.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("instance");
        fsj_22.setLocal(true);
        fsj_22.setName("jukebox");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjt_22.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 t(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(11, 15));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(tutoJukebox)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        fbt_12.setStyle("questionMark");
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLc);
        frp_13.setSize(new fsm_1(-2, -2));
        frp_13.setXOffset(-40);
        frp_13.setYOffset(-15);
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        String string = "tutoJukebox";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setEnableShrinking(false);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(250);
        fdy_12.setStyle("white");
        String string2 = "%jukebox.tuto%";
        string2 = string2.replace("%jukebox.tuto%", fyw_0.gqw().k("jukebox.tuto", new Object[0]));
        fdy_12.setText(string2);
        faw_23.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 u(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLc);
        frp_13.setSize(new fsm_1(-2, -2));
        frp_13.setXOffset(-20);
        frp_13.setYOffset(-13);
        fad_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 v(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setResizeOnce(true);
        frp_12.setSize(new fsm_1(660, 430));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

