/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMG
 */
public class cmg_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "window";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setMaxSize(new fsm_1(300, 330));
        fey_22.setNonBlocking(true);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("showWidget(moveButtonContainer)");
        fey_22.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("hideWidget(moveButtonContainer)");
        fey_22.setOnMouseExit(fmf_22);
        fey_22.setPrefSize(new fsm_1(150, 180));
        fey_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("visible");
        fsj_22.setField("isMapAvailable");
        fsj_22.setName("miniMap");
        fey_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_23);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjn_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_23);
        fjn_22.X(fjl_13);
        fjl_13.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("comparedValue");
        fsj_23.setField("minimapEnable");
        fsj_23.setName("gamePreferences");
        fjl_13.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fjl_13.onChildrenAdded();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjn_22.X(fjw_22);
        fjw_22.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("comparedValue");
        fsj_24.setName("isInFight");
        fjw_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fjw_22.onChildrenAdded();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_23);
        fjn_22.X(fjw_23);
        fjw_23.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("comparedValue");
        fsj_25.setName("isFightSpectator");
        fjw_23.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fjw_23.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fey_2 fey_23 = fey_22;
        fys_0 fys_02 = ((fes_2)fey_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        fys_02.setShape(fzz_0.tGn);
        fey_22.X(fys_02);
        fys_02.guy();
        fys_02.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-20);
        frp_12.setYOffset(-200);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setNonBlocking(false);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLc);
        frp_13.setSize(new fsm_1(24, 32));
        faw_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_22.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        String string2 = "moveButtonContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_23);
        }
        faw_23.setVisible(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLa);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_23.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setPrefSize(new fsm_1(24, 24));
        fad_12.setStyle("moveSecondaryFloatingButton");
        faw_23.X(fad_12);
        fad_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLc);
        frp_15.setSize(new fsm_1(24, 24));
        frp_15.setYOffset(-1);
        fad_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fad_12.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        faw_23.X(fea_12);
        fea_12.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLc);
        frp_16.setSize(new fsm_1(24, 24));
        frp_16.setYOffset(-1);
        fea_12.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setNeedsScissor(true);
        fey_22.X(faw_24);
        faw_24.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setSize(new fsm_1(100.0f, 100.0f));
        frp_17.setX(2);
        frp_17.setY(4);
        faw_24.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        faw_2 faw_25 = faw_24;
        fys_0 fys_03 = ((fes_2)faw_25).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_24.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(35, 0, 0, 5));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        String string3 = "navigator";
        fba_2 fba_22 = new fba_2();
        fba_22.aVI();
        fba_22.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fba_22);
        }
        fba_22.setCursorType(fzo_0.tHq);
        fba_22.setEnableTooltip(false);
        fba_22.setIsoMap(true);
        fba_22.setLandMarkZoom(0.75f);
        fba_22.setMaxZoom(0.065f);
        fba_22.setMinZoom(0.065f);
        fba_22.setNeedsScissor(true);
        fmq_1 fmq_12 = new fmq_1();
        fmq_12.vw("wakfu.controlCenter:onMiniMapItemOut");
        fba_22.setOnItemOut(fmq_12);
        fmr_2 fmr_22 = new fmr_2();
        fmr_22.vw("wakfu.controlCenter:onMiniMapItemOver");
        fba_22.setOnItemOver(fmr_22);
        fmx_2 fmx_22 = new fmx_2();
        fmx_22.vw("wakfu.controlCenter:adminTP");
        fba_22.setOnMapDoubleClick(fmx_22);
        faw_24.X(fba_22);
        fba_22.guy();
        fba_2 fba_23 = fba_22;
        fzb fzb2 = (fzb)((fes_2)fba_23).getAppearance();
        fzb2.setElementMap(fhs_23);
        fba_22.X(fzb2);
        fzb2.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_23);
        fzb2.X(fkk_12);
        fkk_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("color");
        fsj_26.setField("bgColor");
        fsj_26.setName("miniMap");
        fkk_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fzb2.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("mapPath");
        fsj_27.setField("map");
        fsj_27.setName("miniMap");
        fba_22.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("content");
        fsj_28.setField("landmarks/points");
        fsj_28.setName("map");
        fba_22.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("compassContent");
        fsj_29.setField("landmarks/compass");
        fsj_29.setName("map");
        fba_22.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("isoCenterX");
        fsj_210.setField("centerX");
        fsj_210.setName("miniMap");
        fba_22.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_23);
        fsj_211.setAttribute("isoCenterY");
        fsj_211.setField("centerY");
        fsj_211.setName("miniMap");
        fba_22.X(fsj_211);
        fsj_211.guy();
        fsj_211.onChildrenAdded();
        fsj_2 fsj_212 = fsj_2.checkOut();
        fsj_212.setElementMap(fhs_23);
        fsj_212.setAttribute("isoCenterZ");
        fsj_212.setField("centerZ");
        fsj_212.setName("miniMap");
        fba_22.X(fsj_212);
        fsj_212.guy();
        fsj_212.onChildrenAdded();
        fsj_2 fsj_213 = fsj_2.checkOut();
        fsj_213.setElementMap(fhs_23);
        fsj_213.setAttribute("mapId");
        fsj_213.setField("mapId");
        fsj_213.setName("miniMap");
        fba_22.X(fsj_213);
        fsj_213.guy();
        fsj_213.onChildrenAdded();
        fba_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        String string4 = "background";
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, faw_26);
        }
        faw_26.setStyle("minimapBorder");
        fey_22.X(faw_26);
        faw_26.guy();
        faw_2 faw_27 = faw_26;
        fys_0 fys_04 = ((fes_2)faw_27).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_26.X(fys_04);
        fys_04.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(28, 0, 0, 0));
        fys_04.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setSize(new fsm_1(100.0f, 100.0f));
        faw_26.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        faw_26.onChildrenAdded();
        fea_1 fea_13 = new fea_1();
        fea_13.aVI();
        fea_13.setElementMap(fhs_23);
        fey_22.X(fea_13);
        fea_13.guy();
        fea_13.onChildrenAdded();
        fed_2 fed_22 = new fed_2();
        fed_22.aVI();
        fed_22.setElementMap(fhs_23);
        fed_22.setPointAlign(faa_2.tLS);
        fey_22.X(fed_22);
        fed_22.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setAlign(fzw_0.tLo);
        frp_19.setXOffset(-5);
        frp_19.setYOffset(5);
        fed_22.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        fro_15.setAdaptToContentSize(true);
        fed_22.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("resizeAngleSE");
        fed_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_23);
        frp_110.setAlign(fzw_0.tLg);
        frp_110.setXOffset(3);
        frp_110.setYOffset(-1);
        fbt_12.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fed_22.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

