/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMI
 */
public class cmi_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setNonBlocking(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        fbv_22.setText("Mix Debugger");
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_211.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_212.setStyle("white");
        faw_211.X(faw_212);
        faw_212.guy();
        faw_2 faw_213 = faw_212;
        fys_0 fys_06 = ((fes_2)faw_213).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_212.X(fys_06);
        fys_06.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(10, 10, 10, 10));
        fys_06.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_06.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLL);
        frz_25.setHorizontal(false);
        faw_212.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("bold");
        fbv_24.setText("Criterions :");
        faw_212.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setExpandable(false);
        faw_214.setPrefSize(new fsm_1(0, 100));
        faw_214.setStyle("ShortcutRowBackground");
        faw_212.X(faw_214);
        faw_214.guy();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setVerticalScrollBarPosition(1.0f);
        faw_214.X(fcq_22);
        fcq_22.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(350);
        fdy_12.setMinWidth(0);
        fdy_12.setStyle("11");
        fcq_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 5, 0, 0));
        fzq3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("criterions");
        fsj_22.setName("mixDebugger");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_215.setStyle("white");
        faw_211.X(faw_215);
        faw_215.guy();
        faw_2 faw_216 = faw_215;
        fys_0 fys_07 = ((fes_2)faw_216).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_215.X(fys_07);
        fys_07.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(10, 10, 10, 10));
        fys_07.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fys_07.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLL);
        frz_26.setHorizontal(false);
        faw_215.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_23);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("bold");
        fbv_25.setText("Events :");
        faw_215.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setExpandable(false);
        faw_217.setPrefSize(new fsm_1(0, 100));
        faw_217.setStyle("ShortcutRowBackground");
        faw_215.X(faw_217);
        faw_217.guy();
        fcq_2 fcq_23 = new fcq_2();
        fcq_23.aVI();
        fcq_23.setElementMap(fhs_23);
        fcq_23.setVerticalScrollBarPosition(1.0f);
        faw_217.X(fcq_23);
        fcq_23.guy();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        fdy_14.setExpandable(false);
        fdy_14.setMaxWidth(350);
        fdy_14.setMinWidth(0);
        fdy_14.setStyle("11");
        fcq_23.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq4 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq4.setElementMap(fhs_23);
        fdy_14.X(fzq4);
        fzq4.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 5, 0, 0));
        fzq4.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("events");
        fsj_23.setName("mixDebugger");
        fdy_14.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fcq_23.onChildrenAdded();
        faw_217.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setStyle("white");
        faw_211.X(faw_218);
        faw_218.guy();
        faw_2 faw_219 = faw_218;
        fys_0 fys_08 = ((fes_2)faw_219).getAppearance();
        fys_08.setElementMap(fhs_23);
        faw_218.X(fys_08);
        fys_08.guy();
        fzx fzx6 = new fzx();
        fzx6.aVI();
        fzx6.setElementMap(fhs_23);
        fzx6.setInsets(new Insets(10, 10, 10, 10));
        fys_08.X(fzx6);
        fzx6.guy();
        fzx6.onChildrenAdded();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(5, 0, 0, 0));
        fys_08.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_08.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLL);
        frz_27.setHorizontal(false);
        faw_218.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setStyle("bold");
        fbv_26.setText("Cache :");
        faw_218.X(fbv_26);
        fbv_26.guy();
        fbv_26.onChildrenAdded();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        faw_220.setExpandable(false);
        faw_218.X(faw_220);
        faw_220.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLN);
        faw_220.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setExpandable(false);
        fbv_27.setText("Memory : ");
        faw_220.X(fbv_27);
        fbv_27.guy();
        fbv_27.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setExpandable(false);
        fbv_28.setStyle("11Dark");
        faw_220.X(fbv_28);
        fbv_28.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("memoryCache");
        fsj_24.setName("mixDebugger");
        fbv_28.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fbv_28.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_23);
        fbv_29.setExpandable(false);
        fbv_29.setText("Sources size ");
        faw_220.X(fbv_29);
        fbv_29.guy();
        fbv_2 fbv_210 = fbv_29;
        fzq fzq5 = (fzq)((fes_2)fbv_210).getAppearance();
        fzq5.setElementMap(fhs_23);
        fbv_29.X(fzq5);
        fzq5.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 5, 0, 0));
        fzq5.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzq5.onChildrenAdded();
        fbv_29.onChildrenAdded();
        fbv_2 fbv_211 = new fbv_2();
        fbv_211.aVI();
        fbv_211.setElementMap(fhs_23);
        fbv_211.setExpandable(false);
        fbv_211.setText("cache : ");
        faw_220.X(fbv_211);
        fbv_211.guy();
        fbv_211.onChildrenAdded();
        fbv_2 fbv_212 = new fbv_2();
        fbv_212.aVI();
        fbv_212.setElementMap(fhs_23);
        fbv_212.setExpandable(false);
        fbv_212.setStyle("11Dark");
        faw_220.X(fbv_212);
        fbv_212.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("cacheSourcesTotalSize");
        fsj_25.setName("mixDebugger");
        fbv_212.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fbv_212.onChildrenAdded();
        fbv_2 fbv_213 = new fbv_2();
        fbv_213.aVI();
        fbv_213.setElementMap(fhs_23);
        fbv_213.setExpandable(false);
        fbv_213.setText("played : ");
        faw_220.X(fbv_213);
        fbv_213.guy();
        fbv_2 fbv_214 = fbv_213;
        fzq fzq6 = (fzq)((fes_2)fbv_214).getAppearance();
        fzq6.setElementMap(fhs_23);
        fbv_213.X(fzq6);
        fzq6.guy();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_23);
        fzv8.setInsets(new Insets(0, 5, 0, 0));
        fzq6.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fzq6.onChildrenAdded();
        fbv_213.onChildrenAdded();
        fbv_2 fbv_215 = new fbv_2();
        fbv_215.aVI();
        fbv_215.setElementMap(fhs_23);
        fbv_215.setExpandable(false);
        fbv_215.setStyle("11Dark");
        faw_220.X(fbv_215);
        fbv_215.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("text");
        fsj_26.setField("sourcesTotalSize");
        fsj_26.setName("mixDebugger");
        fbv_215.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fbv_215.onChildrenAdded();
        faw_220.onChildrenAdded();
        String string2 = "tabbedContainer";
        fdh_1 fdh_12 = new fdh_1();
        fdh_12.aVI();
        fdh_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fdh_12);
        }
        fdh_12.setSyncTabButtonStateAndTab(false);
        fdh_12.setTabsAlignment(fzY.tLy);
        fdh_12.setTabsLabelAlignment(faa_2.tLO);
        fdh_12.setTabsPosition(fzx_0.tLq);
        fdh_12.setTabsSizesEquilibrate(false);
        fdh_12.setTextOrientation(fzu_0.tKE);
        faw_218.X(fdh_12);
        fdh_12.guy();
        fdh_1 fdh_13 = fdh_12;
        fys_0 fys_09 = ((fes_2)fdh_13).getAppearance();
        fys_09.setElementMap(fhs_23);
        fdh_12.X(fys_09);
        fys_09.guy();
        fzv fzv9 = fzv.checkOut();
        fzv9.setElementMap(fhs_23);
        fzv9.setInsets(new Insets(5, 0, 0, 0));
        fys_09.X(fzv9);
        fzv9.guy();
        fzv9.onChildrenAdded();
        fys_09.onChildrenAdded();
        this.q(fdh_12);
        this.r(fdh_12);
        this.s(fdh_12);
        fdh_12.onChildrenAdded();
        faw_218.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.m(fey_22);
        this.n(fey_22);
        this.q(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 q(fdh_1 fdh_12) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_1 frz_12 = new frz_1();
        frz_12.aVI();
        frz_12.setElementMap(fhs_22);
        frz_12.setText("Log");
        fdh_12.X(frz_12);
        frz_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(0, 150));
        faw_22.setStyle("ShortcutRowBackground");
        frz_12.X(faw_22);
        faw_22.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setStyle("caracs");
        faw_22.X(faw_23);
        faw_23.guy();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setCellSize(new fsm_1(125, 25));
        fbz_22.setPrefSize(new fsm_1(250, 75));
        faw_23.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("cache");
        fsj_22.setName("mixDebugger");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        fje_22.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        String string = "soundGroup";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        faw_24.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.mixDebugger:selectLogSoundGroup(soundGroup)");
        fdd_22.setOnClick(fmz_12);
        fdd_22.setStyle("flat");
        faw_24.X(fdd_22);
        fdd_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fdd_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("selected");
        fsd_13.setField("logFiltered");
        fdd_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdd_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("bold");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fbv_22.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        fbv_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_22);
        fcq_22.setVerticalScrollBarPosition(0.0f);
        faw_22.X(fcq_22);
        fcq_22.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(325);
        fdy_12.setMinWidth(0);
        fdy_12.setStyle("11");
        fcq_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("log");
        fsj_23.setName("mixDebugger");
        fdy_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_25.setStyle("caracs");
        faw_22.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLP);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdd_2 fdd_23 = new fdd_2();
        fdd_23.aVI();
        fdd_23.setElementMap(fhs_22);
        fdd_23.setExpandable(false);
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu.mixDebugger:pause");
        fdd_23.setOnSelectionChange(fmo_12);
        fdd_23.setStyle("flat");
        fdd_23.setText("Pause");
        faw_25.X(fdd_23);
        fdd_23.guy();
        fdd_23.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_25.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.mixDebugger:chooseSaveDirectory");
        fad_12.setOnClick(fmz_13);
        fad_12.setText("...");
        faw_25.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.mixDebugger:save");
        fad_13.setOnClick(fmz_14);
        fad_13.setText("Save");
        faw_25.X(fad_13);
        fad_13.guy();
        fad_13.onChildrenAdded();
        fed_2 fed_22 = new fed_2();
        fed_22.aVI();
        fed_22.setElementMap(fhs_22);
        fed_22.setExpandable(false);
        fed_22.setPointAlign(faa_2.tLS);
        faw_25.X(fed_22);
        fed_22.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        fed_22.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_22);
        fad_14.setExpandable(false);
        fad_14.setNonBlocking(true);
        fad_14.setStyle("Yellow");
        fed_22.X(fad_14);
        fad_14.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fad_14.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fad_1 fad_15 = fad_14;
        fym_0 fym_02 = (fym_0)((fes_2)fad_15).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_14.X(fym_02);
        fym_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(2, 2, 2, 3));
        fym_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_14.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("multidirectionnalCross");
        fed_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fed_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_22.onChildrenAdded();
        frz_12.onChildrenAdded();
        return frz_12;
    }

    public fhi_2 r(fdh_1 fdh_12) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_1 frz_12 = new frz_1();
        frz_12.aVI();
        frz_12.setElementMap(fhs_22);
        frz_12.setText("Ambiance");
        fdh_12.X(frz_12);
        frz_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(0, 150));
        faw_22.setStyle("ShortcutRowBackground");
        frz_12.X(faw_22);
        faw_22.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("caracs");
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_23.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_22);
        fcq_22.setHorizontalScrollBarBehaviour(fzi_0.tHc);
        fcq_22.setVerticalScrollBarPosition(1.0f);
        faw_23.X(fcq_22);
        fcq_22.guy();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_22);
        fdf_12.setInnerExpandable(false);
        fcq_22.X(fdf_12);
        fdf_12.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        fdf_12.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("stratas");
        fsj_22.setName("mixDebugger");
        fdf_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fdf_12.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        fje_22.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 5, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_24.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("bold");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(100.0f, 15));
        fbz_22.setHorizontal(false);
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMinColumns(1);
        faw_24.X(fbz_22);
        fbz_22.guy();
        fbz_2 fbz_23 = fbz_22;
        fza fza2 = (fza)((fes_2)fbz_23).getAppearance();
        fza2.setElementMap(fhs_22);
        fbz_22.X(fza2);
        fza2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 10, 0, 0));
        fza2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fza2.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("content");
        fsd_13.setField("containers");
        fbz_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fbz_22.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjt_23.X(fjx_13);
        fjx_13.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjx_13.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        fje_23.X(faw_26);
        faw_26.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        faw_26.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setNonBlocking(true);
        fbv_23.setStyle("bold");
        faw_26.X(fbv_23);
        fbv_23.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fbv_23.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbv_23.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setNonBlocking(true);
        faw_26.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq2 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_24.X(fzq2);
        fzq2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 3, 0, 0));
        fzq2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("lastAdded");
        fbv_24.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_26.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setExpandable(false);
        faw_27.setStyle("caracs");
        faw_22.X(faw_27);
        faw_27.guy();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_27.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fed_2 fed_22 = new fed_2();
        fed_22.aVI();
        fed_22.setElementMap(fhs_22);
        fed_22.setExpandable(false);
        fed_22.setPointAlign(faa_2.tLS);
        faw_27.X(fed_22);
        fed_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fed_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setNonBlocking(true);
        fad_12.setStyle("Yellow");
        fed_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(2, 2, 2, 3));
        fym_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("multidirectionnalCross");
        fed_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fed_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_22.onChildrenAdded();
        frz_12.onChildrenAdded();
        return frz_12;
    }

    public fhi_2 s(fdh_1 fdh_12) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_1 frz_12 = new frz_1();
        frz_12.aVI();
        frz_12.setElementMap(fhs_22);
        frz_12.setText("Statut");
        fdh_12.X(frz_12);
        frz_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(0, 150));
        faw_22.setStyle("ShortcutRowBackground");
        frz_12.X(faw_22);
        faw_22.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setStyle("caracs");
        faw_22.X(faw_23);
        faw_23.guy();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setCellSize(new fsm_1(125, 25));
        fbz_22.setPrefSize(new fsm_1(250, 75));
        faw_23.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("cache");
        fsj_22.setName("mixDebugger");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        fje_22.X(faw_24);
        faw_24.guy();
        String string = "soundGroup";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        faw_24.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.mixDebugger:selectSoundGroup(soundGroup)");
        fdd_22.setOnClick(fmz_12);
        fdd_22.setStyle("flat");
        faw_24.X(fdd_22);
        fdd_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fdd_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("selected");
        fsd_13.setField("visible");
        fdd_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdd_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("bold");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fbv_22.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        fbv_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_22);
        fcq_22.setVerticalScrollBarPosition(1.0f);
        faw_22.X(fcq_22);
        fcq_22.guy();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_22);
        fdf_12.setExpandable(false);
        fdf_12.setHorizontal(false);
        fdf_12.setInnerExpandable(false);
        fcq_22.X(fdf_12);
        fdf_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("content");
        fsj_23.setField("cache");
        fsj_23.setName("mixDebugger");
        fdf_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        fdf_12.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fdf_12.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_22);
        fjt_23.X(fjx_13);
        fjx_13.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjx_13.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_25.setPrefSize(new fsm_1(380, 0));
        fje_23.X(faw_25);
        faw_25.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        faw_25.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("visible");
        fsd_15.setField("visible");
        faw_25.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_25.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("bold");
        faw_25.X(fbv_23);
        fbv_23.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("name");
        fbv_23.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fbv_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(375);
        fdy_12.setMinWidth(0);
        fdy_12.setStyle("11");
        faw_25.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("text");
        fsd_17.setField("sourcesDescription");
        fdy_12.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_25.onChildrenAdded();
        fje_23.onChildrenAdded();
        fdf_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setStyle("caracs");
        faw_22.X(faw_26);
        faw_26.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_26.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setText("Refresh");
        faw_26.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 0, 5));
        fzq3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        String string2 = "onOff";
        fry_1 fry_12 = new fry_1();
        fry_12.aVI();
        fry_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, (fhv_1)fry_12);
        }
        faw_26.X(fry_12);
        fry_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("value");
        fsj_24.setField("refresh");
        fsj_24.setName("mixDebugger");
        fry_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fry_12.onChildrenAdded();
        fcu_1 fcu_12 = new fcu_1();
        fcu_12.aVI();
        fcu_12.setElementMap(fhs_22);
        fcu_12.setExpandable(false);
        fcu_12.setGroupId("onOff");
        fmh_2 fmh_22 = new fmh_2();
        fmh_22.vw("wakfu.mixDebugger:setRefreshOn");
        fcu_12.setOnMousePress(fmh_22);
        fcu_12.setText("on");
        fcu_12.setValue("true");
        faw_26.X(fcu_12);
        fcu_12.guy();
        fcu_1 fcu_13 = fcu_12;
        fzk fzk2 = (fzk)((fes_2)fcu_13).getAppearance();
        fzk2.setElementMap(fhs_22);
        fcu_12.X(fzk2);
        fzk2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 0, 0, 5));
        fzk2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzk2.onChildrenAdded();
        fcu_12.onChildrenAdded();
        fcu_1 fcu_14 = new fcu_1();
        fcu_14.aVI();
        fcu_14.setElementMap(fhs_22);
        fcu_14.setExpandable(false);
        fcu_14.setGroupId("onOff");
        fmh_2 fmh_23 = new fmh_2();
        fmh_23.vw("wakfu.mixDebugger:setRefreshOff");
        fcu_14.setOnMousePress(fmh_23);
        fcu_14.setText("off");
        fcu_14.setValue("false");
        faw_26.X(fcu_14);
        fcu_14.guy();
        fcu_1 fcu_15 = fcu_14;
        fzk fzk3 = (fzk)((fes_2)fcu_15).getAppearance();
        fzk3.setElementMap(fhs_22);
        fcu_14.X(fzk3);
        fzk3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(0, 0, 0, 10));
        fzk3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzk3.onChildrenAdded();
        fcu_14.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmh_2 fmh_24 = new fmh_2();
        fmh_24.vw("wakfu.mixDebugger:forceRefresh");
        fad_12.setOnMousePress(fmh_24);
        fad_12.setText("Force refresh");
        faw_26.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_26.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fed_2 fed_22 = new fed_2();
        fed_22.aVI();
        fed_22.setElementMap(fhs_22);
        fed_22.setExpandable(false);
        fed_22.setPointAlign(faa_2.tLS);
        faw_26.X(fed_22);
        fed_22.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        fed_22.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setExpandable(false);
        fad_13.setNonBlocking(true);
        fad_13.setStyle("Yellow");
        fed_22.X(fad_13);
        fad_13.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fad_13.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fad_1 fad_14 = fad_13;
        fym_0 fym_02 = (fym_0)((fes_2)fad_14).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_13.X(fym_02);
        fym_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(2, 2, 2, 3));
        fym_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("multidirectionnalCross");
        fed_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fed_22.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_22.onChildrenAdded();
        frz_12.onChildrenAdded();
        return frz_12;
    }

    public fhi_2 m(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(450, 600));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

