/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cML
 */
public class cml_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "moderationPenalFile";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.setPrefSize(new fsm_1(800, 365));
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        fbv_22.setText("Penal file");
        faw_27.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("penalFileUiTitle");
        fsj_22.setName("moderationPanelView");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_210.setExpandable(false);
        faw_28.X(faw_210);
        faw_210.guy();
        String string3 = "deletePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        faw_210.X(frx_12);
        frx_12.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setPrefSize(new fsm_1(10, 0));
        faw_211.setStyle("popup");
        frx_12.X(faw_211);
        faw_211.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setStyle("white");
        String string4 = "%delete%";
        string4 = string4.replace("%delete%", fyw_0.gqw().k("delete", new Object[0]));
        fdy_12.setText(string4);
        faw_211.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_211.onChildrenAdded();
        frx_12.onChildrenAdded();
        String string5 = "penalTable";
        fdq_1 fdq_12 = new fdq_1();
        fdq_12.aVI();
        fdq_12.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fdq_12);
        }
        fdq_12.setCellHeight(30);
        fdq_12.setEnableFilterCache(true);
        fdq_12.setExpandable(false);
        fdq_12.setMaxRows(9);
        fdq_12.setMinRows(9);
        fdq_12.setScrollBarBehaviour(fzi_0.tHb);
        faw_210.X(fdq_12);
        fdq_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("visible");
        fsj_23.setField("isPenalFileLoading");
        fsj_23.setName("moderationPanelView");
        fdq_12.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("content");
        fsj_24.setField("penalFile");
        fsj_24.setName("moderationPanelView");
        fdq_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("tableFilter");
        fsj_25.setField("penalFileFilter");
        fsj_25.setName("moderationPanelView");
        fdq_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fgm_2 fgm_22 = new fgm_2();
        fgm_22.aVI();
        fgm_22.setElementMap(fhs_23);
        fgm_22.setCellWidth(170);
        fgm_22.setColumnId("type");
        fgm_22.setName("Type");
        fdq_12.X(fgm_22);
        fgm_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fgm_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fje_22.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_23.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        String string6 = "penalElement";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        String string7 = "type";
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, faw_212);
        }
        fje_22.X(faw_212);
        faw_212.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_212.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_213 = faw_212;
        fys_0 fys_06 = ((fes_2)faw_213).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_212.X(fys_06);
        fys_06.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_23);
        fkm_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.3f));
        fkm_12.setInsets(new Insets(0, 1, 1, 0));
        fys_06.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_06.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        fdy_14.setExpandable(false);
        fdy_14.setStyle("whiteBold");
        faw_212.X(fdy_14);
        fdy_14.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fsd_13.setField("type");
        fdy_14.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq4 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq4.setElementMap(fhs_23);
        fdy_14.X(fzq4);
        fzq4.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 5, 0, 15));
        fzq4.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_1 fdy_16 = fdy_14;
        fzq fzq5 = (fzq)((fes_2)fdy_16).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlign(faa_2.tLN);
        fdy_14.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        fdy_14.onChildrenAdded();
        String string8 = "deleteNoteButton";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, fad_12);
        }
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.moderationPanel:removeNote(penalElement)");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(deletePopup,deleteNoteButton)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("Close");
        faw_212.X(fad_12);
        fad_12.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("visible");
        fsd_14.setField("isNote");
        fad_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_2 faw_214 = faw_212;
        fys_0 fys_07 = ((fes_2)faw_214).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_212.X(fys_07);
        fys_07.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_23);
        fys_07.X(fkk_12);
        fkk_12.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("color");
        fsd_15.setField("color");
        fkk_12.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fys_07.onChildrenAdded();
        faw_212.onChildrenAdded();
        fje_22.onChildrenAdded();
        fgm_22.onChildrenAdded();
        fgm_2 fgm_23 = new fgm_2();
        fgm_23.aVI();
        fgm_23.setElementMap(fhs_23);
        fgm_23.setCellWidth(125);
        fgm_23.setColumnId("moderator");
        fgm_23.setName("Moderator");
        fdq_12.X(fgm_23);
        fgm_23.guy();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fgm_23.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fje_23.X(fjt_24);
        fjt_24.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_23);
        fjt_24.X(fjx_13);
        fjx_13.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_23);
        fjx_13.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fjt_24.onChildrenAdded();
        String string9 = "type";
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        if (fhs_23 != null && string9 != null) {
            fhs_23.a(string9, faw_215);
        }
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(moderatorNamePopup)");
        faw_215.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        faw_215.setOnPopupHide(fml_13);
        fje_23.X(faw_215);
        faw_215.guy();
        faw_2 faw_216 = faw_215;
        fys_0 fys_08 = ((fes_2)faw_216).getAppearance();
        fys_08.setElementMap(fhs_23);
        faw_215.X(fys_08);
        fys_08.guy();
        fkm_1 fkm_13 = new fkm_1();
        fkm_13.aVI();
        fkm_13.setElementMap(fhs_23);
        fkm_13.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.3f));
        fkm_13.setInsets(new Insets(0, 1, 1, 0));
        fys_08.X(fkm_13);
        fkm_13.guy();
        fkm_13.onChildrenAdded();
        fys_08.onChildrenAdded();
        fdy_1 fdy_17 = new fdy_1();
        fdy_17.aVI();
        fdy_17.setElementMap(fhs_23);
        fdy_17.setStyle("defaultWhite");
        faw_215.X(fdy_17);
        fdy_17.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("text");
        fsd_16.setField("moderatorName");
        fdy_17.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fdy_1 fdy_18 = fdy_17;
        fzq fzq6 = (fzq)((fes_2)fdy_18).getAppearance();
        fzq6.setElementMap(fhs_23);
        fdy_17.X(fzq6);
        fzq6.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 5, 0, 0));
        fzq6.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq6.onChildrenAdded();
        fdy_1 fdy_19 = fdy_17;
        fzq fzq7 = (fzq)((fes_2)fdy_19).getAppearance();
        fzq7.setElementMap(fhs_23);
        fzq7.setAlign(faa_2.tLO);
        fdy_17.X(fzq7);
        fzq7.guy();
        fzq7.onChildrenAdded();
        fdy_17.onChildrenAdded();
        this.R(faw_215);
        faw_215.onChildrenAdded();
        fje_23.onChildrenAdded();
        fgm_23.onChildrenAdded();
        this.Y(fdq_12);
        this.Z(fdq_12);
        fdq_12.onChildrenAdded();
        this.e(faw_210);
        this.F(faw_210);
        this.G(faw_210);
        this.f(faw_210);
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.N(fey_22);
        this.O(fey_22);
        this.P(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "moderatorNamePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        faw_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setMaxWidth(125);
        fbv_22.setMultiline(true);
        fbv_22.setStyle("PopupInformation");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("moderatorName");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_2 fbv_24 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(2, 0, 2, 0));
        fzq3.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(-30, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 Y(fdq_1 fdq_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fgm_2 fgm_22 = new fgm_2();
        fgm_22.aVI();
        fgm_22.setElementMap(fhs_22);
        fgm_22.setCellWidth(150);
        fgm_22.setColumnId("date");
        fgm_22.setName("Date");
        fdq_12.X(fgm_22);
        fgm_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fgm_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string = "type";
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_22);
        }
        fje_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.3f));
        fkm_12.setInsets(new Insets(0, 1, 1, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("defaultWhite");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("date");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_1 fdy_14 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLN);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        fgm_22.onChildrenAdded();
        return fgm_22;
    }

    public fhi_2 Z(fdq_1 fdq_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fgm_2 fgm_22 = new fgm_2();
        fgm_22.aVI();
        fgm_22.setElementMap(fhs_22);
        fgm_22.setCellWidth(300);
        fgm_22.setColumnId("reason");
        fgm_22.setName("Reason / Note");
        fdq_12.X(fgm_22);
        fgm_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fgm_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string = "type";
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_22);
        }
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(reasonPopup)");
        faw_22.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_22.setOnPopupHide(fml_12);
        fje_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.3f));
        fkm_12.setInsets(new Insets(0, 1, 1, 0));
        fys_02.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(295);
        fdy_12.setMinWidth(295);
        fdy_12.setStyle("defaultWhite");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("reason");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_1 fdy_14 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLN);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        String string2 = "reasonPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_12);
        }
        faw_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setStyle("popup");
        frx_12.X(faw_24);
        faw_24.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setMaxWidth(350);
        fbv_22.setMultiline(true);
        fbv_22.setStyle("PopupInformation");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("reason");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq4 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlignment(faa_2.tLN);
        fbv_22.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_2 fbv_24 = fbv_22;
        fzq fzq5 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq5.setElementMap(fhs_22);
        fbv_22.X(fzq5);
        fzq5.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(2, 0, 2, 0));
        fzq5.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq5.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_25 = faw_24;
        fys_0 fys_03 = ((fes_2)faw_25).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_24.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(-30, 0, 0, 0));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_24.onChildrenAdded();
        frx_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        fgm_22.onChildrenAdded();
        return fgm_22;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("isPenalFileLoading");
        fsj_22.setName("moderationPanelView");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        frz_22.setHorizontal(true);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        String string = "%search% :";
        string = string.replace("%search%", fyw_0.gqw().k("search", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_2 fbv_24 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 0, 5));
        fzq3.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        fdu_12.setExpandable(false);
        fdu_12.setMaxWidth(300);
        fdu_12.setMinWidth(300);
        faw_23.X(fdu_12);
        fdu_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("listFilter");
        fsj_23.setField("penalFileFilter");
        fsj_23.setName("moderationPanelView");
        fdu_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(5, 0, 0, 0));
        fys_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(true);
        faw_22.X(faw_23);
        faw_23.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("isPenalFileLoading");
        fsj_22.setName("moderationPanelView");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("CharacterChoiceMainTitle");
        String string = "%loading%";
        string = string.replace("%loading%", fyw_0.gqw().k("loading", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(2, 2, 2, 2));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        return fys_02;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        return null;
    }

    public fhi_2 N(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 O(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.moderationPanel:togglePanelFile");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tKY);
        frp_13.setSize(new fsm_1(-2, -2));
        frp_13.setXOffset(763);
        frp_13.setYOffset(-13);
        fad_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 P(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setResizeOnce(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

