/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMM
 */
public class cmm_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fys_02.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_24.setNonBlocking(false);
        faw_24.setStyle("windowBackgroundSecondary");
        fey_22.X(faw_24);
        faw_24.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_24.X(fea_12);
        fea_12.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setPrefSize(new fsm_1(100.0f, 48));
        faw_25.setStyle("WindowHeaderSmallSecondary");
        fea_12.X(faw_25);
        faw_25.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_25.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_26);
        faw_26.guy();
        faw_26.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setEnableAutoZoomShrink(true);
        fbv_22.setMaxWidth(270);
        fbv_22.setMinWidth(100);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("windowTitle");
        fbv_22.setText("Account players");
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(44, 32));
        faw_25.X(faw_27);
        faw_27.guy();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setPrefSize(new fsm_1(32, 32));
        fad_12.setStyle("crossTertiary");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        faw_27.X(fad_12);
        fad_12.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 0, 12));
        fad_12.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLP);
        fad_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        String string = "windowContentContainer";
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, faw_28);
        }
        faw_28.setPrefSize(new fsm_1(360, 100.0f));
        faw_24.X(faw_28);
        faw_28.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_28.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_28.X(faw_29);
        faw_29.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_28.X(faw_210);
        faw_210.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_210.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_211 = faw_210;
        fys_0 fys_03 = ((fes_2)faw_211).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_210.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(12, 10, 12, 10));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_210.X(faw_212);
        faw_212.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_212.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_213.setStyle("ContentContainer1");
        faw_212.X(faw_213);
        faw_213.guy();
        faw_2 faw_214 = faw_213;
        fys_0 fys_04 = ((fes_2)faw_214).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_213.X(fys_04);
        fys_04.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(8, 8, 8, 8));
        fys_04.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_04.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setExpandable(false);
        fcq_22.setPrefSize(new fsm_1(324, 500));
        fcq_22.setStyle("defaultScrollContainer");
        faw_213.X(fcq_22);
        fcq_22.guy();
        String string2 = "nameList";
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fbz_22);
        }
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(154, 36));
        fbz_22.setHideContainerWithoutItem(true);
        fbz_22.setIdealSizeMaxColumns(2);
        fbz_22.setIdealSizeMinColumns(2);
        fbz_22.setStyle("defaultList");
        fcq_22.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("content");
        fsj_22.setName("moderationRenamingPlayers");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fbz_22.X(fje_22);
        fje_22.guy();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        fje_22.X(faw_215);
        faw_215.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_215.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        String string3 = "nameCB";
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fdd_22);
        }
        fdd_22.setExpandable(false);
        fdd_22.setPrefSize(new fsm_1(154, 36));
        fdd_22.setStyle("defaultCheckbox12");
        faw_215.X(fdd_22);
        fdd_22.guy();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setEnableAutoZoomShrink(true);
        fbv_24.setMaxWidth(122);
        fdd_22.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fbv_24.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fdd_22.onChildrenAdded();
        faw_215.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_216.setStyle("ContentContainer1");
        faw_212.X(faw_216);
        faw_216.guy();
        faw_2 faw_217 = faw_216;
        fys_0 fys_05 = ((fes_2)faw_217).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_216.X(fys_05);
        fys_05.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(8, 8, 8, 8));
        fys_05.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fys_05.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        frz_25.setHgap((short)16);
        faw_216.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        String string4 = "sanctionGroup";
        fry_1 fry_12 = new fry_1();
        fry_12.aVI();
        fry_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, (fhv_1)fry_12);
        }
        faw_216.X(fry_12);
        fry_12.guy();
        fry_12.onChildrenAdded();
        fcu_1 fcu_12 = new fcu_1();
        fcu_12.aVI();
        fcu_12.setElementMap(fhs_23);
        fcu_12.setExpandable(false);
        fcu_12.setGroupId("sanctionGroup");
        fcu_12.setSelected(true);
        fcu_12.setStyle("newRadioButton");
        fcu_12.setText("Warning");
        fcu_12.setValue("warning");
        faw_216.X(fcu_12);
        fcu_12.guy();
        fcu_12.onChildrenAdded();
        fcu_1 fcu_13 = new fcu_1();
        fcu_13.aVI();
        fcu_13.setElementMap(fhs_23);
        fcu_13.setExpandable(false);
        fcu_13.setGroupId("sanctionGroup");
        fcu_13.setStyle("newRadioButton");
        fcu_13.setText("Ban");
        fcu_13.setValue("ban");
        faw_216.X(fcu_13);
        fcu_13.guy();
        fcu_13.onChildrenAdded();
        faw_216.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.moderationPanel:forceSelectedCharactersRename(sanctionGroup,nameList)");
        fad_13.setOnClick(fmz_13);
        fad_13.setPrefSize(new fsm_1(338, 36));
        fad_13.setStyle("primaryMedium");
        fad_13.setText("Force character(s) rename");
        faw_212.X(fad_13);
        fad_13.guy();
        fad_13.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        fey_22.X(faw_218);
        faw_218.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        faw_218.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        faw_218.onChildrenAdded();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setResizeOnce(true);
        fey_22.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

