/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMS
 */
public class cms_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string = "%nationSelection.title%";
        string = string.replace("%nationSelection.title%", fyw_0.gqw().k("nationSelection.title", new Object[0]));
        fbv_22.setText(string);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        String string3 = "list";
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fbz_22);
        }
        fbz_22.setCellSize(new fsm_1(240, 475));
        fbz_22.setPrefSize(new fsm_1(960, 460));
        faw_210.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("content");
        fsj_22.setName("nationSelectionList");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string4 = "nationSelection";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setNonBlocking(false);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.nationSelectionPanel:onMouseOverElement(nationSelection)");
        faw_211.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.nationSelectionPanel:onMouseOutElement");
        faw_211.setOnMouseExit(fmf_22);
        fje_22.X(faw_211);
        faw_211.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_211.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_212.setPrefSize(new fsm_1(220, 60));
        faw_211.X(faw_212);
        faw_212.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLm);
        frp_14.setXOffset(-10);
        faw_212.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_213 = faw_212;
        fys_0 fys_06 = ((fes_2)faw_213).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_212.X(fys_06);
        fys_06.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(20, 0, 0, 0));
        fys_06.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_06.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_212.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(57, 36));
        fbt_12.setNonBlocking(false);
        fbt_12.setStyle("TimelineTimerBackgroundVerticalFlip");
        faw_212.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLf);
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_23);
        ((fys_0)fyY2).setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 0.3f));
        fbt_12.X(fyY2);
        fyY2.guy();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setDisplaySize(new fsm_1(57, 36));
        fbt_14.setNonBlocking(false);
        fbt_14.setStyle("TimelineTimerBackgroundVerticalHorizontalFlip");
        faw_212.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLh);
        fbt_14.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbt_1 fbt_15 = fbt_14;
        fyY fyY3 = (fyY)((fes_2)fbt_15).getAppearance();
        fyY3.setElementMap(fhs_23);
        ((fys_0)fyY3).setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 0.3f));
        fbt_14.X(fyY3);
        fyY3.guy();
        fyY3.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_212.X(faw_214);
        faw_214.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        faw_214.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        fro_15.setAdaptToContentSize(true);
        faw_214.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_214.X(faw_215);
        faw_215.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLa);
        frp_18.setSize(new fsm_1(100.0f, -2));
        faw_215.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_23);
        fbt_16.setExpandable(false);
        fbt_16.setNonBlocking(true);
        fbt_16.setStyle("SundialLeftButtonContainer");
        faw_215.X(fbt_16);
        fbt_16.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLL);
        fbt_16.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fbt_16.onChildrenAdded();
        fbt_1 fbt_17 = new fbt_1();
        fbt_17.aVI();
        fbt_17.setElementMap(fhs_23);
        fbt_17.setNonBlocking(true);
        fbt_17.setStyle("SundialCenterButtonContainer");
        faw_215.X(fbt_17);
        fbt_17.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLL);
        fbt_17.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fbt_17.onChildrenAdded();
        fbt_1 fbt_18 = new fbt_1();
        fbt_18.aVI();
        fbt_18.setElementMap(fhs_23);
        fbt_18.setExpandable(false);
        fbt_18.setNonBlocking(true);
        fbt_18.setStyle("SundialRightButtonContainer");
        faw_215.X(fbt_18);
        fbt_18.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLL);
        fbt_18.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fbt_18.onChildrenAdded();
        faw_215.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.nationSelectionPanel:chooseNation(nationSelection)");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(choosePopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("big");
        String string5 = "%choose%";
        string5 = string5.replace("%choose%", fyw_0.gqw().k("choose", new Object[0]));
        fad_12.setText(string5);
        faw_214.X(fad_12);
        fad_12.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setAlign(fzw_0.tLg);
        fad_12.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_23);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 20, 0, 20));
        fym_02.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(2, 15, 2, 15));
        fym_02.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("modulationColor");
        fsj_23.setName("selectedNation");
        fym_02.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fjt_23.setElseValue("1,1,1");
        fjt_23.setValue("0.28,0.86,0.83,1");
        fsj_23.X(fjt_23);
        fjt_23.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_23);
        fjt_23.X(fjv_12);
        fjv_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("value");
        fjv_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fjv_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fym_02.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("enabled");
        fsj_24.setName("nationSelectionDisabledMessage");
        fad_12.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fsj_24.X(fjt_24);
        fjt_24.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_23);
        fjt_24.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_24.onChildrenAdded();
        String string6 = "choosePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setPrefSize(new fsm_1(10, 0));
        faw_216.setStyle("popup");
        frx_12.X(faw_216);
        faw_216.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKw);
        faw_216.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_216.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        this.R(faw_216);
        this.c(faw_216);
        faw_216.onChildrenAdded();
        frx_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_212.onChildrenAdded();
        this.d(faw_211);
        this.H(faw_211);
        this.I(faw_211);
        faw_211.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.t(fey_22);
        this.u(fey_22);
        this.v(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        String string = "%choose%";
        string = string.replace("%choose%", fyw_0.gqw().k("choose", new Object[0]));
        fbv_22.setText(string);
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("PopupInformation");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("errorColor"));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setName("nationSelectionDisabledMessage");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setName("nationSelectionDisabledMessage");
        fdy_12.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(false);
        faw_23.setStyle("tiledScroll");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 0, 0, 0));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(17, 12, 55, 30));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_23.X(faw_25);
        faw_25.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_25.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_25.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(0, 30));
        faw_26.setStyle("EncyclopediaSplashTitle");
        faw_25.X(faw_26);
        faw_26.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        faw_26.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_27 = faw_26;
        fys_0 fys_03 = ((fes_2)faw_27).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_26.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(0, 10, 3, 10));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(5, 0, 0, 0));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        faw_26.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("StyledBold16White");
        faw_26.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("nation/name");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_25.X(faw_28);
        faw_28.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_28.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setExpandable(false);
        faw_29.setStyle("lineSeparator");
        faw_28.X(faw_29);
        faw_29.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLm);
        frp_14.setSize(new fsm_1(100.0f, 7));
        faw_29.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_29.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        fbt_12.setStyle("KamaPoi");
        faw_28.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLf);
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_22);
        fdy_13.setStyle("StyledBoldDark12");
        String string = "%richness%";
        string = string.replace("%richness%", fyw_0.gqw().k("richness", new Object[0]));
        fdy_13.setText(string);
        faw_28.X(fdy_13);
        fdy_13.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLf);
        fdy_13.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq2 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_13.X(fzq2);
        fzq2.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_22);
        fzx4.setInsets(new Insets(0, 32, 0, 0));
        fzq2.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_13.onChildrenAdded();
        faw_28.onChildrenAdded();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_22);
        fdy_15.setExpandable(false);
        fdy_15.setStyle("titleName12");
        faw_25.X(fdy_15);
        fdy_15.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLO);
        fdy_15.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("totalCash");
        fdy_15.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdy_15.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_210.setExpandable(false);
        faw_25.X(faw_210);
        faw_210.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_210.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_211.setStyle("lineSeparator");
        faw_210.X(faw_211);
        faw_211.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_22);
        frp_17.setAlign(fzw_0.tLm);
        frp_17.setSize(new fsm_1(100.0f, 7));
        faw_211.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        faw_211.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setExpandable(false);
        fbt_13.setStyle("ChestPoi");
        faw_210.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_22);
        frp_18.setAlign(fzw_0.tLf);
        fbt_13.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        fdy_16.setStyle("StyledBoldDark12");
        String string2 = "%inhabitantCount%";
        string2 = string2.replace("%inhabitantCount%", fyw_0.gqw().k("inhabitantCount", new Object[0]));
        fdy_16.setText(string2);
        faw_210.X(fdy_16);
        fdy_16.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_22);
        frp_19.setAlign(fzw_0.tLf);
        fdy_16.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq3 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq3.setElementMap(fhs_22);
        fdy_16.X(fzq3);
        fzq3.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_22);
        fzx5.setInsets(new Insets(0, 32, 0, 0));
        fzq3.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_210.onChildrenAdded();
        fdy_1 fdy_18 = new fdy_1();
        fdy_18.aVI();
        fdy_18.setElementMap(fhs_22);
        fdy_18.setExpandable(false);
        fdy_18.setStyle("titleName12");
        faw_25.X(fdy_18);
        fdy_18.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_22);
        frb_14.setAlign(faa_2.tLO);
        fdy_18.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("populationSize");
        fdy_18.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fdy_18.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setExpandable(false);
        faw_25.X(faw_212);
        faw_212.guy();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        fro_15.setAdaptToContentSize(true);
        faw_212.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_22);
        faw_213.setExpandable(false);
        faw_213.setStyle("lineSeparator");
        faw_212.X(faw_213);
        faw_213.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_22);
        frp_110.setAlign(fzw_0.tLm);
        frp_110.setSize(new fsm_1(100.0f, 7));
        faw_213.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        faw_213.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setExpandable(false);
        fbt_14.setStyle("swordPoi");
        faw_212.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_111 = new frp_1();
        frp_111.aVI();
        frp_111.setElementMap(fhs_22);
        frp_111.setAlign(fzw_0.tLf);
        fbt_14.X(frp_111);
        frp_111.guy();
        frp_111.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fdy_1 fdy_19 = new fdy_1();
        fdy_19.aVI();
        fdy_19.setElementMap(fhs_22);
        fdy_19.setStyle("StyledBoldDark12");
        String string3 = "%nation.governor%";
        string3 = string3.replace("%nation.governor%", fyw_0.gqw().k("nation.governor", new Object[0]));
        fdy_19.setText(string3);
        faw_212.X(fdy_19);
        fdy_19.guy();
        frp_1 frp_112 = new frp_1();
        frp_112.aVI();
        frp_112.setElementMap(fhs_22);
        frp_112.setAlign(fzw_0.tLf);
        fdy_19.X(frp_112);
        frp_112.guy();
        frp_112.onChildrenAdded();
        fdy_1 fdy_110 = fdy_19;
        fzq fzq4 = (fzq)((fes_2)fdy_110).getAppearance();
        fzq4.setElementMap(fhs_22);
        fdy_19.X(fzq4);
        fzq4.guy();
        fzx fzx6 = new fzx();
        fzx6.aVI();
        fzx6.setElementMap(fhs_22);
        fzx6.setInsets(new Insets(0, 32, 0, 0));
        fzq4.X(fzx6);
        fzx6.guy();
        fzx6.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_19.onChildrenAdded();
        faw_212.onChildrenAdded();
        fdy_1 fdy_111 = new fdy_1();
        fdy_111.aVI();
        fdy_111.setElementMap(fhs_22);
        fdy_111.setExpandable(false);
        fdy_111.setStyle("titleName12");
        faw_25.X(fdy_111);
        fdy_111.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_22);
        frb_15.setAlign(faa_2.tLO);
        fdy_111.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("governorName");
        fdy_111.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fdy_111.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_22);
        faw_214.setExpandable(false);
        faw_25.X(faw_214);
        faw_214.guy();
        fro_1 fro_16 = new fro_1();
        fro_16.aVI();
        fro_16.setAdaptToContentSize(true);
        faw_214.X(fro_16);
        fro_16.guy();
        fro_16.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_22);
        faw_215.setExpandable(false);
        faw_215.setStyle("lineSeparator");
        faw_214.X(faw_215);
        faw_215.guy();
        frp_1 frp_113 = new frp_1();
        frp_113.aVI();
        frp_113.setElementMap(fhs_22);
        frp_113.setAlign(fzw_0.tLm);
        frp_113.setSize(new fsm_1(100.0f, 7));
        faw_215.X(frp_113);
        frp_113.guy();
        frp_113.onChildrenAdded();
        faw_215.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_22);
        fbt_15.setExpandable(false);
        fbt_15.setStyle("flagPoi");
        faw_214.X(fbt_15);
        fbt_15.guy();
        frp_1 frp_114 = new frp_1();
        frp_114.aVI();
        frp_114.setElementMap(fhs_22);
        frp_114.setAlign(fzw_0.tLf);
        frp_114.setXOffset(5);
        fbt_15.X(frp_114);
        frp_114.guy();
        frp_114.onChildrenAdded();
        fbt_15.onChildrenAdded();
        fdy_1 fdy_112 = new fdy_1();
        fdy_112.aVI();
        fdy_112.setElementMap(fhs_22);
        fdy_112.setStyle("StyledBoldDark12");
        String string4 = "%territoriesCount%";
        string4 = string4.replace("%territoriesCount%", fyw_0.gqw().k("territoriesCount", new Object[0]));
        fdy_112.setText(string4);
        faw_214.X(fdy_112);
        fdy_112.guy();
        frp_1 frp_115 = new frp_1();
        frp_115.aVI();
        frp_115.setElementMap(fhs_22);
        frp_115.setAlign(fzw_0.tLf);
        fdy_112.X(frp_115);
        frp_115.guy();
        frp_115.onChildrenAdded();
        fdy_1 fdy_113 = fdy_112;
        fzq fzq5 = (fzq)((fes_2)fdy_113).getAppearance();
        fzq5.setElementMap(fhs_22);
        fdy_112.X(fzq5);
        fzq5.guy();
        fzx fzx7 = new fzx();
        fzx7.aVI();
        fzx7.setElementMap(fhs_22);
        fzx7.setInsets(new Insets(0, 32, 0, 0));
        fzq5.X(fzx7);
        fzx7.guy();
        fzx7.onChildrenAdded();
        fzq5.onChildrenAdded();
        fdy_112.onChildrenAdded();
        faw_214.onChildrenAdded();
        fdy_1 fdy_114 = new fdy_1();
        fdy_114.aVI();
        fdy_114.setElementMap(fhs_22);
        fdy_114.setExpandable(false);
        fdy_114.setStyle("titleName12");
        faw_25.X(fdy_114);
        fdy_114.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_22);
        frb_16.setAlign(faa_2.tLO);
        fdy_114.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("territoriesCount");
        fdy_114.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fdy_114.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_22);
        faw_216.setExpandable(false);
        faw_25.X(faw_216);
        faw_216.guy();
        this.e(faw_216);
        this.F(faw_216);
        this.G(faw_216);
        this.f(faw_216);
        faw_216.onChildrenAdded();
        this.g(faw_25);
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        return null;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setStyle("lineSeparator");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(100.0f, 7));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        fbt_12.setStyle("questionPoi");
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setXOffset(5);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("StyledBoldDark12");
        String string = "%nationAlignments%";
        string = string.replace("%nationAlignments%", fyw_0.gqw().k("nationAlignments", new Object[0]));
        fdy_12.setText(string);
        faw_22.X(fdy_12);
        fdy_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        fdy_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 32, 0, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("titleName12");
        faw_22.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fdy_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("nationAlignments");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 H(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(215, -2));
        frp_12.setXOffset(-5);
        frp_12.setYOffset(50);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(80, 80));
        fbt_12.setExpandable(false);
        faw_23.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLf);
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("nation/passportStampIconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setDisplaySize(new fsm_1(140, 100));
        fbt_13.setExpandable(false);
        faw_23.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLh);
        fbt_13.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fbt_13.X(fze3);
        fze3.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("texture");
        fsd_13.setField("selectionIcon");
        fze3.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze3.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 I(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(true);
        faw_23.setStyle("EncyclopediaPane");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(260, 100.0f));
        frp_12.setXOffset(-9);
        frp_12.setYOffset(1);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 35, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 t(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 u(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 v(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

