/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMU
 */
public class cmu_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setNonBlocking(false);
        faw_22.setVisible(false);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(100.0f, 36));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLa);
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(45, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        frz_23.setHgap((short)16);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setExpandable(false);
        fbt_12.setFlipHorizontaly(true);
        fbt_12.setStyle("fancyOrnament");
        faw_25.X(fbt_12);
        fbt_12.guy();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipTitleLight24Bordered");
        String string = "%server.choice.select.world.title%";
        string = string.replace("%server.choice.select.world.title%", fyw_0.gqw().k("server.choice.select.world.title", new Object[0]));
        fbv_22.setText(string);
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setExpandable(false);
        fbt_13.setStyle("fancyOrnament");
        faw_25.X(fbt_13);
        fbt_13.guy();
        fbt_13.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(0, 56));
        faw_26.setStyle("windowBackgroundSecondary");
        faw_22.X(faw_26);
        faw_26.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(0, 12, 0, 12));
        faw_26.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tKY);
        faw_26.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(64, 64, 0, 0));
        faw_26.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        frz_24.setHgap((short)12);
        faw_26.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.newServerChoice:goBackToServerModeChoiceDialog");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(characterBackPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setPrefSize(new fsm_1(36, 36));
        fad_12.setStyle("caretLeftTertiary");
        faw_26.X(fad_12);
        fad_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        fad_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        String string2 = "characterBackPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setPrefSize(new fsm_1(10, 0));
        faw_27.setStyle("popup");
        frx_12.X(faw_27);
        faw_27.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKA);
        faw_27.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setStyle("PopupInformation");
        String string3 = "%back%";
        string3 = string3.replace("%back%", fyw_0.gqw().k("back", new Object[0]));
        fbv_24.setText(string3);
        faw_27.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_27.onChildrenAdded();
        frx_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_26.X(faw_28);
        faw_28.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        faw_28.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_28.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setStyle("wipLightGray12");
        String string4 = "%!server.serverType%";
        string4 = string4.replace("%!server.serverType%", fyw_0.gqw().k("server.serverType", new Object[0]).toUpperCase());
        fbv_26.setText(string4);
        faw_28.X(fbv_26);
        fbv_26.guy();
        fbv_26.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_23);
        fbv_27.setExpandable(false);
        fbv_27.setStyle("wipTitleGray16");
        faw_28.X(fbv_27);
        fbv_27.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("selectedCategory/name");
        fsj_22.setName("serverChoiceView");
        fbv_27.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_27.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_22.X(faw_29);
        faw_29.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setXOffset(-383);
        faw_29.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLO);
        faw_29.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_29.X(faw_210);
        faw_210.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("visible");
        fsj_23.setField("selectedCategory/hasGroups");
        fsj_23.setName("serverChoiceView");
        faw_210.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLO);
        faw_210.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLO);
        frz_27.setHorizontal(false);
        frz_27.setVgap((short)16);
        faw_210.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_210.X(faw_211);
        faw_211.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLO);
        faw_211.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setAlign(faa_2.tLL);
        frz_28.setHorizontal(false);
        frz_28.setVgap((short)16);
        faw_211.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_211.X(faw_212);
        faw_212.guy();
        frz_2 frz_29 = frz_2.checkOut();
        frz_29.setAlign(faa_2.tLN);
        frz_29.setHgap((short)8);
        faw_212.X(frz_29);
        frz_29.guy();
        frz_29.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setDisplaySize(new fsm_1(35, 35));
        fbt_14.setExpandable(false);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(communityPopupGroup)");
        fbt_14.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fbt_14.setOnPopupHide(fml_13);
        faw_212.X(fbt_14);
        fbt_14.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("style");
        fsj_24.setField("selectedGroup/communityStyle");
        fsj_24.setName("serverChoiceView");
        fbt_14.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        String string5 = "communityPopupGroup";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, frx_13);
        }
        frx_13.setAlign(faa_2.tLL);
        frx_13.setHotSpotPosition(faa_2.tLR);
        fbt_14.X(frx_13);
        frx_13.guy();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setPrefSize(new fsm_1(10, 0));
        faw_213.setStyle("popup");
        frx_13.X(faw_213);
        faw_213.guy();
        fru_1 fru_13 = fru_1.checkOut();
        fru_13.setElementMap(fhs_23);
        fru_13.setData(fzt_0.tKA);
        faw_213.X(fru_13);
        fru_13.guy();
        fru_13.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setStyle("wipLight14");
        faw_213.X(fbv_28);
        fbv_28.guy();
        fbv_2 fbv_29 = fbv_28;
        fzq fzq4 = (fzq)((fes_2)fbv_29).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLN);
        fbv_28.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("selectedGroup/communityText");
        fsj_25.setName("serverChoiceView");
        fbv_28.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fbv_28.onChildrenAdded();
        faw_213.onChildrenAdded();
        frx_13.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setExpandable(false);
        faw_212.X(faw_214);
        faw_214.guy();
        frz_2 frz_210 = frz_2.checkOut();
        frz_210.setHgap((short)4);
        faw_214.X(frz_210);
        frz_210.guy();
        frz_210.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLc);
        frp_16.setXOffset(-30);
        frp_16.setYOffset(-10);
        faw_214.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("visible");
        fsj_26.setField("selectedGroup/displayCharactersCount");
        fsj_26.setName("serverChoiceView");
        faw_214.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_23);
        fbt_15.setExpandable(false);
        fbt_15.setStyle("iconGroupQuestFull");
        faw_214.X(fbt_15);
        fbt_15.guy();
        fbt_15.onChildrenAdded();
        fbv_2 fbv_210 = new fbv_2();
        fbv_210.aVI();
        fbv_210.setElementMap(fhs_23);
        fbv_210.setExpandable(false);
        fbv_210.setStyle("wipLight14Bordered");
        faw_214.X(fbv_210);
        fbv_210.guy();
        fbv_2 fbv_211 = fbv_210;
        fzq fzq5 = (fzq)((fes_2)fbv_211).getAppearance();
        fzq5.setElementMap(fhs_23);
        fbv_210.X(fzq5);
        fzq5.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 2, 0));
        fzq5.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq5.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("text");
        fsj_27.setField("selectedGroup/charactersCountText");
        fsj_27.setName("serverChoiceView");
        fbv_210.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fbv_210.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setExpandable(false);
        faw_211.X(faw_215);
        faw_215.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("visible");
        fsj_28.setField("selectedCategory/hasGroups");
        fsj_28.setName("serverChoiceView");
        faw_215.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        frz_2 frz_211 = frz_2.checkOut();
        frz_211.setAlign(faa_2.tLN);
        faw_215.X(frz_211);
        frz_211.guy();
        frz_211.onChildrenAdded();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLO);
        faw_215.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        String string6 = "serverGroup";
        fry_1 fry_12 = new fry_1();
        fry_12.aVI();
        fry_12.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, (fhv_1)fry_12);
        }
        faw_215.X(fry_12);
        fry_12.guy();
        fry_12.onChildrenAdded();
        String string7 = "test";
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fdf_12);
        }
        fdf_12.setExpandable(false);
        fdf_12.setInnerExpandable(false);
        faw_215.X(fdf_12);
        fdf_12.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("content");
        fsj_29.setField("selectedCategory/groups");
        fsj_29.setName("serverChoiceView");
        fdf_12.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        this.u(fdf_12);
        fdf_12.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_211.onChildrenAdded();
        this.c(faw_210);
        faw_210.onChildrenAdded();
        this.H(faw_29);
        faw_29.onChildrenAdded();
        this.J(faw_22);
        this.O(faw_22);
        this.P(faw_22);
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 u(fdf_1 fdf_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fdf_12.X(fje_22);
        fje_22.guy();
        String string = "group";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        fcu_1 fcu_12 = new fcu_1();
        fcu_12.aVI();
        fcu_12.setElementMap(fhs_22);
        fcu_12.setExpandable(false);
        fcu_12.setGroupId("serverGroup");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.newServerChoice:selectGroup(group)");
        fcu_12.setOnClick(fmz_12);
        fje_22.X(fcu_12);
        fcu_12.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fcu_12.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, -20, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("name");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("style");
        fsd_14.setField("radioButtonStyle");
        fcu_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("prefSize");
        fsd_15.setField("radioButtonSize");
        fcu_12.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("selected");
        fsd_16.setField("isSelected");
        fcu_12.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fcu_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setExpandable(false);
        faw_22.setPrefSize(new fsm_1(6, 100.0f));
        faw_22.setStyle("tabSeparator");
        fje_22.X(faw_22);
        faw_22.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("visible");
        fsd_17.setField("displaySeparator");
        faw_22.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "groupScrollContainer";
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fcq_22);
        }
        fcq_22.setHorizontalScrollBarBehaviour(fzi_0.tHc);
        fcq_22.setPrefSize(new fsm_1(100.0f, 324));
        fcq_22.setStyle("defaultScrollContainer");
        fcq_22.setVerticalScrollBarBehaviour(fzi_0.tHb);
        faw_22.X(fcq_22);
        fcq_22.guy();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_22);
        fdf_12.setHideContainerWithoutItem(true);
        fdf_12.setHorizontal(false);
        fdf_12.setInnerExpandable(false);
        fdf_12.setPrefSize(new fsm_1(100.0f, 324));
        fdf_12.setSelectionable(false);
        fcq_22.X(fdf_12);
        fdf_12.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        frz_22.setVgap((short)8);
        fdf_12.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdf_1 fdf_13 = fdf_12;
        fza fza2 = (fza)((fes_2)fdf_13).getAppearance();
        fza2.setElementMap(fhs_22);
        fdf_12.X(fza2);
        fza2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 14, 0, 4));
        fza2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fza2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("selectedGroup");
        fsj_22.setName("serverChoiceView");
        fdf_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fdf_12.X(fje_22);
        fje_22.guy();
        String string2 = "serverGroup";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        fdf_1 fdf_14 = new fdf_1();
        fdf_14.aVI();
        fdf_14.setElementMap(fhs_22);
        fdf_14.setHorizontal(false);
        fje_22.X(fdf_14);
        fdf_14.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("visible");
        fsd_13.setField("isCollapsed");
        fdf_14.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsd_13.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_13.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(418, 100.0f));
        fdf_14.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        fdf_14.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("content");
        fsd_14.setField("servers");
        fdf_14.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        String string3 = "serverIR";
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, fje_23);
        }
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.newServerChoice:selectServer");
        fje_23.setOnItemClick(fmo_22);
        fmp_1 fmp_12 = new fmp_1();
        fmp_12.vw("wakfu.newServerChoice:enterServerDoubleClick");
        fje_23.setOnItemDoubleClick(fmp_12);
        fdf_14.X(fje_23);
        fje_23.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(444, 108));
        fje_23.X(faw_23);
        faw_23.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 8, 0, 8));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setStyle("listElementDefault");
        faw_23.X(faw_25);
        faw_25.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("style");
        fsd_15.setField("isSelected");
        faw_25.X(fsd_15);
        fsd_15.guy();
        fjk_1 fjk_12 = new fjk_1();
        fjk_12.aVI();
        fjk_12.setElementMap(fhs_22);
        fjk_12.setDefaultValue("listElementDefault");
        fsd_15.X(fjk_12);
        fjk_12.guy();
        fjp_2 fjp_22 = new fjp_2();
        fjp_22.aVI();
        fjp_22.setElementMap(fhs_22);
        fjp_22.setValue("listElementOver");
        fjk_12.X(fjp_22);
        fjp_22.guy();
        fjx_2 fjx_22 = new fjx_2();
        fjx_22.aVI();
        fjx_22.setElementMap(fhs_22);
        fjx_22.setValue("hover");
        fjx_22.setWidgetId("serverIR");
        fjp_22.X(fjx_22);
        fjx_22.guy();
        fjx_22.onChildrenAdded();
        fjp_22.onChildrenAdded();
        fjk_12.onChildrenAdded();
        fsd_15.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_03 = ((fes_2)faw_26).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_25.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(0, 16, 0, 16));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(444, 96));
        faw_25.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_25.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        faw_25.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("texture");
        fsd_16.setField("TileIllustrationUrl");
        fze2.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 1, 0));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setStyle("ornament2NEWhite");
        faw_25.X(faw_27);
        faw_27.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(428, 80));
        faw_27.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_28 = faw_27;
        fys_0 fys_04 = ((fes_2)faw_28).getAppearance();
        fys_04.setElementMap(fhs_22);
        fys_04.setMaxModulationColor(new fhl_2("black25"));
        fys_04.setModulationColor(new fhl_2("black25"));
        faw_27.X(fys_04);
        fys_04.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("modulationColor");
        fsd_17.setField("isSelected");
        fys_04.X(fsd_17);
        fsd_17.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fjt_23.setElseValue("black25");
        fjt_23.setValue("mainTextTitleColor@0.75");
        fsd_17.X(fjt_23);
        fjt_23.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_23.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_17.onChildrenAdded();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_22);
        fsd_18.setAttribute("maxModulationColor");
        fsd_18.setField("isSelected");
        fys_04.X(fsd_18);
        fsd_18.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fjt_24.setElseValue("black25");
        fjt_24.setValue("mainTextTitleColor@0.75");
        fsd_18.X(fjt_24);
        fjt_24.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_22);
        fjt_24.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_18.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_25.X(faw_29);
        faw_29.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        faw_29.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        frz_24.setHorizontal(false);
        frz_24.setVgap((short)8);
        faw_29.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipTitleLight21Bordered");
        faw_29.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_19 = new fsd_1();
        fsd_19.aVI();
        fsd_19.setElementMap(fhs_22);
        fsd_19.setAttribute("text");
        fsd_19.setField("name");
        fbv_22.X(fsd_19);
        fsd_19.guy();
        fsd_19.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_210.setExpandable(false);
        faw_29.X(faw_210);
        faw_210.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        frz_25.setHgap((short)4);
        faw_210.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_210.X(faw_211);
        faw_211.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLN);
        frz_26.setHgap((short)4);
        faw_211.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fsd_1 fsd_110 = new fsd_1();
        fsd_110.aVI();
        fsd_110.setElementMap(fhs_22);
        fsd_110.setAttribute("visible");
        fsd_110.setField("displayCharactersCount");
        faw_211.X(fsd_110);
        fsd_110.guy();
        fsd_110.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setExpandable(false);
        fbt_14.setStyle("iconGroupQuestFull");
        faw_211.X(fbt_14);
        fbt_14.guy();
        fbt_14.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("wipLight14Bordered");
        faw_211.X(fbv_23);
        fbv_23.guy();
        fbv_2 fbv_24 = fbv_23;
        fzq fzq2 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_23.X(fzq2);
        fzq2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_111 = new fsd_1();
        fsd_111.aVI();
        fsd_111.setElementMap(fhs_22);
        fsd_111.setAttribute("text");
        fsd_111.setField("charactersCountText");
        fbv_23.X(fsd_111);
        fsd_111.guy();
        fsd_111.onChildrenAdded();
        fbv_23.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_22);
        fbt_15.setExpandable(false);
        fbt_15.setStyle("dotSeparator");
        faw_211.X(fbt_15);
        fbt_15.guy();
        fsd_1 fsd_112 = new fsd_1();
        fsd_112.aVI();
        fsd_112.setElementMap(fhs_22);
        fsd_112.setAttribute("visible");
        fsd_112.setField("isSingleAccount");
        fbt_15.X(fsd_112);
        fsd_112.guy();
        fsd_112.onChildrenAdded();
        fbt_15.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setExpandable(false);
        faw_212.setStyle("labelItemRarityCommon");
        faw_210.X(faw_212);
        faw_212.guy();
        fsd_1 fsd_113 = new fsd_1();
        fsd_113.aVI();
        fsd_113.setElementMap(fhs_22);
        fsd_113.setAttribute("visible");
        fsd_113.setField("isSingleAccount");
        faw_212.X(fsd_113);
        fsd_113.guy();
        fsd_113.onChildrenAdded();
        faw_2 faw_213 = faw_212;
        fys_0 fys_05 = ((fes_2)faw_213).getAppearance();
        fys_05.setElementMap(fhs_22);
        faw_212.X(fys_05);
        fys_05.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_22);
        fzx4.setInsets(new Insets(2, 8, 4, 8));
        fys_05.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_05.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setStyle("wipLight12Bordered");
        String string4 = "%!server.singleAccount.label%";
        string4 = string4.replace("%!server.singleAccount.label%", fyw_0.gqw().k("server.singleAccount.label", new Object[0]).toUpperCase());
        fbv_25.setText(string4);
        faw_212.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_29.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_22);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(communityPopup)");
        fbt_16.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_16.setOnPopupHide(fml_12);
        faw_25.X(fbt_16);
        fbt_16.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setField("selectedCategory/hasGroups");
        fsj_23.setName("serverChoiceView");
        fbt_16.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fjt_25.setSwapValueAndElseValue(true);
        fsj_23.X(fjt_25);
        fjt_25.guy();
        this.c(fjt_25);
        fjt_25.onChildrenAdded();
        fsj_23.onChildrenAdded();
        this.a(fbt_16);
        this.n(fbt_16);
        this.r(fbt_16);
        fbt_16.onChildrenAdded();
        this.f(faw_25);
        faw_25.onChildrenAdded();
        this.g(faw_23);
        faw_23.onChildrenAdded();
        fje_23.onChildrenAdded();
        fdf_14.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        fcq_22.onChildrenAdded();
        return fcq_22;
    }

    public fhi_2 c(fjt_2 fjt_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        return fjl_12;
    }

    public fhi_2 a(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setXOffset(-4);
        frp_12.setYOffset(-24);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 n(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("style");
        fsd_12.setField("communityStyle");
        fbt_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        return fsd_12;
    }

    public fhi_2 r(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "communityPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("wipLight14");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("communityText");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(statusPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLo);
        frp_12.setXOffset(4);
        frp_12.setYOffset(12);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("style");
        fsd_12.setField("statusStyle");
        fbt_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        String string = "statusPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_23.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("statusText");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("selectorBorder");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(456, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("isSelected");
        faw_23.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 H(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 0, 4));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        faw_23.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("selectedCategory/hasGroups");
        fsj_22.setName("serverChoiceView");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_22);
        fdf_12.setExpandable(false);
        fdf_12.setHorizontal(false);
        faw_23.X(fdf_12);
        fdf_12.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        frz_22.setHorizontal(false);
        frz_22.setVgap((short)0);
        fdf_12.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLL);
        fdf_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("content");
        fsj_23.setField("selectedCategory/combinedGroupsServers");
        fsj_23.setName("serverChoiceView");
        fdf_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        String string = "serverIR";
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fje_22);
        }
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.newServerChoice:selectServer");
        fje_22.setOnItemClick(fmo_22);
        fmp_1 fmp_12 = new fmp_1();
        fmp_12.vw("wakfu.newServerChoice:enterServerDoubleClick");
        fje_22.setOnItemDoubleClick(fmp_12);
        fdf_12.X(fje_22);
        fje_22.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setPrefSize(new fsm_1(444, 108));
        fje_22.X(faw_25);
        faw_25.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_25.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_03 = ((fes_2)faw_26).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_25.X(fys_03);
        fys_03.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 8, 0, 8));
        fys_03.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setStyle("listElementDefault");
        faw_25.X(faw_27);
        faw_27.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("style");
        fsd_12.setField("isSelected");
        faw_27.X(fsd_12);
        fsd_12.guy();
        fjk_1 fjk_12 = new fjk_1();
        fjk_12.aVI();
        fjk_12.setElementMap(fhs_22);
        fjk_12.setDefaultValue("listElementDefault");
        fsd_12.X(fjk_12);
        fjk_12.guy();
        fjp_2 fjp_22 = new fjp_2();
        fjp_22.aVI();
        fjp_22.setElementMap(fhs_22);
        fjp_22.setValue("listElementOver");
        fjk_12.X(fjp_22);
        fjp_22.guy();
        fjx_2 fjx_22 = new fjx_2();
        fjx_22.aVI();
        fjx_22.setElementMap(fhs_22);
        fjx_22.setValue("hover");
        fjx_22.setWidgetId("serverIR");
        fjp_22.X(fjx_22);
        fjx_22.guy();
        fjx_22.onChildrenAdded();
        fjp_22.onChildrenAdded();
        fjk_12.onChildrenAdded();
        fsd_12.onChildrenAdded();
        faw_2 faw_28 = faw_27;
        fys_0 fys_04 = ((fes_2)faw_28).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_27.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(0, 16, 0, 16));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(444, 96));
        faw_27.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_27.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        faw_27.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("texture");
        fsd_13.setField("TileIllustrationUrl");
        fze2.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 1, 0));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setStyle("ornament2NEWhite");
        faw_27.X(faw_29);
        faw_29.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(428, 80));
        faw_29.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_210 = faw_29;
        fys_0 fys_05 = ((fes_2)faw_210).getAppearance();
        fys_05.setElementMap(fhs_22);
        fys_05.setMaxModulationColor(new fhl_2("black25"));
        fys_05.setModulationColor(new fhl_2("black25"));
        faw_29.X(fys_05);
        fys_05.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("modulationColor");
        fsd_14.setField("isSelected");
        fys_05.X(fsd_14);
        fsd_14.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fjt_23.setElseValue("black25");
        fjt_23.setValue("mainTextTitleColor@0.75");
        fsd_14.X(fjt_23);
        fjt_23.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_23.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_14.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("maxModulationColor");
        fsd_15.setField("isSelected");
        fys_05.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fjt_24.setElseValue("black25");
        fjt_24.setValue("mainTextTitleColor@0.75");
        fsd_15.X(fjt_24);
        fjt_24.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_22);
        fjt_24.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_15.onChildrenAdded();
        fys_05.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_27.X(faw_211);
        faw_211.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_211.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_211.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipTitleLight21Bordered");
        faw_211.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("name");
        fbv_22.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setExpandable(false);
        faw_211.X(faw_212);
        faw_212.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        frz_24.setHgap((short)4);
        faw_212.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_22);
        faw_213.setExpandable(false);
        faw_212.X(faw_213);
        faw_213.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        frz_25.setHgap((short)4);
        faw_213.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("visible");
        fsd_17.setField("displayCharactersCount");
        faw_213.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setExpandable(false);
        fbt_14.setStyle("iconGroupQuestFull");
        faw_213.X(fbt_14);
        fbt_14.guy();
        fbt_14.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("wipLight14Bordered");
        faw_213.X(fbv_23);
        fbv_23.guy();
        fbv_2 fbv_24 = fbv_23;
        fzq fzq2 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_23.X(fzq2);
        fzq2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_22);
        fsd_18.setAttribute("text");
        fsd_18.setField("charactersCountText");
        fbv_23.X(fsd_18);
        fsd_18.guy();
        fsd_18.onChildrenAdded();
        fbv_23.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_22);
        fbt_15.setExpandable(false);
        fbt_15.setStyle("dotSeparator");
        faw_213.X(fbt_15);
        fbt_15.guy();
        fsd_1 fsd_19 = new fsd_1();
        fsd_19.aVI();
        fsd_19.setElementMap(fhs_22);
        fsd_19.setAttribute("visible");
        fsd_19.setField("isSingleAccount");
        fbt_15.X(fsd_19);
        fsd_19.guy();
        fsd_19.onChildrenAdded();
        fbt_15.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_22);
        faw_214.setExpandable(false);
        faw_214.setStyle("labelItemRarityCommon");
        faw_212.X(faw_214);
        faw_214.guy();
        fsd_1 fsd_110 = new fsd_1();
        fsd_110.aVI();
        fsd_110.setElementMap(fhs_22);
        fsd_110.setAttribute("visible");
        fsd_110.setField("isSingleAccount");
        faw_214.X(fsd_110);
        fsd_110.guy();
        fsd_110.onChildrenAdded();
        faw_2 faw_215 = faw_214;
        fys_0 fys_06 = ((fes_2)faw_215).getAppearance();
        fys_06.setElementMap(fhs_22);
        faw_214.X(fys_06);
        fys_06.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_22);
        fzx4.setInsets(new Insets(2, 8, 4, 8));
        fys_06.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_06.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setStyle("wipLight12Bordered");
        String string2 = "%!server.singleAccount.label%";
        string2 = string2.replace("%!server.singleAccount.label%", fyw_0.gqw().k("server.singleAccount.label", new Object[0]).toUpperCase());
        fbv_25.setText(string2);
        faw_214.X(fbv_25);
        fbv_25.guy();
        fbv_25.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_211.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_22);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(communityPopup)");
        fbt_16.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_16.setOnPopupHide(fml_12);
        faw_27.X(fbt_16);
        fbt_16.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLc);
        frp_16.setXOffset(-4);
        frp_16.setYOffset(-24);
        fbt_16.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fsd_1 fsd_111 = new fsd_1();
        fsd_111.aVI();
        fsd_111.setElementMap(fhs_22);
        fsd_111.setAttribute("style");
        fsd_111.setField("communityStyle");
        fbt_16.X(fsd_111);
        fsd_111.guy();
        fsd_111.onChildrenAdded();
        String string3 = "communityPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_16.X(frx_12);
        frx_12.guy();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_22);
        faw_216.setPrefSize(new fsm_1(10, 0));
        faw_216.setStyle("popup");
        frx_12.X(faw_216);
        faw_216.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_216.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_22);
        fbv_26.setStyle("PopupInformation");
        faw_216.X(fbv_26);
        fbv_26.guy();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq3 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLN);
        fbv_26.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsd_1 fsd_112 = new fsd_1();
        fsd_112.aVI();
        fsd_112.setElementMap(fhs_22);
        fsd_112.setAttribute("text");
        fsd_112.setField("communityText");
        fbv_26.X(fsd_112);
        fsd_112.guy();
        fsd_112.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_216.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_16.onChildrenAdded();
        this.I(faw_27);
        faw_27.onChildrenAdded();
        this.h(faw_25);
        faw_25.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 I(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(statusPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLo);
        frp_12.setXOffset(4);
        frp_12.setYOffset(12);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("style");
        fsd_12.setField("statusStyle");
        fbt_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        String string = "statusPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_23.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("statusText");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 h(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("selectorBorder");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(456, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("isSelected");
        faw_23.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 J(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setXOffset(348);
        frp_12.setYOffset(-231);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_24.setPrefSize(new fsm_1(590, 399));
        faw_23.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_25.setVisible(false);
        faw_24.X(faw_25);
        faw_25.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_25.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("selectedServer");
        fsj_22.setName("serverChoiceView");
        faw_25.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLR);
        frz_22.setHorizontal(false);
        faw_25.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        String string = "selectedServer";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        faw_25.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("value");
        fsj_23.setField("selectedServer");
        fsj_23.setName("serverChoiceView");
        frv_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setPrefSize(new fsm_1(100.0f, 399));
        faw_25.X(faw_26);
        faw_26.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLR);
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_26.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        String string2 = "descriptionContainer";
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, faw_27);
        }
        faw_27.setExpandable(false);
        fme_1 fme_12 = new fme_1();
        fme_12.vw("wakfu.newServerChoice:enterDescriptionContainer(descriptionContainer)");
        faw_27.setOnMouseEnter(fme_12);
        fmf_2 fmf_22 = new fmf_2();
        fmf_22.vw("wakfu.newServerChoice:leaveDescriptionContainer(descriptionContainer)");
        faw_27.setOnMouseExit(fmf_22);
        faw_26.X(faw_27);
        faw_27.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(8, 8, 0, 8));
        faw_27.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLR);
        frz_24.setHorizontal(false);
        frz_24.setVgap((short)0);
        faw_27.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipTitleLight27Bordered");
        faw_27.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("selectedServer/name");
        fsj_24.setName("serverChoiceView");
        fbv_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_22);
        fcq_22.setMaxSize(new fsm_1(540, 139));
        fcq_22.setNonBlocking(false);
        fcq_22.setStyle("defaultScrollContainer");
        faw_27.X(fcq_22);
        fcq_22.guy();
        fcq_2 fcq_23 = fcq_22;
        fys_0 fys_02 = ((fes_2)fcq_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        fcq_22.X(fys_02);
        fys_02.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(8, 0, 0, 0));
        fys_02.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_02.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setMaxWidth(540);
        fbv_24.setMultiline(true);
        fbv_24.setStyle("wipLight16Bordered");
        fcq_22.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 8, 0));
        fzq3.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("visible");
        fsj_25.setField("selectedServer/description");
        fsj_25.setName("serverChoiceView");
        fbv_24.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_25.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjt_23.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("text");
        fsj_26.setField("selectedServer/description");
        fsj_26.setName("serverChoiceView");
        fbv_24.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fbv_24.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_26 = fbv_24;
        fzq fzq4 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlign(faa_2.tLO);
        fbv_24.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fcq_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_26.X(faw_28);
        faw_28.guy();
        frz_2 frz_25 = frz_2.checkOut();
        faw_28.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setExpandable(false);
        faw_29.setStyle("black25");
        faw_28.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_03 = ((fes_2)faw_210).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_29.X(fys_03);
        fys_03.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_22);
        fzx4.setInsets(new Insets(8, 8, 8, 8));
        fys_03.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_29.X(faw_211);
        faw_211.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHgap((short)4);
        faw_211.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLc);
        frp_14.setXOffset(-30);
        frp_14.setYOffset(-10);
        faw_211.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("visible");
        fsj_27.setField("selectedServer/displayCharactersCount");
        fsj_27.setName("serverChoiceView");
        faw_211.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        fbt_12.setStyle("iconGroupQuestFull");
        faw_211.X(fbt_12);
        fbt_12.guy();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_22);
        fbv_27.setExpandable(false);
        fbv_27.setStyle("wipLight14Bordered");
        faw_211.X(fbv_27);
        fbv_27.guy();
        fbv_2 fbv_28 = fbv_27;
        fzq fzq5 = (fzq)((fes_2)fbv_28).getAppearance();
        fzq5.setElementMap(fhs_22);
        fbv_27.X(fzq5);
        fzq5.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 2, 0));
        fzq5.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq5.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_22);
        fsj_28.setAttribute("text");
        fsj_28.setField("selectedServer/charactersCountText");
        fsj_28.setName("serverChoiceView");
        fbv_27.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fbv_27.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setExpandable(false);
        fbt_13.setStyle("dotSeparator");
        faw_211.X(fbt_13);
        fbt_13.guy();
        fbt_1 fbt_14 = fbt_13;
        fyY fyY2 = (fyY)((fes_2)fbt_14).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_13.X(fyY2);
        fyY2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 8, 0, 8));
        fyY2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_211.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_22);
        fbt_15.setExpandable(false);
        faw_29.X(fbt_15);
        fbt_15.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_22);
        fsj_29.setAttribute("style");
        fsj_29.setField("selectedServer/statusStyle");
        fsj_29.setName("serverChoiceView");
        fbt_15.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fbt_15.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_22);
        fbv_29.setExpandable(false);
        fbv_29.setStyle("wipLight14Bordered");
        faw_29.X(fbv_29);
        fbv_29.guy();
        fbv_2 fbv_210 = fbv_29;
        fzq fzq6 = (fzq)((fes_2)fbv_210).getAppearance();
        fzq6.setElementMap(fhs_22);
        fbv_29.X(fzq6);
        fzq6.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(0, 4, 2, 0));
        fzq6.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq6.onChildrenAdded();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_22);
        fsj_210.setAttribute("text");
        fsj_210.setField("selectedServer/statusText");
        fsj_210.setName("serverChoiceView");
        fbv_29.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fbv_29.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setExpandable(false);
        faw_26.X(faw_212);
        faw_212.guy();
        frz_2 frz_27 = frz_2.checkOut();
        faw_212.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_22);
        faw_213.setExpandable(false);
        faw_213.setStyle("black25");
        faw_212.X(faw_213);
        faw_213.guy();
        faw_2 faw_214 = faw_213;
        fys_0 fys_04 = ((fes_2)faw_214).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_213.X(fys_04);
        fys_04.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_22);
        fzx5.setInsets(new Insets(8, 8, 8, 8));
        fys_04.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setHgap((short)8);
        faw_213.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_22);
        faw_215.setExpandable(false);
        faw_213.X(faw_215);
        faw_215.guy();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_22);
        fsj_211.setAttribute("visible");
        fsj_211.setField("selectedServer/isSingleAccount");
        fsj_211.setName("serverChoiceView");
        faw_215.X(fsj_211);
        fsj_211.guy();
        fsj_211.onChildrenAdded();
        fbv_2 fbv_211 = new fbv_2();
        fbv_211.aVI();
        fbv_211.setElementMap(fhs_22);
        fbv_211.setExpandable(false);
        fbv_211.setStyle("wipLight14Bordered");
        String string3 = "%server.singleAccount.label%";
        string3 = string3.replace("%server.singleAccount.label%", fyw_0.gqw().k("server.singleAccount.label", new Object[0]));
        fbv_211.setText(string3);
        faw_215.X(fbv_211);
        fbv_211.guy();
        fbv_2 fbv_212 = fbv_211;
        fzq fzq7 = (fzq)((fes_2)fbv_212).getAppearance();
        fzq7.setElementMap(fhs_22);
        fbv_211.X(fzq7);
        fzq7.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_22);
        fzv6.setInsets(new Insets(0, 0, 2, 0));
        fzq7.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzq7.onChildrenAdded();
        fbv_211.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_22);
        fbt_16.setExpandable(false);
        fbt_16.setStyle("dotSeparator");
        faw_215.X(fbt_16);
        fbt_16.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("isSingleAccount");
        fbt_16.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbt_1 fbt_17 = fbt_16;
        fyY fyY3 = (fyY)((fes_2)fbt_17).getAppearance();
        fyY3.setElementMap(fhs_22);
        fbt_16.X(fyY3);
        fyY3.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_22);
        fzv7.setInsets(new Insets(0, 8, 0, 0));
        fyY3.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fyY3.onChildrenAdded();
        fbt_16.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_22);
        faw_216.setExpandable(false);
        faw_213.X(faw_216);
        faw_216.guy();
        frz_2 frz_29 = frz_2.checkOut();
        frz_29.setHgap((short)4);
        faw_216.X(frz_29);
        frz_29.guy();
        frz_29.onChildrenAdded();
        fbt_1 fbt_18 = new fbt_1();
        fbt_18.aVI();
        fbt_18.setElementMap(fhs_22);
        fbt_18.setExpandable(false);
        faw_216.X(fbt_18);
        fbt_18.guy();
        this.e(fbt_18);
        fbt_18.onChildrenAdded();
        this.i(faw_216);
        faw_216.onChildrenAdded();
        this.j(faw_213);
        this.L(faw_213);
        faw_213.onChildrenAdded();
        faw_212.onChildrenAdded();
        this.M(faw_26);
        this.N(faw_26);
        faw_26.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("style");
        fsj_22.setField("selectedServer/communityStyle");
        fsj_22.setName("serverChoiceView");
        fbt_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 i(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipLight14Bordered");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("selectedServer/communityText");
        fsj_22.setName("serverChoiceView");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 j(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        fbt_12.setStyle("dotSeparator");
        faw_22.X(fbt_12);
        fbt_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("selectedServer/populationStyle");
        fsj_22.setName("serverChoiceView");
        fbt_12.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 L(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("selectedServer/populationStyle");
        fsj_22.setName("serverChoiceView");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHgap((short)4);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        faw_23.X(fbt_12);
        fbt_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("style");
        fsj_23.setField("selectedServer/populationStyle");
        fsj_23.setName("serverChoiceView");
        fbt_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("wipLight14Bordered");
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 2, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("selectedServer/populationText");
        fsj_24.setName("serverChoiceView");
        fbv_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 M(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(12, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setNetEnabledId("serverSelectionLock");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.newServerChoice:enterServer(selectedServer)");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(290, 52));
        fad_12.setStyle("primaryLarge");
        String string = "%play%";
        string = string.replace("%play%", fyw_0.gqw().k("play", new Object[0]));
        fad_12.setText(string);
        faw_23.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("enabled");
        fsj_22.setField("selectedServer/isOnline");
        fsj_22.setName("serverChoiceView");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("selectedServer/playButtonText");
        fsj_23.setName("serverChoiceView");
        fad_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 N(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(268, 36));
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.newServerChoice:forceAccountOnServer(selectedServer)");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(268, 36));
        fad_12.setStyle("negativeMedium");
        String string = "%admin.account.force%";
        string = string.replace("%admin.account.force%", fyw_0.gqw().k("admin.account.force", new Object[0]));
        fad_12.setText(string);
        faw_23.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("selectedServer/canForceAccount");
        fsj_22.setName("serverChoiceView");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("enabled");
        fsj_23.setField("selectedServer/isOnline");
        fsj_23.setName("serverChoiceView");
        fad_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 O(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(484, 100.0f));
        faw_23.setVisible(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setXOffset(330);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("selectedServer");
        fsj_22.setName("serverChoiceView");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjt_22.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setMaxWidth(300);
        fbv_22.setMultiline(true);
        fbv_22.setStyle("wipLight30BoldBordered");
        String string = "%server.choice.no.selected.server%";
        string = string.replace("%server.choice.no.selected.server%", fyw_0.gqw().k("server.choice.no.selected.server", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 P(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(false);
        faw_23.setPrefSize(new fsm_1(56, 56));
        faw_23.setStyle("windowBackgroundSecondary");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(64, 0, 0, 64));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu:openMenuDialog");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descOpenMenuPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setPrefSize(new fsm_1(36, 36));
        fad_12.setStyle("cogTertiary");
        faw_23.X(fad_12);
        fad_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fad_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        String string = "descOpenMenuPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setPrefSize(new fsm_1(10, 0));
        faw_25.setStyle("popup");
        frx_12.X(faw_25);
        faw_25.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_25.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        String string2 = "%menu%";
        string2 = string2.replace("%menu%", fyw_0.gqw().k("menu", new Object[0]));
        fbv_22.setText(string2);
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        frx_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }
}

