/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cMv
 */
public class cmv_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setNonBlocking(false);
        faw_22.setPrefSize(new fsm_1(360, 27));
        faw_22.setStyle("windowBackgroundSmallRepeated");
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(8, 0, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setStyle("wipTitleLight18");
        String string = "%menu%";
        string = string.replace("%menu%", fyw_0.gqw().k("menu", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLm);
        fbv_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_23.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("wipLight12");
        faw_23.X(fbv_24);
        fbv_24.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLo);
        fbv_24.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setName("buildVersion");
        fbv_24.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 15));
        fzq3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_2 fbv_26 = fbv_24;
        fzq fzq4 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLR);
        fbv_24.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setExpandable(true);
        faw_22.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_03 = ((fes_2)faw_26).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_25.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(10, 10, 10, 10));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_25.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        frz_23.setVgap((short)8);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.menu:openOptionsDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(308, 36));
        fad_12.setStyle("secondaryMedium");
        String string2 = "%options%";
        string2 = string2.replace("%options%", fyw_0.gqw().k("options", new Object[0]));
        fad_12.setText(string2);
        faw_25.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_23);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu:checkAntiAddictionAccount");
        fad_13.setOnClick(fmz_13);
        fad_13.setPrefSize(new fsm_1(308, 36));
        fad_13.setStyle("secondaryMedium");
        String string3 = "%antiAddictionAccountCheck%";
        string3 = string3.replace("%antiAddictionAccountCheck%", fyw_0.gqw().k("antiAddictionAccountCheck", new Object[0]));
        fad_13.setText(string3);
        faw_25.X(fad_13);
        fad_13.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("visible");
        fsj_23.setName("antiAddictionEnabled");
        fad_13.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjt_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fad_13.onChildrenAdded();
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_23);
        fad_14.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.menu:goToWorldChoiceDialog");
        fad_14.setOnClick(fmz_14);
        fad_14.setPrefSize(new fsm_1(308, 36));
        fad_14.setStyle("secondaryMedium");
        String string4 = "%changeCharacter%";
        string4 = string4.replace("%changeCharacter%", fyw_0.gqw().k("changeCharacter", new Object[0]));
        fad_14.setText(string4);
        faw_25.X(fad_14);
        fad_14.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("visible");
        fsj_24.setName("isInGame");
        fad_14.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsj_24.X(fjt_23);
        fjt_23.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_23);
        fjt_23.X(fjn_22);
        fjn_22.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_23);
        fjn_22.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjn_22.X(fjw_22);
        fjw_22.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("comparedValue");
        fsj_25.setField("character.change.disabled");
        fsj_25.setName("systemConfiguration");
        fjw_22.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fjw_22.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fad_14.onChildrenAdded();
        fad_1 fad_15 = new fad_1();
        fad_15.aVI();
        fad_15.setElementMap(fhs_23);
        fad_15.setExpandable(false);
        fmz_1 fmz_15 = new fmz_1();
        fmz_15.vw("wakfu.menu:contactModerator");
        fad_15.setOnClick(fmz_15);
        fad_15.setPrefSize(new fsm_1(308, 36));
        fad_15.setStyle("secondaryMedium");
        String string5 = "%contactModerator%";
        string5 = string5.replace("%contactModerator%", fyw_0.gqw().k("contactModerator", new Object[0]));
        fad_15.setText(string5);
        faw_25.X(fad_15);
        fad_15.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("enabled");
        fsj_26.setName("hasModeratorChatRequest");
        fad_15.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("visible");
        fsj_27.setName("isInGame");
        fad_15.X(fsj_27);
        fsj_27.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fsj_27.X(fjt_24);
        fjt_24.guy();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_23);
        fjt_24.X(fjn_23);
        fjn_23.guy();
        fjl_1 fjl_14 = new fjl_1();
        fjl_14.aVI();
        fjl_14.setElementMap(fhs_23);
        fjn_23.X(fjl_14);
        fjl_14.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("comparedValue");
        fsj_28.setField("contactModerator.enable");
        fsj_28.setName("systemConfiguration");
        fjl_14.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fjl_14.onChildrenAdded();
        fjl_1 fjl_15 = new fjl_1();
        fjl_15.aVI();
        fjl_15.setElementMap(fhs_23);
        fjn_23.X(fjl_15);
        fjl_15.guy();
        fjl_15.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_27.onChildrenAdded();
        fad_15.onChildrenAdded();
        fad_1 fad_16 = new fad_1();
        fad_16.aVI();
        fad_16.setElementMap(fhs_23);
        fad_16.setExpandable(false);
        fmz_1 fmz_16 = new fmz_1();
        fmz_16.vw("wakfu.menu:goBackToServerSelection");
        fad_16.setOnClick(fmz_16);
        fad_16.setPrefSize(new fsm_1(308, 36));
        fad_16.setStyle("secondaryMedium");
        String string6 = "%change.server%";
        string6 = string6.replace("%change.server%", fyw_0.gqw().k("change.server", new Object[0]));
        fad_16.setText(string6);
        faw_25.X(fad_16);
        fad_16.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("visible");
        fsj_29.setName("isConnected");
        fad_16.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fad_16.onChildrenAdded();
        fad_1 fad_17 = new fad_1();
        fad_17.aVI();
        fad_17.setElementMap(fhs_23);
        fad_17.setExpandable(false);
        fmz_1 fmz_17 = new fmz_1();
        fmz_17.vw("wakfu.menu:loggoff");
        fad_17.setOnClick(fmz_17);
        fad_17.setPrefSize(new fsm_1(308, 36));
        fad_17.setStyle("secondaryMedium");
        String string7 = "%disconnect%";
        string7 = string7.replace("%disconnect%", fyw_0.gqw().k("disconnect", new Object[0]));
        fad_17.setText(string7);
        fad_17.setVisible(false);
        faw_25.X(fad_17);
        fad_17.guy();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("visible");
        fsj_210.setName("displayDisconnectButton");
        fad_17.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fad_17.onChildrenAdded();
        fad_1 fad_18 = new fad_1();
        fad_18.aVI();
        fad_18.setElementMap(fhs_23);
        fad_18.setExpandable(false);
        fmz_1 fmz_18 = new fmz_1();
        fmz_18.vw("wakfu:openReportBugDialog");
        fad_18.setOnClick(fmz_18);
        fad_18.setPrefSize(new fsm_1(308, 36));
        fad_18.setStyle("secondaryMedium");
        String string8 = "%desc.bugReport%";
        string8 = string8.replace("%desc.bugReport%", fyw_0.gqw().k("desc.bugReport", new Object[0]));
        fad_18.setText(string8);
        faw_25.X(fad_18);
        fad_18.guy();
        fad_18.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(100.0f, 0));
        faw_25.X(faw_27);
        faw_27.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_27.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_28 = faw_27;
        fys_0 fys_04 = ((fes_2)faw_28).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_27.X(fys_04);
        fys_04.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(4, 0, 4, 0));
        fys_04.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_27.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_05 = ((fes_2)faw_210).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_29.X(fys_05);
        fys_05.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_23);
        fkm_12.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.15f));
        fkm_12.setInsets(new Insets(2, 0, 0, 0));
        fys_05.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fys_05.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_27.X(faw_211);
        faw_211.guy();
        faw_2 faw_212 = faw_211;
        fys_0 fys_06 = ((fes_2)faw_212).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_211.X(fys_06);
        fys_06.guy();
        fkm_1 fkm_13 = new fkm_1();
        fkm_13.aVI();
        fkm_13.setElementMap(fhs_23);
        fkm_13.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.05f));
        fkm_13.setInsets(new Insets(0, 0, 2, 0));
        fys_06.X(fkm_13);
        fkm_13.guy();
        fkm_13.onChildrenAdded();
        fys_06.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_27.onChildrenAdded();
        fad_1 fad_19 = new fad_1();
        fad_19.aVI();
        fad_19.setElementMap(fhs_23);
        fad_19.setExpandable(false);
        fmz_1 fmz_19 = new fmz_1();
        fmz_19.vw("wakfu:quit");
        fad_19.setOnClick(fmz_19);
        fad_19.setPrefSize(new fsm_1(308, 36));
        fad_19.setStyle("secondaryMedium");
        String string9 = "%quit%";
        string9 = string9.replace("%quit%", fyw_0.gqw().k("quit", new Object[0]));
        fad_19.setText(string9);
        faw_25.X(fad_19);
        fad_19.guy();
        fad_19.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setExpandable(false);
        faw_213.setPrefSize(new fsm_1(100.0f, 0));
        faw_25.X(faw_213);
        faw_213.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_213.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_214 = faw_213;
        fys_0 fys_07 = ((fes_2)faw_214).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_213.X(fys_07);
        fys_07.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(4, 0, 4, 0));
        fys_07.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_07.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_213.X(faw_215);
        faw_215.guy();
        faw_2 faw_216 = faw_215;
        fys_0 fys_08 = ((fes_2)faw_216).getAppearance();
        fys_08.setElementMap(fhs_23);
        faw_215.X(fys_08);
        fys_08.guy();
        fkm_1 fkm_14 = new fkm_1();
        fkm_14.aVI();
        fkm_14.setElementMap(fhs_23);
        fkm_14.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.15f));
        fkm_14.setInsets(new Insets(2, 0, 0, 0));
        fys_08.X(fkm_14);
        fkm_14.guy();
        fkm_14.onChildrenAdded();
        fys_08.onChildrenAdded();
        faw_215.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_213.X(faw_217);
        faw_217.guy();
        faw_2 faw_218 = faw_217;
        fys_0 fys_09 = ((fes_2)faw_218).getAppearance();
        fys_09.setElementMap(fhs_23);
        faw_217.X(fys_09);
        fys_09.guy();
        fkm_1 fkm_15 = new fkm_1();
        fkm_15.aVI();
        fkm_15.setElementMap(fhs_23);
        fkm_15.setColor(new awx_2(1.0f, 1.0f, 1.0f, 0.05f));
        fkm_15.setInsets(new Insets(0, 0, 2, 0));
        fys_09.X(fkm_15);
        fkm_15.guy();
        fkm_15.onChildrenAdded();
        fys_09.onChildrenAdded();
        faw_217.onChildrenAdded();
        faw_213.onChildrenAdded();
        this.R(faw_25);
        faw_25.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.menu:closeMenuDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setPrefSize(new fsm_1(308, 36));
        fad_12.setStyle("primaryMedium");
        String string = "%backToGame%";
        string = string.replace("%backToGame%", fyw_0.gqw().k("backToGame", new Object[0]));
        fad_12.setText(string);
        faw_22.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        return fad_12;
    }
}

