/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNd
 */
public class cnd_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        feq_1 feq_12 = new feq_1();
        feq_12.aVI();
        feq_12.setElementMap(fhs_23);
        feq_12.setAlign(faa_2.tLL);
        feq_12.setPrefSize(new fsm_1(256, 220));
        feq_12.setYOffset(20);
        feq_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(-2, -2));
        feq_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        feq_12.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setNonBlocking(true);
        feq_12.X(faw_22);
        faw_22.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("visible");
        fsj_22.setField("pvpRankEnabled");
        fsj_22.setName("overHead");
        faw_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(128, 256));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        faw_22.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("texture");
        fsj_23.setField("pvpRankIconUrl");
        fsj_23.setName("overHead");
        fze2.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        fde_12.setNonBlocking(true);
        faw_22.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setDisplaySize(new fsm_1(128, 256));
        fbt_13.setExpandable(false);
        fbt_13.setNonBlocking(true);
        faw_22.X(fbt_13);
        fbt_13.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setFlipHorizontaly(true);
        fbt_13.X(fze3);
        fze3.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("texture");
        fsj_24.setField("pvpRankIconUrl");
        fsj_24.setName("overHead");
        fze3.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fze3.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setPrefSize(new fsm_1(100, 15));
        faw_23.setStyle("greyBackgrounded");
        feq_12.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        fys_02.setModulationColor(new awx_2(0.2f, 0.2f, 0.2f, 0.85f));
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(3, 3, 3, 3));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 65, 0, 65));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLa);
        frp_14.setSize(new fsm_1(-2, -2));
        frp_14.setYOffset(-160);
        faw_23.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_23.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_25.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_25.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setEnableShrinking(false);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(300);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("DefaultWhite");
        faw_25.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        fdy_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("title");
        fsj_25.setName("overHead");
        fdy_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("visible");
        fsj_26.setField("title");
        fsj_26.setName("overHead");
        fdy_12.X(fsj_26);
        fsj_26.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_26.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_26.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        fdf_12.setHorizontal(false);
        fdf_12.setNonBlocking(true);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu:transferClickEventToWorldInteractionFrame");
        fdf_12.setOnClick(fmz_12);
        fdf_12.setSelectionable(false);
        faw_25.X(fdf_12);
        fdf_12.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        fdf_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fdf_1 fdf_13 = fdf_12;
        fza fza2 = (fza)((fes_2)fdf_13).getAppearance();
        fza2.setElementMap(fhs_23);
        fdf_12.X(fza2);
        fza2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 3));
        fza2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fza2.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("content");
        fsj_27.setField("overHeadInfos");
        fsj_27.setName("overHead");
        fdf_12.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("visible");
        fsj_28.setField("overHeadInfos");
        fsj_28.setName("overHead");
        fdf_12.X(fsj_28);
        fsj_28.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsj_28.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_23);
        fjt_23.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_28.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fdf_12.X(fje_22);
        fje_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fje_22.X(fjx_12);
        fjx_12.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fjx_12.X(fjt_24);
        fjt_24.guy();
        fjd_1 fjd_14 = new fjd_1();
        fjd_14.aVI();
        fjd_14.setElementMap(fhs_23);
        fjt_24.X(fjd_14);
        fjd_14.guy();
        fjd_14.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fjx_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        fje_22.X(faw_26);
        faw_26.guy();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setDisplaySize(new fsm_1(32, 32));
        fbt_14.setExpandable(false);
        fbt_14.setNonBlocking(true);
        faw_26.X(fbt_14);
        fbt_14.guy();
        fbt_1 fbt_15 = fbt_14;
        fyY fyY2 = (fyY)((fes_2)fbt_15).getAppearance();
        fyY2.setElementMap(fhs_23);
        fbt_14.X(fyY2);
        fyY2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 3));
        fyY2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyY2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("visible");
        fsd_12.setField("iconUrl");
        fbt_14.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_23);
        fsd_12.X(fjt_25);
        fjt_25.guy();
        fjd_1 fjd_15 = new fjd_1();
        fjd_15.aVI();
        fjd_15.setElementMap(fhs_23);
        fjt_25.X(fjd_15);
        fjd_15.guy();
        fjd_15.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsd_12.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        fbt_14.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fbt_14.X(fze4);
        fze4.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("texture");
        fsd_13.setField("iconUrl");
        fze4.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze4.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_23);
        fdy_13.setEnableShrinking(false);
        fdy_13.setMaxWidth(300);
        fdy_13.setMinWidth(50);
        fdy_13.setNonBlocking(true);
        fdy_13.setStyle("DefaultWhite");
        faw_26.X(fdy_13);
        fdy_13.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLO);
        fdy_13.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq2 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fdy_13.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("text");
        fsd_14.setField("text");
        fdy_13.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fdy_13.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        fje_22.X(faw_27);
        faw_27.guy();
        fdf_1 fdf_14 = new fdf_1();
        fdf_14.aVI();
        fdf_14.setElementMap(fhs_23);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu:transferClickEventToWorldInteractionFrame");
        fdf_14.setOnClick(fmz_13);
        faw_27.X(fdf_14);
        fdf_14.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("visible");
        fsd_15.setField("overIconsUrl");
        fdf_14.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_23);
        fsd_15.X(fjt_26);
        fjt_26.guy();
        fjd_1 fjd_16 = new fjd_1();
        fjd_16.aVI();
        fjd_16.setElementMap(fhs_23);
        fjt_26.X(fjd_16);
        fjd_16.guy();
        fjd_16.onChildrenAdded();
        fjt_26.onChildrenAdded();
        fsd_15.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("content");
        fsd_16.setField("overIconsUrl");
        fdf_14.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fdf_14.X(fje_23);
        fje_23.guy();
        fjx_1 fjx_13 = new fjx_1();
        fjx_13.aVI();
        fjx_13.setElementMap(fhs_23);
        fje_23.X(fjx_13);
        fjx_13.guy();
        fjt_2 fjt_27 = new fjt_2();
        fjt_27.aVI();
        fjt_27.setElementMap(fhs_23);
        fjx_13.X(fjt_27);
        fjt_27.guy();
        fjd_1 fjd_17 = new fjd_1();
        fjd_17.aVI();
        fjd_17.setElementMap(fhs_23);
        fjt_27.X(fjd_17);
        fjd_17.guy();
        fjd_17.onChildrenAdded();
        fjt_27.onChildrenAdded();
        fjx_13.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_23);
        fbt_16.setDisplaySize(new fsm_1(32, 32));
        fbt_16.setExpandable(false);
        fbt_16.setNonBlocking(true);
        fje_23.X(fbt_16);
        fbt_16.guy();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fbt_16.X(fze5);
        fze5.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_23);
        fsd_17.setAttribute("texture");
        fze5.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        fze5.onChildrenAdded();
        fbt_16.onChildrenAdded();
        fje_23.onChildrenAdded();
        fdf_14.onChildrenAdded();
        faw_27.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_28.setNonBlocking(true);
        faw_23.X(faw_28);
        faw_28.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLc);
        faw_28.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("visible");
        fsj_29.setField("breedIconUrl");
        fsj_29.setName("overHead");
        faw_28.X(fsj_29);
        fsj_29.guy();
        fjt_2 fjt_28 = new fjt_2();
        fjt_28.aVI();
        fjt_28.setElementMap(fhs_23);
        fsj_29.X(fjt_28);
        fjt_28.guy();
        fjd_1 fjd_18 = new fjd_1();
        fjd_18.aVI();
        fjd_18.setElementMap(fhs_23);
        fjt_28.X(fjd_18);
        fjd_18.guy();
        fjd_18.onChildrenAdded();
        fjt_28.onChildrenAdded();
        fsj_29.onChildrenAdded();
        this.R(faw_28);
        this.c(faw_28);
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        feq_12.onChildrenAdded();
        return feq_12;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        return null;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setXOffset(-7);
        frp_12.setYOffset(-1);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("modulationColor");
        fsj_22.setField("breedIconColor");
        fsj_22.setName("overHead");
        fyY2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fyY2.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("texture");
        fsj_23.setField("breedIconUrl");
        fsj_23.setName("overHead");
        fze2.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }
}

