/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNf
 */
public class cnf_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setNonBlocking(true);
        fey_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.setNonBlocking(false);
        faw_22.setPrefSize(new fsm_1(662, 450));
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setAlign(fzw_0.tLa);
        frp_13.setSize(new fsm_1(-2, -2));
        faw_22.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_22.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_22.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 0, 80, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("PassportLeft2");
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLf);
        frp_14.setSize(new fsm_1(331, 450));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("PassportRight");
        faw_22.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLh);
        frp_15.setSize(new fsm_1(331, 450));
        fbt_13.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_23);
        faw_22.X(faw_24);
        faw_24.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("visible");
        fsj_22.setName("passportCategory");
        faw_24.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_23);
        fjv_12.setValue("0");
        fjt_22.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        faw_24.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_24.X(faw_25);
        faw_25.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLf);
        frp_17.setSize(new fsm_1(50.0f, 100.0f));
        faw_25.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        faw_25.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setNonBlocking(true);
        fbt_14.setStyle("scrollIcon");
        faw_25.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLc);
        frp_18.setSize(new fsm_1(-2, -2));
        frp_18.setXOffset(-10);
        frp_18.setYOffset(-45);
        fbt_14.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_23);
        faw_25.X(fbt_15);
        fbt_15.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setAlign(fzw_0.tKY);
        frp_19.setSize(new fsm_1(107, 99));
        frp_19.setXOffset(40);
        frp_19.setYOffset(-155);
        fbt_15.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("visible");
        fsj_23.setField("hasNation");
        fsj_23.setName("localPlayer");
        fbt_15.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbt_1 fbt_16 = fbt_15;
        fyY fyY2 = (fyY)((fes_2)fbt_16).getAppearance();
        fyY2.setElementMap(fhs_23);
        fbt_15.X(fyY2);
        fyY2.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fyY2.X(fze2);
        fze2.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("texture");
        fsj_24.setField("nation/passportStampIconUrl");
        fsj_24.setName("localPlayer");
        fze2.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fze2.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_15.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setStyle("titleNameBold");
        faw_25.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_23);
        frp_110.setAlign(fzw_0.tLc);
        frp_110.setSize(new fsm_1(190, 30));
        frp_110.setXOffset(-10);
        frp_110.setYOffset(-58);
        fbv_22.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("name");
        fsj_25.setName("localPlayer");
        fbv_22.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("passportTitleColor"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_25.X(faw_26);
        faw_26.guy();
        frp_1 frp_111 = new frp_1();
        frp_111.aVI();
        frp_111.setElementMap(fhs_23);
        frp_111.setAlign(fzw_0.tLc);
        frp_111.setSize(new fsm_1(180, -2));
        frp_111.setXOffset(-40);
        frp_111.setYOffset(-90);
        faw_26.X(frp_111);
        frp_111.guy();
        frp_111.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setMaxLines(3);
        fbv_24.setMaxWidth(135);
        fbv_24.setMultiline(true);
        fbv_24.setNonBlocking(true);
        fbv_24.setPrefSize(new fsm_1(135, 0));
        fbv_24.setStyle("blueBold11");
        faw_26.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 0));
        fzq3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("text");
        fsj_26.setField("currentTitle");
        fsj_26.setName("localPlayer");
        fbv_24.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("modulationColor");
        fsj_27.setField("currentTitleRarityColor");
        fsj_27.setName("localPlayer");
        fbv_24.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_26.onChildrenAdded();
        fbt_1 fbt_17 = new fbt_1();
        fbt_17.aVI();
        fbt_17.setElementMap(fhs_23);
        fbt_17.setStyle("portrait");
        faw_25.X(fbt_17);
        fbt_17.guy();
        frp_1 frp_112 = new frp_1();
        frp_112.aVI();
        frp_112.setElementMap(fhs_23);
        frp_112.setAlign(fzw_0.tKY);
        frp_112.setSize(new fsm_1(-2, -2));
        frp_112.setXOffset(48);
        frp_112.setYOffset(-45);
        fbt_17.X(frp_112);
        frp_112.guy();
        frp_112.onChildrenAdded();
        fbt_17.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setNeedsScissor(true);
        faw_25.X(faw_27);
        faw_27.guy();
        frp_1 frp_113 = new frp_1();
        frp_113.aVI();
        frp_113.setElementMap(fhs_23);
        frp_113.setAlign(fzw_0.tKY);
        frp_113.setSize(new fsm_1(65, 80));
        frp_113.setXOffset(58);
        frp_113.setYOffset(-55);
        faw_27.X(frp_113);
        frp_113.guy();
        frp_113.onChildrenAdded();
        String string = "localPlayerDisplay";
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fax_12);
        }
        fax_12.setAnimName("AnimStatique-UI");
        fax_12.setDirection(2);
        fax_12.setOffsetX(-15.0f);
        fax_12.setOffsetY(-120.0f);
        fax_12.setPrefSize(new fsm_1(100, 0));
        fax_12.setScale(2.2f);
        faw_27.X(fax_12);
        fax_12.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("animatedElement");
        fsj_28.setField("actorDescriptorLibrary");
        fsj_28.setName("localPlayer");
        fax_12.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("equipment");
        fsj_29.setField("actorEquipment");
        fsj_29.setName("localPlayer");
        fax_12.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_25.X(faw_28);
        faw_28.guy();
        frp_1 frp_114 = new frp_1();
        frp_114.aVI();
        frp_114.setElementMap(fhs_23);
        frp_114.setAlign(fzw_0.tLa);
        frp_114.setSize(new fsm_1(100.0f, 120));
        frp_114.setYOffset(-155);
        faw_28.X(frp_114);
        frp_114.guy();
        frp_114.onChildrenAdded();
        faw_2 faw_29 = faw_28;
        fys_0 fys_03 = ((fes_2)faw_29).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_28.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 145, 0, 10));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_28.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_28.X(faw_210);
        faw_210.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setStyle("StyledBoldDark12");
        faw_210.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq4 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq4.setElementMap(fhs_23);
        fdy_12.X(fzq4);
        fzq4.guy();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("textColor");
        fsj_210.setField("nation/nationColor");
        fsj_210.setName("localPlayer");
        fzq4.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 0, 2, 0));
        fzq4.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_23);
        fsj_211.setAttribute("text");
        fsj_211.setField("nation/nationName");
        fsj_211.setName("localPlayer");
        fdy_12.X(fsj_211);
        fsj_211.guy();
        fsj_211.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fbt_1 fbt_18 = new fbt_1();
        fbt_18.aVI();
        fbt_18.setElementMap(fhs_23);
        fbt_18.setExpandable(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descNationChangePopup)");
        fbt_18.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_18.setOnPopupHide(fml_12);
        fbt_18.setStyle("questionMark");
        faw_210.X(fbt_18);
        fbt_18.guy();
        String string2 = "descNationChangePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fbt_18.X(frx_12);
        frx_12.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setPrefSize(new fsm_1(10, 0));
        faw_211.setStyle("popup");
        frx_12.X(faw_211);
        faw_211.guy();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        fdy_14.setMaxWidth(250);
        fdy_14.setStyle("white");
        String string3 = "%passport.ChangeTooltip%";
        string3 = string3.replace("%passport.ChangeTooltip%", fyw_0.gqw().k("passport.ChangeTooltip", new Object[0]));
        fdy_14.setText(string3);
        faw_211.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq5 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlignment(faa_2.tLN);
        fdy_14.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_211.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_1 fbt_19 = fbt_18;
        fyY fyY3 = (fyY)((fes_2)fbt_19).getAppearance();
        fyY3.setElementMap(fhs_23);
        fbt_18.X(fyY3);
        fyY3.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 0, 0, 10));
        fyY3.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fyY3.onChildrenAdded();
        fbt_18.onChildrenAdded();
        faw_210.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setExpandable(false);
        fbv_26.setStyle("smallTitle");
        String string4 = "%nation.rank%";
        string4 = string4.replace("%nation.rank%", fyw_0.gqw().k("nation.rank", new Object[0]));
        fbv_26.setText(string4);
        faw_28.X(fbv_26);
        fbv_26.guy();
        fbv_26.onChildrenAdded();
        this.R(faw_28);
        this.c(faw_28);
        faw_28.onChildrenAdded();
        this.d(faw_25);
        this.e(faw_25);
        faw_25.onChildrenAdded();
        this.F(faw_24);
        faw_24.onChildrenAdded();
        this.G(faw_22);
        this.f(faw_22);
        this.J(faw_22);
        faw_22.onChildrenAdded();
        this.v(fey_22);
        this.F(fey_22);
        this.G(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(180, 4));
        fbt_12.setExpandable(false);
        fbt_12.setStyle("TiledScrollBottom");
        faw_22.X(fbt_12);
        fbt_12.guy();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("StyledBold12");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("nation/nationRankDescription");
        fsj_22.setName("localPlayer");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tKY);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(100);
        frp_12.setYOffset(-120);
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("style");
        fsj_22.setField("nation/isPassportActive");
        fsj_22.setName("localPlayer");
        fbt_12.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fjt_22.setElseValue("passportInvalid");
        fjt_22.setValue("passportValid");
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(100.0f, 140));
        frp_12.setYOffset(-255);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 50, 0, 10));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("smallTitle");
        String string = "%citizen.score%";
        string = string.replace("%citizen.score%", fyw_0.gqw().k("citizen.score", new Object[0]));
        fbv_22.setText(string);
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("StyledBold12");
        faw_25.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("textColor");
        fsj_22.setField("nation/nationColor");
        fsj_22.setName("localPlayer");
        fzq2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setField("nation/nativeNationCitizenScore");
        fsj_23.setName("localPlayer");
        fdy_12.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("nation/nativeNationCitizenScore/score");
        fsj_24.setName("localPlayer");
        fdy_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_25.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descCitizenPointsPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        fbt_12.setStyle("questionMark");
        faw_25.X(fbt_12);
        fbt_12.guy();
        String string2 = "descCitizenPointsPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setPrefSize(new fsm_1(10, 0));
        faw_26.setStyle("popup");
        frx_12.X(faw_26);
        faw_26.guy();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setMaxWidth(250);
        fdy_14.setStyle("white");
        String string3 = "%nation.citizenship.points.explaination%";
        string3 = string3.replace("%nation.citizenship.points.explaination%", fyw_0.gqw().k("nation.citizenship.points.explaination", new Object[0]));
        fdy_14.setText(string3);
        faw_26.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlignment(faa_2.tLN);
        fdy_14.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_26.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 0, 10));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_25.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setDisplaySize(new fsm_1(280, 4));
        fbt_14.setExpandable(false);
        fbt_14.setStyle("TiledScrollBottom");
        faw_23.X(fbt_14);
        fbt_14.guy();
        fbt_14.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setExpandable(false);
        faw_23.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_27.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(5, 0, 0, 0));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_27.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setExpandable(false);
        fbv_23.setStyle("smallTitle");
        String string4 = "%citizen.status%";
        string4 = string4.replace("%citizen.status%", fyw_0.gqw().k("citizen.status", new Object[0]));
        fbv_23.setText(string4);
        faw_27.X(fbv_23);
        fbv_23.guy();
        fbv_23.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        fdy_16.setStyle("StyledBold12");
        faw_27.X(fdy_16);
        fdy_16.guy();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq4 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq4.setElementMap(fhs_22);
        fdy_16.X(fzq4);
        fzq4.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("textColor");
        fsj_25.setField("nation/nationColor");
        fsj_25.setName("localPlayer");
        fzq4.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("visible");
        fsj_26.setField("nation/nativeNationCitizenScore");
        fsj_26.setName("localPlayer");
        fdy_16.X(fsj_26);
        fsj_26.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_26.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjt_23.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_26.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("text");
        fsj_27.setField("nation/nativeNationCitizenScore/rankDescription");
        fsj_27.setName("localPlayer");
        fdy_16.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_27.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_22);
        fbt_15.setDisplaySize(new fsm_1(280, 4));
        fbt_15.setExpandable(false);
        fbt_15.setStyle("TiledScrollBottom");
        faw_23.X(fbt_15);
        fbt_15.guy();
        fbt_15.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(100.0f, 14));
        fbz_22.setHorizontal(false);
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMaxRows(8);
        fbz_22.setIdealSizeMinColumns(1);
        fbz_22.setIdealSizeMinRows(1);
        faw_23.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        fje_22.X(faw_29);
        faw_29.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_29.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fdy_1 fdy_18 = new fdy_1();
        fdy_18.aVI();
        fdy_18.setElementMap(fhs_22);
        fdy_18.setStyle("StyledBold12");
        faw_29.X(fdy_18);
        fdy_18.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fdy_18.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_18.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_22);
        fbt_16.setDisplaySize(new fsm_1(280, 1));
        fbt_16.setExpandable(false);
        fbt_16.setStyle("TiledScrollBottom");
        faw_29.X(fbt_16);
        fbt_16.guy();
        fbt_16.onChildrenAdded();
        faw_29.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setSize(new fsm_1(50.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(63, 10, 25, 35));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setVisible(false);
        faw_22.X(faw_23);
        faw_23.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("passportCategory");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjv_12.setValue("1");
        fjt_22.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("chestIcon");
        faw_23.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tKY);
        frp_13.setSize(new fsm_1(-2, -2));
        frp_13.setXOffset(45);
        frp_13.setYOffset(-45);
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("whiteTitle");
        String string = "%protector.secret.desc%";
        string = string.replace("%protector.secret.desc%", fyw_0.gqw().k("protector.secret.desc", new Object[0]));
        fbv_22.setText(string);
        faw_23.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tKY);
        frp_14.setSize(new fsm_1(-2, -2));
        frp_14.setXOffset(85);
        frp_14.setYOffset(-65);
        fbv_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("passportTitleColor"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setStyle("whiteTitle");
        faw_23.X(fbv_24);
        fbv_24.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tKY);
        frp_15.setSize(new fsm_1(-2, -2));
        frp_15.setXOffset(350);
        frp_15.setYOffset(-63);
        fbv_24.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_24.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new fhl_2("passportTitleColor"));
        fyp_03.setName("text");
        fzq3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("pageDescription");
        fsj_23.setName("secrets");
        fbv_24.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setCellSize(new fsm_1(50.0f, 95));
        fbz_22.setHorizontal(true);
        faw_23.X(fbz_22);
        fbz_22.guy();
        fbz_2 fbz_23 = fbz_22;
        fza fza2 = (fza)((fes_2)fbz_23).getAppearance();
        fza2.setElementMap(fhs_22);
        fbz_22.X(fza2);
        fza2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(92, 40, 43, 40));
        fza2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fza2.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        fbz_22.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("content");
        fsj_24.setField("secrets");
        fsj_24.setName("secrets");
        fbz_22.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_22.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_23.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        String string2 = "item";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        fsd_12.setField("item");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        fje_22.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(2, 12, 2, 12));
        fys_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_26.setStyle("encyclopediaSplashTitle");
        faw_24.X(faw_26);
        faw_26.guy();
        faw_2 faw_27 = faw_26;
        fys_0 fys_03 = ((fes_2)faw_27).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_26.X(fys_03);
        fys_03.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(3, 3, 3, 3));
        fys_03.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        faw_26.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setDisplaySize(new fsm_1(32, 32));
        fbt_13.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu:openRefItemDetailWindow(item)");
        fbt_13.setOnClick(fmz_12);
        faw_26.X(fbt_13);
        fbt_13.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_13.X(fze2);
        fze2.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("texture");
        fsd_13.setField("item/iconUrl");
        fze2.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_26.X(faw_28);
        faw_28.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_28.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(200);
        fdy_12.setStyle("WhiteBold11");
        faw_28.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        fdy_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("name");
        fdy_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_22);
        fdy_13.setExpandable(false);
        fdy_13.setMaxWidth(200);
        fdy_13.setStyle("darkBold");
        faw_28.X(fdy_13);
        fdy_13.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLN);
        fdy_13.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("level");
        fdy_13.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq4 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq4.setElementMap(fhs_22);
        fdy_13.X(fzq4);
        fzq4.guy();
        fyp_0 fyp_04 = fyp_0.checkOut();
        fyp_04.setElementMap(fhs_22);
        fyp_04.setColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fyp_04.setName("text");
        fzq4.X(fyp_04);
        fyp_04.guy();
        fyp_04.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_13.onChildrenAdded();
        faw_28.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_26.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setDisplaySize(new fsm_1(16, 16));
        fbt_14.setExpandable(false);
        fbt_14.setStyle("apply");
        faw_26.X(fbt_14);
        fbt_14.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("visible");
        fsd_16.setField("isComplete");
        fbt_14.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fbt_1 fbt_15 = fbt_14;
        fyY fyY2 = (fyY)((fes_2)fbt_15).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_14.X(fyY2);
        fyY2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 3, 0, 20));
        fyY2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_26.onChildrenAdded();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_22);
        fdy_15.setMaxWidth(250);
        fdy_15.setStyle("darkBold");
        faw_24.X(fdy_15);
        fdy_15.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("text");
        fsd_17.setField("description");
        fdy_15.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        fdy_15.onChildrenAdded();
        faw_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fbz_22.X(fje_23);
        fje_23.guy();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        fje_23.X(faw_29);
        faw_29.guy();
        faw_29.onChildrenAdded();
        fje_23.onChildrenAdded();
        fbz_22.onChildrenAdded();
        String string3 = "secrets";
        frv_1 frv_13 = new frv_1();
        frv_13.aVI();
        frv_13.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, frv_13);
        }
        faw_23.X(frv_13);
        frv_13.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("value");
        fsj_25.setName("secrets");
        frv_13.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        frv_13.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.passport:previousSecretPage(secrets)");
        fad_12.setOnClick(fmz_13);
        fad_12.setStyle("CharacterCreationLeftArrow");
        faw_23.X(fad_12);
        fad_12.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_22);
        frp_17.setAlign(fzw_0.tLk);
        frp_17.setSize(new fsm_1(-2, -2));
        frp_17.setXOffset(155);
        frp_17.setYOffset(38);
        fad_12.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("enabled");
        fsj_26.setField("hasPreviousPage");
        fsj_26.setName("secrets");
        fad_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fad_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setExpandable(false);
        fmz_1 fmz_14 = new fmz_1();
        fmz_14.vw("wakfu.passport:nextSecretPage(secrets)");
        fad_13.setOnClick(fmz_14);
        fad_13.setStyle("CharacterCreationRightArrow");
        faw_23.X(fad_13);
        fad_13.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_22);
        frp_18.setAlign(fzw_0.tLo);
        frp_18.setSize(new fsm_1(-2, -2));
        frp_18.setXOffset(-155);
        frp_18.setYOffset(38);
        fad_13.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("enabled");
        fsj_27.setField("hasNextPage");
        fsj_27.setName("secrets");
        fad_13.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setVisible(false);
        faw_22.X(faw_23);
        faw_23.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("passportPvpDecorator");
        faw_23.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLa);
        frp_13.setSize(new fsm_1(-2, -2));
        frp_13.setXOffset(0);
        frp_13.setYOffset(-45);
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(250);
        fdy_12.setMinWidth(250);
        fdy_12.setStyle("whiteTitle");
        String string = "%passport.pvp.nation%";
        string = string.replace("%passport.pvp.nation%", fyw_0.gqw().k("passport.pvp.nation", new Object[0]));
        fdy_12.setText(string);
        faw_23.X(fdy_12);
        fdy_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tKY);
        frp_14.setSize(new fsm_1(-2, -2));
        frp_14.setXOffset(50);
        frp_14.setYOffset(-65);
        fdy_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("passportTitleColor"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setMaxWidth(250);
        fdy_14.setMinWidth(250);
        fdy_14.setStyle("whiteTitle");
        String string2 = "%passport.pvp.score%";
        string2 = string2.replace("%passport.pvp.score%", fyw_0.gqw().k("passport.pvp.score", new Object[0]));
        fdy_14.setText(string2);
        faw_23.X(fdy_14);
        fdy_14.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tKY);
        frp_15.setSize(new fsm_1(-2, -2));
        frp_15.setXOffset(355);
        frp_15.setYOffset(-63);
        fdy_14.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLO);
        fdy_14.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new fhl_2("passportTitleColor"));
        fyp_03.setName("text");
        fzq3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setStyle("passportBackgroundDeco1");
        faw_23.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLo);
        frp_16.setSize(new fsm_1(-2, -2));
        frp_16.setXOffset(-50);
        frp_16.setYOffset(100);
        fbt_13.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setStyle("passportBackgroundDeco2");
        faw_23.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_22);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setSize(new fsm_1(-2, -2));
        frp_17.setXOffset(-50);
        frp_17.setYOffset(-100);
        fbt_14.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fbt_1 fbt_15 = new fbt_1();
        fbt_15.aVI();
        fbt_15.setElementMap(fhs_22);
        fbt_15.setStyle("passportBackgroundDeco3");
        faw_23.X(fbt_15);
        fbt_15.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_22);
        frp_18.setAlign(fzw_0.tKY);
        frp_18.setSize(new fsm_1(-2, -2));
        frp_18.setXOffset(15);
        frp_18.setYOffset(-100);
        fbt_15.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fbt_15.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_22);
        frp_19.setAlign(fzw_0.tLf);
        frp_19.setSize(new fsm_1(50.0f, 100.0f));
        faw_24.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(90, 35, 35, 5));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_24.X(faw_26);
        faw_26.guy();
        String string3 = "nationsRadioGroup";
        fry_1 fry_12 = new fry_1();
        fry_12.aVI();
        fry_12.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, (fhv_1)fry_12);
        }
        faw_26.X(fry_12);
        fry_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("value");
        fsj_22.setField("nationId");
        fsj_22.setLocal(true);
        fsj_22.setName("pvpLadderEntry");
        fry_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fry_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        faw_26.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(48, 48));
        fbz_22.setExpandable(false);
        fbz_22.setIdealSizeMaxRows(1);
        fbz_22.setIdealSizeMinRows(1);
        faw_26.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("content");
        fsj_23.setField("nations");
        fsj_23.setName("nations");
        fbz_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        fje_22.X(faw_27);
        faw_27.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_27.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_22);
        fbt_16.setDisplaySize(new fsm_1(38, 38));
        faw_27.X(fbt_16);
        fbt_16.guy();
        fbt_1 fbt_17 = fbt_16;
        fyY fyY2 = (fyY)((fes_2)fbt_17).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_16.X(fyY2);
        fyY2.guy();
        fyY2.onChildrenAdded();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_22);
        frp_110.setAlign(fzw_0.tLg);
        frp_110.setSize(new fsm_1(-2, -2));
        fbt_16.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_16.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("flagIconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_16.onChildrenAdded();
        fcu_1 fcu_12 = new fcu_1();
        fcu_12.aVI();
        fcu_12.setElementMap(fhs_22);
        fcu_12.setEnabled(false);
        fcu_12.setGroupId("nationsRadioGroup");
        fcu_12.setStyle("nationSelect");
        faw_27.X(fcu_12);
        fcu_12.guy();
        frp_1 frp_111 = new frp_1();
        frp_111.aVI();
        frp_111.setElementMap(fhs_22);
        frp_111.setAlign(fzw_0.tLg);
        frp_111.setSize(new fsm_1(100.0f, 100.0f));
        fcu_12.X(frp_111);
        frp_111.guy();
        frp_111.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("value");
        fsd_13.setField("nationId");
        fcu_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fcu_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_26.onChildrenAdded();
        fbt_1 fbt_18 = new fbt_1();
        fbt_18.aVI();
        fbt_18.setElementMap(fhs_22);
        fbt_18.setDisplaySize(new fsm_1(180, 4));
        fbt_18.setExpandable(false);
        fbt_18.setStyle("TiledScrollBottom");
        faw_24.X(fbt_18);
        fbt_18.guy();
        fbt_1 fbt_19 = fbt_18;
        fyY fyY3 = (fyY)((fes_2)fbt_19).getAppearance();
        fyY3.setElementMap(fhs_22);
        fbt_18.X(fyY3);
        fyY3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(3, 0, 3, 0));
        fyY3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY3.onChildrenAdded();
        fbt_18.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_24.X(faw_28);
        faw_28.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_28.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_28.X(faw_29);
        faw_29.guy();
        frp_1 frp_112 = new frp_1();
        frp_112.aVI();
        frp_112.setElementMap(fhs_22);
        frp_112.setAlign(fzw_0.tLa);
        frp_112.setSize(new fsm_1(100.0f, -2));
        frp_112.setYOffset(-20);
        faw_29.X(frp_112);
        frp_112.guy();
        frp_112.onChildrenAdded();
        faw_2 faw_210 = faw_29;
        fys_0 fys_03 = ((fes_2)faw_210).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_29.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        fbt_1 fbt_110 = new fbt_1();
        fbt_110.aVI();
        fbt_110.setElementMap(fhs_22);
        fbt_110.setDisplaySize(new fsm_1(64, 128));
        fbt_110.setExpandable(false);
        faw_29.X(fbt_110);
        fbt_110.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fbt_110.X(fze3);
        fze3.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("texture");
        fsj_24.setField("pvpRankPassportIconUrl");
        fsj_24.setLocal(true);
        fsj_24.setName("pvpLadderEntry");
        fze3.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fze3.onChildrenAdded();
        fbt_110.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        fde_12.setExpandable(false);
        fde_12.setPrefSize(new fsm_1(60, 0));
        faw_29.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbt_1 fbt_111 = new fbt_1();
        fbt_111.aVI();
        fbt_111.setElementMap(fhs_22);
        fbt_111.setDisplaySize(new fsm_1(64, 128));
        fbt_111.setExpandable(false);
        faw_29.X(fbt_111);
        fbt_111.guy();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_22);
        fze4.setFlipHorizontaly(true);
        fbt_111.X(fze4);
        fze4.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("texture");
        fsj_25.setField("pvpRankPassportIconUrl");
        fsj_25.setLocal(true);
        fsj_25.setName("pvpLadderEntry");
        fze4.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fze4.onChildrenAdded();
        fbt_111.onChildrenAdded();
        faw_29.onChildrenAdded();
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_22);
        fax_12.setAnimName("AnimStatique");
        fax_12.setDirection(2);
        fax_12.setOffsetX(0.0f);
        fax_12.setOffsetY(-80.0f);
        fax_12.setScale(2.0f);
        faw_28.X(fax_12);
        fax_12.guy();
        frp_1 frp_113 = new frp_1();
        frp_113.aVI();
        frp_113.setElementMap(fhs_22);
        frp_113.setAlign(fzw_0.tLg);
        frp_113.setSize(new fsm_1(100.0f, 100.0f));
        fax_12.X(frp_113);
        frp_113.guy();
        frp_113.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("animName");
        fsj_26.setField("animName");
        fsj_26.setLocal(true);
        fsj_26.setName("pvpLadderEntry");
        fax_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("animatedElement");
        fsj_27.setField("animatedElement");
        fsj_27.setLocal(true);
        fsj_27.setName("pvpLadderEntry");
        fax_12.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_211.setPrefSize(new fsm_1(200, 40));
        faw_211.setStyle("pvpRank");
        faw_24.X(faw_211);
        faw_211.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        faw_211.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_212 = faw_211;
        fys_0 fys_04 = ((fes_2)faw_212).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_211.X(fys_04);
        fys_04.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(5, 0, 20, 0));
        fys_04.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_04.onChildrenAdded();
        this.g(faw_211);
        this.H(faw_211);
        faw_211.onChildrenAdded();
        faw_24.onChildrenAdded();
        this.I(faw_23);
        this.h(faw_23);
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        return null;
    }

    public fhi_2 H(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(250);
        fdy_12.setStyle("title");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("rank");
        fsj_22.setLocal(true);
        fsj_22.setName("pvpLadderEntry");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("defaultDarkColor"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 I(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setSize(new fsm_1(50.0f, 100.0f));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(90, 5, 35, 35));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLO);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("titleNameBold12");
        String string = "%pvpRanking%%colon%";
        string = string.replace("%pvpRanking%", fyw_0.gqw().k("pvpRanking", new Object[0]));
        string = string.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fdy_12.setText(string);
        faw_25.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 0, 0));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("defaultDarkColor"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setExpandable(false);
        fdy_14.setMaxWidth(170);
        fdy_14.setStyle("titleNameBold12");
        faw_25.X(fdy_14);
        fdy_14.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("ranking");
        fsj_22.setLocal(true);
        fsj_22.setName("pvpLadderEntry");
        fdy_14.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLN);
        fdy_14.X(fzq3);
        fzq3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 10, 0, 10));
        fzq3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new fhl_2("defaultDarkColor"));
        fyp_03.setName("text");
        fzq3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_25.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(180, 4));
        fbt_12.setExpandable(false);
        fbt_12.setStyle("TiledScrollBottom");
        faw_23.X(fbt_12);
        fbt_12.guy();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(3, 0, 3, 0));
        fyY2.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_23.X(faw_26);
        faw_26.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLO);
        faw_26.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        fdy_16.setExpandable(false);
        fdy_16.setStyle("titleNameBold12");
        String string2 = "%pvpStrength%%colon%";
        string2 = string2.replace("%pvpStrength%", fyw_0.gqw().k("pvpStrength", new Object[0]));
        string2 = string2.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fdy_16.setText(string2);
        faw_26.X(fdy_16);
        fdy_16.guy();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq4 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlign(faa_2.tLN);
        fdy_16.X(fzq4);
        fzq4.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_22);
        fzv6.setInsets(new Insets(0, 0, 0, 0));
        fzq4.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fyp_0 fyp_04 = fyp_0.checkOut();
        fyp_04.setElementMap(fhs_22);
        fyp_04.setColor(new fhl_2("defaultDarkColor"));
        fyp_04.setName("text");
        fzq4.X(fyp_04);
        fyp_04.guy();
        fyp_04.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_16.onChildrenAdded();
        fdy_1 fdy_18 = new fdy_1();
        fdy_18.aVI();
        fdy_18.setElementMap(fhs_22);
        fdy_18.setExpandable(false);
        fdy_18.setMaxWidth(170);
        fdy_18.setStyle("titleNameBold12");
        faw_26.X(fdy_18);
        fdy_18.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("score");
        fsj_23.setLocal(true);
        fsj_23.setName("pvpLadderEntry");
        fdy_18.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_1 fdy_19 = fdy_18;
        fzq fzq5 = (fzq)((fes_2)fdy_19).getAppearance();
        fzq5.setElementMap(fhs_22);
        fzq5.setAlign(faa_2.tLN);
        fdy_18.X(fzq5);
        fzq5.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_22);
        fzv7.setInsets(new Insets(0, 10, 0, 10));
        fzq5.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fyp_0 fyp_05 = fyp_0.checkOut();
        fyp_05.setElementMap(fhs_22);
        fyp_05.setColor(new fhl_2("defaultDarkColor"));
        fyp_05.setName("text");
        fzq5.X(fyp_05);
        fyp_05.guy();
        fyp_05.onChildrenAdded();
        fzq5.onChildrenAdded();
        fdy_18.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setDisplaySize(new fsm_1(28, 21));
        fbt_14.setExpandable(false);
        fbt_14.setStyle("trophyIcon");
        faw_26.X(fbt_14);
        fbt_14.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fbt_14.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbt_1 fbt_15 = fbt_14;
        fyY fyY3 = (fyY)((fes_2)fbt_15).getAppearance();
        fyY3.setElementMap(fhs_22);
        fbt_14.X(fyY3);
        fyY3.guy();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_22);
        fzv8.setInsets(new Insets(0, 0, 0, 0));
        fyY3.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fyY3.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_26.onChildrenAdded();
        fbt_1 fbt_16 = new fbt_1();
        fbt_16.aVI();
        fbt_16.setElementMap(fhs_22);
        fbt_16.setDisplaySize(new fsm_1(180, 4));
        fbt_16.setExpandable(false);
        fbt_16.setStyle("TiledScrollBottom");
        faw_23.X(fbt_16);
        fbt_16.guy();
        fbt_1 fbt_17 = fbt_16;
        fyY fyY4 = (fyY)((fes_2)fbt_17).getAppearance();
        fyY4.setElementMap(fhs_22);
        fbt_16.X(fyY4);
        fyY4.guy();
        fzv fzv9 = fzv.checkOut();
        fzv9.setElementMap(fhs_22);
        fzv9.setInsets(new Insets(3, 0, 3, 0));
        fyY4.X(fzv9);
        fzv9.guy();
        fzv9.onChildrenAdded();
        fyY4.onChildrenAdded();
        fbt_16.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setExpandable(false);
        faw_23.X(faw_27);
        faw_27.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLO);
        faw_27.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fdy_1 fdy_110 = new fdy_1();
        fdy_110.aVI();
        fdy_110.setElementMap(fhs_22);
        fdy_110.setExpandable(false);
        fdy_110.setStyle("titleNameBold12");
        String string3 = "%pvpCoins%%colon%";
        string3 = string3.replace("%pvpCoins%", fyw_0.gqw().k("pvpCoins", new Object[0]));
        string3 = string3.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fdy_110.setText(string3);
        faw_27.X(fdy_110);
        fdy_110.guy();
        fdy_1 fdy_111 = fdy_110;
        fzq fzq6 = (fzq)((fes_2)fdy_111).getAppearance();
        fzq6.setElementMap(fhs_22);
        fzq6.setAlign(faa_2.tLN);
        fdy_110.X(fzq6);
        fzq6.guy();
        fzv fzv10 = fzv.checkOut();
        fzv10.setElementMap(fhs_22);
        fzv10.setInsets(new Insets(0, 0, 0, 0));
        fzq6.X(fzv10);
        fzv10.guy();
        fzv10.onChildrenAdded();
        fyp_0 fyp_06 = fyp_0.checkOut();
        fyp_06.setElementMap(fhs_22);
        fyp_06.setColor(new fhl_2("defaultDarkColor"));
        fyp_06.setName("text");
        fzq6.X(fyp_06);
        fyp_06.guy();
        fyp_06.onChildrenAdded();
        fzq6.onChildrenAdded();
        fdy_110.onChildrenAdded();
        fdy_1 fdy_112 = new fdy_1();
        fdy_112.aVI();
        fdy_112.setElementMap(fhs_22);
        fdy_112.setExpandable(false);
        fdy_112.setMaxWidth(170);
        fdy_112.setStyle("titleNameBold12");
        faw_27.X(fdy_112);
        fdy_112.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("nation/pvpMoney");
        fsj_24.setName("localPlayer");
        fdy_112.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_1 fdy_113 = fdy_112;
        fzq fzq7 = (fzq)((fes_2)fdy_113).getAppearance();
        fzq7.setElementMap(fhs_22);
        fzq7.setAlign(faa_2.tLN);
        fdy_112.X(fzq7);
        fzq7.guy();
        fzv fzv11 = fzv.checkOut();
        fzv11.setElementMap(fhs_22);
        fzv11.setInsets(new Insets(0, 10, 0, 10));
        fzq7.X(fzv11);
        fzv11.guy();
        fzv11.onChildrenAdded();
        fyp_0 fyp_07 = fyp_0.checkOut();
        fyp_07.setElementMap(fhs_22);
        fyp_07.setColor(new fhl_2("defaultDarkColor"));
        fyp_07.setName("text");
        fzq7.X(fyp_07);
        fyp_07.guy();
        fyp_07.onChildrenAdded();
        fzq7.onChildrenAdded();
        fdy_112.onChildrenAdded();
        fbt_1 fbt_18 = new fbt_1();
        fbt_18.aVI();
        fbt_18.setElementMap(fhs_22);
        fbt_18.setExpandable(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(pvpMoneyPopup)");
        fbt_18.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_18.setOnPopupHide(fml_12);
        fbt_18.setStyle("gloryOrbIcon");
        faw_27.X(fbt_18);
        fbt_18.guy();
        String string4 = "pvpMoneyPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string4 != null) {
            fhs_22.a(string4, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fbt_18.X(frx_12);
        frx_12.guy();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setPrefSize(new fsm_1(10, 0));
        faw_28.setStyle("popup");
        frx_12.X(faw_28);
        faw_28.guy();
        fdy_1 fdy_114 = new fdy_1();
        fdy_114.aVI();
        fdy_114.setElementMap(fhs_22);
        fdy_114.setMaxWidth(250);
        fdy_114.setStyle("white");
        String string5 = "%passport.pvp.money.desc%";
        string5 = string5.replace("%passport.pvp.money.desc%", fyw_0.gqw().k("passport.pvp.money.desc", new Object[0]));
        fdy_114.setText(string5);
        faw_28.X(fdy_114);
        fdy_114.guy();
        fdy_1 fdy_115 = fdy_114;
        fzq fzq8 = (fzq)((fes_2)fdy_115).getAppearance();
        fzq8.setElementMap(fhs_22);
        fzq8.setAlignment(faa_2.tLN);
        fdy_114.X(fzq8);
        fzq8.guy();
        fzq8.onChildrenAdded();
        fdy_114.onChildrenAdded();
        faw_28.onChildrenAdded();
        frx_12.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLO);
        fbt_18.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fbt_1 fbt_19 = fbt_18;
        fyY fyY5 = (fyY)((fes_2)fbt_19).getAppearance();
        fyY5.setElementMap(fhs_22);
        fbt_18.X(fyY5);
        fyY5.guy();
        fzv fzv12 = fzv.checkOut();
        fzv12.setElementMap(fhs_22);
        fzv12.setInsets(new Insets(0, 0, 0, 0));
        fyY5.X(fzv12);
        fzv12.guy();
        fzv12.onChildrenAdded();
        fyY5.onChildrenAdded();
        fbt_18.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setExpandable(false);
        faw_23.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_03 = ((fes_2)faw_210).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_29.X(fys_03);
        fys_03.guy();
        fzv fzv13 = fzv.checkOut();
        fzv13.setElementMap(fhs_22);
        fzv13.setInsets(new Insets(5, 5, 5, 5));
        fys_03.X(fzv13);
        fzv13.guy();
        fzv13.onChildrenAdded();
        fys_03.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_29.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbt_1 fbt_110 = new fbt_1();
        fbt_110.aVI();
        fbt_110.setElementMap(fhs_22);
        fbt_110.setStyle("scrollButtonShadow");
        faw_29.X(fbt_110);
        fbt_110.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, -2));
        fbt_110.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_110.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu:nationPvpLadderDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("scroll");
        String string6 = "%pvp.openPvpLadder%";
        string6 = string6.replace("%pvp.openPvpLadder%", fyw_0.gqw().k("pvp.openPvpLadder", new Object[0]));
        fad_12.setText(string6);
        faw_29.X(fad_12);
        fad_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, -2));
        fad_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzv fzv14 = fzv.checkOut();
        fzv14.setElementMap(fhs_22);
        fzv14.setInsets(new Insets(5, 10, 5, 10));
        fym_02.X(fzv14);
        fzv14.guy();
        fzv14.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 h(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("passportCategory");
        faw_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_22);
        fjv_12.setValue("2");
        fjt_22.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 J(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("backgroundDisplayClose");
        faw_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setXOffset(-40);
        frp_12.setYOffset(-35);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 v(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("passportCategory");
        faw_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_22.X(fjn_22);
        fjn_22.guy();
        fjc_1 fjc_12 = new fjc_1();
        fjc_12.aVI();
        fjc_12.setElementMap(fhs_22);
        fjc_12.setValue("2");
        fjn_22.X(fjc_12);
        fjc_12.guy();
        fjc_12.onChildrenAdded();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjn_22.X(fjl_12);
        fjl_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("comparedValue");
        fsj_23.setField("hasNation");
        fsj_23.setName("localPlayer");
        fjl_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fjl_12.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(450);
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.passport:setCategory(2)");
        fbt_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(pvpCategoryPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        fbt_12.setStyle("pennon");
        faw_22.X(fbt_12);
        fbt_12.guy();
        String string = "pvpCategoryPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(250);
        fdy_12.setStyle("white");
        String string2 = "%passport.pvp.desc%";
        string2 = string2.replace("%passport.pvp.desc%", fyw_0.gqw().k("passport.pvp.desc", new Object[0]));
        fdy_12.setText(string2);
        faw_23.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("passportPvpCategoryIcon");
        faw_22.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLk);
        frp_14.setSize(new fsm_1(-2, -2));
        frp_14.setXOffset(22);
        frp_14.setYOffset(53);
        fbt_13.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 F(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("passportCategory");
        faw_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjc_1 fjc_12 = new fjc_1();
        fjc_12.aVI();
        fjc_12.setElementMap(fhs_22);
        fjc_12.setValue("1");
        fjt_22.X(fjc_12);
        fjc_12.guy();
        fjc_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(525);
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.passport:setCategory(1)");
        fbt_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(secretCategoryPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        fbt_12.setStyle("pennon");
        faw_22.X(fbt_12);
        fbt_12.guy();
        String string = "secretCategoryPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(250);
        fdy_12.setStyle("white");
        String string2 = "%protector.secret.desc%";
        string2 = string2.replace("%protector.secret.desc%", fyw_0.gqw().k("protector.secret.desc", new Object[0]));
        fdy_12.setText(string2);
        faw_23.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("chestIcon");
        faw_22.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLk);
        frp_14.setSize(new fsm_1(-2, -2));
        frp_14.setXOffset(20);
        frp_14.setYOffset(54);
        fbt_13.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 G(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setVisible(false);
        fey_22.X(faw_22);
        faw_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setName("passportCategory");
        faw_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjc_1 fjc_12 = new fjc_1();
        fjc_12.aVI();
        fjc_12.setElementMap(fhs_22);
        fjc_12.setValue("0");
        fjt_22.X(fjc_12);
        fjc_12.guy();
        fjc_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLk);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(50);
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.passport:setCategory(0)");
        fbt_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(generalCategoryPopup)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        fbt_12.setStyle("pennon");
        faw_22.X(fbt_12);
        fbt_12.guy();
        String string = "generalCategoryPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLP);
        frx_12.setHotSpotPosition(faa_2.tLN);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(250);
        fdy_12.setStyle("white");
        String string2 = "%summary%";
        string2 = string2.replace("%summary%", fyw_0.gqw().k("summary", new Object[0]));
        fdy_12.setText(string2);
        faw_23.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("scrollIcon");
        faw_22.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLk);
        frp_14.setSize(new fsm_1(-2, -2));
        frp_14.setXOffset(20);
        frp_14.setYOffset(52);
        fbt_13.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }
}

