/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNG
 */
public class cng_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "resourcesCollectorWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string2 = "%seedSpreader.seed%";
        string2 = string2.replace("%seedSpreader.seed%", fyw_0.gqw().k("seedSpreader.seed", new Object[0]));
        fbv_22.setText(string2);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string3 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_211.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_211.X(faw_212);
        faw_212.guy();
        faw_2 faw_213 = faw_212;
        fys_0 fys_06 = ((fes_2)faw_213).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_212.X(fys_06);
        fys_06.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 10, 0, 10));
        fys_06.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_06.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_212.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setStyle("caracs");
        faw_212.X(faw_214);
        faw_214.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_214.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_215 = faw_214;
        fys_0 fys_07 = ((fes_2)faw_215).getAppearance();
        fys_07.setElementMap(fhs_23);
        fys_07.setModulationColor(new awx_2(0.9f, 0.9f, 0.9f, 1.0f));
        faw_214.X(fys_07);
        fys_07.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 0, 0, 0));
        fys_07.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_07.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_212.X(faw_216);
        faw_216.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        frp_15.setXOffset(3);
        faw_216.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_217 = faw_216;
        fys_0 fys_08 = ((fes_2)faw_217).getAppearance();
        fys_08.setElementMap(fhs_23);
        faw_216.X(fys_08);
        fys_08.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(7, 1, 5, 0));
        fys_08.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_08.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setExpandable(false);
        faw_216.X(faw_218);
        faw_218.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_218.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        String string4 = "seedSlot";
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, faw_219);
        }
        faw_219.setPrefSize(new fsm_1(55, 55));
        faw_219.setStyle("itemBackground");
        faw_218.X(faw_219);
        faw_219.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        faw_219.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        faw_219.onChildrenAdded();
        fcv_1 fcv_12 = new fcv_1();
        fcv_12.aVI();
        fcv_12.setElementMap(fhs_23);
        faw_218.X(fcv_12);
        fcv_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("content");
        fsj_22.setName("seedSpreaderItem");
        fcv_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setSize(new fsm_1(55, 55));
        fcv_12.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fcv_12.X(fje_22);
        fje_22.guy();
        fbd_1 fbd_12 = new fbd_1();
        fbd_12.aVI();
        fbd_12.setElementMap(fhs_23);
        fbd_12.setNonBlocking(false);
        fmh_1 fmh_12 = new fmh_1();
        fmh_12.vw("wakfu.seedSpreader:removeSeed");
        fbd_12.setOnDrag(fmh_12);
        fje_22.X(fbd_12);
        fbd_12.guy();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        faw_220.setNonBlocking(true);
        fbd_12.X(faw_220);
        faw_220.guy();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        fro_15.setAdaptToContentSize(true);
        faw_220.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setNonBlocking(true);
        fbv_24.setStyle("White10Bordered");
        faw_220.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("visible");
        fsd_12.setField("quantity");
        fbv_24.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsd_12.X(fjt_22);
        fjt_22.guy();
        fjp_1 fjp_12 = new fjp_1();
        fjp_12.aVI();
        fjp_12.setElementMap(fhs_23);
        fjp_12.setValue("1");
        fjt_22.X(fjp_12);
        fjp_12.guy();
        fjp_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_12.onChildrenAdded();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setAlign(fzw_0.tLk);
        fbv_24.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 6, 6, 0));
        fzq3.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fsd_13.setField("quantity");
        fbv_24.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_220.onChildrenAdded();
        fbd_12.onChildrenAdded();
        fje_22.onChildrenAdded();
        fcv_12.onChildrenAdded();
        faw_218.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        faw_2 faw_221 = faw_2.checkOut();
        faw_221.setElementMap(fhs_23);
        fey_22.X(faw_221);
        faw_221.guy();
        frp_1 frp_19 = new frp_1();
        frp_19.aVI();
        frp_19.setElementMap(fhs_23);
        frp_19.setSize(new fsm_1(100.0f, 100.0f));
        faw_221.X(frp_19);
        frp_19.guy();
        frp_19.onChildrenAdded();
        faw_221.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_23);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.seedSpreader:closeWindow");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_110 = new frp_1();
        frp_110.aVI();
        frp_110.setElementMap(fhs_23);
        frp_110.setAlign(fzw_0.tLc);
        frp_110.setSize(new fsm_1(-2, -2));
        frp_110.setXOffset(-18);
        frp_110.setYOffset(-12);
        fad_12.X(frp_110);
        frp_110.guy();
        frp_110.onChildrenAdded();
        fad_12.onChildrenAdded();
        frp_1 frp_111 = new frp_1();
        frp_111.aVI();
        frp_111.setElementMap(fhs_23);
        frp_111.setAlign(fzw_0.tLf);
        frp_111.setInitValue(true);
        frp_111.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_111);
        frp_111.guy();
        frp_111.onChildrenAdded();
        fey_22.onChildrenAdded();
        return fey_22;
    }
}

