/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNn
 */
public class cnn_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "confirmPurchaseWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("StyledBold16White");
        String string2 = "%protector.kamas.transfer%";
        string2 = string2.replace("%protector.kamas.transfer%", fyw_0.gqw().k("protector.kamas.transfer", new Object[0]));
        fdy_12.setText(string2);
        faw_27.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 0));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string3 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(true);
        faw_210.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_210.X(faw_211);
        faw_211.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(true);
        faw_211.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setPrefSize(new fsm_1(0, 35));
        faw_212.setStyle("flat");
        faw_211.X(faw_212);
        faw_212.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        faw_212.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setHorizontal(false);
        faw_212.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setStyle("bold");
        String string4 = "%protector.kamasToTransfer%";
        string4 = string4.replace("%protector.kamasToTransfer%", fyw_0.gqw().k("protector.kamasToTransfer", new Object[0]));
        fbv_22.setText(string4);
        faw_212.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLO);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setPrefSize(new fsm_1(150, 0));
        faw_213.setStyle("ShortcutRowBackgroundFull");
        faw_212.X(faw_213);
        faw_213.guy();
        faw_2 faw_214 = faw_213;
        fys_0 fys_06 = ((fes_2)faw_214).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_213.X(fys_06);
        fys_06.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(2, 5, 2, 5));
        fys_06.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_06.onChildrenAdded();
        String string5 = "amountTextEditor";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fdu_12);
        }
        fdu_12.setFocused(true);
        fmu_2 fmu_22 = new fmu_2();
        fmu_22.vw("wakfu.protectorManagement:validateBudgetTransfer(confirmButton)");
        fdu_12.setOnKeyType(fmu_22);
        fdu_12.setRestrict("[0-9]+");
        fdu_12.setSelectOnFocus(true);
        fdu_12.setStyle("dark");
        fdu_12.setText("0");
        faw_213.X(fdu_12);
        fdu_12.guy();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq4 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLP);
        fdu_12.X(fzq4);
        fzq4.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 0, 0, 0));
        fzq4.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setPrefSize(new fsm_1(0, 35));
        faw_215.setStyle("flat");
        faw_211.X(faw_215);
        faw_215.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLO);
        faw_215.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setHorizontal(false);
        faw_215.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setStyle("bold");
        String string6 = "%protector.funds%";
        string6 = string6.replace("%protector.funds%", fyw_0.gqw().k("protector.funds", new Object[0]));
        fbv_24.setText(string6);
        faw_215.X(fbv_24);
        fbv_24.guy();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq5 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlign(faa_2.tLO);
        fbv_24.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setPrefSize(new fsm_1(100, 0));
        faw_216.setStyle("ShortcutRowBackgroundFull");
        faw_215.X(faw_216);
        faw_216.guy();
        faw_2 faw_217 = faw_216;
        fys_0 fys_07 = ((fes_2)faw_217).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_216.X(fys_07);
        fys_07.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(2, 5, 2, 5));
        fys_07.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fys_07.onChildrenAdded();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_23);
        fbv_26.setStyle("bold");
        faw_216.X(fbv_26);
        fbv_26.guy();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq6 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq6.setElementMap(fhs_23);
        fzq6.setAlign(faa_2.tLP);
        fbv_26.X(fzq6);
        fzq6.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 0, 0, 3));
        fzq6.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzq6.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("walletHandler/totalAmount");
        fsj_22.setName("protector");
        fbv_26.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_215.onChildrenAdded();
        String string7 = "territoryCombo";
        fas_1 fas_12 = new fas_1();
        fas_12.aVI();
        fas_12.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fas_12);
        }
        fas_12.setExpandable(false);
        fas_12.setPrefSize(new fsm_1(250, 0));
        faw_211.X(fas_12);
        fas_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setField("protectorList");
        fsj_23.setName("nation");
        fas_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fcv_1 fcv_12 = new fcv_1();
        fcv_12.aVI();
        fcv_12.setElementMap(fhs_23);
        fas_12.X(fcv_12);
        fcv_12.guy();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fcv_12.X(fje_22);
        fje_22.guy();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        fje_22.X(faw_218);
        faw_218.guy();
        frz_2 frz_28 = frz_2.checkOut();
        frz_28.setHorizontal(false);
        faw_218.X(frz_28);
        frz_28.guy();
        frz_28.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_23);
        fbv_28.setNonBlocking(true);
        fbv_28.setStyle("bold");
        faw_218.X(fbv_28);
        fbv_28.guy();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLO);
        fbv_28.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("territoryName");
        fbv_28.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_28.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_23);
        fbv_29.setNonBlocking(true);
        fbv_29.setStyle("bold");
        faw_218.X(fbv_29);
        fbv_29.guy();
        frb_1 frb_16 = new frb_1();
        frb_16.aVI();
        frb_16.setElementMap(fhs_23);
        frb_16.setAlign(faa_2.tLO);
        fbv_29.X(frb_16);
        frb_16.guy();
        frb_16.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fsd_13.setField("cash");
        fbv_29.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_29.onChildrenAdded();
        faw_218.onChildrenAdded();
        fje_22.onChildrenAdded();
        fcv_12.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_23);
        fbz_22.setCellSize(new fsm_1(100.0f, 30));
        fbz_22.setHorizontal(false);
        fas_12.X(fbz_22);
        fbz_22.guy();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_23);
        fbz_22.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_23.X(fjt_22);
        fjt_22.guy();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_23);
        fjy_22.setKey("evenIndex");
        fjt_22.X(fjy_22);
        fjy_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjy_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        fje_23.X(faw_219);
        faw_219.guy();
        frz_2 frz_29 = frz_2.checkOut();
        frz_29.setHorizontal(false);
        faw_219.X(frz_29);
        frz_29.guy();
        frz_29.onChildrenAdded();
        faw_2 faw_220 = faw_219;
        fys_0 fys_08 = ((fes_2)faw_220).getAppearance();
        fys_08.setElementMap(fhs_23);
        faw_219.X(fys_08);
        fys_08.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_23);
        fkk_12.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.1f));
        fys_08.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_08.onChildrenAdded();
        fbv_2 fbv_210 = new fbv_2();
        fbv_210.aVI();
        fbv_210.setElementMap(fhs_23);
        fbv_210.setExpandable(false);
        fbv_210.setNonBlocking(true);
        fbv_210.setStyle("bold");
        faw_219.X(fbv_210);
        fbv_210.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("text");
        fsd_14.setField("territoryName");
        fbv_210.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        this.i(fbv_210);
        fbv_210.onChildrenAdded();
        this.c(faw_219);
        faw_219.onChildrenAdded();
        fje_23.onChildrenAdded();
        this.m(fbz_22);
        fbz_22.onChildrenAdded();
        fas_12.onChildrenAdded();
        faw_211.onChildrenAdded();
        this.e(faw_210);
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.n(fey_22);
        this.q(fey_22);
        this.r(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 i(fbv_2 fbv_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 10, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        return fzq2;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("bold");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("cash");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 10, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 m(fbz_2 fbz_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fje_22.X(faw_22);
        faw_22.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("bold");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("territoryName");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 10, 0, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setNonBlocking(true);
        fbv_24.setStyle("bold");
        faw_22.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("cash");
        fbv_24.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_22);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 10, 0, 0));
        fzq3.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLP);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_23.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("yellow");
        faw_24.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_1 fad_13 = fad_12;
        fym_0 fym_02 = (fym_0)((fes_2)fad_13).getAppearance();
        fym_02.setElementMap(fhs_22);
        fad_12.X(fym_02);
        fym_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(7, 7, 7, 7));
        fym_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fym_02.onChildrenAdded();
        fad_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("cancel");
        faw_24.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_25.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        String string = "confirmButton";
        fad_1 fad_14 = new fad_1();
        fad_14.aVI();
        fad_14.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fad_14);
        }
        fad_14.setEnabled(true);
        fad_14.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.protectorManagement:transferBudget(amountTextEditor,territoryCombo)");
        fad_14.setOnClick(fmz_13);
        fad_14.setStyle("yellow");
        faw_25.X(fad_14);
        fad_14.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        fad_14.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fad_1 fad_15 = fad_14;
        fym_0 fym_03 = (fym_0)((fes_2)fad_15).getAppearance();
        fym_03.setElementMap(fhs_22);
        fad_14.X(fym_03);
        fym_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(7, 7, 7, 7));
        fym_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fym_03.onChildrenAdded();
        fad_14.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setNonBlocking(true);
        fbt_13.setStyle("apply");
        faw_25.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        fbt_13.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

