/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNw
 */
public class cnw_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-20);
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("tiledScroll");
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(20, 12, 20, 13));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(13, 0, 13, 0));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setNonBlocking(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_23);
        faw_26.setExpandable(false);
        faw_26.setStyle("AchievementUnlockedSplashScaled2");
        faw_25.X(faw_26);
        faw_26.guy();
        faw_2 faw_27 = faw_26;
        fys_0 fys_03 = ((fes_2)faw_27).getAppearance();
        fys_03.setElementMap(fhs_23);
        faw_26.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 13, 0, 0));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(13, 10, 13, 10));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("defaultBold22");
        faw_26.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("achievementIndexText");
        fsj_22.setLocal(true);
        fsj_22.setName("questListBar");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLL);
        fbv_22.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("scrollFleshColor"));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 10));
        fzq2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(180);
        fdy_12.setStyle("styledBoldWhite12");
        faw_26.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLL);
        fdy_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setField("name");
        fsj_23.setLocal(true);
        fsj_23.setName("displayedAchievement");
        fdy_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fdy_12.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_23);
        fyp_03.setColor(new fhl_2("scrollFleshColor"));
        fzq3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        fdf_12.setExpandable(false);
        fdf_12.setHorizontal(false);
        faw_25.X(fdf_12);
        fdf_12.guy();
        fdf_1 fdf_13 = fdf_12;
        fza fza2 = (fza)((fes_2)fdf_13).getAppearance();
        fza2.setElementMap(fhs_23);
        fdf_12.X(fza2);
        fza2.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 15, 0, 15));
        fza2.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fza2.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("content");
        fsj_24.setField("goals");
        fsj_24.setLocal(true);
        fsj_24.setName("displayedAchievement");
        fdf_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fdf_12.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_23);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        fje_22.X(faw_28);
        faw_28.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_28.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        fdy_14.setExpandable(false);
        fdy_14.setMaxWidth(180);
        fdy_14.setMinWidth(180);
        fdy_14.setStyle("styledBoldDark12");
        faw_28.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq4 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLN);
        fdy_14.X(fzq4);
        fzq4.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 0, 0, 0));
        fzq4.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(7, 0, 7, 0));
        fzq4.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("description");
        fdy_14.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_28.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_23);
        fdy_16.setExpandable(false);
        fdy_16.setNonBlocking(true);
        fdy_16.setStyle("styledBoldDark12");
        faw_28.X(fdy_16);
        fdy_16.guy();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq5 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlign(faa_2.tLO);
        fdy_16.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("text");
        fsd_13.setField("progressionText");
        fdy_16.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("visible");
        fsd_14.setField("isCompleted");
        fdy_16.X(fsd_14);
        fsd_14.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsd_14.X(fjt_23);
        fjt_23.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_23);
        fjt_23.X(fjn_22);
        fjn_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjn_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_23);
        fjn_22.X(fjw_23);
        fjw_23.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("comparedValue");
        fsd_15.setField("progressionText");
        fjw_23.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fsd_15.X(fjt_24);
        fjt_24.guy();
        fjv_1 fjv_12 = new fjv_1();
        fjv_12.aVI();
        fjv_12.setElementMap(fhs_23);
        fjv_12.setValue("-1");
        fjt_24.X(fjv_12);
        fjv_12.guy();
        fjv_12.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_15.onChildrenAdded();
        fjw_23.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_14.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_28.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        fdy_1 fdy_18 = new fdy_1();
        fdy_18.aVI();
        fdy_18.setElementMap(fhs_23);
        fdy_18.setExpandable(false);
        fdy_18.setMaxWidth(200);
        fdy_18.setStyle("darkBold");
        fdy_18.setText("bg");
        faw_25.X(fdy_18);
        fdy_18.guy();
        fdy_1 fdy_19 = fdy_18;
        fzq fzq6 = (fzq)((fes_2)fdy_19).getAppearance();
        fzq6.setElementMap(fhs_23);
        fdy_18.X(fzq6);
        fzq6.guy();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(5, 20, 5, 20));
        fzq6.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fzq6.onChildrenAdded();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLN);
        fdy_18.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("text");
        fsj_25.setField("backgroundText");
        fsj_25.setLocal(true);
        fsj_25.setName("displayedAchievement");
        fdy_18.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("visible");
        fsj_26.setField("backgroundText");
        fsj_26.setLocal(true);
        fsj_26.setName("displayedAchievement");
        fdy_18.X(fsj_26);
        fsj_26.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_23);
        fsj_26.X(fjt_25);
        fjt_25.guy();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_23);
        fjt_25.X(fjn_23);
        fjn_23.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_23);
        fjn_23.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjc_1 fjc_12 = new fjc_1();
        fjc_12.aVI();
        fjc_12.setElementMap(fhs_23);
        fjc_12.setValue("");
        fjn_23.X(fjc_12);
        fjc_12.guy();
        fjc_12.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsj_26.onChildrenAdded();
        fdy_18.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setExpandable(false);
        faw_25.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_04 = ((fes_2)faw_210).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_29.X(fys_04);
        fys_04.guy();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_23);
        fzv8.setInsets(new Insets(5, 13, 5, 13));
        fys_04.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fys_04.onChildrenAdded();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_23);
        frb_15.setAlign(faa_2.tLO);
        faw_29.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_29.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(210, 29));
        fbt_12.setStyle("scrollTitleBar");
        faw_29.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLf);
        frp_14.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fdy_1 fdy_110 = new fdy_1();
        fdy_110.aVI();
        fdy_110.setElementMap(fhs_23);
        fdy_110.setNonBlocking(true);
        fdy_110.setStyle("styledBoldWhite12");
        String string = "%achievement.reward%";
        string = string.replace("%achievement.reward%", fyw_0.gqw().k("achievement.reward", new Object[0]));
        fdy_110.setText(string);
        faw_29.X(fdy_110);
        fdy_110.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLf);
        frp_15.setSize(new fsm_1(100.0f, 2));
        fdy_110.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fdy_1 fdy_111 = fdy_110;
        fzq fzq7 = (fzq)((fes_2)fdy_111).getAppearance();
        fzq7.setElementMap(fhs_23);
        fzq7.setAlign(faa_2.tLO);
        fdy_110.X(fzq7);
        fzq7.guy();
        fyp_0 fyp_04 = fyp_0.checkOut();
        fyp_04.setElementMap(fhs_23);
        fyp_04.setColor(new fhl_2("scrollFleshColor"));
        fzq7.X(fyp_04);
        fyp_04.guy();
        fyp_04.onChildrenAdded();
        fzq7.onChildrenAdded();
        fdy_110.onChildrenAdded();
        faw_29.onChildrenAdded();
        this.R(faw_25);
        faw_25.onChildrenAdded();
        this.c(faw_23);
        faw_23.onChildrenAdded();
        this.d(faw_22);
        this.e(faw_22);
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(170, 52));
        fbz_22.setExpandable(false);
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMinColumns(1);
        fbz_22.setPrefSize(new fsm_1(0, 0));
        faw_22.X(fbz_22);
        fbz_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("rewards");
        fsj_22.setLocal(true);
        fsj_22.setName("displayedAchievement");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fbz_22.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbz_2 fbz_23 = fbz_22;
        fza fza2 = (fza)((fes_2)fbz_23).getAppearance();
        fza2.setElementMap(fhs_22);
        fbz_22.X(fza2);
        fza2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 0, 0));
        fza2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fza2.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu:openItemDetailWindow()");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        fje_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 0, 5));
        fys_02.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_02.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setStyle("IconEmptyEmote");
        faw_24.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setDisplaySize(new fsm_1(48, 48));
        faw_24.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(-2, -2));
        fbt_13.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_13.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("iconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("bold");
        faw_24.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(5, 5, 5, 5));
        fzq2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("defaultDarkColor"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLo);
        frp_14.setSize(new fsm_1(-2, -2));
        fbv_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("quantity");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("visible");
        fsd_14.setField("quantity");
        fbv_22.X(fsd_14);
        fsd_14.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsd_14.X(fjt_23);
        fjt_23.guy();
        fjp_1 fjp_12 = new fjp_1();
        fjp_12.aVI();
        fjp_12.setElementMap(fhs_22);
        fjp_12.setValue("1");
        fjt_23.X(fjp_12);
        fjp_12.guy();
        fjp_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_14.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(115);
        fdy_12.setStyle("styledBoldDark10");
        faw_23.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("description");
        fdy_12.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLL);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(10, 0, 0, 0));
        fzq3.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        return fbz_22;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setVisible(false);
        faw_23.setExpandable(false);
        faw_23.setNonBlocking(false);
        faw_22.X(faw_23);
        faw_23.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setLocal(true);
        fsj_22.setName("questListBar");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(19, 20));
        fbz_22.setIdealSizeMaxColumns(10);
        fbz_22.setIdealSizeMaxRows(1);
        fbz_22.setIdealSizeMinColumns(1);
        fbz_22.setIdealSizeMinRows(1);
        faw_23.X(fbz_22);
        fbz_22.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fbz_22.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("content");
        fsj_23.setField("quests");
        fsj_23.setLocal(true);
        fsj_23.setName("questListBar");
        fbz_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_22.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_23.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjx_12.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        fje_22.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setStyle("AchievementListComplete");
        faw_24.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("isCompleted");
        fbt_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setStyle("AchievementListInactive");
        faw_24.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(-2, -2));
        fbt_13.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("visible");
        fsd_13.setField("isActivated");
        fbt_13.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fsd_13.X(fjt_24);
        fjt_24.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_24.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsd_13.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setStyle("AchievementListActive");
        faw_24.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(-2, -2));
        fbt_14.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("visible");
        fsd_14.setField("isActivated");
        fbt_14.X(fsd_14);
        fsd_14.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fsd_14.X(fjt_25);
        fjt_25.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_25.X(fjn_22);
        fjn_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjn_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_22);
        fjn_22.X(fjw_23);
        fjw_23.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("comparedValue");
        fsd_15.setField("isCompleted");
        fjw_23.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fjw_23.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsd_14.onChildrenAdded();
        fbt_14.onChildrenAdded();
        String string = "quest";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frv_12);
        }
        faw_24.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("value");
        frv_12.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_2 faw_25 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 15, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLO);
        faw_23.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(260, 45));
        fbt_12.setStyle("ScrollBorderTop2");
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(260, 45));
        fbt_12.setStyle("ScrollBorderBottom2");
        faw_22.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbt_12.onChildrenAdded();
        return fbt_12;
    }
}

