/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cNz
 */
public class cnz_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        String string = "craftWindow";
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fey_22);
        }
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        faw_27.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("name");
        fsj_22.setName("recipeView");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        faw_210.X(fdf_12);
        fdf_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("content");
        fsj_23.setName("recipeView");
        fdf_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fdf_12.X(fje_22);
        fje_22.guy();
        String string3 = "recipe";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("value");
        fsj_24.setName("recipeView");
        frv_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        fje_22.X(faw_211);
        faw_211.guy();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_211.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setNonBlocking(true);
        fdy_12.setPrefSize(new fsm_1(46, 0));
        fdy_12.setStyle("whiteBold");
        faw_211.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("text");
        fsd_12.setField("levelShort");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setField("isConceptual");
        fsj_25.setLocal(true);
        fsj_25.setName("craft");
        fdy_12.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_25.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fdy_1 fdy_14 = fdy_12;
        fzq fzq4 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq4.setElementMap(fhs_23);
        fdy_12.X(fzq4);
        fzq4.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 6, 0, 3));
        fzq4.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_212.setNonBlocking(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.crafts:openProducedItemDescription(recipe,craftWindow);wakfu.crafts:clickOnRecipeResult(recipe)");
        faw_212.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(recipeDesc)");
        faw_212.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_212.setOnPopupHide(fml_12);
        faw_212.setPrefSize(new fsm_1(54, 54));
        faw_211.X(faw_212);
        faw_212.guy();
        String string4 = "recipeDesc";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_212.X(frx_12);
        frx_12.guy();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setPrefSize(new fsm_1(10, 0));
        faw_213.setStyle("popup");
        frx_12.X(faw_213);
        faw_213.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_213.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_23);
        fdy_15.setExpandable(false);
        fdy_15.setStyle("PopupInformation");
        String string5 = "%rightClickToShowDetailWindow%";
        string5 = string5.replace("%rightClickToShowDetailWindow%", fyw_0.gqw().k("rightClickToShowDetailWindow", new Object[0]));
        fdy_15.setText(string5);
        faw_213.X(fdy_15);
        fdy_15.guy();
        fdy_1 fdy_16 = fdy_15;
        fzq fzq5 = (fzq)((fes_2)fdy_16).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlignment(faa_2.tLN);
        fdy_15.X(fzq5);
        fzq5.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new awx_2(0.8f, 0.8f, 0.8f, 0.8f));
        fzq5.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq5.onChildrenAdded();
        fdy_15.onChildrenAdded();
        fdy_1 fdy_17 = new fdy_1();
        fdy_17.aVI();
        fdy_17.setElementMap(fhs_23);
        fdy_17.setMaxWidth(250);
        fdy_17.setStyle("white");
        faw_213.X(fdy_17);
        fdy_17.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_23);
        fsd_13.setAttribute("visible");
        fsd_13.setField("criterionDescription");
        fdy_17.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsd_13.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_23);
        fjt_23.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_13.onChildrenAdded();
        fdy_1 fdy_18 = fdy_17;
        fzq fzq6 = (fzq)((fes_2)fdy_18).getAppearance();
        fzq6.setElementMap(fhs_23);
        fzq6.setAlign(faa_2.tLN);
        fdy_17.X(fzq6);
        fzq6.guy();
        fzq6.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_23);
        fsd_14.setAttribute("text");
        fsd_14.setField("criterionDescription");
        fdy_17.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fdy_17.onChildrenAdded();
        faw_213.onChildrenAdded();
        frx_12.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_212.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_214 = faw_212;
        fys_0 fys_06 = ((fes_2)faw_214).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_212.X(fys_06);
        fys_06.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 3, 0, 3));
        fys_06.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_06.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setDisplaySize(new fsm_1(48, 48));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        faw_212.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_23);
        fsd_15.setAttribute("texture");
        fsd_15.setField("themeItemBorderUrl");
        fze2.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        String string6 = "recipeIcon";
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fbt_13);
        }
        fbt_13.setDisplaySize(new fsm_1(48, 48));
        fbt_13.setNonBlocking(true);
        faw_212.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(-2, -2));
        fbt_13.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fbt_13.X(fze3);
        fze3.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_23);
        fsd_16.setAttribute("texture");
        fsd_16.setField("iconUrl");
        fze3.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fze3.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setDisplaySize(new fsm_1(16, 16));
        fbt_14.setStyle("craftUpgrade");
        faw_212.X(fbt_14);
        fbt_14.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_23);
        fsd_17.setAttribute("visible");
        fsd_17.setField("isUpgrade");
        fbt_14.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLo);
        frp_16.setXOffset(-3);
        frp_16.setYOffset(6);
        fbt_14.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setNonBlocking(true);
        fbv_24.setStyle("White10Bordered");
        faw_212.X(fbv_24);
        fbv_24.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLo);
        fbv_24.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq7 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq7.setElementMap(fhs_23);
        fbv_24.X(fzq7);
        fzq7.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 6, 6, 0));
        fzq7.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzq7.onChildrenAdded();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_23);
        fsd_18.setAttribute("text");
        fsd_18.setField("quantityText");
        fbv_24.X(fsd_18);
        fsd_18.guy();
        fsd_18.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_212.onChildrenAdded();
        this.R(faw_211);
        this.c(faw_211);
        this.d(faw_211);
        this.e(faw_211);
        faw_211.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.n(fey_22);
        this.q(fey_22);
        this.r(fey_22);
        this.N(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(3, 8, 0, 3));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLN);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setEnableAutoZoomShrink(true);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(220);
        fdy_12.setMultiline(false);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("Bold");
        faw_25.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("nameWithRarity");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_12.onChildrenAdded();
        String string = "ingredientList";
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fbz_22);
        }
        fbz_22.setCellSize(new fsm_1(27, 26));
        fbz_22.setExpandable(false);
        fbz_22.setPrefSize(new fsm_1(216, 26));
        faw_25.X(fbz_22);
        fbz_22.guy();
        fbz_2 fbz_23 = fbz_22;
        fza fza2 = (fza)((fes_2)fbz_23).getAppearance();
        fza2.setElementMap(fhs_22);
        fbz_22.X(fza2);
        fza2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(3, 0, 0, 0));
        fza2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fza2.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("content");
        fsd_13.setField("ingredients");
        fbz_22.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.crafts:clickOnRecipeIngredient");
        fje_22.setOnItemClick(fmo_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        String string2 = "ingredient";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frv_12);
        }
        fje_22.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("value");
        frv_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setNonBlocking(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.crafts:openIngredientDescription(ingredient,craftWindow)");
        faw_26.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(descIngredient)");
        faw_26.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_26.setOnPopupHide(fml_12);
        fje_22.X(faw_26);
        faw_26.guy();
        String string3 = "descIngredient";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_26.X(frx_12);
        frx_12.guy();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setPrefSize(new fsm_1(10, 0));
        faw_27.setStyle("popup");
        frx_12.X(faw_27);
        faw_27.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKw);
        faw_27.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_27.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_22);
        fdy_13.setExpandable(false);
        fdy_13.setStyle("white");
        faw_27.X(fdy_13);
        fdy_13.guy();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq2 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fdy_13.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("name");
        fdy_13.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fdy_13.onChildrenAdded();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_22);
        fdy_15.setExpandable(false);
        fdy_15.setStyle("white");
        String string4 = "(%desc.missingIngredient%)";
        string4 = string4.replace("%desc.missingIngredient%", fyw_0.gqw().k("desc.missingIngredient", new Object[0]));
        fdy_15.setText(string4);
        faw_27.X(fdy_15);
        fdy_15.guy();
        fdy_1 fdy_16 = fdy_15;
        fzq fzq3 = (fzq)((fes_2)fdy_16).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLN);
        fdy_15.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("visible");
        fsd_16.setField("isPossessed");
        fdy_15.X(fsd_16);
        fsd_16.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsd_16.X(fjt_23);
        fjt_23.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_23.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsd_16.onChildrenAdded();
        fdy_15.onChildrenAdded();
        faw_27.onChildrenAdded();
        frx_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        faw_26.X(faw_28);
        faw_28.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_28.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_29 = faw_28;
        fys_0 fys_03 = ((fes_2)faw_29).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_28.X(fys_03);
        fys_03.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 0, 0, 1));
        fys_03.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_03.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(26, 26));
        fbt_12.setNonBlocking(true);
        faw_28.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("texture");
        fsd_17.setField("themeItemBorderUrl");
        fze2.X(fsd_17);
        fsd_17.guy();
        fsd_17.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        String string5 = "icon";
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        if (fhs_22 != null && string5 != null) {
            fhs_22.a(string5, fbt_13);
        }
        fbt_13.setDisplaySize(new fsm_1(26, 26));
        fbt_13.setNonBlocking(true);
        faw_28.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(-2, -2));
        fbt_13.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fbt_13.X(fze3);
        fze3.guy();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_22);
        fsd_18.setAttribute("texture");
        fsd_18.setField("iconUrl");
        fze3.X(fsd_18);
        fsd_18.guy();
        fsd_18.onChildrenAdded();
        fze3.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("White10Bordered");
        faw_28.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLo);
        fbv_22.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq4 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq4.setElementMap(fhs_22);
        fbv_22.X(fzq4);
        fzq4.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 0, 4, 4));
        fzq4.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsd_1 fsd_19 = new fsd_1();
        fsd_19.aVI();
        fsd_19.setElementMap(fhs_22);
        fsd_19.setAttribute("text");
        fsd_19.setField("quantity");
        fbv_22.X(fsd_19);
        fsd_19.guy();
        fsd_19.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_26.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(90, 0));
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 3, 0, 3));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 6, 0, 6));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setExpandable(false);
        faw_23.X(faw_25);
        faw_25.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("whiteBold");
        faw_25.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("productionPercentageShort");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("isConceptual");
        fsj_22.setLocal(true);
        fsj_22.setName("craft");
        faw_25.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_23.X(faw_26);
        faw_26.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLN);
        faw_26.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        String string = "craftXpText";
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fdy_14);
        }
        fdy_14.setExpandable(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(xpGainPopup,craftXpText)");
        fdy_14.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fdy_14.setOnPopupHide(fml_12);
        fdy_14.setStyle("whiteBold");
        faw_26.X(fdy_14);
        fdy_14.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("craftXp");
        fdy_14.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLP);
        fdy_14.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("craftXp");
        fsj_23.setName("recipeView");
        fdy_14.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(16, 14));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("xpIcon");
        faw_26.X(fbt_12);
        fbt_12.guy();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 3, 0, 0));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        String string2 = "xpGainPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_26.X(frx_12);
        frx_12.guy();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setPrefSize(new fsm_1(10, 0));
        faw_27.setStyle("popup");
        frx_12.X(faw_27);
        faw_27.guy();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        fdy_16.setExpandable(false);
        fdy_16.setStyle("white");
        String string3 = "%craft.base.xp%";
        string3 = string3.replace("%craft.base.xp%", fyw_0.gqw().k("craft.base.xp", new Object[0]));
        fdy_16.setText(string3);
        faw_27.X(fdy_16);
        fdy_16.guy();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq4 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlign(faa_2.tLN);
        fdy_16.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fdy_16.onChildrenAdded();
        fdy_1 fdy_18 = new fdy_1();
        fdy_18.aVI();
        fdy_18.setElementMap(fhs_22);
        fdy_18.setStyle("white");
        fdy_18.setText("craftXp");
        faw_27.X(fdy_18);
        fdy_18.guy();
        fdy_1 fdy_19 = fdy_18;
        fzq fzq5 = (fzq)((fes_2)fdy_19).getAppearance();
        fzq5.setElementMap(fhs_22);
        fzq5.setAlign(faa_2.tLN);
        fdy_18.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("baseCraftXp");
        fsj_24.setName("recipeView");
        fdy_18.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_18.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setDisplaySize(new fsm_1(16, 14));
        fbt_14.setExpandable(false);
        fbt_14.setNonBlocking(true);
        fbt_14.setStyle("xpIcon");
        faw_27.X(fbt_14);
        fbt_14.guy();
        fbt_1 fbt_15 = fbt_14;
        fyY fyY3 = (fyY)((fes_2)fbt_15).getAppearance();
        fyY3.setElementMap(fhs_22);
        fbt_14.X(fyY3);
        fyY3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 3, 0, 0));
        fyY3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fyY3.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_27.onChildrenAdded();
        frx_12.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("visible");
        fsj_25.setField("isConceptual");
        fsj_25.setLocal(true);
        fsj_25.setName("craft");
        faw_26.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_25.X(fjt_23);
        fjt_23.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_23.X(fjn_22);
        fjn_22.guy();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_22);
        fjn_22.X(fjw_23);
        fjw_23.guy();
        fjw_23.onChildrenAdded();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_22);
        fjn_22.X(fjn_23);
        fjn_23.guy();
        fjp_1 fjp_12 = new fjp_1();
        fjp_12.aVI();
        fjp_12.setElementMap(fhs_22);
        fjp_12.setValue("0");
        fjn_23.X(fjp_12);
        fjp_12.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("comparedValue");
        fsd_14.setField("craftXp");
        fjp_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fjp_12.onChildrenAdded();
        fjp_1 fjp_13 = new fjp_1();
        fjp_13.aVI();
        fjp_13.setElementMap(fhs_22);
        fjp_13.setValue("0");
        fjn_23.X(fjp_13);
        fjp_13.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("comparedValue");
        fsd_15.setField("productionPercentageValue");
        fjp_13.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fjp_13.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_25.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(22, 0));
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 3, 0, 3));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setVisible(false);
        faw_23.X(faw_25);
        faw_25.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_25.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("canUseAsIngredient");
        faw_25.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        String string = "displayLinkedRecipesButton";
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fad_12);
        }
        fad_12.setStyle("yellowSmall");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.crafts:displayRecipesWithIngredient(recipe)");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(displayLinkedRecipesPopup,displayLinkedRecipesButton)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        faw_25.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(16, 16));
        fbt_12.setNonBlocking(true);
        fbt_12.setStyle("passportRecipesDone");
        faw_25.X(fbt_12);
        fbt_12.guy();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(3, 3, 3, 3));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(-2, -2));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_25.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        faw_23.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_22.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new fhl_2("oddCellColor"));
        fys_02.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        return fys_02;
    }

    public fhi_2 n(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 r(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(200, 200));
        frp_12.setXOffset(-120);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 N(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "displayLinkedRecipesPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fey_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("white");
        String string2 = "%craft.displayLinkedRecipes%";
        string2 = string2.replace("%craft.displayLinkedRecipes%", fyw_0.gqw().k("craft.displayLinkedRecipes", new Object[0]));
        fdy_12.setText(string2);
        faw_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }
}

