/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cOZ
 */
public class coz_1
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.setPack(true);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_27.setExpandable(false);
        faw_25.X(faw_27);
        faw_27.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_27.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string = "%tutorials%";
        string = string.replace("%tutorials%", fyw_0.gqw().k("tutorials", new Object[0]));
        fbv_22.setText(string);
        faw_27.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlignment(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 0, 0, 5));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_23.X(faw_28);
        faw_28.guy();
        faw_2 faw_29 = faw_28;
        fys_0 fys_05 = ((fes_2)faw_29).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_28.X(fys_05);
        fys_05.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_210);
        }
        faw_28.X(faw_210);
        faw_210.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_210.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_211 = faw_210;
        fys_0 fys_06 = ((fes_2)faw_211).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_210.X(fys_06);
        fys_06.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(10, 0, 0, 0));
        fys_06.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_06.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setStyle("ScrollString");
        faw_210.X(faw_212);
        faw_212.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLh);
        frp_14.setSize(new fsm_1(10, 100.0f));
        frp_14.setXOffset(-11);
        faw_212.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_213 = faw_212;
        fys_0 fys_07 = ((fes_2)faw_213).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_212.X(fys_07);
        fys_07.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(60, 0, 60, 0));
        fys_07.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_07.onChildrenAdded();
        faw_212.onChildrenAdded();
        fcq_2 fcq_22 = new fcq_2();
        fcq_22.aVI();
        fcq_22.setElementMap(fhs_23);
        fcq_22.setExpandable(false);
        fcq_22.setHorizontalScrollBarBehaviour(fzi_0.tHc);
        fcq_22.setPageJumpRatio(0.3f);
        fcq_22.setStyle("Encyclopedia");
        fcq_22.setVerticalScrollBarBehaviour(fzi_0.tHb);
        faw_210.X(fcq_22);
        fcq_22.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        fcq_22.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fcq_2 fcq_23 = fcq_22;
        fys_0 fys_08 = ((fes_2)fcq_23).getAppearance();
        fys_08.setElementMap(fhs_23);
        fcq_22.X(fys_08);
        fys_08.guy();
        fzx fzx5 = new fzx();
        fzx5.aVI();
        fzx5.setElementMap(fhs_23);
        fzx5.setInsets(new Insets(0, 10, 0, 0));
        fys_08.X(fzx5);
        fzx5.guy();
        fzx5.onChildrenAdded();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(35, 3, 45, 0));
        fys_08.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_08.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setExpandable(false);
        faw_214.setPrefSize(new fsm_1(390, 370));
        faw_214.setStyle("tiledScroll");
        fcq_22.X(faw_214);
        faw_214.guy();
        faw_2 faw_215 = faw_214;
        fys_0 fys_09 = ((fes_2)faw_215).getAppearance();
        fys_09.setElementMap(fhs_23);
        faw_214.X(fys_09);
        fys_09.guy();
        fzx fzx6 = new fzx();
        fzx6.aVI();
        fzx6.setElementMap(fhs_23);
        fzx6.setInsets(new Insets(5, 0, 0, 0));
        fys_09.X(fzx6);
        fzx6.guy();
        fzx6.onChildrenAdded();
        fzv fzv7 = fzv.checkOut();
        fzv7.setElementMap(fhs_23);
        fzv7.setInsets(new Insets(0, 0, 0, 5));
        fys_09.X(fzv7);
        fzv7.guy();
        fzv7.onChildrenAdded();
        fys_09.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_214.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setExpandable(false);
        faw_216.setPrefSize(new fsm_1(0, 30));
        faw_216.setStyle("EncyclopediaSplashTitle");
        faw_214.X(faw_216);
        faw_216.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_23);
        frb_13.setAlign(faa_2.tLO);
        faw_216.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        faw_2 faw_217 = faw_216;
        fys_0 fys_010 = ((fes_2)faw_217).getAppearance();
        fys_010.setElementMap(fhs_23);
        faw_216.X(fys_010);
        fys_010.guy();
        fzx fzx7 = new fzx();
        fzx7.aVI();
        fzx7.setElementMap(fhs_23);
        fzx7.setInsets(new Insets(0, 15, 3, 15));
        fys_010.X(fzx7);
        fzx7.guy();
        fzx7.onChildrenAdded();
        fzv fzv8 = fzv.checkOut();
        fzv8.setElementMap(fhs_23);
        fzv8.setInsets(new Insets(5, 0, 0, 0));
        fys_010.X(fzv8);
        fzv8.guy();
        fzv8.onChildrenAdded();
        fys_010.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLO);
        faw_216.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setExpandable(false);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("StyledBold16White");
        String string3 = "%upgrades%";
        string3 = string3.replace("%upgrades%", fyw_0.gqw().k("upgrades", new Object[0]));
        fdy_12.setText(string3);
        faw_216.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setField("currentPage/name");
        fsj_22.setName("tutorialBook");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("visible");
        fsj_23.setField("hasSearch");
        fsj_23.setName("tutorialBook");
        faw_216.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        faw_216.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setExpandable(false);
        faw_218.setPrefSize(new fsm_1(0, 30));
        faw_218.setStyle("EncyclopediaSplashTitle");
        faw_214.X(faw_218);
        faw_218.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_23);
        frb_14.setAlign(faa_2.tLO);
        faw_218.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        faw_2 faw_219 = faw_218;
        fys_0 fys_011 = ((fes_2)faw_219).getAppearance();
        fys_011.setElementMap(fhs_23);
        faw_218.X(fys_011);
        fys_011.guy();
        fzx fzx8 = new fzx();
        fzx8.aVI();
        fzx8.setElementMap(fhs_23);
        fzx8.setInsets(new Insets(0, 0, 3, 0));
        fys_011.X(fzx8);
        fzx8.guy();
        fzx8.onChildrenAdded();
        fzv fzv9 = fzv.checkOut();
        fzv9.setElementMap(fhs_23);
        fzv9.setInsets(new Insets(5, 0, 0, 0));
        fys_011.X(fzv9);
        fzv9.guy();
        fzv9.onChildrenAdded();
        fys_011.onChildrenAdded();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLO);
        faw_218.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_23);
        fdy_13.setExpandable(false);
        fdy_13.setNonBlocking(true);
        fdy_13.setStyle("StyledBold16White");
        String string4 = "%upgrades%";
        string4 = string4.replace("%upgrades%", fyw_0.gqw().k("upgrades", new Object[0]));
        fdy_13.setText(string4);
        faw_218.X(fdy_13);
        fdy_13.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("searchResult");
        fsj_24.setName("tutorialBook");
        fdy_13.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_13.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setField("hasSearch");
        fsj_25.setName("tutorialBook");
        faw_218.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        faw_218.onChildrenAdded();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_23);
        fdf_12.setClickSoundId(600117);
        fdf_12.setHorizontal(false);
        fdf_12.setInnerExpandable(false);
        faw_214.X(fdf_12);
        fdf_12.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(100.0f, 100.0f));
        fdf_12.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLL);
        frz_27.setHorizontal(false);
        fdf_12.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        fdf_1 fdf_13 = fdf_12;
        fza fza2 = (fza)((fes_2)fdf_13).getAppearance();
        fza2.setElementMap(fhs_23);
        fdf_12.X(fza2);
        fza2.guy();
        fzv fzv10 = fzv.checkOut();
        fzv10.setElementMap(fhs_23);
        fzv10.setInsets(new Insets(0, 0, 30, 10));
        fza2.X(fzv10);
        fzv10.guy();
        fzv10.onChildrenAdded();
        fza2.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("content");
        fsj_26.setField("tutorials");
        fsj_26.setName("tutorialBook");
        fdf_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_23);
        fmo_2 fmo_22 = new fmo_2();
        fmo_22.vw("wakfu.tutorialBook:launchTutorial");
        fje_22.setOnItemClick(fmo_22);
        fdf_12.X(fje_22);
        fje_22.guy();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        fje_22.X(faw_220);
        faw_220.guy();
        String string5 = "selectedTutorial";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, frv_12);
        }
        faw_220.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_23);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_220.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_221 = faw_2.checkOut();
        faw_221.setElementMap(fhs_23);
        faw_221.setNonBlocking(false);
        faw_220.X(faw_221);
        faw_221.guy();
        this.R(faw_221);
        this.c(faw_221);
        this.d(faw_221);
        this.e(faw_221);
        faw_221.onChildrenAdded();
        faw_220.onChildrenAdded();
        fje_22.onChildrenAdded();
        fdf_12.onChildrenAdded();
        faw_214.onChildrenAdded();
        fcq_22.onChildrenAdded();
        this.F(faw_210);
        this.G(faw_210);
        this.f(faw_210);
        this.g(faw_210);
        faw_210.onChildrenAdded();
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.O(fey_22);
        this.P(fey_22);
        this.t(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 c(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        return null;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setPrefSize(new fsm_1(0, 30));
        faw_24.setStyle("TiledScrollCenter");
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLf);
        frp_13.setSize(new fsm_1(100.0f, -2));
        faw_24.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        faw_24.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setStyle("TiledScrollTop");
        faw_23.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tKY);
        frp_14.setSize(new fsm_1(100.0f, -2));
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setStyle("TiledScrollBottom");
        faw_23.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLk);
        frp_15.setSize(new fsm_1(100.0f, -2));
        fbt_13.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_13.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setMaxWidth(280);
        fbv_22.setStyle("darkBold");
        faw_23.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLf);
        fbv_22.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        fdd_22.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.tutorialBook:launchTutorial(selectedTutorial)");
        fdd_22.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(launchTutorialPopup)");
        fdd_22.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fdd_22.setOnPopupHide(fml_12);
        fdd_22.setStyle("eye");
        faw_22.X(fdd_22);
        fdd_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        fdd_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fdd_2 fdd_23 = fdd_22;
        fzs fzs2 = (fzs)((fes_2)fdd_23).getAppearance();
        fzs2.setElementMap(fhs_22);
        fdd_22.X(fzs2);
        fzs2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 0, 3));
        fzs2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzs2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("selected");
        fsd_12.setField("isLaunched");
        fdd_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        String string = "launchTutorialPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fdd_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("isLaunched");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        String string2 = "%tutorial.launch%";
        string2 = string2.replace("%tutorial.launch%", fyw_0.gqw().k("tutorial.launch", new Object[0]));
        fjt_22.setElseValue(string2);
        String string3 = "%tutorial.stop%";
        string3 = string3.replace("%tutorial.stop%", fyw_0.gqw().k("tutorial.stop", new Object[0]));
        fjt_22.setValue(string3);
        fsd_13.X(fjt_22);
        fjt_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_13.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        fdd_22.onChildrenAdded();
        return fdd_22;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.tutorialBook:clearSearch(tutorialSearch)");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(goBackPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("AchievementsGoBack");
        faw_22.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("hasSearch");
        fsj_22.setName("tutorialBook");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        String string = "goBackPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setPrefSize(new fsm_1(10, 0));
        faw_23.setStyle("popup");
        frx_12.X(faw_23);
        faw_23.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_23.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        String string2 = "%back%";
        string2 = string2.replace("%back%", fyw_0.gqw().k("back", new Object[0]));
        fbv_22.setText(string2);
        faw_23.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_23.onChildrenAdded();
        frx_12.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setXOffset(-40);
        frp_12.setYOffset(-50);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("visible");
        fsj_23.setName("searchActive");
        fad_12.X(fsj_23);
        fsj_23.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_23.X(fjt_22);
        fjt_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_23.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(true);
        faw_23.setStyle("EncyclopediaPane");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setSize(new fsm_1(454, 525));
        frp_12.setXOffset(-10);
        frp_12.setYOffset(1);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(20, 0, 30, 3));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tKY);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 20, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(true);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        String string = "tutorialSearch";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fdu_12);
        }
        String string2 = "%tutorialBook.search%";
        string2 = string2.replace("%tutorialBook.search%", fyw_0.gqw().k("tutorialBook.search", new Object[0]));
        fdu_12.tX(string2);
        fdu_12.abk(256);
        fmt_2 fmt_22 = new fmt_2();
        fmt_22.vw("wakfu.tutorialBook:searchTutorial");
        fdu_12.setOnKeyRelease(fmt_22);
        fdu_12.setPrefSize(new fsm_1(200, 0));
        fdu_12.setRestrict("[.*&[^<>]]");
        faw_23.X(fdu_12);
        fdu_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fdu_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(450, 0));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 5, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("hasSearch");
        fsj_22.setName("tutorialBook");
        faw_23.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setClickSoundId(600014);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.tutorialBook:setPreviousTutorialPage");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(previousTutorialsPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("characterCreationLeftArrow");
        faw_23.X(fad_12);
        fad_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("enabled");
        fsj_23.setField("hasPreviousPage");
        fsj_23.setName("tutorialBook");
        fad_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        String string = "previousTutorialsPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setPrefSize(new fsm_1(10, 0));
        faw_25.setStyle("popup");
        frx_12.X(faw_25);
        faw_25.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("PopupInformation");
        String string2 = "%tutorials.previousTutorials%";
        string2 = string2.replace("%tutorials.previousTutorials%", fyw_0.gqw().k("tutorials.previousTutorials", new Object[0]));
        fbv_22.setText(string2);
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        frx_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setPrefSize(new fsm_1(75, 0));
        fbv_24.setStyle("title");
        faw_23.X(fbv_24);
        fbv_24.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("numPages");
        fsj_24.setName("tutorialBook");
        fbv_24.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLO);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setClickSoundId(600015);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.tutorialBook:setNextTutorialPage");
        fad_13.setOnClick(fmz_13);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(nextTutorialsPopup)");
        fad_13.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fad_13.setOnPopupHide(fml_13);
        fad_13.setStyle("characterCreationRightArrow");
        faw_23.X(fad_13);
        fad_13.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("enabled");
        fsj_25.setField("hasNextPage");
        fsj_25.setName("tutorialBook");
        fad_13.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        String string3 = "nextTutorialsPopup";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, frx_13);
        }
        frx_13.setAlign(faa_2.tLL);
        frx_13.setHotSpotPosition(faa_2.tLR);
        fad_13.X(frx_13);
        frx_13.guy();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setPrefSize(new fsm_1(10, 0));
        faw_26.setStyle("popup");
        frx_13.X(faw_26);
        faw_26.guy();
        fbv_2 fbv_26 = new fbv_2();
        fbv_26.aVI();
        fbv_26.setElementMap(fhs_22);
        fbv_26.setStyle("PopupInformation");
        String string4 = "%tutorials.nextTutorials%";
        string4 = string4.replace("%tutorials.nextTutorials%", fyw_0.gqw().k("tutorials.nextTutorials", new Object[0]));
        fbv_26.setText(string4);
        faw_26.X(fbv_26);
        fbv_26.guy();
        fbv_2 fbv_27 = fbv_26;
        fzq fzq4 = (fzq)((fes_2)fbv_27).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlign(faa_2.tLN);
        fbv_26.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fbv_26.onChildrenAdded();
        faw_26.onChildrenAdded();
        frx_13.onChildrenAdded();
        fad_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 O(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 P(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("unloadDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 t(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setResizeOnce(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

