/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cPg
 */
public class cpg_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_25.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_27 = faw_25;
        fys_0 fys_05 = ((fes_2)faw_27).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_25.X(fys_05);
        fys_05.guy();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_23);
        fzx4.setInsets(new Insets(10, 0, 10, 5));
        fys_05.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fys_05.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_23);
        faw_28.setExpandable(false);
        faw_25.X(faw_28);
        faw_28.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        faw_28.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLP);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 20, 0, 20));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("text");
        fsj_22.setName("voteList");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        String string = "%vote.title%";
        string = string.replace("%vote.title%", fyw_0.gqw().k("vote.title", new Object[0]));
        fjt_22.setElseValue(string);
        String string2 = "%nation.electionResults%";
        string2 = string2.replace("%nation.electionResults%", fyw_0.gqw().k("nation.electionResults", new Object[0]));
        fjt_22.setValue(string2);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_23);
        fjt_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_23);
        faw_28.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_23);
        fbv_24.setExpandable(false);
        fbv_24.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(feeWarningPopup)");
        fbv_24.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbv_24.setOnPopupHide(fml_12);
        fbv_24.setStyle("StyledBold16White");
        fbv_24.setText("?");
        faw_28.X(fbv_24);
        fbv_24.guy();
        String string3 = "feeWarningPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbv_24.X(frx_12);
        frx_12.guy();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        faw_29.setPrefSize(new fsm_1(10, 0));
        faw_29.setStyle("popup");
        frx_12.X(faw_29);
        faw_29.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKA);
        faw_29.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setHorizontal(false);
        faw_29.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setMaxWidth(400);
        fdy_12.setStyle("white");
        faw_29.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("text");
        fsj_23.setName("voteInscription.feeWarning");
        fdy_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_29.onChildrenAdded();
        frx_12.onChildrenAdded();
        fbv_2 fbv_25 = fbv_24;
        fzq fzq3 = (fzq)((fes_2)fbv_25).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlign(faa_2.tLN);
        fbv_24.X(fzq3);
        fzq3.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 0, 0, 20));
        fzq3.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fzq3.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_28.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_23);
        fdy_13.setExpandable(false);
        fdy_13.setNonBlocking(true);
        fdy_13.setStyle("whiteBold");
        faw_25.X(fdy_13);
        fdy_13.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("text");
        fsj_24.setField("electionClosureDescription");
        fsj_24.setName("nation");
        fdy_13.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setName("voteList");
        fdy_13.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_23);
        fsj_25.X(fjt_23);
        fjt_23.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_23);
        fjt_23.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq4 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLO);
        fdy_13.X(fzq4);
        fzq4.guy();
        fzq4.onChildrenAdded();
        fdy_13.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_25.X(faw_210);
        faw_210.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLO);
        faw_210.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setExpandable(false);
        faw_210.X(faw_211);
        faw_211.guy();
        fdy_1 fdy_15 = new fdy_1();
        fdy_15.aVI();
        fdy_15.setElementMap(fhs_23);
        fdy_15.setExpandable(false);
        fdy_15.setNonBlocking(true);
        fdy_15.setStyle("whiteBold");
        faw_211.X(fdy_15);
        fdy_15.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("text");
        fsj_26.setField("electionTotalVotes");
        fsj_26.setName("nation");
        fdy_15.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fdy_15.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_212.setExpandable(false);
        faw_210.X(faw_212);
        faw_212.guy();
        faw_2 faw_213 = faw_212;
        fys_0 fys_06 = ((fes_2)faw_213).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_212.X(fys_06);
        fys_06.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(0, 10, 0, 0));
        fys_06.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_06.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_23);
        fdy_16.setExpandable(false);
        fdy_16.setNonBlocking(true);
        fdy_16.setStyle("whiteBold");
        faw_212.X(fdy_16);
        fdy_16.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("text");
        fsj_27.setField("electionTotalCandidates");
        fsj_27.setName("nation");
        fdy_16.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_23.X(faw_214);
        faw_214.guy();
        faw_2 faw_215 = faw_214;
        fys_0 fys_07 = ((fes_2)faw_215).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_214.X(fys_07);
        fys_07.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 12, 0, 12));
        fys_07.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fys_07.onChildrenAdded();
        String string4 = "windowContentContainer";
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, faw_216);
        }
        faw_214.X(faw_216);
        faw_216.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLL);
        frz_26.setHorizontal(false);
        faw_216.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        faw_2 faw_217 = faw_2.checkOut();
        faw_217.setElementMap(fhs_23);
        faw_217.setExpandable(false);
        faw_216.X(faw_217);
        faw_217.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_217.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("visible");
        fsj_28.setName("voteList");
        faw_217.X(fsj_28);
        fsj_28.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_23);
        fsj_28.X(fjt_24);
        fjt_24.guy();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_23);
        fjt_24.X(fjw_23);
        fjw_23.guy();
        fjw_23.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_28.onChildrenAdded();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_217.X(faw_218);
        faw_218.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLa);
        frp_14.setSize(new fsm_1(100.0f, -2));
        faw_218.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_218.X(faw_219);
        faw_219.guy();
        frz_2 frz_27 = frz_2.checkOut();
        frz_27.setAlign(faa_2.tLN);
        faw_219.X(frz_27);
        frz_27.guy();
        frz_27.onChildrenAdded();
        faw_2 faw_220 = faw_2.checkOut();
        faw_220.setElementMap(fhs_23);
        faw_220.setExpandable(false);
        faw_219.X(faw_220);
        faw_220.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_220.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setStyle("Portrait");
        faw_220.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(87, 102));
        fbt_12.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_221 = faw_2.checkOut();
        faw_221.setElementMap(fhs_23);
        faw_221.setNeedsScissor(true);
        faw_220.X(faw_221);
        faw_221.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(55, 68));
        frp_16.setXOffset(-1);
        faw_221.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_23);
        fax_12.setAnimName("AnimStatique");
        fax_12.setDirection(2);
        fax_12.setOffsetX(0.0f);
        fax_12.setOffsetY(-125.0f);
        fax_12.setScale(2.2f);
        faw_221.X(fax_12);
        fax_12.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("animatedElement");
        fsj_29.setField("actorDescriptorLibrary");
        fsj_29.setName("localPlayer");
        fax_12.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_23);
        fsj_210.setAttribute("equipment");
        fsj_210.setField("actorEquipment");
        fsj_210.setName("localPlayer");
        fax_12.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_221.onChildrenAdded();
        faw_220.onChildrenAdded();
        this.R(faw_219);
        faw_219.onChildrenAdded();
        faw_218.onChildrenAdded();
        faw_217.onChildrenAdded();
        this.I(faw_216);
        faw_216.onChildrenAdded();
        faw_214.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.s(fey_22);
        this.aL(fey_22);
        this.E(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 R(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_23.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setStyle("titleBar");
        faw_24.X(faw_25);
        faw_25.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_25.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setExpandable(false);
        faw_24.X(faw_26);
        faw_26.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLg);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_26.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        faw_2 faw_27 = faw_26;
        fys_0 fys_02 = ((fes_2)faw_27).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_26.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 2, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 9, 2, 9));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setMaxWidth(150);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        faw_26.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("name");
        fsj_22.setName("localPlayer");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_26.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(false);
        fbv_24.setStyle("whiteBold");
        String string = "%nation.rank%%colon%";
        string = string.replace("%nation.rank%", fyw_0.gqw().k("nation.rank", new Object[0]));
        string = string.replace("%colon%", fyw_0.gqw().k("colon", new Object[0]));
        fbv_24.setText(string);
        faw_26.X(fbv_24);
        fbv_24.guy();
        fbv_24.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setExpandable(false);
        fbv_25.setStyle("whiteBold");
        faw_26.X(fbv_25);
        fbv_25.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("nation/nativeNationCitizenScore/rankDescription");
        fsj_23.setName("localPlayer");
        fbv_25.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setExpandable(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(feeWarningPopup)");
        faw_28.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_28.setOnPopupHide(fml_12);
        faw_23.X(faw_28);
        faw_28.guy();
        String string2 = "feeWarningPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_28.X(frx_12);
        frx_12.guy();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setPrefSize(new fsm_1(10, 0));
        faw_29.setStyle("popup");
        frx_12.X(faw_29);
        faw_29.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("visible");
        fsj_24.setField("nation/canApplyForGovernorConcerningCrimes");
        fsj_24.setName("localPlayer");
        faw_29.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_24.X(fjt_22);
        fjt_22.guy();
        fjg_2 fjg_22 = new fjg_2();
        fjg_22.aVI();
        fjg_22.setElementMap(fhs_22);
        fjt_22.X(fjg_22);
        fjg_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjg_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_22);
        fjg_22.X(fjw_23);
        fjw_23.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("comparedValue");
        fsj_25.setField("candidateRegistrationFee");
        fsj_25.setName("nation");
        fjw_23.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_25.X(fjt_23);
        fjt_23.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjt_23.X(fja_12);
        fja_12.guy();
        fjp_1 fjp_12 = new fjp_1();
        fjp_12.aVI();
        fjp_12.setElementMap(fhs_22);
        fja_12.X(fjp_12);
        fjp_12.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("value");
        fsj_26.setField("kamas");
        fsj_26.setName("localPlayer");
        fjp_12.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fjp_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fjw_23.onChildrenAdded();
        fjg_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_29.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_29.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMinWidth(300);
        fdy_12.setStyle("white");
        faw_29.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("text");
        fsj_27.setField("nation/candidateRegistrationWarningInfo");
        fsj_27.setName("localPlayer");
        fdy_12.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_22);
        fdy_12.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new awx_2(1.0f, 0.0f, 0.0f, 1.0f));
        fzq3.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_29.onChildrenAdded();
        frx_12.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLL);
        frz_24.setHorizontal(false);
        faw_28.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_210.setExpandable(false);
        faw_28.X(faw_210);
        faw_210.guy();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setAlign(faa_2.tLN);
        faw_210.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        String string3 = "slogan";
        fdu_1 fdu_12 = new fdu_1();
        fdu_12.aVI();
        fdu_12.setElementMap(fhs_22);
        if (fhs_22 != null && string3 != null) {
            fhs_22.a(string3, fdu_12);
        }
        String string4 = "%voteInscription.slogan%";
        string4 = string4.replace("%voteInscription.slogan%", fyw_0.gqw().k("voteInscription.slogan", new Object[0]));
        fdu_12.tX(string4);
        fdu_12.abk(200);
        fdu_12.setMaxWidth(200);
        fdu_12.setMultiline(true);
        fms_2 fms_22 = new fms_2();
        fms_22.vw("wakfu.voteInformation:onKeyPress");
        fdu_12.setOnKeyPress(fms_22);
        fdu_12.setPrefSize(new fsm_1(0, 55));
        fdu_12.setSelectOnFocus(true);
        faw_210.X(fdu_12);
        fdu_12.guy();
        fdu_1 fdu_13 = fdu_12;
        fzq fzq4 = (fzq)((fes_2)fdu_13).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlign(faa_2.tLK);
        fdu_12.X(fzq4);
        fzq4.guy();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_22);
        fsj_28.setAttribute("modulationColor");
        fsj_28.setField("nation/canApplyForGovernorConcerningCrimes");
        fsj_28.setName("localPlayer");
        fzq4.X(fsj_28);
        fsj_28.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fjt_24.setElseValue("0.7,0.7,0.7,1");
        fjt_24.setValue("1,1,1,1");
        fsj_28.X(fjt_24);
        fjt_24.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_24.X(fjn_22);
        fjn_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjn_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_22);
        fjn_22.X(fjl_13);
        fjl_13.guy();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_22);
        fsj_29.setAttribute("comparedValue");
        fsj_29.setField("candidateRegistrationFee");
        fsj_29.setName("nation");
        fjl_13.X(fsj_29);
        fsj_29.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fsj_29.X(fjt_25);
        fjt_25.guy();
        fja_1 fja_13 = new fja_1();
        fja_13.aVI();
        fja_13.setElementMap(fhs_22);
        fjt_25.X(fja_13);
        fja_13.guy();
        fjp_1 fjp_13 = new fjp_1();
        fjp_13.aVI();
        fjp_13.setElementMap(fhs_22);
        fja_13.X(fjp_13);
        fjp_13.guy();
        fsj_2 fsj_210 = fsj_2.checkOut();
        fsj_210.setElementMap(fhs_22);
        fsj_210.setAttribute("value");
        fsj_210.setField("kamas");
        fsj_210.setName("localPlayer");
        fjp_13.X(fsj_210);
        fsj_210.guy();
        fsj_210.onChildrenAdded();
        fjp_13.onChildrenAdded();
        fja_13.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsj_29.onChildrenAdded();
        fjl_13.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_28.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsj_2 fsj_211 = fsj_2.checkOut();
        fsj_211.setElementMap(fhs_22);
        fsj_211.setAttribute("editable");
        fsj_211.setField("nation/canApplyForGovernorConcerningCrimes");
        fsj_211.setName("localPlayer");
        fdu_12.X(fsj_211);
        fsj_211.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_22);
        fsj_211.X(fjt_26);
        fjt_26.guy();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_22);
        fjt_26.X(fjn_23);
        fjn_23.guy();
        fjl_1 fjl_14 = new fjl_1();
        fjl_14.aVI();
        fjl_14.setElementMap(fhs_22);
        fjn_23.X(fjl_14);
        fjl_14.guy();
        fjl_14.onChildrenAdded();
        fjl_1 fjl_15 = new fjl_1();
        fjl_15.aVI();
        fjl_15.setElementMap(fhs_22);
        fjn_23.X(fjl_15);
        fjl_15.guy();
        fsj_2 fsj_212 = fsj_2.checkOut();
        fsj_212.setElementMap(fhs_22);
        fsj_212.setAttribute("comparedValue");
        fsj_212.setField("candidateRegistrationFee");
        fsj_212.setName("nation");
        fjl_15.X(fsj_212);
        fsj_212.guy();
        fjt_2 fjt_27 = new fjt_2();
        fjt_27.aVI();
        fjt_27.setElementMap(fhs_22);
        fsj_212.X(fjt_27);
        fjt_27.guy();
        fja_1 fja_14 = new fja_1();
        fja_14.aVI();
        fja_14.setElementMap(fhs_22);
        fjt_27.X(fja_14);
        fja_14.guy();
        fjp_1 fjp_14 = new fjp_1();
        fjp_14.aVI();
        fjp_14.setElementMap(fhs_22);
        fja_14.X(fjp_14);
        fjp_14.guy();
        fsj_2 fsj_213 = fsj_2.checkOut();
        fsj_213.setElementMap(fhs_22);
        fsj_213.setAttribute("value");
        fsj_213.setField("kamas");
        fsj_213.setName("localPlayer");
        fjp_14.X(fsj_213);
        fsj_213.guy();
        fsj_213.onChildrenAdded();
        fjp_14.onChildrenAdded();
        fja_14.onChildrenAdded();
        fjt_27.onChildrenAdded();
        fsj_212.onChildrenAdded();
        fjl_15.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjt_26.onChildrenAdded();
        fsj_211.onChildrenAdded();
        fdu_12.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_210.X(faw_211);
        faw_211.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_211.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.voteInformation:validate(slogan)");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(feeWarningPopup2)");
        fad_12.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        fad_12.setOnPopupHide(fml_13);
        fad_12.setStyle("book");
        faw_211.X(fad_12);
        fad_12.guy();
        String string5 = "feeWarningPopup2";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_22);
        if (fhs_22 != null && string5 != null) {
            fhs_22.a(string5, frx_13);
        }
        frx_13.setAlign(faa_2.tLL);
        frx_13.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_13);
        frx_13.guy();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setPrefSize(new fsm_1(10, 0));
        faw_212.setStyle("popup");
        frx_13.X(faw_212);
        faw_212.guy();
        fsj_2 fsj_214 = fsj_2.checkOut();
        fsj_214.setElementMap(fhs_22);
        fsj_214.setAttribute("visible");
        fsj_214.setField("nation/canApplyForGovernorConcerningCrimes");
        fsj_214.setName("localPlayer");
        faw_212.X(fsj_214);
        fsj_214.guy();
        fjt_2 fjt_28 = new fjt_2();
        fjt_28.aVI();
        fjt_28.setElementMap(fhs_22);
        fsj_214.X(fjt_28);
        fjt_28.guy();
        fjg_2 fjg_23 = new fjg_2();
        fjg_23.aVI();
        fjg_23.setElementMap(fhs_22);
        fjt_28.X(fjg_23);
        fjg_23.guy();
        fjw_2 fjw_24 = new fjw_2();
        fjw_24.aVI();
        fjw_24.setElementMap(fhs_22);
        fjg_23.X(fjw_24);
        fjw_24.guy();
        fjw_24.onChildrenAdded();
        this.f(fjg_23);
        fjg_23.onChildrenAdded();
        fjt_28.onChildrenAdded();
        fsj_214.onChildrenAdded();
        this.d(faw_212);
        this.e(faw_212);
        this.F(faw_212);
        faw_212.onChildrenAdded();
        frx_13.onChildrenAdded();
        this.G(fad_12);
        this.H(fad_12);
        fad_12.onChildrenAdded();
        this.g(faw_211);
        faw_211.onChildrenAdded();
        faw_210.onChildrenAdded();
        this.H(faw_28);
        faw_28.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 f(fjg_2 fjg_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjg_22.X(fjw_22);
        fjw_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("comparedValue");
        fsj_22.setField("candidateRegistrationFee");
        fsj_22.setName("nation");
        fjw_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fja_1 fja_12 = new fja_1();
        fja_12.aVI();
        fja_12.setElementMap(fhs_22);
        fjt_22.X(fja_12);
        fja_12.guy();
        fjp_1 fjp_12 = new fjp_1();
        fjp_12.aVI();
        fjp_12.setElementMap(fhs_22);
        fja_12.X(fjp_12);
        fjp_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("value");
        fsj_23.setField("kamas");
        fsj_23.setName("localPlayer");
        fjp_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fjp_12.onChildrenAdded();
        fja_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fjw_22.onChildrenAdded();
        return fjw_22;
    }

    public fhi_2 d(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        return fru_12;
    }

    public fhi_2 e(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        return null;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMaxWidth(120);
        fdy_12.setStyle("white");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("nation/candidateRegistrationWarningInfo");
        fsj_22.setName("localPlayer");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new awx_2(1.0f, 0.0f, 0.0f, 1.0f));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 G(fad_1 fad_12) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 H(fad_1 fad_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("enabled");
        fsj_22.setName("electionSloganDirty");
        fad_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 g(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("title");
        String string = "%voteInscription.validate%";
        string = string.replace("%voteInscription.validate%", fyw_0.gqw().k("voteInscription.validate", new Object[0]));
        fbv_22.setText(string);
        faw_22.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("defaultBlackColor"));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 H(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("bold");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setName("electionSloganLength");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 I(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(435, 510));
        faw_22.X(faw_23);
        faw_23.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_24.setStyle("tiledScroll");
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        frp_12.setYOffset(3);
        faw_24.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(30, 22, 25, 20));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(15, 0, 135, 0));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("bold");
        String string = "%voteInformation.noCandidate%";
        string = string.replace("%voteInformation.noCandidate%", fyw_0.gqw().k("voteInformation.noCandidate", new Object[0]));
        fbv_22.setText(string);
        faw_24.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(5, 0, 5, 0));
        fzq2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fzq2.onChildrenAdded();
        fbv_2 fbv_24 = fbv_22;
        fzq fzq3 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLO);
        fbv_22.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("candidates");
        fsj_22.setName("nation");
        fbv_22.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsj_22.X(fjt_22);
        fjt_22.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjt_22.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_22.onChildrenAdded();
        fbv_22.onChildrenAdded();
        fdf_1 fdf_12 = new fdf_1();
        fdf_12.aVI();
        fdf_12.setElementMap(fhs_22);
        fdf_12.setExpandable(false);
        fdf_12.setHorizontal(false);
        fdf_12.setPrefSize(new fsm_1(365, 0));
        faw_24.X(fdf_12);
        fdf_12.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("content");
        fsj_23.setField("candidates");
        fsj_23.setName("nation");
        fdf_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("visible");
        fsj_24.setField("candidates");
        fsj_24.setName("nation");
        fdf_12.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_24.X(fjt_23);
        fjt_23.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_23.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fdf_1 fdf_13 = fdf_12;
        fza fza2 = (fza)((fes_2)fdf_13).getAppearance();
        fza2.setElementMap(fhs_22);
        fdf_12.X(fza2);
        fza2.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 3, 0, 3));
        fza2.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fza2.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fdf_12.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fje_22.X(fjt_24);
        fjt_24.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_24.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_13 = new fjd_1();
        fjd_13.aVI();
        fjd_13.setElementMap(fhs_22);
        fjx_12.X(fjd_13);
        fjd_13.guy();
        fjd_13.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_24.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        fje_22.X(faw_26);
        faw_26.guy();
        String string2 = "candidate";
        frv_1 frv_12 = new frv_1();
        frv_12.aVI();
        frv_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, frv_12);
        }
        faw_26.X(frv_12);
        frv_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("value");
        frv_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        frv_12.onChildrenAdded();
        faw_2 faw_27 = faw_26;
        fys_0 fys_03 = ((fes_2)faw_27).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_26.X(fys_03);
        fys_03.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(0, 15, 0, 0));
        fys_03.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_03.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_26.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_26.X(faw_28);
        faw_28.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLm);
        frp_13.setSize(new fsm_1(100.0f, 80.0f));
        faw_28.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("visible");
        fsd_13.setField("isGovernor");
        faw_28.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        faw_2 faw_29 = faw_28;
        fys_0 fys_04 = ((fes_2)faw_29).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_28.X(fys_04);
        fys_04.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new awx_2(0.75f, 0.6f, 0.0f, 0.5f));
        fys_04.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_04.onChildrenAdded();
        faw_28.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setExpandable(false);
        fbt_12.setStyle("TiledScrollBottom");
        faw_26.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLk);
        frp_14.setYOffset(-1);
        fbt_12.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("visible");
        fsd_14.setField("isGovernor");
        fbt_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_210.setExpandable(false);
        faw_26.X(faw_210);
        faw_210.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLf);
        faw_210.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setAlign(faa_2.tLL);
        frz_23.setHorizontal(false);
        faw_210.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_210.X(faw_211);
        faw_211.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_211.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setStyle("EncyclopediaSplashTitle");
        faw_211.X(faw_212);
        faw_212.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLf);
        frp_16.setSize(new fsm_1(300, 38));
        faw_212.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fro_1 fro_15 = new fro_1();
        fro_15.aVI();
        faw_212.X(fro_15);
        fro_15.guy();
        fro_15.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_22);
        faw_212.X(faw_213);
        faw_213.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_22);
        frp_17.setAlign(fzw_0.tLf);
        faw_213.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_213.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setExpandable(false);
        fbv_25.setMaxWidth(200);
        fbv_25.setStyle("StyledBold16White");
        faw_213.X(fbv_25);
        fbv_25.guy();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq4 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlignment(faa_2.tLN);
        fbv_25.X(fzq4);
        fzq4.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(0, 10, 5, 0));
        fzq4.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("modulationColor");
        fsd_15.setField("isEnabled");
        fzq4.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        fjt_25.setElseValue("0.7,0.7,0.7");
        fjt_25.setValue("1,1,1");
        fsd_15.X(fjt_25);
        fjt_25.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_25.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsd_15.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("text");
        fsd_16.setField("name");
        fbv_25.X(fsd_16);
        fsd_16.guy();
        fsd_16.onChildrenAdded();
        fsd_1 fsd_17 = new fsd_1();
        fsd_17.aVI();
        fsd_17.setElementMap(fhs_22);
        fsd_17.setAttribute("visible");
        fsd_17.setField("isGovernor");
        fbv_25.X(fsd_17);
        fsd_17.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_22);
        fsd_17.X(fjt_26);
        fjt_26.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_26.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_26.onChildrenAdded();
        fsd_17.onChildrenAdded();
        fbv_25.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_22);
        fbv_27.setExpandable(false);
        fbv_27.setMaxWidth(200);
        fbv_27.setStyle("StyledBold16White");
        faw_213.X(fbv_27);
        fbv_27.guy();
        fbv_2 fbv_28 = fbv_27;
        fzq fzq5 = (fzq)((fes_2)fbv_28).getAppearance();
        fzq5.setElementMap(fhs_22);
        fzq5.setAlignment(faa_2.tLN);
        fbv_27.X(fzq5);
        fzq5.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_22);
        fzv6.setInsets(new Insets(0, 10, 5, 0));
        fzq5.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fsd_1 fsd_18 = new fsd_1();
        fsd_18.aVI();
        fsd_18.setElementMap(fhs_22);
        fsd_18.setAttribute("modulationColor");
        fsd_18.setField("isEnabled");
        fzq5.X(fsd_18);
        fsd_18.guy();
        fjt_2 fjt_27 = new fjt_2();
        fjt_27.aVI();
        fjt_27.setElementMap(fhs_22);
        fjt_27.setElseValue("0.7,0.7,0.7");
        fjt_27.setValue("1,1,1");
        fsd_18.X(fjt_27);
        fjt_27.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_22);
        fjt_27.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjt_27.onChildrenAdded();
        fsd_18.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new awx_2(0.95f, 0.95f, 0.35f, 1.0f));
        fzq5.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq5.onChildrenAdded();
        fsd_1 fsd_19 = new fsd_1();
        fsd_19.aVI();
        fsd_19.setElementMap(fhs_22);
        fsd_19.setAttribute("text");
        fsd_19.setField("name");
        fbv_27.X(fsd_19);
        fsd_19.guy();
        fsd_19.onChildrenAdded();
        fsd_1 fsd_110 = new fsd_1();
        fsd_110.aVI();
        fsd_110.setElementMap(fhs_22);
        fsd_110.setAttribute("visible");
        fsd_110.setField("isGovernor");
        fbv_27.X(fsd_110);
        fsd_110.guy();
        fsd_110.onChildrenAdded();
        fbv_27.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_22);
        fbv_29.setExpandable(false);
        fbv_29.setStyle("bold");
        fbv_29.setText(", ");
        faw_213.X(fbv_29);
        fbv_29.guy();
        fbv_2 fbv_210 = fbv_29;
        fzq fzq6 = (fzq)((fes_2)fbv_210).getAppearance();
        fzq6.setElementMap(fhs_22);
        fzq6.setAlignment(faa_2.tLN);
        fbv_29.X(fzq6);
        fzq6.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fzq6.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzx fzx4 = new fzx();
        fzx4.aVI();
        fzx4.setElementMap(fhs_22);
        fzx4.setInsets(new Insets(0, 0, 1, 0));
        fzq6.X(fzx4);
        fzx4.guy();
        fzx4.onChildrenAdded();
        fzq6.onChildrenAdded();
        fsd_1 fsd_111 = new fsd_1();
        fsd_111.aVI();
        fsd_111.setElementMap(fhs_22);
        fsd_111.setAttribute("visible");
        fsd_111.setField("guildName");
        fbv_29.X(fsd_111);
        fsd_111.guy();
        this.j(fsd_111);
        fsd_111.onChildrenAdded();
        fbv_29.onChildrenAdded();
        this.J(faw_213);
        faw_213.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_211.onChildrenAdded();
        this.K(faw_210);
        this.i(faw_210);
        faw_210.onChildrenAdded();
        this.j(faw_26);
        faw_26.onChildrenAdded();
        fje_22.onChildrenAdded();
        this.U(fdf_12);
        fdf_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        this.O(faw_23);
        this.P(faw_23);
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 j(fsd_1 fsd_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsd_12.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        return fjt_22;
    }

    public fhi_2 J(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setMaxWidth(160);
        fbv_22.setStyle("bold");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 0, 1, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("guildName");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("visible");
        fsd_13.setField("guildName");
        fbv_22.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsd_13.X(fjt_22);
        fjt_22.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjt_22.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_13.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 K(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_23.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setStyle("TiledScrollCenter");
        faw_23.X(faw_24);
        faw_24.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_24.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_24.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setStyle("TiledScrollTop");
        faw_23.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tKY);
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setStyle("TiledScrollBottom");
        faw_23.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLk);
        fbt_13.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setPrefSize(new fsm_1(260, 0));
        faw_23.X(faw_25);
        faw_25.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLf);
        faw_25.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_02 = ((fes_2)faw_26).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_25.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 10, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxWidth(180);
        fdy_12.setStyle("darkBold");
        faw_25.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLN);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(7, 0, 7, 0));
        fzq2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("rankDescription");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_25.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setExpandable(false);
        faw_25.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLh);
        fbt_14.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("style");
        fsd_13.setField("wakfuValue");
        fbt_14.X(fsd_13);
        fsd_13.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fjt_22.setElseValue("WakfuIcon");
        fjt_22.setValue("StasisIcon");
        fsd_13.X(fjt_22);
        fjt_22.guy();
        fjr_1 fjr_12 = new fjr_1();
        fjr_12.aVI();
        fjr_12.setElementMap(fhs_22);
        fjr_12.setValue("0");
        fjt_22.X(fjr_12);
        fjr_12.guy();
        fjr_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_13.onChildrenAdded();
        fbt_1 fbt_15 = fbt_14;
        fyY fyY2 = (fyY)((fes_2)fbt_15).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_14.X(fyY2);
        fyY2.guy();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("modulationColor");
        fsd_14.setField("wakfuStasisColor");
        fyY2.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fyY2.onChildrenAdded();
        fbt_14.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("darkBold");
        faw_25.X(fbv_22);
        fbv_22.guy();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("wakfuStasisDescription");
        fbv_22.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 i(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMaxSize(new fsm_1(280, 75));
        fdy_12.setMaxWidth(300);
        fdy_12.setPrefSize(new fsm_1(0, 85));
        fdy_12.setShrinkable(true);
        fdy_12.setStyle("darkBold");
        faw_22.X(fdy_12);
        fdy_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        fdy_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("slogan");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_12.onChildrenAdded();
        return fdy_12;
    }

    public fhi_2 j(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_23.setPrefSize(new fsm_1(0, 130));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setXOffset(-5);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_24.setExpandable(false);
        faw_23.X(faw_24);
        faw_24.guy();
        faw_2 faw_25 = faw_24;
        fys_0 fys_02 = ((fes_2)faw_25).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_24.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setStyle("Portrait");
        faw_24.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLm);
        frp_13.setSize(new fsm_1(87, 102));
        fbt_12.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_24.X(faw_26);
        faw_26.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLm);
        frp_14.setSize(new fsm_1(55, 68));
        frp_14.setXOffset(-1);
        frp_14.setYOffset(16);
        faw_26.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_2 faw_27 = faw_26;
        fys_0 fys_03 = ((fes_2)faw_27).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_26.X(fys_03);
        fys_03.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fkk_12.setColor(new awx_2(0.5f, 0.5f, 0.5f, 0.5f));
        fys_03.X(fkk_12);
        fkk_12.guy();
        fkk_12.onChildrenAdded();
        fys_03.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("visible");
        fsd_12.setField("isEnabled");
        faw_26.X(fsd_12);
        fsd_12.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fsd_12.X(fjt_22);
        fjt_22.guy();
        fjw_2 fjw_22 = new fjw_2();
        fjw_22.aVI();
        fjw_22.setElementMap(fhs_22);
        fjt_22.X(fjw_22);
        fjw_22.guy();
        fjw_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_12.onChildrenAdded();
        faw_26.onChildrenAdded();
        faw_2 faw_28 = faw_2.checkOut();
        faw_28.setElementMap(fhs_22);
        faw_28.setNeedsScissor(true);
        faw_24.X(faw_28);
        faw_28.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_22);
        frp_15.setAlign(fzw_0.tLm);
        frp_15.setSize(new fsm_1(55, 68));
        frp_15.setYOffset(15);
        faw_28.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_22);
        fax_12.setAnimName("AnimStatique");
        fax_12.setDirection(2);
        fax_12.setOffsetX(0.0f);
        fax_12.setOffsetY(-125.0f);
        fax_12.setScale(2.2f);
        faw_28.X(fax_12);
        fax_12.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("animatedElement");
        fsd_13.setField("actorDescriptorLibrary");
        fax_12.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_28.onChildrenAdded();
        fbt_1 fbt_13 = new fbt_1();
        fbt_13.aVI();
        fbt_13.setElementMap(fhs_22);
        fbt_13.setStyle("GovernorFrame");
        faw_24.X(fbt_13);
        fbt_13.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_22);
        frp_16.setAlign(fzw_0.tLa);
        frp_16.setSize(new fsm_1(89, 111));
        fbt_13.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("visible");
        fsd_14.setField("isGovernor");
        fbt_13.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fbt_13.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setExpandable(false);
        faw_23.X(faw_29);
        faw_29.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("visible");
        fsj_22.setField("nation/hasVoted");
        fsj_22.setName("localPlayer");
        faw_29.X(fsj_22);
        fsj_22.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fsj_22.X(fjt_23);
        fjt_23.guy();
        fjn_2 fjn_22 = new fjn_2();
        fjn_22.aVI();
        fjn_22.setElementMap(fhs_22);
        fjt_23.X(fjn_22);
        fjn_22.guy();
        fjw_2 fjw_23 = new fjw_2();
        fjw_23.aVI();
        fjw_23.setElementMap(fhs_22);
        fjn_22.X(fjw_23);
        fjw_23.guy();
        fjw_23.onChildrenAdded();
        fjw_2 fjw_24 = new fjw_2();
        fjw_24.aVI();
        fjw_24.setElementMap(fhs_22);
        fjn_22.X(fjw_24);
        fjw_24.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("comparedValue");
        fsj_23.setName("voteList");
        fjw_24.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fjw_24.onChildrenAdded();
        fjn_22.onChildrenAdded();
        fjt_23.onChildrenAdded();
        fsj_22.onChildrenAdded();
        faw_2 faw_210 = faw_29;
        fys_0 fys_04 = ((fes_2)faw_210).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_29.X(fys_04);
        fys_04.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 2, 0, 0));
        fys_04.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_04.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_29.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.voteInformation:voteFor(candidate)");
        fad_12.setOnClick(fmz_12);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(voteForPopup)");
        fad_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fad_12.setOnPopupHide(fml_12);
        fad_12.setStyle("Yellow");
        faw_29.X(fad_12);
        fad_12.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_22);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setSize(new fsm_1(60, 100.0f));
        fad_12.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        String string = "voteForPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fad_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setStyle("popup");
        frx_12.X(faw_211);
        faw_211.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_211.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setStyle("white");
        String string2 = "%nation.vote.voteFor%";
        string2 = string2.replace("%nation.vote.voteFor%", fyw_0.gqw().k("nation.vote.voteFor", new Object[0]));
        fbv_22.setText(string2);
        faw_211.X(fbv_22);
        fbv_22.guy();
        fbv_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setMinWidth(200);
        fdy_12.setStyle("white");
        String string3 = "%nation.rank.unauthorized.for.vote%";
        string3 = string3.replace("%nation.rank.unauthorized.for.vote%", fyw_0.gqw().k("nation.rank.unauthorized.for.vote", new Object[0]));
        fdy_12.setText(string3);
        faw_211.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fdy_12.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new awx_2(1.0f, 0.0f, 0.0f, 1.0f));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("visible");
        fsj_24.setField("nation/canVoteConcerningCrimes");
        fsj_24.setName("localPlayer");
        fdy_12.X(fsj_24);
        fsj_24.guy();
        fjt_2 fjt_24 = new fjt_2();
        fjt_24.aVI();
        fjt_24.setElementMap(fhs_22);
        fsj_24.X(fjt_24);
        fjt_24.guy();
        fjw_2 fjw_25 = new fjw_2();
        fjw_25.aVI();
        fjw_25.setElementMap(fhs_22);
        fjt_24.X(fjw_25);
        fjw_25.guy();
        fjw_25.onChildrenAdded();
        fjt_24.onChildrenAdded();
        fsj_24.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("text");
        fsj_25.setName("subscribedAccount");
        fdy_12.X(fsj_25);
        fsj_25.guy();
        fjt_2 fjt_25 = new fjt_2();
        fjt_25.aVI();
        fjt_25.setElementMap(fhs_22);
        String string4 = "%error.playerNotSubscribed%";
        string4 = string4.replace("%error.playerNotSubscribed%", fyw_0.gqw().k("error.playerNotSubscribed", new Object[0]));
        fjt_25.setElseValue(string4);
        String string5 = "%nation.rank.unauthorized.for.vote%";
        string5 = string5.replace("%nation.rank.unauthorized.for.vote%", fyw_0.gqw().k("nation.rank.unauthorized.for.vote", new Object[0]));
        fjt_25.setValue(string5);
        fsj_25.X(fjt_25);
        fjt_25.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjt_25.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjt_25.onChildrenAdded();
        fsj_25.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setExpandable(false);
        fdy_14.setMinWidth(200);
        fdy_14.setStyle("white");
        String string6 = "%nation.vote.disabledCandidate%";
        string6 = string6.replace("%nation.vote.disabledCandidate%", fyw_0.gqw().k("nation.vote.disabledCandidate", new Object[0]));
        fdy_14.setText(string6);
        faw_211.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq3 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq3.setElementMap(fhs_22);
        fdy_14.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new awx_2(1.0f, 0.0f, 0.0f, 1.0f));
        fzq3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("visible");
        fsd_15.setField("isEnabled");
        fdy_14.X(fsd_15);
        fsd_15.guy();
        fjt_2 fjt_26 = new fjt_2();
        fjt_26.aVI();
        fjt_26.setElementMap(fhs_22);
        fsd_15.X(fjt_26);
        fjt_26.guy();
        fjw_2 fjw_26 = new fjw_2();
        fjw_26.aVI();
        fjw_26.setElementMap(fhs_22);
        fjt_26.X(fjw_26);
        fjw_26.guy();
        fjw_26.onChildrenAdded();
        fjt_26.onChildrenAdded();
        fsd_15.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_211.onChildrenAdded();
        frx_12.onChildrenAdded();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("enabled");
        fsd_16.setField("isEnabled");
        fad_12.X(fsd_16);
        fsd_16.guy();
        fjt_2 fjt_27 = new fjt_2();
        fjt_27.aVI();
        fjt_27.setElementMap(fhs_22);
        fsd_16.X(fjt_27);
        fjt_27.guy();
        fjn_2 fjn_23 = new fjn_2();
        fjn_23.aVI();
        fjn_23.setElementMap(fhs_22);
        fjt_27.X(fjn_23);
        fjn_23.guy();
        fjl_1 fjl_13 = new fjl_1();
        fjl_13.aVI();
        fjl_13.setElementMap(fhs_22);
        fjn_23.X(fjl_13);
        fjl_13.guy();
        fjl_13.onChildrenAdded();
        fjl_1 fjl_14 = new fjl_1();
        fjl_14.aVI();
        fjl_14.setElementMap(fhs_22);
        fjn_23.X(fjl_14);
        fjl_14.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("comparedValue");
        fsj_26.setField("nation/canVoteConcerningCrimes");
        fsj_26.setName("localPlayer");
        fjl_14.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fjl_14.onChildrenAdded();
        fjn_23.onChildrenAdded();
        fjt_27.onChildrenAdded();
        fsd_16.onChildrenAdded();
        fad_12.onChildrenAdded();
        String string7 = "text";
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_22);
        if (fhs_22 != null && string7 != null) {
            fhs_22.a(string7, fdy_16);
        }
        fdy_16.setExpandable(false);
        fdy_16.setNonBlocking(true);
        fdy_16.setStyle("DarkBold11");
        String string8 = "%desc.mru.vote%";
        string8 = string8.replace("%desc.mru.vote%", fyw_0.gqw().k("desc.mru.vote", new Object[0]));
        fdy_16.setText(string8);
        faw_29.X(fdy_16);
        fdy_16.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_22);
        frp_18.setAlign(fzw_0.tLg);
        frp_18.setSize(new fsm_1(100.0f, 100.0f));
        fdy_16.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq4 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq4.setElementMap(fhs_22);
        fzq4.setAlign(faa_2.tLO);
        fdy_16.X(fzq4);
        fzq4.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(7, 9, 7, 9));
        fzq4.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fzq4.onChildrenAdded();
        fdy_16.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setExpandable(false);
        faw_23.X(faw_212);
        faw_212.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_22);
        fsj_27.setAttribute("visible");
        fsj_27.setName("voteList");
        faw_212.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fbv_2 fbv_23 = new fbv_2();
        fbv_23.aVI();
        fbv_23.setElementMap(fhs_22);
        fbv_23.setStyle("darkBold");
        faw_212.X(fbv_23);
        fbv_23.guy();
        fbv_2 fbv_24 = fbv_23;
        fzq fzq5 = (fzq)((fes_2)fbv_24).getAppearance();
        fzq5.setElementMap(fhs_22);
        fzq5.setAlignment(faa_2.tLP);
        fbv_23.X(fzq5);
        fzq5.guy();
        this.t(fzq5);
        fzq5.onChildrenAdded();
        this.Y(fbv_23);
        fbv_23.onChildrenAdded();
        faw_212.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 t(fzq fzq2) {
        fhs_2 fhs_22 = this.nei.peek();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 0, 3));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        return fzv2;
    }

    public fhi_2 Y(fbv_2 fbv_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("ballotCount");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        return fsd_12;
    }

    public fhi_2 U(fdf_1 fdf_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fdf_12.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fje_22.X(faw_22);
        faw_22.guy();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 O(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setNonBlocking(true);
        faw_23.setStyle("EncyclopediaPane");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLg);
        frp_12.setSize(new fsm_1(430, 495));
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 P(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setSize(new fsm_1(375, -2));
        frp_12.setYOffset(35);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLO);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.voteInformation:previousPage");
        fad_12.setOnClick(fmz_12);
        fad_12.setStyle("CharacterCreationLeftArrow");
        faw_23.X(fad_12);
        fad_12.guy();
        fad_12.onChildrenAdded();
        fde_1 fde_12 = new fde_1();
        fde_12.aVI();
        fde_12.setElementMap(fhs_22);
        faw_23.X(fde_12);
        fde_12.guy();
        fde_12.onChildrenAdded();
        fad_1 fad_13 = new fad_1();
        fad_13.aVI();
        fad_13.setElementMap(fhs_22);
        fad_13.setExpandable(false);
        fmz_1 fmz_13 = new fmz_1();
        fmz_13.vw("wakfu.voteInformation:nextPage");
        fad_13.setOnClick(fmz_13);
        fad_13.setStyle("CharacterCreationRightArrow");
        faw_23.X(fad_13);
        fad_13.guy();
        fad_13.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 s(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 aL(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.voteInformation:closeDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 E(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLa);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }
}

