/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from cPh
 */
public class cph_2
implements fhk_1 {
    private Stack<fhs_2> nei = new Stack();
    private fhu_1 nej;

    @Override
    public fhi_2 a(fhu_1 fhu_12, fhs_2 fhs_22) {
        this.nej = fhu_12;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fey_2 fey_22 = new fey_2();
        fey_22.aVI();
        fey_22.setElementMap(fhs_23);
        fey_22.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        fey_22.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_23);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_23);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_23);
        faw_23.setStyle("windowNew");
        fey_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_23);
        faw_23.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(10, 5, 12, 5));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_23);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_23.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setAlign(faa_2.tLL);
        frz_22.setHorizontal(false);
        faw_23.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fea_1 fea_12 = new fea_1();
        fea_12.aVI();
        fea_12.setElementMap(fhs_23);
        fea_12.setExpandable(false);
        faw_23.X(fea_12);
        fea_12.guy();
        fea_1 fea_13 = fea_12;
        fys_0 fys_03 = ((fes_2)fea_13).getAppearance();
        fys_03.setElementMap(fhs_23);
        fea_12.X(fys_03);
        fys_03.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_23);
        fzv2.setInsets(new Insets(0, 10, 0, 10));
        fys_03.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_03.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_23);
        faw_25.setStyle("titleBar");
        fea_12.X(faw_25);
        faw_25.guy();
        faw_2 faw_26 = faw_25;
        fys_0 fys_04 = ((fes_2)faw_26).getAppearance();
        fys_04.setElementMap(fhs_23);
        faw_25.X(fys_04);
        fys_04.guy();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_23);
        fzx3.setInsets(new Insets(3, 20, 3, 20));
        fys_04.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fys_04.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_23);
        fbv_22.setExpandable(false);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("StyledBold16White");
        String string = "%weather.info.title%";
        string = string.replace("%weather.info.title%", fyw_0.gqw().k("weather.info.title", new Object[0]));
        fbv_22.setText(string);
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        fea_12.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_23);
        faw_23.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_05 = ((fes_2)faw_28).getAppearance();
        fys_05.setElementMap(fhs_23);
        faw_27.X(fys_05);
        fys_05.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_23);
        fzv3.setInsets(new Insets(0, 12, 0, 12));
        fys_05.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fys_05.onChildrenAdded();
        String string2 = "windowContentContainer";
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, faw_29);
        }
        faw_27.X(faw_29);
        faw_29.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_29.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_23);
        faw_210.setExpandable(false);
        faw_29.X(faw_210);
        faw_210.guy();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        fro_13.setAdaptToContentSize(true);
        faw_210.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_23);
        faw_211.setStyle("titleBar");
        faw_210.X(faw_211);
        faw_211.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_23);
        frp_14.setAlign(fzw_0.tLg);
        frp_14.setSize(new fsm_1(100.0f, 100.0f));
        faw_211.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_23);
        faw_210.X(faw_212);
        faw_212.guy();
        frp_1 frp_15 = new frp_1();
        frp_15.aVI();
        frp_15.setElementMap(fhs_23);
        frp_15.setAlign(fzw_0.tLg);
        frp_15.setSize(new fsm_1(100.0f, 100.0f));
        faw_212.X(frp_15);
        frp_15.guy();
        frp_15.onChildrenAdded();
        frz_2 frz_24 = frz_2.checkOut();
        frz_24.setAlign(faa_2.tLN);
        faw_212.X(frz_24);
        frz_24.guy();
        frz_24.onChildrenAdded();
        faw_2 faw_213 = faw_2.checkOut();
        faw_213.setElementMap(fhs_23);
        faw_213.setPrefSize(new fsm_1(81, 81));
        faw_213.setExpandable(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(protectorNamePopup,1)");
        faw_213.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_213.setOnPopupHide(fml_12);
        faw_212.X(faw_213);
        faw_213.guy();
        fro_1 fro_14 = new fro_1();
        fro_14.aVI();
        fro_14.setAdaptToContentSize(true);
        faw_213.X(fro_14);
        fro_14.guy();
        fro_14.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_23);
        faw_214.setNeedsScissor(true);
        faw_213.X(faw_214);
        faw_214.guy();
        frp_1 frp_16 = new frp_1();
        frp_16.aVI();
        frp_16.setElementMap(fhs_23);
        frp_16.setAlign(fzw_0.tLg);
        frp_16.setSize(new fsm_1(61, 61));
        faw_214.X(frp_16);
        frp_16.guy();
        frp_16.onChildrenAdded();
        fax_1 fax_12 = new fax_1();
        fax_12.aVI();
        fax_12.setElementMap(fhs_23);
        fax_12.setAnimName("AnimStatique-Neutre");
        fax_12.setDirection(1);
        fax_12.setOffsetX(1.0f);
        fax_12.setOffsetY(-7.0f);
        fax_12.setScale(1.0f);
        faw_214.X(fax_12);
        fax_12.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_23);
        fsj_22.setAttribute("animatedElement");
        fsj_22.setField("animation");
        fsj_22.setName("protector");
        fax_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_23);
        fsj_23.setAttribute("animName");
        fsj_23.setField("animName");
        fsj_23.setName("protector");
        fax_12.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fax_12.onChildrenAdded();
        faw_214.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_23);
        fbt_12.setStyle("protectorFrame");
        faw_213.X(fbt_12);
        fbt_12.guy();
        frp_1 frp_17 = new frp_1();
        frp_17.aVI();
        frp_17.setElementMap(fhs_23);
        frp_17.setAlign(fzw_0.tLg);
        frp_17.setSize(new fsm_1(100.0f, 100.0f));
        fbt_12.X(frp_17);
        frp_17.guy();
        frp_17.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_23);
        fbt_12.X(fyY2);
        fyY2.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_23);
        fsj_24.setAttribute("modulationColor");
        fsj_24.setField("protectorSatisfactionColor");
        fsj_24.setName("wakfuGlobalZoneManager");
        fyY2.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fyY2.onChildrenAdded();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_23);
        fsj_25.setAttribute("visible");
        fsj_25.setName("wakfuEcosystemEnabled");
        fbt_12.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_2 faw_215 = faw_2.checkOut();
        faw_215.setElementMap(fhs_23);
        faw_215.setNonBlocking(false);
        fmk_2 fmk_23 = new fmk_2();
        fmk_23.vw("popup(messagesPopup2)");
        faw_215.setOnPopupDisplay(fmk_23);
        fml_1 fml_13 = new fml_1();
        fml_13.vw("closePopup");
        faw_215.setOnPopupHide(fml_13);
        faw_215.setStyle("protectorFrameOver");
        faw_213.X(faw_215);
        faw_215.guy();
        frp_1 frp_18 = new frp_1();
        frp_18.aVI();
        frp_18.setElementMap(fhs_23);
        frp_18.setSize(new fsm_1(100.0f, 100.0f));
        frp_18.setXOffset(1);
        frp_18.setYOffset(-1);
        faw_215.X(frp_18);
        frp_18.guy();
        frp_18.onChildrenAdded();
        String string3 = "messagesPopup2";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, frx_12);
        }
        frx_12.setHotSpotPosition(faa_2.tLR);
        faw_215.X(frx_12);
        frx_12.guy();
        faw_2 faw_216 = faw_2.checkOut();
        faw_216.setElementMap(fhs_23);
        faw_216.setPrefSize(new fsm_1(10, 0));
        faw_216.setStyle("popup");
        frx_12.X(faw_216);
        faw_216.guy();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_23);
        fsj_26.setAttribute("visible");
        fsj_26.setField("protectorNationId");
        fsj_26.setName("wakfuGlobalZoneManager");
        faw_216.X(fsj_26);
        fsj_26.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_23);
        fsj_26.X(fjt_22);
        fjt_22.guy();
        fjc_1 fjc_12 = new fjc_1();
        fjc_12.aVI();
        fjc_12.setElementMap(fhs_23);
        fjc_12.setValue("0");
        fjt_22.X(fjc_12);
        fjc_12.guy();
        fjc_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsj_26.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_23);
        fbt_14.setNonBlocking(false);
        faw_216.X(fbt_14);
        fbt_14.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fbt_14.X(fze2);
        fze2.guy();
        fsj_2 fsj_27 = fsj_2.checkOut();
        fsj_27.setElementMap(fhs_23);
        fsj_27.setAttribute("texture");
        fsj_27.setField("protectorNationIcon");
        fsj_27.setName("wakfuGlobalZoneManager");
        fze2.X(fsj_27);
        fsj_27.guy();
        fsj_27.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_14.onChildrenAdded();
        faw_216.onChildrenAdded();
        frx_12.onChildrenAdded();
        faw_215.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_23);
        frb_12.setAlign(faa_2.tLO);
        faw_213.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_217 = faw_213;
        fys_0 fys_06 = ((fes_2)faw_217).getAppearance();
        fys_06.setElementMap(fhs_23);
        faw_213.X(fys_06);
        fys_06.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_23);
        fzv4.setInsets(new Insets(0, 5, 0, 0));
        fys_06.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_06.onChildrenAdded();
        String string4 = "protectorNamePopup";
        frx_1 frx_13 = new frx_1();
        frx_13.aVI();
        frx_13.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, frx_13);
        }
        frx_13.setAlign(faa_2.tLR);
        frx_13.setHotSpotPosition(faa_2.tLL);
        faw_213.X(frx_13);
        frx_13.guy();
        faw_2 faw_218 = faw_2.checkOut();
        faw_218.setElementMap(fhs_23);
        faw_218.setPrefSize(new fsm_1(10, 0));
        faw_218.setStyle("popup");
        frx_13.X(faw_218);
        faw_218.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_23);
        fru_12.setData(fzt_0.tKA);
        faw_218.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_25 = frz_2.checkOut();
        frz_25.setHorizontal(false);
        faw_218.X(frz_25);
        frz_25.guy();
        frz_25.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_23);
        fdy_12.setStyle("white");
        faw_218.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_23);
        fzq3.setAlignment(faa_2.tLO);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fsj_2 fsj_28 = fsj_2.checkOut();
        fsj_28.setElementMap(fhs_23);
        fsj_28.setAttribute("text");
        fsj_28.setField("name");
        fsj_28.setName("protector");
        fdy_12.X(fsj_28);
        fsj_28.guy();
        fsj_28.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_218.onChildrenAdded();
        frx_13.onChildrenAdded();
        faw_213.onChildrenAdded();
        faw_2 faw_219 = faw_2.checkOut();
        faw_219.setElementMap(fhs_23);
        faw_212.X(faw_219);
        faw_219.guy();
        frz_2 frz_26 = frz_2.checkOut();
        frz_26.setAlign(faa_2.tLL);
        frz_26.setHorizontal(false);
        faw_219.X(frz_26);
        frz_26.guy();
        frz_26.onChildrenAdded();
        faw_2 faw_220 = faw_219;
        fys_0 fys_07 = ((fes_2)faw_220).getAppearance();
        fys_07.setElementMap(fhs_23);
        faw_219.X(fys_07);
        fys_07.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_23);
        fzv5.setInsets(new Insets(5, 0, 5, 0));
        fys_07.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_07.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_23);
        fdy_14.setExpandable(false);
        fdy_14.setMaxWidth(200);
        fdy_14.setMultiline(false);
        fdy_14.setNonBlocking(true);
        fdy_14.setStyle("StyledBold16White");
        faw_219.X(fdy_14);
        fdy_14.guy();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq4 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq4.setElementMap(fhs_23);
        fzq4.setAlign(faa_2.tLN);
        fdy_14.X(fzq4);
        fzq4.guy();
        fzv fzv6 = fzv.checkOut();
        fzv6.setElementMap(fhs_23);
        fzv6.setInsets(new Insets(0, 7, 0, 0));
        fzq4.X(fzv6);
        fzv6.guy();
        fzv6.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsj_2 fsj_29 = fsj_2.checkOut();
        fsj_29.setElementMap(fhs_23);
        fsj_29.setAttribute("text");
        fsj_29.setField("name");
        fsj_29.setName("protector");
        fdy_14.X(fsj_29);
        fsj_29.guy();
        fsj_29.onChildrenAdded();
        fdy_14.onChildrenAdded();
        fdy_1 fdy_16 = new fdy_1();
        fdy_16.aVI();
        fdy_16.setElementMap(fhs_23);
        fdy_16.setExpandable(false);
        fdy_16.setMaxWidth(150);
        fdy_16.setNonBlocking(false);
        fmk_2 fmk_24 = new fmk_2();
        fmk_24.vw("popup(zoneNamePopup,1)");
        fdy_16.setOnPopupDisplay(fmk_24);
        fml_1 fml_14 = new fml_1();
        fml_14.vw("closePopup");
        fdy_16.setOnPopupHide(fml_14);
        fdy_16.setStyle("white");
        faw_219.X(fdy_16);
        fdy_16.guy();
        fdy_1 fdy_17 = fdy_16;
        fzq fzq5 = (fzq)((fes_2)fdy_17).getAppearance();
        fzq5.setElementMap(fhs_23);
        fzq5.setAlign(faa_2.tLN);
        fdy_16.X(fzq5);
        fzq5.guy();
        this.k(fzq5);
        this.u(fzq5);
        fzq5.onChildrenAdded();
        this.T(fdy_16);
        this.R(fdy_16);
        fdy_16.onChildrenAdded();
        this.F(faw_219);
        faw_219.onChildrenAdded();
        this.G(faw_212);
        faw_212.onChildrenAdded();
        faw_210.onChildrenAdded();
        this.f(faw_29);
        faw_29.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_23.onChildrenAdded();
        this.s(fey_22);
        this.aL(fey_22);
        this.E(fey_22);
        this.Q(fey_22);
        this.Y(fey_22);
        this.Z(fey_22);
        fey_22.onChildrenAdded();
        return fey_22;
    }

    public fhi_2 k(fzq fzq2) {
        fhs_2 fhs_22 = this.nei.peek();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("greenColor"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        return fyp_02;
    }

    public fhi_2 u(fzq fzq2) {
        fhs_2 fhs_22 = this.nei.peek();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 7, 2, 0));
        fzq2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        return fzv2;
    }

    public fhi_2 T(fdy_1 fdy_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("zoneName");
        fsj_22.setName("ambienceZone");
        fdy_12.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        return fsj_22;
    }

    public fhi_2 R(fdy_1 fdy_12) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "zoneNamePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fdy_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_13 = new fdy_1();
        fdy_13.aVI();
        fdy_13.setElementMap(fhs_22);
        fdy_13.setStyle("white");
        faw_22.X(fdy_13);
        fdy_13.guy();
        fdy_1 fdy_14 = fdy_13;
        fzq fzq2 = (fzq)((fes_2)fdy_14).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_13.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("text");
        fsj_22.setField("zoneName");
        fsj_22.setName("ambienceZone");
        fdy_13.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fdy_13.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 F(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        faw_23.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        fro_12.setAdaptToContentSize(true);
        faw_24.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setStyle("backgroundPopup");
        faw_24.X(faw_25);
        faw_25.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_25.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_2 faw_26 = faw_25;
        fys_0 fys_02 = ((fes_2)faw_26).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_25.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(5, 0, 5, 0));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_25.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_24.X(faw_27);
        faw_27.guy();
        faw_2 faw_28 = faw_27;
        fys_0 fys_03 = ((fes_2)faw_28).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_27.X(fys_03);
        fys_03.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 5, 0, 10));
        fys_03.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_03.onChildrenAdded();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setSize(new fsm_1(100.0f, 100.0f));
        faw_27.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(true);
        faw_27.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_29.setNonBlocking(true);
        faw_27.X(faw_29);
        faw_29.guy();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(true);
        faw_29.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(48, 48));
        fbt_12.setExpandable(false);
        fbt_12.setNonBlocking(true);
        faw_29.X(fbt_12);
        fbt_12.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLO);
        fbt_12.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("texture");
        fsj_22.setField("currentWeather/iconUrl");
        fsj_22.setName("weather.manager");
        fze2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setExpandable(false);
        fbv_22.setNonBlocking(true);
        fbv_22.setStyle("defaultWhiteBold22");
        faw_29.X(fbv_22);
        fbv_22.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_22);
        frb_14.setAlign(faa_2.tLO);
        fbv_22.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fbv_22.X(fzq2);
        fzq2.guy();
        fkm_1 fkm_12 = new fkm_1();
        fkm_12.aVI();
        fkm_12.setElementMap(fhs_22);
        fkm_12.setColor(new fhl_2("gray80Color", 0.3f));
        fkm_12.setInsets(new Insets(0, 1, 0, 0));
        fzq2.X(fkm_12);
        fkm_12.guy();
        fkm_12.onChildrenAdded();
        fzx fzx3 = new fzx();
        fzx3.aVI();
        fzx3.setElementMap(fhs_22);
        fzx3.setInsets(new Insets(0, 3, 0, 0));
        fzq2.X(fzx3);
        fzx3.guy();
        fzx3.onChildrenAdded();
        fzq2.onChildrenAdded();
        frb_1 frb_15 = new frb_1();
        frb_15.aVI();
        frb_15.setElementMap(fhs_22);
        frb_15.setAlign(faa_2.tLO);
        fbv_22.X(frb_15);
        frb_15.guy();
        frb_15.onChildrenAdded();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("text");
        fsj_23.setField("currentWeather/currentTemperature");
        fsj_23.setName("weather.manager");
        fbv_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_210 = faw_2.checkOut();
        faw_210.setElementMap(fhs_22);
        faw_23.X(faw_210);
        faw_210.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setMultiline(false);
        fdy_12.setNonBlocking(true);
        fdy_12.setStyle("StyledBold16White");
        faw_210.X(fdy_12);
        fdy_12.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("text");
        fsj_24.setField("currentWeather/seasonDescription");
        fsj_24.setName("weather.manager");
        fdy_12.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_22);
        fzq3.setAlign(faa_2.tLP);
        fdy_12.X(fzq3);
        fzq3.guy();
        fzq3.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_210.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 G(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setExpandable(false);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_23;
        fys_0 fys_02 = ((fes_2)faw_24).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_23.X(fys_02);
        fys_02.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 5, 0, 10));
        fys_02.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fys_02.onChildrenAdded();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(70, 70));
        faw_23.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("texture");
        fsj_22.setField("nation/flagIconUrl");
        fsj_22.setName("protector");
        fze2.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 f(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_22.X(faw_23);
        faw_23.guy();
        faw_2 faw_24 = faw_2.checkOut();
        faw_24.setElementMap(fhs_22);
        faw_23.X(faw_24);
        faw_24.guy();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_24.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        faw_2 faw_25 = faw_2.checkOut();
        faw_25.setElementMap(fhs_22);
        faw_25.setPrefSize(new fsm_1(0, 20));
        faw_25.setStyle("titleBar");
        faw_24.X(faw_25);
        faw_25.guy();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setStyle("whiteBold");
        String string = "%weather.forecast%";
        string = string.replace("%weather.forecast%", fyw_0.gqw().k("weather.forecast", new Object[0]));
        fbv_22.setText(string);
        faw_25.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fbv_22.onChildrenAdded();
        faw_25.onChildrenAdded();
        fbz_2 fbz_22 = new fbz_2();
        fbz_22.aVI();
        fbz_22.setElementMap(fhs_22);
        fbz_22.setAutoIdealSize(true);
        fbz_22.setCellSize(new fsm_1(200, 48));
        fbz_22.setExpandable(false);
        fbz_22.setIdealSizeMaxColumns(1);
        fbz_22.setIdealSizeMaxRows(5);
        fbz_22.setIdealSizeMinColumns(1);
        fbz_22.setIdealSizeMinRows(5);
        faw_24.X(fbz_22);
        fbz_22.guy();
        fbz_2 fbz_23 = fbz_22;
        fza fza2 = (fza)((fes_2)fbz_23).getAppearance();
        fza2.setElementMap(fhs_22);
        fbz_22.X(fza2);
        fza2.guy();
        fzv fzv2 = fzv.checkOut();
        fzv2.setElementMap(fhs_22);
        fzv2.setInsets(new Insets(0, 0, 0, 0));
        fza2.X(fzv2);
        fzv2.guy();
        fzv2.onChildrenAdded();
        fza2.onChildrenAdded();
        fsj_2 fsj_22 = fsj_2.checkOut();
        fsj_22.setElementMap(fhs_22);
        fsj_22.setAttribute("content");
        fsj_22.setField("weatherOfDays");
        fsj_22.setName("weather.manager");
        fbz_22.X(fsj_22);
        fsj_22.guy();
        fsj_22.onChildrenAdded();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        faw_2 faw_26 = faw_2.checkOut();
        faw_26.setElementMap(fhs_22);
        faw_26.setNonBlocking(false);
        fje_22.X(faw_26);
        faw_26.guy();
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        fbt_12.setDisplaySize(new fsm_1(48, 48));
        fbt_12.setExpandable(false);
        faw_26.X(fbt_12);
        fbt_12.guy();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLO);
        fbt_12.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        fbt_1 fbt_13 = fbt_12;
        fyY fyY2 = (fyY)((fes_2)fbt_13).getAppearance();
        fyY2.setElementMap(fhs_22);
        fbt_12.X(fyY2);
        fyY2.guy();
        fzv fzv3 = fzv.checkOut();
        fzv3.setElementMap(fhs_22);
        fzv3.setInsets(new Insets(0, 5, 0, 5));
        fyY2.X(fzv3);
        fzv3.guy();
        fzv3.onChildrenAdded();
        fyY2.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("iconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        fbv_2 fbv_24 = new fbv_2();
        fbv_24.aVI();
        fbv_24.setElementMap(fhs_22);
        fbv_24.setExpandable(true);
        fbv_24.setMaxSize(new fsm_1(75, 32));
        fbv_24.setPrefSize(new fsm_1(75, 0));
        fbv_24.setStyle("whiteBold");
        faw_26.X(fbv_24);
        fbv_24.guy();
        fsd_1 fsd_13 = new fsd_1();
        fsd_13.aVI();
        fsd_13.setElementMap(fhs_22);
        fsd_13.setAttribute("text");
        fsd_13.setField("dayDescription");
        fbv_24.X(fsd_13);
        fsd_13.guy();
        fsd_13.onChildrenAdded();
        fbv_24.onChildrenAdded();
        faw_2 faw_27 = faw_2.checkOut();
        faw_27.setElementMap(fhs_22);
        faw_27.setExpandable(false);
        faw_27.setPrefSize(new fsm_1(50, 48));
        faw_26.X(faw_27);
        faw_27.guy();
        fro_1 fro_12 = new fro_1();
        fro_12.aVI();
        faw_27.X(fro_12);
        fro_12.guy();
        fro_12.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setExpandable(false);
        fdy_12.setStyle("defaultBold16");
        faw_27.X(fdy_12);
        fdy_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLm);
        frp_12.setYOffset(5);
        fdy_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq3 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq3.setElementMap(fhs_22);
        fdy_12.X(fzq3);
        fzq3.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("mecanicLightBlueColor"));
        fyp_02.setName("text");
        fzq3.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq3.onChildrenAdded();
        fsd_1 fsd_14 = new fsd_1();
        fsd_14.aVI();
        fsd_14.setElementMap(fhs_22);
        fsd_14.setAttribute("text");
        fsd_14.setField("minTemperatureWithMods");
        fdy_12.X(fsd_14);
        fsd_14.guy();
        fsd_14.onChildrenAdded();
        fdy_12.onChildrenAdded();
        fdy_1 fdy_14 = new fdy_1();
        fdy_14.aVI();
        fdy_14.setElementMap(fhs_22);
        fdy_14.setExpandable(false);
        fdy_14.setStyle("defaultBold16");
        faw_27.X(fdy_14);
        fdy_14.guy();
        frp_1 frp_13 = new frp_1();
        frp_13.aVI();
        frp_13.setElementMap(fhs_22);
        frp_13.setAlign(fzw_0.tLa);
        frp_13.setYOffset(-3);
        fdy_14.X(frp_13);
        frp_13.guy();
        frp_13.onChildrenAdded();
        fdy_1 fdy_15 = fdy_14;
        fzq fzq4 = (fzq)((fes_2)fdy_15).getAppearance();
        fzq4.setElementMap(fhs_22);
        fdy_14.X(fzq4);
        fzq4.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_22);
        fyp_03.setColor(new fhl_2("mecanicLightBlueColor", 0.8f));
        fyp_03.setName("text");
        fzq4.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fzq4.onChildrenAdded();
        fsd_1 fsd_15 = new fsd_1();
        fsd_15.aVI();
        fsd_15.setElementMap(fhs_22);
        fsd_15.setAttribute("text");
        fsd_15.setField("maxTemperatureWithMods");
        fdy_14.X(fsd_15);
        fsd_15.guy();
        fsd_15.onChildrenAdded();
        fdy_14.onChildrenAdded();
        faw_27.onChildrenAdded();
        faw_2 faw_28 = faw_26;
        fys_0 fys_02 = ((fes_2)faw_28).getAppearance();
        fys_02.setElementMap(fhs_22);
        faw_26.X(fys_02);
        fys_02.guy();
        fkk_1 fkk_12 = new fkk_1();
        fkk_12.aVI();
        fkk_12.setElementMap(fhs_22);
        fys_02.X(fkk_12);
        fkk_12.guy();
        fsd_1 fsd_16 = new fsd_1();
        fsd_16.aVI();
        fsd_16.setElementMap(fhs_22);
        fsd_16.setAttribute("color");
        fkk_12.X(fsd_16);
        fsd_16.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fjt_22.setElseValue("oddCellColor");
        fjt_22.setValue("evenCellColor");
        fsd_16.X(fjt_22);
        fjt_22.guy();
        fjy_2 fjy_22 = new fjy_2();
        fjy_22.aVI();
        fjy_22.setElementMap(fhs_22);
        fjy_22.setKey("evenIndex");
        fjt_22.X(fjy_22);
        fjy_22.guy();
        fjl_1 fjl_12 = new fjl_1();
        fjl_12.aVI();
        fjl_12.setElementMap(fhs_22);
        fjy_22.X(fjl_12);
        fjl_12.guy();
        fjl_12.onChildrenAdded();
        fjy_22.onChildrenAdded();
        fjt_22.onChildrenAdded();
        fsd_16.onChildrenAdded();
        fkk_12.onChildrenAdded();
        fys_02.onChildrenAdded();
        faw_26.onChildrenAdded();
        fje_22.onChildrenAdded();
        fbz_22.onChildrenAdded();
        faw_24.onChildrenAdded();
        faw_2 faw_29 = faw_2.checkOut();
        faw_29.setElementMap(fhs_22);
        faw_23.X(faw_29);
        faw_29.guy();
        faw_2 faw_210 = faw_29;
        fys_0 fys_03 = ((fes_2)faw_210).getAppearance();
        fys_03.setElementMap(fhs_22);
        faw_29.X(fys_03);
        fys_03.guy();
        fzv fzv4 = fzv.checkOut();
        fzv4.setElementMap(fhs_22);
        fzv4.setInsets(new Insets(0, 3, 0, 0));
        fys_03.X(fzv4);
        fzv4.guy();
        fzv4.onChildrenAdded();
        fys_03.onChildrenAdded();
        frz_2 frz_23 = frz_2.checkOut();
        frz_23.setHorizontal(false);
        faw_29.X(frz_23);
        frz_23.guy();
        frz_23.onChildrenAdded();
        faw_2 faw_211 = faw_2.checkOut();
        faw_211.setElementMap(fhs_22);
        faw_211.setExpandable(false);
        faw_211.setPrefSize(new fsm_1(0, 20));
        faw_211.setStyle("titleBar");
        faw_29.X(faw_211);
        faw_211.guy();
        fbv_2 fbv_25 = new fbv_2();
        fbv_25.aVI();
        fbv_25.setElementMap(fhs_22);
        fbv_25.setStyle("whiteBold");
        String string2 = "%weather.resources.climate%";
        string2 = string2.replace("%weather.resources.climate%", fyw_0.gqw().k("weather.resources.climate", new Object[0]));
        fbv_25.setText(string2);
        faw_211.X(fbv_25);
        fbv_25.guy();
        fbv_2 fbv_26 = fbv_25;
        fzq fzq5 = (fzq)((fes_2)fbv_26).getAppearance();
        fzq5.setElementMap(fhs_22);
        fzq5.setAlign(faa_2.tLO);
        fbv_25.X(fzq5);
        fzq5.guy();
        fzq5.onChildrenAdded();
        fbv_25.onChildrenAdded();
        faw_211.onChildrenAdded();
        faw_2 faw_212 = faw_2.checkOut();
        faw_212.setElementMap(fhs_22);
        faw_212.setExpandable(false);
        faw_29.X(faw_212);
        faw_212.guy();
        faw_2 faw_213 = faw_212;
        fys_0 fys_04 = ((fes_2)faw_213).getAppearance();
        fys_04.setElementMap(fhs_22);
        faw_212.X(fys_04);
        fys_04.guy();
        fzv fzv5 = fzv.checkOut();
        fzv5.setElementMap(fhs_22);
        fzv5.setInsets(new Insets(8, 0, 8, 0));
        fys_04.X(fzv5);
        fzv5.guy();
        fzv5.onChildrenAdded();
        fys_04.onChildrenAdded();
        fdd_2 fdd_22 = new fdd_2();
        fdd_22.aVI();
        fdd_22.setElementMap(fhs_22);
        fmo_1 fmo_12 = new fmo_1();
        fmo_12.vw("wakfu.weatherInformation:onCulturesSelectionChange");
        fdd_22.setOnSelectionChange(fmo_12);
        fdd_22.setStyle("filter");
        faw_212.X(fdd_22);
        fdd_22.guy();
        fsj_2 fsj_23 = fsj_2.checkOut();
        fsj_23.setElementMap(fhs_22);
        fsj_23.setAttribute("selected");
        fsj_23.setField("displayCultures");
        fsj_23.setName("weather.manager");
        fdd_22.X(fsj_23);
        fsj_23.guy();
        fsj_23.onChildrenAdded();
        fdd_22.onChildrenAdded();
        fbv_2 fbv_27 = new fbv_2();
        fbv_27.aVI();
        fbv_27.setElementMap(fhs_22);
        fbv_27.setStyle("bold");
        String string3 = "%resource.cultures%";
        string3 = string3.replace("%resource.cultures%", fyw_0.gqw().k("resource.cultures", new Object[0]));
        fbv_27.setText(string3);
        faw_212.X(fbv_27);
        fbv_27.guy();
        fbv_27.onChildrenAdded();
        fdd_2 fdd_23 = new fdd_2();
        fdd_23.aVI();
        fdd_23.setElementMap(fhs_22);
        fmo_1 fmo_13 = new fmo_1();
        fmo_13.vw("wakfu.weatherInformation:onPlantsSelectionChange");
        fdd_23.setOnSelectionChange(fmo_13);
        fdd_23.setStyle("filter");
        faw_212.X(fdd_23);
        fdd_23.guy();
        fsj_2 fsj_24 = fsj_2.checkOut();
        fsj_24.setElementMap(fhs_22);
        fsj_24.setAttribute("selected");
        fsj_24.setField("displayPlants");
        fsj_24.setName("weather.manager");
        fdd_23.X(fsj_24);
        fsj_24.guy();
        fsj_24.onChildrenAdded();
        fdd_23.onChildrenAdded();
        fbv_2 fbv_28 = new fbv_2();
        fbv_28.aVI();
        fbv_28.setElementMap(fhs_22);
        fbv_28.setStyle("bold");
        String string4 = "%resource.plants%";
        string4 = string4.replace("%resource.plants%", fyw_0.gqw().k("resource.plants", new Object[0]));
        fbv_28.setText(string4);
        faw_212.X(fbv_28);
        fbv_28.guy();
        fbv_28.onChildrenAdded();
        fdd_2 fdd_24 = new fdd_2();
        fdd_24.aVI();
        fdd_24.setElementMap(fhs_22);
        fmo_1 fmo_14 = new fmo_1();
        fmo_14.vw("wakfu.weatherInformation:onTreesSelectionChange");
        fdd_24.setOnSelectionChange(fmo_14);
        fdd_24.setStyle("filter");
        faw_212.X(fdd_24);
        fdd_24.guy();
        fsj_2 fsj_25 = fsj_2.checkOut();
        fsj_25.setElementMap(fhs_22);
        fsj_25.setAttribute("selected");
        fsj_25.setField("displayTrees");
        fsj_25.setName("weather.manager");
        fdd_24.X(fsj_25);
        fsj_25.guy();
        fsj_25.onChildrenAdded();
        fdd_24.onChildrenAdded();
        fbv_2 fbv_29 = new fbv_2();
        fbv_29.aVI();
        fbv_29.setElementMap(fhs_22);
        fbv_29.setStyle("bold");
        String string5 = "%resource.trees%";
        string5 = string5.replace("%resource.trees%", fyw_0.gqw().k("resource.trees", new Object[0]));
        fbv_29.setText(string5);
        faw_212.X(fbv_29);
        fbv_29.guy();
        fbv_29.onChildrenAdded();
        faw_212.onChildrenAdded();
        String string6 = "resource";
        fbz_2 fbz_24 = new fbz_2();
        fbz_24.aVI();
        fbz_24.setElementMap(fhs_22);
        if (fhs_22 != null && string6 != null) {
            fhs_22.a(string6, fbz_24);
        }
        fbz_24.setCellSize(new fsm_1(100.0f, 68));
        fbz_24.setHorizontal(false);
        fbz_24.setPrefSize(new fsm_1(209, 0));
        faw_29.X(fbz_24);
        fbz_24.guy();
        frb_1 frb_13 = new frb_1();
        frb_13.aVI();
        frb_13.setElementMap(fhs_22);
        frb_13.setAlign(faa_2.tLO);
        fbz_24.X(frb_13);
        frb_13.guy();
        frb_13.onChildrenAdded();
        fsj_2 fsj_26 = fsj_2.checkOut();
        fsj_26.setElementMap(fhs_22);
        fsj_26.setAttribute("content");
        fsj_26.setField("resources");
        fsj_26.setName("weather.manager");
        fbz_24.X(fsj_26);
        fsj_26.guy();
        fsj_26.onChildrenAdded();
        fje_2 fje_23 = new fje_2();
        fje_23.aVI();
        fje_23.setElementMap(fhs_22);
        fbz_24.X(fje_23);
        fje_23.guy();
        fjt_2 fjt_23 = new fjt_2();
        fjt_23.aVI();
        fjt_23.setElementMap(fhs_22);
        fje_23.X(fjt_23);
        fjt_23.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_23.X(fjx_12);
        fjx_12.guy();
        fjd_1 fjd_12 = new fjd_1();
        fjd_12.aVI();
        fjd_12.setElementMap(fhs_22);
        fjx_12.X(fjd_12);
        fjd_12.guy();
        fjd_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_23.onChildrenAdded();
        faw_2 faw_214 = faw_2.checkOut();
        faw_214.setElementMap(fhs_22);
        faw_214.setExpandable(false);
        faw_214.setPrefSize(new fsm_1(196, 68));
        faw_214.setStyle("weatherInfo");
        fje_23.X(faw_214);
        faw_214.guy();
        frb_1 frb_14 = new frb_1();
        frb_14.aVI();
        frb_14.setElementMap(fhs_22);
        frb_14.setAlign(faa_2.tLN);
        faw_214.X(frb_14);
        frb_14.guy();
        frb_14.onChildrenAdded();
        fro_1 fro_13 = new fro_1();
        fro_13.aVI();
        faw_214.X(fro_13);
        fro_13.guy();
        fro_13.onChildrenAdded();
        fbt_1 fbt_14 = new fbt_1();
        fbt_14.aVI();
        fbt_14.setElementMap(fhs_22);
        fbt_14.setDisplaySize(new fsm_1(48, 48));
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(resourceNamePopup)");
        fbt_14.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_14.setOnPopupHide(fml_12);
        faw_214.X(fbt_14);
        fbt_14.guy();
        frp_1 frp_14 = new frp_1();
        frp_14.aVI();
        frp_14.setElementMap(fhs_22);
        frp_14.setAlign(fzw_0.tLf);
        frp_14.setSize(new fsm_1(48, 48));
        frp_14.setXOffset(30);
        fbt_14.X(frp_14);
        frp_14.guy();
        frp_14.onChildrenAdded();
        this.w(fbt_14);
        this.x(fbt_14);
        fbt_14.onChildrenAdded();
        this.I(faw_214);
        this.h(faw_214);
        this.J(faw_214);
        this.K(faw_214);
        this.i(faw_214);
        this.j(faw_214);
        this.L(faw_214);
        this.M(faw_214);
        this.N(faw_214);
        this.O(faw_214);
        faw_214.onChildrenAdded();
        fje_23.onChildrenAdded();
        this.t(fbz_24);
        fbz_24.onChildrenAdded();
        faw_29.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 w(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("iconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 x(fbt_1 fbt_12) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "resourceNamePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fbt_12.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("white11");
        faw_22.X(fdy_12);
        fdy_12.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("name");
        fdy_12.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 I(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setPrefSize(new fsm_1(25, 0));
        fbv_22.setStyle("SmallBoldTitleDark");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("gray50Color"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLo);
        frp_12.setXOffset(-63);
        frp_12.setYOffset(8);
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("extendedMinTemperature");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 h(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setPrefSize(new fsm_1(25, 0));
        fbv_22.setStyle("SmallBoldTitleDark");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("gray50Color"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLo);
        frp_12.setXOffset(-33);
        frp_12.setYOffset(8);
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("idealMinTemperature");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 J(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "coldContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(badTemperaturePopup,coldContainer)");
        faw_23.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_23.setOnPopupHide(fml_12);
        faw_23.setPrefSize(new fsm_1(90, 20));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLo);
        frp_12.setYOffset(8);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 K(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setPrefSize(new fsm_1(30, 0));
        fbv_22.setStyle("defaultBold14Black");
        faw_22.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setXOffset(-53);
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("idealMinTemperature");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 i(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setPrefSize(new fsm_1(30, 0));
        fbv_22.setStyle("defaultBold14Black");
        faw_22.X(fbv_22);
        fbv_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setXOffset(-13);
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("idealMaxTemperature");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 j(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "averageTempContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(optimalTemperaturePopup,averageTempContainer)");
        faw_23.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_23.setOnPopupHide(fml_12);
        faw_23.setPrefSize(new fsm_1(83, 20));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 L(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setPrefSize(new fsm_1(25, 0));
        fbv_22.setStyle("SmallBoldTitleDark");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("gray50Color"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setXOffset(-63);
        frp_12.setYOffset(-7);
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("idealMaxTemperature");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 M(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fbv_2 fbv_22 = new fbv_2();
        fbv_22.aVI();
        fbv_22.setElementMap(fhs_22);
        fbv_22.setPrefSize(new fsm_1(25, 0));
        fbv_22.setStyle("SmallBoldTitleDark");
        faw_22.X(fbv_22);
        fbv_22.guy();
        fbv_2 fbv_23 = fbv_22;
        fzq fzq2 = (fzq)((fes_2)fbv_23).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlign(faa_2.tLO);
        fbv_22.X(fzq2);
        fzq2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("gray50Color"));
        fyp_02.setName("text");
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fzq2.onChildrenAdded();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setXOffset(-33);
        frp_12.setYOffset(-7);
        fbv_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("text");
        fsd_12.setField("extendedMaxTemperature");
        fbv_22.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fbv_22.onChildrenAdded();
        return fbv_22;
    }

    public fhi_2 N(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "hotContainer";
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, faw_23);
        }
        faw_23.setNonBlocking(false);
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(badTemperaturePopup,hotContainer)");
        faw_23.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        faw_23.setOnPopupHide(fml_12);
        faw_23.setPrefSize(new fsm_1(90, 20));
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setYOffset(-7);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 O(faw_2 faw_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_23 = faw_2.checkOut();
        faw_23.setElementMap(fhs_22);
        faw_23.setStyle("weatherInfoHumidity");
        faw_22.X(faw_23);
        faw_23.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLf);
        frp_12.setXOffset(7);
        faw_23.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        String string = "humidityImage";
        fbt_1 fbt_12 = new fbt_1();
        fbt_12.aVI();
        fbt_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fbt_12);
        }
        fbt_12.setDisplaySize(new fsm_1(31, 31));
        fmk_2 fmk_22 = new fmk_2();
        fmk_22.vw("popup(optimalHumidityPopup,humidityImage)");
        fbt_12.setOnPopupDisplay(fmk_22);
        fml_1 fml_12 = new fml_1();
        fml_12.vw("closePopup");
        fbt_12.setOnPopupHide(fml_12);
        faw_23.X(fbt_12);
        fbt_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fbt_12.X(fze2);
        fze2.guy();
        fsd_1 fsd_12 = new fsd_1();
        fsd_12.aVI();
        fsd_12.setElementMap(fhs_22);
        fsd_12.setAttribute("texture");
        fsd_12.setField("idealRainIconUrl");
        fze2.X(fsd_12);
        fsd_12.guy();
        fsd_12.onChildrenAdded();
        fze2.onChildrenAdded();
        fbt_12.onChildrenAdded();
        faw_23.onChildrenAdded();
        return faw_23;
    }

    public fhi_2 t(fbz_2 fbz_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fje_2 fje_22 = new fje_2();
        fje_22.aVI();
        fje_22.setElementMap(fhs_22);
        fbz_22.X(fje_22);
        fje_22.guy();
        fjt_2 fjt_22 = new fjt_2();
        fjt_22.aVI();
        fjt_22.setElementMap(fhs_22);
        fje_22.X(fjt_22);
        fjt_22.guy();
        fjx_1 fjx_12 = new fjx_1();
        fjx_12.aVI();
        fjx_12.setElementMap(fhs_22);
        fjt_22.X(fjx_12);
        fjx_12.guy();
        fje_1 fje_12 = new fje_1();
        fje_12.aVI();
        fje_12.setElementMap(fhs_22);
        fjx_12.X(fje_12);
        fje_12.guy();
        fje_12.onChildrenAdded();
        fjx_12.onChildrenAdded();
        fjt_22.onChildrenAdded();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setExpandable(false);
        faw_22.setPrefSize(new fsm_1(196, 68));
        faw_22.setStyle("weatherInfo");
        fje_22.X(faw_22);
        faw_22.guy();
        faw_2 faw_23 = faw_22;
        fys_0 fys_02 = ((fes_2)faw_23).getAppearance();
        fys_02.setElementMap(fhs_22);
        fys_02.setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 0.4f));
        faw_22.X(fys_02);
        fys_02.guy();
        fys_02.onChildrenAdded();
        frb_1 frb_12 = new frb_1();
        frb_12.aVI();
        frb_12.setElementMap(fhs_22);
        frb_12.setAlign(faa_2.tLN);
        faw_22.X(frb_12);
        frb_12.guy();
        frb_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        fje_22.onChildrenAdded();
        return fje_22;
    }

    public fhi_2 s(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        fey_22.X(faw_22);
        faw_22.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setSize(new fsm_1(100.0f, 100.0f));
        faw_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        return faw_22;
    }

    public fhi_2 aL(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fad_1 fad_12 = new fad_1();
        fad_12.aVI();
        fad_12.setElementMap(fhs_22);
        fad_12.setExpandable(false);
        fad_12.setStyle("close");
        fmz_1 fmz_12 = new fmz_1();
        fmz_12.vw("wakfu.weatherInformation:closeDialog");
        fad_12.setOnClick(fmz_12);
        fey_22.X(fad_12);
        fad_12.guy();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLc);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-18);
        frp_12.setYOffset(-12);
        fad_12.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        fad_12.onChildrenAdded();
        return fad_12;
    }

    public fhi_2 E(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        frp_1 frp_12 = new frp_1();
        frp_12.aVI();
        frp_12.setElementMap(fhs_22);
        frp_12.setAlign(fzw_0.tLh);
        frp_12.setInitValue(true);
        frp_12.setSize(new fsm_1(-2, -2));
        frp_12.setXOffset(-20);
        fey_22.X(frp_12);
        frp_12.guy();
        frp_12.onChildrenAdded();
        return frp_12;
    }

    public fhi_2 Q(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "optimalHumidityPopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fey_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("white");
        String string2 = "%weather.resource.climate.optimalHumidity%";
        string2 = string2.replace("%weather.resource.climate.optimalHumidity%", fyw_0.gqw().k("weather.resource.climate.optimalHumidity", new Object[0]));
        fdy_12.setText(string2);
        faw_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 Y(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "optimalTemperaturePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fey_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("white");
        String string2 = "%weather.resource.climate.optimalTemperature%";
        string2 = string2.replace("%weather.resource.climate.optimalTemperature%", fyw_0.gqw().k("weather.resource.climate.optimalTemperature", new Object[0]));
        fdy_12.setText(string2);
        faw_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }

    public fhi_2 Z(fey_2 fey_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "badTemperaturePopup";
        frx_1 frx_12 = new frx_1();
        frx_12.aVI();
        frx_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, frx_12);
        }
        frx_12.setAlign(faa_2.tLL);
        frx_12.setHotSpotPosition(faa_2.tLR);
        fey_22.X(frx_12);
        frx_12.guy();
        faw_2 faw_22 = faw_2.checkOut();
        faw_22.setElementMap(fhs_22);
        faw_22.setPrefSize(new fsm_1(10, 0));
        faw_22.setStyle("popup");
        frx_12.X(faw_22);
        faw_22.guy();
        fru_1 fru_12 = fru_1.checkOut();
        fru_12.setElementMap(fhs_22);
        fru_12.setData(fzt_0.tKA);
        faw_22.X(fru_12);
        fru_12.guy();
        fru_12.onChildrenAdded();
        frz_2 frz_22 = frz_2.checkOut();
        frz_22.setHorizontal(false);
        faw_22.X(frz_22);
        frz_22.guy();
        frz_22.onChildrenAdded();
        fdy_1 fdy_12 = new fdy_1();
        fdy_12.aVI();
        fdy_12.setElementMap(fhs_22);
        fdy_12.setStyle("white");
        String string2 = "%weather.resource.climate.badTemperature%";
        string2 = string2.replace("%weather.resource.climate.badTemperature%", fyw_0.gqw().k("weather.resource.climate.badTemperature", new Object[0]));
        fdy_12.setText(string2);
        faw_22.X(fdy_12);
        fdy_12.guy();
        fdy_1 fdy_13 = fdy_12;
        fzq fzq2 = (fzq)((fes_2)fdy_13).getAppearance();
        fzq2.setElementMap(fhs_22);
        fzq2.setAlignment(faa_2.tLO);
        fdy_12.X(fzq2);
        fzq2.guy();
        fzq2.onChildrenAdded();
        fdy_12.onChildrenAdded();
        faw_22.onChildrenAdded();
        frx_12.onChildrenAdded();
        return frx_12;
    }
}

