/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from diA
 */
public class dia_1
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fym_0 fym_02 = (fym_0)fes_23.getAppearance();
        fym_02.setElementMap(fhs_23);
        fym_02.setAlignment(faa_2.tLO);
        fym_02.setState("default");
        fes_22.X(fym_02);
        fym_02.guy();
        String string = "pmCogLightPrimaryMedium";
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fze2);
        }
        fze2.setHeight(16);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txCog"));
        fze2.setWidth(16);
        fze2.setX(2);
        fze2.setY(2);
        fym_02.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        fym_02.X(fkd_12);
        fkd_12.guy();
        fkd_12.onChildrenAdded();
        fym_02.onChildrenAdded();
        fes_2 fes_24 = fes_22;
        fym_0 fym_03 = (fym_0)fes_24.getAppearance();
        fym_03.setElementMap(fhs_23);
        fym_03.setAlignment(faa_2.tLO);
        fym_03.setState("mouseHover");
        fes_22.X(fym_03);
        fym_03.guy();
        String string2 = "pmCogPrimaryLight";
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fze3);
        }
        fze3.setHeight(16);
        fze3.setPosition(fzw_0.tLg);
        fze3.setTexture(this.okR.uF("txCog"));
        fze3.setWidth(16);
        fze3.setX(2);
        fze3.setY(24);
        fym_03.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        String string3 = "pmbHoverButtonTertiary";
        fkd_1 fkd_13 = fkd_1.checkOut();
        fkd_13.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fkd_13);
        }
        fkd_13.setScaled(true);
        fym_03.X(fkd_13);
        fkd_13.guy();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(6);
        fze4.setPosition(fzw_0.tKY);
        fze4.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze4.setWidth(6);
        fze4.setX(0);
        fze4.setY(38);
        fkd_13.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(1);
        fze5.setPosition(fzw_0.tLf);
        fze5.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze5.setWidth(6);
        fze5.setX(0);
        fze5.setY(44);
        fkd_13.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(6);
        fze6.setPosition(fzw_0.tLk);
        fze6.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze6.setWidth(6);
        fze6.setX(0);
        fze6.setY(68);
        fkd_13.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(6);
        fze7.setPosition(fzw_0.tLa);
        fze7.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze7.setWidth(1);
        fze7.setX(18);
        fze7.setY(38);
        fkd_13.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setHeight(1);
        fze8.setPosition(fzw_0.tLg);
        fze8.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze8.setWidth(1);
        fze8.setX(18);
        fze8.setY(56);
        fkd_13.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setHeight(6);
        fze9.setPosition(fzw_0.tLm);
        fze9.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze9.setWidth(1);
        fze9.setX(18);
        fze9.setY(68);
        fkd_13.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setHeight(6);
        fze10.setPosition(fzw_0.tLc);
        fze10.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze10.setWidth(6);
        fze10.setX(30);
        fze10.setY(38);
        fkd_13.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        fze11.setHeight(1);
        fze11.setPosition(fzw_0.tLh);
        fze11.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze11.setWidth(6);
        fze11.setX(30);
        fze11.setY(56);
        fkd_13.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fze fze12 = fze.checkOut();
        fze12.setElementMap(fhs_23);
        fze12.setHeight(6);
        fze12.setPosition(fzw_0.tLo);
        fze12.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze12.setWidth(6);
        fze12.setX(30);
        fze12.setY(68);
        fkd_13.X(fze12);
        fze12.guy();
        fze12.onChildrenAdded();
        fkd_13.onChildrenAdded();
        fym_03.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fym_0 fym_04 = (fym_0)fes_25.getAppearance();
        fym_04.setElementMap(fhs_23);
        fym_04.setAlignment(faa_2.tLO);
        fym_04.setState("pressed");
        fes_22.X(fym_04);
        fym_04.guy();
        String string4 = "pmCogWhite100";
        fze fze13 = fze.checkOut();
        fze13.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fze13);
        }
        fze13.setHeight(16);
        fze13.setPosition(fzw_0.tLg);
        fze13.setTexture(this.okR.uF("txCog"));
        fze13.setWidth(16);
        fze13.setX(2);
        fze13.setY(46);
        fym_04.X(fze13);
        fze13.guy();
        fze13.onChildrenAdded();
        String string5 = "pmbPressedButtonTertiary";
        fkd_1 fkd_14 = fkd_1.checkOut();
        fkd_14.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fkd_14);
        }
        fkd_14.setScaled(true);
        fym_04.X(fkd_14);
        fkd_14.guy();
        fze fze14 = fze.checkOut();
        fze14.setElementMap(fhs_23);
        fze14.setHeight(6);
        fze14.setPosition(fzw_0.tKY);
        fze14.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze14.setWidth(6);
        fze14.setX(0);
        fze14.setY(76);
        fkd_14.X(fze14);
        fze14.guy();
        fze14.onChildrenAdded();
        fze fze15 = fze.checkOut();
        fze15.setElementMap(fhs_23);
        fze15.setHeight(1);
        fze15.setPosition(fzw_0.tLf);
        fze15.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze15.setWidth(6);
        fze15.setX(0);
        fze15.setY(82);
        fkd_14.X(fze15);
        fze15.guy();
        fze15.onChildrenAdded();
        fze fze16 = fze.checkOut();
        fze16.setElementMap(fhs_23);
        fze16.setHeight(6);
        fze16.setPosition(fzw_0.tLk);
        fze16.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze16.setWidth(6);
        fze16.setX(0);
        fze16.setY(106);
        fkd_14.X(fze16);
        fze16.guy();
        fze16.onChildrenAdded();
        fze fze17 = fze.checkOut();
        fze17.setElementMap(fhs_23);
        fze17.setHeight(6);
        fze17.setPosition(fzw_0.tLa);
        fze17.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze17.setWidth(1);
        fze17.setX(18);
        fze17.setY(76);
        fkd_14.X(fze17);
        fze17.guy();
        fze17.onChildrenAdded();
        fze fze18 = fze.checkOut();
        fze18.setElementMap(fhs_23);
        fze18.setHeight(1);
        fze18.setPosition(fzw_0.tLg);
        fze18.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze18.setWidth(1);
        fze18.setX(18);
        fze18.setY(94);
        fkd_14.X(fze18);
        fze18.guy();
        fze18.onChildrenAdded();
        fze fze19 = fze.checkOut();
        fze19.setElementMap(fhs_23);
        fze19.setHeight(6);
        fze19.setPosition(fzw_0.tLm);
        fze19.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze19.setWidth(1);
        fze19.setX(18);
        fze19.setY(106);
        fkd_14.X(fze19);
        fze19.guy();
        fze19.onChildrenAdded();
        fze fze20 = fze.checkOut();
        fze20.setElementMap(fhs_23);
        fze20.setHeight(6);
        fze20.setPosition(fzw_0.tLc);
        fze20.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze20.setWidth(6);
        fze20.setX(30);
        fze20.setY(76);
        fkd_14.X(fze20);
        fze20.guy();
        fze20.onChildrenAdded();
        fze fze21 = fze.checkOut();
        fze21.setElementMap(fhs_23);
        fze21.setHeight(1);
        fze21.setPosition(fzw_0.tLh);
        fze21.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze21.setWidth(6);
        fze21.setX(30);
        fze21.setY(94);
        fkd_14.X(fze21);
        fze21.guy();
        fze21.onChildrenAdded();
        fze fze22 = fze.checkOut();
        fze22.setElementMap(fhs_23);
        fze22.setHeight(6);
        fze22.setPosition(fzw_0.tLo);
        fze22.setTexture(this.okR.uF("txTertiaryToggleSmall"));
        fze22.setWidth(6);
        fze22.setX(30);
        fze22.setY(106);
        fkd_14.X(fze22);
        fze22.guy();
        fze22.onChildrenAdded();
        fkd_14.onChildrenAdded();
        fym_04.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fym_0 fym_05 = (fym_0)fes_26.getAppearance();
        fym_05.setElementMap(fhs_23);
        fym_05.setAlignment(faa_2.tLO);
        fym_05.setState("disabled");
        fes_22.X(fym_05);
        fym_05.guy();
        String string6 = "pmCogWhite25";
        fze fze23 = fze.checkOut();
        fze23.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fze23);
        }
        fze23.setHeight(16);
        fze23.setPosition(fzw_0.tLg);
        fze23.setTexture(this.okR.uF("txCog"));
        fze23.setWidth(16);
        fze23.setX(2);
        fze23.setY(90);
        fym_05.X(fze23);
        fze23.guy();
        fze23.onChildrenAdded();
        fkd_1 fkd_15 = fkd_1.checkOut();
        fkd_15.setElementMap(fhs_23);
        fym_05.X(fkd_15);
        fkd_15.guy();
        fkd_15.onChildrenAdded();
        fym_05.onChildrenAdded();
    }
}

