/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from did
 */
public class did_1
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fym_0 fym_02 = (fym_0)fes_23.getAppearance();
        fym_02.setElementMap(fhs_23);
        fym_02.setAlignment(faa_2.tLO);
        fym_02.setState("default");
        fes_22.X(fym_02);
        fym_02.guy();
        String string = "pmbDefaultChatTabButton";
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fkd_12);
        }
        fkd_12.setScaled(true);
        fym_02.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(7);
        fze2.setPosition(fzw_0.tKY);
        fze2.setTexture(this.okR.uF("txChatTabButton"));
        fze2.setWidth(7);
        fze2.setX(0);
        fze2.setY(18);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(1);
        fze3.setPosition(fzw_0.tLf);
        fze3.setTexture(this.okR.uF("txChatTabButton"));
        fze3.setWidth(7);
        fze3.setX(0);
        fze3.setY(26);
        fkd_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(7);
        fze4.setPosition(fzw_0.tLk);
        fze4.setTexture(this.okR.uF("txChatTabButton"));
        fze4.setWidth(7);
        fze4.setX(0);
        fze4.setY(27);
        fkd_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(7);
        fze5.setPosition(fzw_0.tLa);
        fze5.setTexture(this.okR.uF("txChatTabButton"));
        fze5.setWidth(1);
        fze5.setX(8);
        fze5.setY(18);
        fkd_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(1);
        fze6.setPosition(fzw_0.tLg);
        fze6.setTexture(this.okR.uF("txChatTabButton"));
        fze6.setWidth(1);
        fze6.setX(8);
        fze6.setY(26);
        fkd_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(7);
        fze7.setPosition(fzw_0.tLm);
        fze7.setTexture(this.okR.uF("txChatTabButton"));
        fze7.setWidth(1);
        fze7.setX(8);
        fze7.setY(27);
        fkd_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setHeight(7);
        fze8.setPosition(fzw_0.tLc);
        fze8.setTexture(this.okR.uF("txChatTabButton"));
        fze8.setWidth(7);
        fze8.setX(9);
        fze8.setY(18);
        fkd_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setHeight(1);
        fze9.setPosition(fzw_0.tLh);
        fze9.setTexture(this.okR.uF("txChatTabButton"));
        fze9.setWidth(7);
        fze9.setX(9);
        fze9.setY(26);
        fkd_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setHeight(7);
        fze10.setPosition(fzw_0.tLo);
        fze10.setTexture(this.okR.uF("txChatTabButton"));
        fze10.setWidth(7);
        fze10.setX(9);
        fze10.setY(27);
        fkd_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkd_12.onChildrenAdded();
        String string2 = "pmPlusLightPrimaryMedium";
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fze11);
        }
        fze11.setHeight(16);
        fze11.setPosition(fzw_0.tLg);
        fze11.setTexture(this.okR.uF("txPlusNew"));
        fze11.setWidth(16);
        fze11.setX(2);
        fze11.setY(2);
        fym_02.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fym_02.onChildrenAdded();
        fes_2 fes_24 = fes_22;
        fym_0 fym_03 = (fym_0)fes_24.getAppearance();
        fym_03.setElementMap(fhs_23);
        fym_03.setAlignment(faa_2.tLO);
        fym_03.setState("mouseHover");
        fes_22.X(fym_03);
        fym_03.guy();
        String string3 = "pmbHoverPressedChatTabButton";
        fkd_1 fkd_13 = fkd_1.checkOut();
        fkd_13.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fkd_13);
        }
        fkd_13.setScaled(true);
        fym_03.X(fkd_13);
        fkd_13.guy();
        fze fze12 = fze.checkOut();
        fze12.setElementMap(fhs_23);
        fze12.setHeight(7);
        fze12.setPosition(fzw_0.tKY);
        fze12.setTexture(this.okR.uF("txChatTabButton"));
        fze12.setWidth(7);
        fze12.setX(0);
        fze12.setY(36);
        fkd_13.X(fze12);
        fze12.guy();
        fze12.onChildrenAdded();
        fze fze13 = fze.checkOut();
        fze13.setElementMap(fhs_23);
        fze13.setHeight(1);
        fze13.setPosition(fzw_0.tLf);
        fze13.setTexture(this.okR.uF("txChatTabButton"));
        fze13.setWidth(7);
        fze13.setX(0);
        fze13.setY(44);
        fkd_13.X(fze13);
        fze13.guy();
        fze13.onChildrenAdded();
        fze fze14 = fze.checkOut();
        fze14.setElementMap(fhs_23);
        fze14.setHeight(7);
        fze14.setPosition(fzw_0.tLk);
        fze14.setTexture(this.okR.uF("txChatTabButton"));
        fze14.setWidth(7);
        fze14.setX(0);
        fze14.setY(45);
        fkd_13.X(fze14);
        fze14.guy();
        fze14.onChildrenAdded();
        fze fze15 = fze.checkOut();
        fze15.setElementMap(fhs_23);
        fze15.setHeight(7);
        fze15.setPosition(fzw_0.tLa);
        fze15.setTexture(this.okR.uF("txChatTabButton"));
        fze15.setWidth(1);
        fze15.setX(8);
        fze15.setY(36);
        fkd_13.X(fze15);
        fze15.guy();
        fze15.onChildrenAdded();
        fze fze16 = fze.checkOut();
        fze16.setElementMap(fhs_23);
        fze16.setHeight(1);
        fze16.setPosition(fzw_0.tLg);
        fze16.setTexture(this.okR.uF("txChatTabButton"));
        fze16.setWidth(1);
        fze16.setX(8);
        fze16.setY(44);
        fkd_13.X(fze16);
        fze16.guy();
        fze16.onChildrenAdded();
        fze fze17 = fze.checkOut();
        fze17.setElementMap(fhs_23);
        fze17.setHeight(7);
        fze17.setPosition(fzw_0.tLm);
        fze17.setTexture(this.okR.uF("txChatTabButton"));
        fze17.setWidth(1);
        fze17.setX(8);
        fze17.setY(45);
        fkd_13.X(fze17);
        fze17.guy();
        fze17.onChildrenAdded();
        fze fze18 = fze.checkOut();
        fze18.setElementMap(fhs_23);
        fze18.setHeight(7);
        fze18.setPosition(fzw_0.tLc);
        fze18.setTexture(this.okR.uF("txChatTabButton"));
        fze18.setWidth(7);
        fze18.setX(9);
        fze18.setY(36);
        fkd_13.X(fze18);
        fze18.guy();
        fze18.onChildrenAdded();
        fze fze19 = fze.checkOut();
        fze19.setElementMap(fhs_23);
        fze19.setHeight(1);
        fze19.setPosition(fzw_0.tLh);
        fze19.setTexture(this.okR.uF("txChatTabButton"));
        fze19.setWidth(7);
        fze19.setX(9);
        fze19.setY(44);
        fkd_13.X(fze19);
        fze19.guy();
        fze19.onChildrenAdded();
        fze fze20 = fze.checkOut();
        fze20.setElementMap(fhs_23);
        fze20.setHeight(7);
        fze20.setPosition(fzw_0.tLo);
        fze20.setTexture(this.okR.uF("txChatTabButton"));
        fze20.setWidth(7);
        fze20.setX(9);
        fze20.setY(45);
        fkd_13.X(fze20);
        fze20.guy();
        fze20.onChildrenAdded();
        fkd_13.onChildrenAdded();
        String string4 = "pmPlusPrimaryLight";
        fze fze21 = fze.checkOut();
        fze21.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fze21);
        }
        fze21.setHeight(16);
        fze21.setPosition(fzw_0.tLg);
        fze21.setTexture(this.okR.uF("txPlusNew"));
        fze21.setWidth(16);
        fze21.setX(2);
        fze21.setY(24);
        fym_03.X(fze21);
        fze21.guy();
        fze21.onChildrenAdded();
        fym_03.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fym_0 fym_04 = (fym_0)fes_25.getAppearance();
        fym_04.setElementMap(fhs_23);
        fym_04.setAlignment(faa_2.tLO);
        fym_04.setState("pressed");
        fes_22.X(fym_04);
        fym_04.guy();
        String string5 = "pmbHoverPressedChatTabButton";
        fkd_1 fkd_14 = fkd_1.checkOut();
        fkd_14.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fkd_14);
        }
        fkd_14.setScaled(true);
        fym_04.X(fkd_14);
        fkd_14.guy();
        fze fze22 = fze.checkOut();
        fze22.setElementMap(fhs_23);
        fze22.setHeight(7);
        fze22.setPosition(fzw_0.tKY);
        fze22.setTexture(this.okR.uF("txChatTabButton"));
        fze22.setWidth(7);
        fze22.setX(0);
        fze22.setY(36);
        fkd_14.X(fze22);
        fze22.guy();
        fze22.onChildrenAdded();
        fze fze23 = fze.checkOut();
        fze23.setElementMap(fhs_23);
        fze23.setHeight(1);
        fze23.setPosition(fzw_0.tLf);
        fze23.setTexture(this.okR.uF("txChatTabButton"));
        fze23.setWidth(7);
        fze23.setX(0);
        fze23.setY(44);
        fkd_14.X(fze23);
        fze23.guy();
        fze23.onChildrenAdded();
        fze fze24 = fze.checkOut();
        fze24.setElementMap(fhs_23);
        fze24.setHeight(7);
        fze24.setPosition(fzw_0.tLk);
        fze24.setTexture(this.okR.uF("txChatTabButton"));
        fze24.setWidth(7);
        fze24.setX(0);
        fze24.setY(45);
        fkd_14.X(fze24);
        fze24.guy();
        fze24.onChildrenAdded();
        fze fze25 = fze.checkOut();
        fze25.setElementMap(fhs_23);
        fze25.setHeight(7);
        fze25.setPosition(fzw_0.tLa);
        fze25.setTexture(this.okR.uF("txChatTabButton"));
        fze25.setWidth(1);
        fze25.setX(8);
        fze25.setY(36);
        fkd_14.X(fze25);
        fze25.guy();
        fze25.onChildrenAdded();
        fze fze26 = fze.checkOut();
        fze26.setElementMap(fhs_23);
        fze26.setHeight(1);
        fze26.setPosition(fzw_0.tLg);
        fze26.setTexture(this.okR.uF("txChatTabButton"));
        fze26.setWidth(1);
        fze26.setX(8);
        fze26.setY(44);
        fkd_14.X(fze26);
        fze26.guy();
        fze26.onChildrenAdded();
        fze fze27 = fze.checkOut();
        fze27.setElementMap(fhs_23);
        fze27.setHeight(7);
        fze27.setPosition(fzw_0.tLm);
        fze27.setTexture(this.okR.uF("txChatTabButton"));
        fze27.setWidth(1);
        fze27.setX(8);
        fze27.setY(45);
        fkd_14.X(fze27);
        fze27.guy();
        fze27.onChildrenAdded();
        fze fze28 = fze.checkOut();
        fze28.setElementMap(fhs_23);
        fze28.setHeight(7);
        fze28.setPosition(fzw_0.tLc);
        fze28.setTexture(this.okR.uF("txChatTabButton"));
        fze28.setWidth(7);
        fze28.setX(9);
        fze28.setY(36);
        fkd_14.X(fze28);
        fze28.guy();
        fze28.onChildrenAdded();
        fze fze29 = fze.checkOut();
        fze29.setElementMap(fhs_23);
        fze29.setHeight(1);
        fze29.setPosition(fzw_0.tLh);
        fze29.setTexture(this.okR.uF("txChatTabButton"));
        fze29.setWidth(7);
        fze29.setX(9);
        fze29.setY(44);
        fkd_14.X(fze29);
        fze29.guy();
        fze29.onChildrenAdded();
        fze fze30 = fze.checkOut();
        fze30.setElementMap(fhs_23);
        fze30.setHeight(7);
        fze30.setPosition(fzw_0.tLo);
        fze30.setTexture(this.okR.uF("txChatTabButton"));
        fze30.setWidth(7);
        fze30.setX(9);
        fze30.setY(45);
        fkd_14.X(fze30);
        fze30.guy();
        fze30.onChildrenAdded();
        fkd_14.onChildrenAdded();
        String string6 = "pmPlusWhite100";
        fze fze31 = fze.checkOut();
        fze31.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fze31);
        }
        fze31.setHeight(16);
        fze31.setPosition(fzw_0.tLg);
        fze31.setTexture(this.okR.uF("txPlusNew"));
        fze31.setWidth(16);
        fze31.setX(2);
        fze31.setY(46);
        fym_04.X(fze31);
        fze31.guy();
        fze31.onChildrenAdded();
        fym_04.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fym_0 fym_05 = (fym_0)fes_26.getAppearance();
        fym_05.setElementMap(fhs_23);
        fym_05.setAlignment(faa_2.tLO);
        fym_05.setState("disabled");
        fes_22.X(fym_05);
        fym_05.guy();
        String string7 = "pmbDisabledChatTabButton";
        fkd_1 fkd_15 = fkd_1.checkOut();
        fkd_15.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fkd_15);
        }
        fkd_15.setScaled(true);
        fym_05.X(fkd_15);
        fkd_15.guy();
        fze fze32 = fze.checkOut();
        fze32.setElementMap(fhs_23);
        fze32.setHeight(7);
        fze32.setPosition(fzw_0.tKY);
        fze32.setTexture(this.okR.uF("txChatTabButton"));
        fze32.setWidth(7);
        fze32.setX(0);
        fze32.setY(0);
        fkd_15.X(fze32);
        fze32.guy();
        fze32.onChildrenAdded();
        fze fze33 = fze.checkOut();
        fze33.setElementMap(fhs_23);
        fze33.setHeight(1);
        fze33.setPosition(fzw_0.tLf);
        fze33.setTexture(this.okR.uF("txChatTabButton"));
        fze33.setWidth(7);
        fze33.setX(0);
        fze33.setY(8);
        fkd_15.X(fze33);
        fze33.guy();
        fze33.onChildrenAdded();
        fze fze34 = fze.checkOut();
        fze34.setElementMap(fhs_23);
        fze34.setHeight(7);
        fze34.setPosition(fzw_0.tLk);
        fze34.setTexture(this.okR.uF("txChatTabButton"));
        fze34.setWidth(7);
        fze34.setX(0);
        fze34.setY(9);
        fkd_15.X(fze34);
        fze34.guy();
        fze34.onChildrenAdded();
        fze fze35 = fze.checkOut();
        fze35.setElementMap(fhs_23);
        fze35.setHeight(7);
        fze35.setPosition(fzw_0.tLa);
        fze35.setTexture(this.okR.uF("txChatTabButton"));
        fze35.setWidth(1);
        fze35.setX(8);
        fze35.setY(0);
        fkd_15.X(fze35);
        fze35.guy();
        fze35.onChildrenAdded();
        fze fze36 = fze.checkOut();
        fze36.setElementMap(fhs_23);
        fze36.setHeight(1);
        fze36.setPosition(fzw_0.tLg);
        fze36.setTexture(this.okR.uF("txChatTabButton"));
        fze36.setWidth(1);
        fze36.setX(8);
        fze36.setY(8);
        fkd_15.X(fze36);
        fze36.guy();
        fze36.onChildrenAdded();
        fze fze37 = fze.checkOut();
        fze37.setElementMap(fhs_23);
        fze37.setHeight(7);
        fze37.setPosition(fzw_0.tLm);
        fze37.setTexture(this.okR.uF("txChatTabButton"));
        fze37.setWidth(1);
        fze37.setX(8);
        fze37.setY(9);
        fkd_15.X(fze37);
        fze37.guy();
        fze37.onChildrenAdded();
        fze fze38 = fze.checkOut();
        fze38.setElementMap(fhs_23);
        fze38.setHeight(7);
        fze38.setPosition(fzw_0.tLc);
        fze38.setTexture(this.okR.uF("txChatTabButton"));
        fze38.setWidth(7);
        fze38.setX(9);
        fze38.setY(0);
        fkd_15.X(fze38);
        fze38.guy();
        fze38.onChildrenAdded();
        fze fze39 = fze.checkOut();
        fze39.setElementMap(fhs_23);
        fze39.setHeight(1);
        fze39.setPosition(fzw_0.tLh);
        fze39.setTexture(this.okR.uF("txChatTabButton"));
        fze39.setWidth(7);
        fze39.setX(9);
        fze39.setY(8);
        fkd_15.X(fze39);
        fze39.guy();
        fze39.onChildrenAdded();
        fze fze40 = fze.checkOut();
        fze40.setElementMap(fhs_23);
        fze40.setHeight(7);
        fze40.setPosition(fzw_0.tLo);
        fze40.setTexture(this.okR.uF("txChatTabButton"));
        fze40.setWidth(7);
        fze40.setX(9);
        fze40.setY(9);
        fkd_15.X(fze40);
        fze40.guy();
        fze40.onChildrenAdded();
        fkd_15.onChildrenAdded();
        this.b(fym_05);
        fym_05.onChildrenAdded();
    }

    public fhi_2 b(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        String string = "pmPlusWhite25";
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fze2);
        }
        fze2.setHeight(16);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txPlusNew"));
        fze2.setWidth(16);
        fze2.setX(2);
        fze2.setY(90);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }
}

