/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from dpV
 */
public class dpv_0
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fym_0 fym_02 = (fym_0)fes_23.getAppearance();
        fym_02.setElementMap(fhs_23);
        fym_02.setAlignment(faa_2.tLO);
        fym_02.setState("default");
        fes_22.X(fym_02);
        fym_02.guy();
        fyW fyW2 = fyW.checkOut();
        fyW2.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10Bold"));
        fyW2.setElementMap(fhs_23);
        fym_02.X(fyW2);
        fyW2.guy();
        fyW2.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("whiteColor"));
        fym_02.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        fkd_12.setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fym_02.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(19);
        fze2.setPosition(fzw_0.tKY);
        fze2.setTexture(this.okR.uF("themeDefault"));
        fze2.setWidth(26);
        fze2.setX(621);
        fze2.setY(937);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(0);
        fze3.setPosition(fzw_0.tLf);
        fze3.setTexture(this.okR.uF("themeDefault"));
        fze3.setWidth(26);
        fze3.setX(621);
        fze3.setY(956);
        fkd_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(19);
        fze4.setPosition(fzw_0.tLk);
        fze4.setTexture(this.okR.uF("themeDefault"));
        fze4.setWidth(26);
        fze4.setX(621);
        fze4.setY(956);
        fkd_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(19);
        fze5.setPosition(fzw_0.tLa);
        fze5.setTexture(this.okR.uF("themeDefault"));
        fze5.setWidth(1);
        fze5.setX(650);
        fze5.setY(937);
        fkd_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(0);
        fze6.setPosition(fzw_0.tLg);
        fze6.setTexture(this.okR.uF("themeDefault"));
        fze6.setWidth(1);
        fze6.setX(650);
        fze6.setY(956);
        fkd_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(19);
        fze7.setPosition(fzw_0.tLm);
        fze7.setTexture(this.okR.uF("themeDefault"));
        fze7.setWidth(1);
        fze7.setX(650);
        fze7.setY(956);
        fkd_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setFlipHorizontaly(true);
        fze8.setHeight(19);
        fze8.setPosition(fzw_0.tLc);
        fze8.setTexture(this.okR.uF("themeDefault"));
        fze8.setWidth(26);
        fze8.setX(621);
        fze8.setY(937);
        fkd_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setFlipHorizontaly(true);
        fze9.setHeight(0);
        fze9.setPosition(fzw_0.tLh);
        fze9.setTexture(this.okR.uF("themeDefault"));
        fze9.setWidth(26);
        fze9.setX(621);
        fze9.setY(956);
        fkd_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setFlipHorizontaly(true);
        fze10.setHeight(19);
        fze10.setPosition(fzw_0.tLo);
        fze10.setTexture(this.okR.uF("themeDefault"));
        fze10.setWidth(26);
        fze10.setX(621);
        fze10.setY(956);
        fkd_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkd_12.onChildrenAdded();
        fym_02.onChildrenAdded();
        fes_2 fes_24 = fes_22;
        fym_0 fym_03 = (fym_0)fes_24.getAppearance();
        fym_03.setElementMap(fhs_23);
        fym_03.setAlignment(faa_2.tLO);
        fym_03.setState("mouseHover");
        fes_22.X(fym_03);
        fym_03.guy();
        fkd_1 fkd_13 = fkd_1.checkOut();
        fkd_13.setElementMap(fhs_23);
        fkd_13.setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fym_03.X(fkd_13);
        fkd_13.guy();
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        fze11.setHeight(19);
        fze11.setPosition(fzw_0.tKY);
        fze11.setTexture(this.okR.uF("themeOver"));
        fze11.setWidth(26);
        fze11.setX(621);
        fze11.setY(937);
        fkd_13.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fze fze12 = fze.checkOut();
        fze12.setElementMap(fhs_23);
        fze12.setHeight(0);
        fze12.setPosition(fzw_0.tLf);
        fze12.setTexture(this.okR.uF("themeOver"));
        fze12.setWidth(26);
        fze12.setX(621);
        fze12.setY(956);
        fkd_13.X(fze12);
        fze12.guy();
        fze12.onChildrenAdded();
        fze fze13 = fze.checkOut();
        fze13.setElementMap(fhs_23);
        fze13.setHeight(19);
        fze13.setPosition(fzw_0.tLk);
        fze13.setTexture(this.okR.uF("themeOver"));
        fze13.setWidth(26);
        fze13.setX(621);
        fze13.setY(956);
        fkd_13.X(fze13);
        fze13.guy();
        fze13.onChildrenAdded();
        fze fze14 = fze.checkOut();
        fze14.setElementMap(fhs_23);
        fze14.setHeight(19);
        fze14.setPosition(fzw_0.tLa);
        fze14.setTexture(this.okR.uF("themeOver"));
        fze14.setWidth(1);
        fze14.setX(650);
        fze14.setY(937);
        fkd_13.X(fze14);
        fze14.guy();
        fze14.onChildrenAdded();
        fze fze15 = fze.checkOut();
        fze15.setElementMap(fhs_23);
        fze15.setHeight(0);
        fze15.setPosition(fzw_0.tLg);
        fze15.setTexture(this.okR.uF("themeOver"));
        fze15.setWidth(1);
        fze15.setX(650);
        fze15.setY(956);
        fkd_13.X(fze15);
        fze15.guy();
        fze15.onChildrenAdded();
        fze fze16 = fze.checkOut();
        fze16.setElementMap(fhs_23);
        fze16.setHeight(19);
        fze16.setPosition(fzw_0.tLm);
        fze16.setTexture(this.okR.uF("themeOver"));
        fze16.setWidth(1);
        fze16.setX(650);
        fze16.setY(956);
        fkd_13.X(fze16);
        fze16.guy();
        fze16.onChildrenAdded();
        fze fze17 = fze.checkOut();
        fze17.setElementMap(fhs_23);
        fze17.setFlipHorizontaly(true);
        fze17.setHeight(19);
        fze17.setPosition(fzw_0.tLc);
        fze17.setTexture(this.okR.uF("themeOver"));
        fze17.setWidth(26);
        fze17.setX(621);
        fze17.setY(937);
        fkd_13.X(fze17);
        fze17.guy();
        fze17.onChildrenAdded();
        fze fze18 = fze.checkOut();
        fze18.setElementMap(fhs_23);
        fze18.setFlipHorizontaly(true);
        fze18.setHeight(0);
        fze18.setPosition(fzw_0.tLh);
        fze18.setTexture(this.okR.uF("themeOver"));
        fze18.setWidth(26);
        fze18.setX(621);
        fze18.setY(956);
        fkd_13.X(fze18);
        fze18.guy();
        fze18.onChildrenAdded();
        fze fze19 = fze.checkOut();
        fze19.setElementMap(fhs_23);
        fze19.setFlipHorizontaly(true);
        fze19.setHeight(19);
        fze19.setPosition(fzw_0.tLo);
        fze19.setTexture(this.okR.uF("themeOver"));
        fze19.setWidth(26);
        fze19.setX(621);
        fze19.setY(956);
        fkd_13.X(fze19);
        fze19.guy();
        fze19.onChildrenAdded();
        fkd_13.onChildrenAdded();
        fym_03.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fym_0 fym_04 = (fym_0)fes_25.getAppearance();
        fym_04.setElementMap(fhs_23);
        fym_04.setAlignment(faa_2.tLO);
        fym_04.setState("pressed");
        fes_22.X(fym_04);
        fym_04.guy();
        fkd_1 fkd_14 = fkd_1.checkOut();
        fkd_14.setElementMap(fhs_23);
        fkd_14.setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 1.0f));
        fym_04.X(fkd_14);
        fkd_14.guy();
        fze fze20 = fze.checkOut();
        fze20.setElementMap(fhs_23);
        fze20.setHeight(19);
        fze20.setPosition(fzw_0.tKY);
        fze20.setTexture(this.okR.uF("themePressed"));
        fze20.setWidth(26);
        fze20.setX(621);
        fze20.setY(937);
        fkd_14.X(fze20);
        fze20.guy();
        fze20.onChildrenAdded();
        fze fze21 = fze.checkOut();
        fze21.setElementMap(fhs_23);
        fze21.setHeight(0);
        fze21.setPosition(fzw_0.tLf);
        fze21.setTexture(this.okR.uF("themePressed"));
        fze21.setWidth(26);
        fze21.setX(621);
        fze21.setY(956);
        fkd_14.X(fze21);
        fze21.guy();
        fze21.onChildrenAdded();
        fze fze22 = fze.checkOut();
        fze22.setElementMap(fhs_23);
        fze22.setHeight(19);
        fze22.setPosition(fzw_0.tLk);
        fze22.setTexture(this.okR.uF("themePressed"));
        fze22.setWidth(26);
        fze22.setX(621);
        fze22.setY(956);
        fkd_14.X(fze22);
        fze22.guy();
        fze22.onChildrenAdded();
        fze fze23 = fze.checkOut();
        fze23.setElementMap(fhs_23);
        fze23.setHeight(19);
        fze23.setPosition(fzw_0.tLa);
        fze23.setTexture(this.okR.uF("themePressed"));
        fze23.setWidth(1);
        fze23.setX(650);
        fze23.setY(937);
        fkd_14.X(fze23);
        fze23.guy();
        fze23.onChildrenAdded();
        fze fze24 = fze.checkOut();
        fze24.setElementMap(fhs_23);
        fze24.setHeight(0);
        fze24.setPosition(fzw_0.tLg);
        fze24.setTexture(this.okR.uF("themePressed"));
        fze24.setWidth(1);
        fze24.setX(650);
        fze24.setY(956);
        fkd_14.X(fze24);
        fze24.guy();
        fze24.onChildrenAdded();
        fze fze25 = fze.checkOut();
        fze25.setElementMap(fhs_23);
        fze25.setHeight(19);
        fze25.setPosition(fzw_0.tLm);
        fze25.setTexture(this.okR.uF("themePressed"));
        fze25.setWidth(1);
        fze25.setX(650);
        fze25.setY(956);
        fkd_14.X(fze25);
        fze25.guy();
        fze25.onChildrenAdded();
        fze fze26 = fze.checkOut();
        fze26.setElementMap(fhs_23);
        fze26.setFlipHorizontaly(true);
        fze26.setHeight(19);
        fze26.setPosition(fzw_0.tLc);
        fze26.setTexture(this.okR.uF("themePressed"));
        fze26.setWidth(26);
        fze26.setX(621);
        fze26.setY(937);
        fkd_14.X(fze26);
        fze26.guy();
        fze26.onChildrenAdded();
        fze fze27 = fze.checkOut();
        fze27.setElementMap(fhs_23);
        fze27.setFlipHorizontaly(true);
        fze27.setHeight(0);
        fze27.setPosition(fzw_0.tLh);
        fze27.setTexture(this.okR.uF("themePressed"));
        fze27.setWidth(26);
        fze27.setX(621);
        fze27.setY(956);
        fkd_14.X(fze27);
        fze27.guy();
        fze27.onChildrenAdded();
        fze fze28 = fze.checkOut();
        fze28.setElementMap(fhs_23);
        fze28.setFlipHorizontaly(true);
        fze28.setHeight(19);
        fze28.setPosition(fzw_0.tLo);
        fze28.setTexture(this.okR.uF("themePressed"));
        fze28.setWidth(26);
        fze28.setX(621);
        fze28.setY(956);
        fkd_14.X(fze28);
        fze28.guy();
        fze28.onChildrenAdded();
        fkd_14.onChildrenAdded();
        fym_04.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fym_0 fym_05 = (fym_0)fes_26.getAppearance();
        fym_05.setElementMap(fhs_23);
        fym_05.setAlignment(faa_2.tLO);
        fym_05.setState("disabled");
        fes_22.X(fym_05);
        fym_05.guy();
        fkd_1 fkd_15 = fkd_1.checkOut();
        fkd_15.setElementMap(fhs_23);
        fkd_15.setModulationColor(new awx_2(1.0f, 1.0f, 1.0f, 0.8f));
        fym_05.X(fkd_15);
        fkd_15.guy();
        fze fze29 = fze.checkOut();
        fze29.setElementMap(fhs_23);
        fze29.setHeight(19);
        fze29.setPosition(fzw_0.tKY);
        fze29.setTexture(this.okR.uF("themeDefault"));
        fze29.setWidth(26);
        fze29.setX(621);
        fze29.setY(937);
        fkd_15.X(fze29);
        fze29.guy();
        fze29.onChildrenAdded();
        fze fze30 = fze.checkOut();
        fze30.setElementMap(fhs_23);
        fze30.setHeight(0);
        fze30.setPosition(fzw_0.tLf);
        fze30.setTexture(this.okR.uF("themeDefault"));
        fze30.setWidth(26);
        fze30.setX(621);
        fze30.setY(956);
        fkd_15.X(fze30);
        fze30.guy();
        fze30.onChildrenAdded();
        fze fze31 = fze.checkOut();
        fze31.setElementMap(fhs_23);
        fze31.setHeight(19);
        fze31.setPosition(fzw_0.tLk);
        fze31.setTexture(this.okR.uF("themeDefault"));
        fze31.setWidth(26);
        fze31.setX(621);
        fze31.setY(956);
        fkd_15.X(fze31);
        fze31.guy();
        fze31.onChildrenAdded();
        fze fze32 = fze.checkOut();
        fze32.setElementMap(fhs_23);
        fze32.setHeight(19);
        fze32.setPosition(fzw_0.tLa);
        fze32.setTexture(this.okR.uF("themeDefault"));
        fze32.setWidth(1);
        fze32.setX(650);
        fze32.setY(937);
        fkd_15.X(fze32);
        fze32.guy();
        fze32.onChildrenAdded();
        fze fze33 = fze.checkOut();
        fze33.setElementMap(fhs_23);
        fze33.setHeight(0);
        fze33.setPosition(fzw_0.tLg);
        fze33.setTexture(this.okR.uF("themeDefault"));
        fze33.setWidth(1);
        fze33.setX(650);
        fze33.setY(956);
        fkd_15.X(fze33);
        fze33.guy();
        fze33.onChildrenAdded();
        fze fze34 = fze.checkOut();
        fze34.setElementMap(fhs_23);
        fze34.setHeight(19);
        fze34.setPosition(fzw_0.tLm);
        fze34.setTexture(this.okR.uF("themeDefault"));
        fze34.setWidth(1);
        fze34.setX(650);
        fze34.setY(956);
        fkd_15.X(fze34);
        fze34.guy();
        fze34.onChildrenAdded();
        fze fze35 = fze.checkOut();
        fze35.setElementMap(fhs_23);
        fze35.setFlipHorizontaly(true);
        fze35.setHeight(19);
        fze35.setPosition(fzw_0.tLc);
        fze35.setTexture(this.okR.uF("themeDefault"));
        fze35.setWidth(26);
        fze35.setX(621);
        fze35.setY(937);
        fkd_15.X(fze35);
        fze35.guy();
        fze35.onChildrenAdded();
        fze fze36 = fze.checkOut();
        fze36.setElementMap(fhs_23);
        fze36.setFlipHorizontaly(true);
        fze36.setHeight(0);
        fze36.setPosition(fzw_0.tLh);
        fze36.setTexture(this.okR.uF("themeDefault"));
        fze36.setWidth(26);
        fze36.setX(621);
        fze36.setY(956);
        fkd_15.X(fze36);
        fze36.guy();
        fze36.onChildrenAdded();
        fze fze37 = fze.checkOut();
        fze37.setElementMap(fhs_23);
        fze37.setFlipHorizontaly(true);
        fze37.setHeight(19);
        fze37.setPosition(fzw_0.tLo);
        fze37.setTexture(this.okR.uF("themeDefault"));
        fze37.setWidth(26);
        fze37.setX(621);
        fze37.setY(956);
        fkd_15.X(fze37);
        fze37.guy();
        fze37.onChildrenAdded();
        fkd_15.onChildrenAdded();
        fym_05.onChildrenAdded();
    }
}

