/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from drW
 */
public class drw_1
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fym_0 fym_02 = (fym_0)fes_23.getAppearance();
        fym_02.setElementMap(fhs_23);
        fym_02.setAlignment(faa_2.tLO);
        fym_02.setState("default");
        fes_22.X(fym_02);
        fym_02.guy();
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        fym_02.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(24);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze2.setWidth(24);
        fze2.setX(0);
        fze2.setY(0);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fkd_12.onChildrenAdded();
        String string = "pmChevronTopWhite100";
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fze3);
        }
        fze3.setFlipVerticaly(true);
        fze3.setHeight(16);
        fze3.setPosition(fzw_0.tLg);
        fze3.setTexture(this.okR.uF("txChevronBottom"));
        fze3.setWidth(16);
        fze3.setX(2);
        fze3.setY(46);
        fym_02.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fym_02.onChildrenAdded();
        fes_2 fes_24 = fes_22;
        fym_0 fym_03 = (fym_0)fes_24.getAppearance();
        fym_03.setElementMap(fhs_23);
        fym_03.setAlignment(faa_2.tLO);
        fym_03.setState("mouseHover");
        fes_22.X(fym_03);
        fym_03.guy();
        fkd_1 fkd_13 = fkd_1.checkOut();
        fkd_13.setElementMap(fhs_23);
        fym_03.X(fkd_13);
        fkd_13.guy();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(24);
        fze4.setPosition(fzw_0.tLg);
        fze4.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze4.setWidth(24);
        fze4.setX(0);
        fze4.setY(26);
        fkd_13.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fkd_13.onChildrenAdded();
        String string2 = "pmChevronTopWhite100";
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fze5);
        }
        fze5.setFlipVerticaly(true);
        fze5.setHeight(16);
        fze5.setPosition(fzw_0.tLg);
        fze5.setTexture(this.okR.uF("txChevronBottom"));
        fze5.setWidth(16);
        fze5.setX(2);
        fze5.setY(46);
        fym_03.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fym_03.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fym_0 fym_04 = (fym_0)fes_25.getAppearance();
        fym_04.setElementMap(fhs_23);
        fym_04.setAlignment(faa_2.tLO);
        fym_04.setState("pressed");
        fes_22.X(fym_04);
        fym_04.guy();
        fkd_1 fkd_14 = fkd_1.checkOut();
        fkd_14.setElementMap(fhs_23);
        fym_04.X(fkd_14);
        fkd_14.guy();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(24);
        fze6.setPosition(fzw_0.tLg);
        fze6.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze6.setWidth(24);
        fze6.setX(0);
        fze6.setY(52);
        fkd_14.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fkd_14.onChildrenAdded();
        String string3 = "pmChevronTopWhite100";
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fze7);
        }
        fze7.setFlipVerticaly(true);
        fze7.setHeight(16);
        fze7.setPosition(fzw_0.tLg);
        fze7.setTexture(this.okR.uF("txChevronBottom"));
        fze7.setWidth(16);
        fze7.setX(2);
        fze7.setY(46);
        fym_04.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fym_04.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fym_0 fym_05 = (fym_0)fes_26.getAppearance();
        fym_05.setElementMap(fhs_23);
        fym_05.setAlignment(faa_2.tLO);
        fym_05.setState("disabled");
        fes_22.X(fym_05);
        fym_05.guy();
        fkd_1 fkd_15 = fkd_1.checkOut();
        fkd_15.setElementMap(fhs_23);
        fym_05.X(fkd_15);
        fkd_15.guy();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setHeight(24);
        fze8.setPosition(fzw_0.tLg);
        fze8.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze8.setWidth(24);
        fze8.setX(0);
        fze8.setY(78);
        fkd_15.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        String string4 = "pmChevronTopWhite100";
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fze9);
        }
        fze9.setFlipVerticaly(true);
        fze9.setHeight(16);
        fze9.setPosition(fzw_0.tLg);
        fze9.setTexture(this.okR.uF("txChevronBottom"));
        fze9.setWidth(16);
        fze9.setX(2);
        fze9.setY(46);
        fkd_15.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fkd_15.onChildrenAdded();
        fym_05.onChildrenAdded();
        fes_2 fes_27 = fes_22;
        fym_0 fym_06 = (fym_0)fes_27.getAppearance();
        fym_06.setElementMap(fhs_23);
        fym_06.setAlignment(faa_2.tLO);
        fym_06.setState("selected");
        fes_22.X(fym_06);
        fym_06.guy();
        fkd_1 fkd_16 = fkd_1.checkOut();
        fkd_16.setElementMap(fhs_23);
        fym_06.X(fkd_16);
        fkd_16.guy();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setHeight(24);
        fze10.setPosition(fzw_0.tLg);
        fze10.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze10.setWidth(24);
        fze10.setX(0);
        fze10.setY(0);
        fkd_16.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkd_16.onChildrenAdded();
        String string5 = "pmChevronBottomWhite100";
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fze11);
        }
        fze11.setHeight(16);
        fze11.setPosition(fzw_0.tLg);
        fze11.setTexture(this.okR.uF("txChevronBottom"));
        fze11.setWidth(16);
        fze11.setX(2);
        fze11.setY(46);
        fym_06.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fym_06.onChildrenAdded();
        fes_2 fes_28 = fes_22;
        fym_0 fym_07 = (fym_0)fes_28.getAppearance();
        fym_07.setElementMap(fhs_23);
        fym_07.setAlignment(faa_2.tLO);
        fym_07.setState("mouseHoverSelected");
        fes_22.X(fym_07);
        fym_07.guy();
        fkd_1 fkd_17 = fkd_1.checkOut();
        fkd_17.setElementMap(fhs_23);
        fym_07.X(fkd_17);
        fkd_17.guy();
        fze fze12 = fze.checkOut();
        fze12.setElementMap(fhs_23);
        fze12.setHeight(24);
        fze12.setPosition(fzw_0.tLg);
        fze12.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze12.setWidth(24);
        fze12.setX(0);
        fze12.setY(26);
        fkd_17.X(fze12);
        fze12.guy();
        fze12.onChildrenAdded();
        fkd_17.onChildrenAdded();
        String string6 = "pmChevronBottomWhite100";
        fze fze13 = fze.checkOut();
        fze13.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fze13);
        }
        fze13.setHeight(16);
        fze13.setPosition(fzw_0.tLg);
        fze13.setTexture(this.okR.uF("txChevronBottom"));
        fze13.setWidth(16);
        fze13.setX(2);
        fze13.setY(46);
        fym_07.X(fze13);
        fze13.guy();
        fze13.onChildrenAdded();
        fym_07.onChildrenAdded();
        fes_2 fes_29 = fes_22;
        fym_0 fym_08 = (fym_0)fes_29.getAppearance();
        fym_08.setElementMap(fhs_23);
        fym_08.setAlignment(faa_2.tLO);
        fym_08.setState("pressedSelected");
        fes_22.X(fym_08);
        fym_08.guy();
        fkd_1 fkd_18 = fkd_1.checkOut();
        fkd_18.setElementMap(fhs_23);
        fym_08.X(fkd_18);
        fkd_18.guy();
        fze fze14 = fze.checkOut();
        fze14.setElementMap(fhs_23);
        fze14.setHeight(24);
        fze14.setPosition(fzw_0.tLg);
        fze14.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze14.setWidth(24);
        fze14.setX(0);
        fze14.setY(52);
        fkd_18.X(fze14);
        fze14.guy();
        fze14.onChildrenAdded();
        fkd_18.onChildrenAdded();
        String string7 = "pmChevronBottomWhite100";
        fze fze15 = fze.checkOut();
        fze15.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fze15);
        }
        fze15.setHeight(16);
        fze15.setPosition(fzw_0.tLg);
        fze15.setTexture(this.okR.uF("txChevronBottom"));
        fze15.setWidth(16);
        fze15.setX(2);
        fze15.setY(46);
        fym_08.X(fze15);
        fze15.guy();
        fze15.onChildrenAdded();
        fym_08.onChildrenAdded();
        fes_2 fes_210 = fes_22;
        fym_0 fym_09 = (fym_0)fes_210.getAppearance();
        fym_09.setElementMap(fhs_23);
        fym_09.setAlignment(faa_2.tLO);
        fym_09.setState("disabledSelected");
        fes_22.X(fym_09);
        fym_09.guy();
        fkd_1 fkd_19 = fkd_1.checkOut();
        fkd_19.setElementMap(fhs_23);
        fym_09.X(fkd_19);
        fkd_19.guy();
        fze fze16 = fze.checkOut();
        fze16.setElementMap(fhs_23);
        fze16.setHeight(24);
        fze16.setPosition(fzw_0.tLg);
        fze16.setTexture(this.okR.uF("txSecondaryFloatingButton"));
        fze16.setWidth(24);
        fze16.setX(0);
        fze16.setY(78);
        fkd_19.X(fze16);
        fze16.guy();
        fze16.onChildrenAdded();
        String string8 = "pmChevronBottomWhite100";
        fze fze17 = fze.checkOut();
        fze17.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, fze17);
        }
        fze17.setHeight(16);
        fze17.setPosition(fzw_0.tLg);
        fze17.setTexture(this.okR.uF("txChevronBottom"));
        fze17.setWidth(16);
        fze17.setX(2);
        fze17.setY(46);
        fkd_19.X(fze17);
        fze17.guy();
        fze17.onChildrenAdded();
        fkd_19.onChildrenAdded();
        fym_09.onChildrenAdded();
    }
}

