/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from dty
 */
public class dty_2
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fes_2 fes_24 = fes_22;
        fym_0 fym_02 = (fym_0)fes_24.getAppearance();
        fym_02.setElementMap(fhs_23);
        fym_02.setState("default");
        fes_22.X(fym_02);
        fym_02.guy();
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_23);
        fym_02.X(fkh_12);
        fkh_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(4);
        fze2.setPosition(fzw_0.tKY);
        fze2.setTexture(this.okR.uF("themeDefault"));
        fze2.setWidth(4);
        fze2.setX(105);
        fze2.setY(1);
        fkh_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(4);
        fze3.setPosition(fzw_0.tLa);
        fze3.setTexture(this.okR.uF("themeDefault"));
        fze3.setWidth(5);
        fze3.setX(109);
        fze3.setY(1);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(4);
        fze4.setPosition(fzw_0.tLc);
        fze4.setTexture(this.okR.uF("themeDefault"));
        fze4.setWidth(4);
        fze4.setX(113);
        fze4.setY(1);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(13);
        fze5.setPosition(fzw_0.tLh);
        fze5.setTexture(this.okR.uF("themeDefault"));
        fze5.setWidth(4);
        fze5.setX(113);
        fze5.setY(5);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(4);
        fze6.setPosition(fzw_0.tLo);
        fze6.setTexture(this.okR.uF("themeDefault"));
        fze6.setWidth(4);
        fze6.setX(113);
        fze6.setY(18);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(4);
        fze7.setPosition(fzw_0.tLm);
        fze7.setTexture(this.okR.uF("themeDefault"));
        fze7.setWidth(5);
        fze7.setX(109);
        fze7.setY(18);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setHeight(4);
        fze8.setPosition(fzw_0.tLk);
        fze8.setTexture(this.okR.uF("themeDefault"));
        fze8.setWidth(4);
        fze8.setX(105);
        fze8.setY(18);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setHeight(13);
        fze9.setPosition(fzw_0.tLf);
        fze9.setTexture(this.okR.uF("themeDefault"));
        fze9.setWidth(4);
        fze9.setX(105);
        fze9.setY(4);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fkh_12.onChildrenAdded();
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        fkd_12.setEnabled(true);
        fkd_12.setScaled(true);
        fym_02.X(fkd_12);
        fkd_12.guy();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setHeight(1);
        fze10.setPosition(fzw_0.tLg);
        fze10.setTexture(this.okR.uF("themeDefault"));
        fze10.setWidth(4);
        fze10.setX(109);
        fze10.setY(6);
        fkd_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkd_12.onChildrenAdded();
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        fze11.setHeight(6);
        fze11.setPosition(fzw_0.tLg);
        fze11.setRotation(asp_1.dad);
        fze11.setTexture(this.okR.uF("themeDefault"));
        fze11.setWidth(4);
        fze11.setX(109);
        fze11.setY(9);
        fym_02.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fym_02.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fym_0 fym_03 = (fym_0)fes_25.getAppearance();
        fym_03.setElementMap(fhs_23);
        fym_03.setState("mouseHover");
        fes_22.X(fym_03);
        fym_03.guy();
        fkh_1 fkh_13 = new fkh_1();
        fkh_13.aVI();
        fkh_13.setElementMap(fhs_23);
        fym_03.X(fkh_13);
        fkh_13.guy();
        fze fze12 = fze.checkOut();
        fze12.setElementMap(fhs_23);
        fze12.setHeight(4);
        fze12.setPosition(fzw_0.tKY);
        fze12.setTexture(this.okR.uF("themeOver"));
        fze12.setWidth(4);
        fze12.setX(105);
        fze12.setY(1);
        fkh_13.X(fze12);
        fze12.guy();
        fze12.onChildrenAdded();
        fze fze13 = fze.checkOut();
        fze13.setElementMap(fhs_23);
        fze13.setHeight(4);
        fze13.setPosition(fzw_0.tLa);
        fze13.setTexture(this.okR.uF("themeOver"));
        fze13.setWidth(5);
        fze13.setX(109);
        fze13.setY(1);
        fkh_13.X(fze13);
        fze13.guy();
        fze13.onChildrenAdded();
        fze fze14 = fze.checkOut();
        fze14.setElementMap(fhs_23);
        fze14.setHeight(4);
        fze14.setPosition(fzw_0.tLc);
        fze14.setTexture(this.okR.uF("themeOver"));
        fze14.setWidth(4);
        fze14.setX(113);
        fze14.setY(1);
        fkh_13.X(fze14);
        fze14.guy();
        fze14.onChildrenAdded();
        fze fze15 = fze.checkOut();
        fze15.setElementMap(fhs_23);
        fze15.setHeight(13);
        fze15.setPosition(fzw_0.tLh);
        fze15.setTexture(this.okR.uF("themeOver"));
        fze15.setWidth(4);
        fze15.setX(113);
        fze15.setY(5);
        fkh_13.X(fze15);
        fze15.guy();
        fze15.onChildrenAdded();
        fze fze16 = fze.checkOut();
        fze16.setElementMap(fhs_23);
        fze16.setHeight(4);
        fze16.setPosition(fzw_0.tLo);
        fze16.setTexture(this.okR.uF("themeOver"));
        fze16.setWidth(4);
        fze16.setX(113);
        fze16.setY(18);
        fkh_13.X(fze16);
        fze16.guy();
        fze16.onChildrenAdded();
        fze fze17 = fze.checkOut();
        fze17.setElementMap(fhs_23);
        fze17.setHeight(4);
        fze17.setPosition(fzw_0.tLm);
        fze17.setTexture(this.okR.uF("themeOver"));
        fze17.setWidth(5);
        fze17.setX(109);
        fze17.setY(18);
        fkh_13.X(fze17);
        fze17.guy();
        fze17.onChildrenAdded();
        fze fze18 = fze.checkOut();
        fze18.setElementMap(fhs_23);
        fze18.setHeight(4);
        fze18.setPosition(fzw_0.tLk);
        fze18.setTexture(this.okR.uF("themeOver"));
        fze18.setWidth(4);
        fze18.setX(105);
        fze18.setY(18);
        fkh_13.X(fze18);
        fze18.guy();
        fze18.onChildrenAdded();
        fze fze19 = fze.checkOut();
        fze19.setElementMap(fhs_23);
        fze19.setHeight(13);
        fze19.setPosition(fzw_0.tLf);
        fze19.setTexture(this.okR.uF("themeOver"));
        fze19.setWidth(4);
        fze19.setX(105);
        fze19.setY(4);
        fkh_13.X(fze19);
        fze19.guy();
        fze19.onChildrenAdded();
        fkh_13.onChildrenAdded();
        fkd_1 fkd_13 = fkd_1.checkOut();
        fkd_13.setElementMap(fhs_23);
        fkd_13.setEnabled(true);
        fkd_13.setScaled(true);
        fym_03.X(fkd_13);
        fkd_13.guy();
        fze fze20 = fze.checkOut();
        fze20.setElementMap(fhs_23);
        fze20.setHeight(2);
        fze20.setPosition(fzw_0.tLg);
        fze20.setTexture(this.okR.uF("themeOver"));
        fze20.setWidth(4);
        fze20.setX(109);
        fze20.setY(5);
        fkd_13.X(fze20);
        fze20.guy();
        fze20.onChildrenAdded();
        fkd_13.onChildrenAdded();
        fze fze21 = fze.checkOut();
        fze21.setElementMap(fhs_23);
        fze21.setHeight(6);
        fze21.setPosition(fzw_0.tLg);
        fze21.setRotation(asp_1.dad);
        fze21.setTexture(this.okR.uF("themeOver"));
        fze21.setWidth(4);
        fze21.setX(109);
        fze21.setY(9);
        fym_03.X(fze21);
        fze21.guy();
        fze21.onChildrenAdded();
        fym_03.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fym_0 fym_04 = (fym_0)fes_26.getAppearance();
        fym_04.setElementMap(fhs_23);
        fym_04.setState("pressed");
        fes_22.X(fym_04);
        fym_04.guy();
        fkh_1 fkh_14 = new fkh_1();
        fkh_14.aVI();
        fkh_14.setElementMap(fhs_23);
        fym_04.X(fkh_14);
        fkh_14.guy();
        fze fze22 = fze.checkOut();
        fze22.setElementMap(fhs_23);
        fze22.setHeight(4);
        fze22.setPosition(fzw_0.tKY);
        fze22.setTexture(this.okR.uF("themePressed"));
        fze22.setWidth(4);
        fze22.setX(105);
        fze22.setY(1);
        fkh_14.X(fze22);
        fze22.guy();
        fze22.onChildrenAdded();
        fze fze23 = fze.checkOut();
        fze23.setElementMap(fhs_23);
        fze23.setHeight(4);
        fze23.setPosition(fzw_0.tLa);
        fze23.setTexture(this.okR.uF("themePressed"));
        fze23.setWidth(5);
        fze23.setX(109);
        fze23.setY(1);
        fkh_14.X(fze23);
        fze23.guy();
        fze23.onChildrenAdded();
        fze fze24 = fze.checkOut();
        fze24.setElementMap(fhs_23);
        fze24.setHeight(4);
        fze24.setPosition(fzw_0.tLc);
        fze24.setTexture(this.okR.uF("themePressed"));
        fze24.setWidth(4);
        fze24.setX(113);
        fze24.setY(1);
        fkh_14.X(fze24);
        fze24.guy();
        fze24.onChildrenAdded();
        fze fze25 = fze.checkOut();
        fze25.setElementMap(fhs_23);
        fze25.setHeight(13);
        fze25.setPosition(fzw_0.tLh);
        fze25.setTexture(this.okR.uF("themePressed"));
        fze25.setWidth(4);
        fze25.setX(113);
        fze25.setY(5);
        fkh_14.X(fze25);
        fze25.guy();
        fze25.onChildrenAdded();
        fze fze26 = fze.checkOut();
        fze26.setElementMap(fhs_23);
        fze26.setHeight(4);
        fze26.setPosition(fzw_0.tLo);
        fze26.setTexture(this.okR.uF("themePressed"));
        fze26.setWidth(4);
        fze26.setX(113);
        fze26.setY(18);
        fkh_14.X(fze26);
        fze26.guy();
        fze26.onChildrenAdded();
        fze fze27 = fze.checkOut();
        fze27.setElementMap(fhs_23);
        fze27.setHeight(4);
        fze27.setPosition(fzw_0.tLm);
        fze27.setTexture(this.okR.uF("themePressed"));
        fze27.setWidth(5);
        fze27.setX(109);
        fze27.setY(18);
        fkh_14.X(fze27);
        fze27.guy();
        fze27.onChildrenAdded();
        fze fze28 = fze.checkOut();
        fze28.setElementMap(fhs_23);
        fze28.setHeight(4);
        fze28.setPosition(fzw_0.tLk);
        fze28.setTexture(this.okR.uF("themePressed"));
        fze28.setWidth(4);
        fze28.setX(105);
        fze28.setY(18);
        fkh_14.X(fze28);
        fze28.guy();
        fze28.onChildrenAdded();
        fze fze29 = fze.checkOut();
        fze29.setElementMap(fhs_23);
        fze29.setHeight(13);
        fze29.setPosition(fzw_0.tLf);
        fze29.setTexture(this.okR.uF("themePressed"));
        fze29.setWidth(4);
        fze29.setX(105);
        fze29.setY(4);
        fkh_14.X(fze29);
        fze29.guy();
        fze29.onChildrenAdded();
        fkh_14.onChildrenAdded();
        fkd_1 fkd_14 = fkd_1.checkOut();
        fkd_14.setElementMap(fhs_23);
        fkd_14.setEnabled(true);
        fkd_14.setScaled(true);
        fym_04.X(fkd_14);
        fkd_14.guy();
        fze fze30 = fze.checkOut();
        fze30.setElementMap(fhs_23);
        fze30.setHeight(2);
        fze30.setPosition(fzw_0.tLg);
        fze30.setTexture(this.okR.uF("themePressed"));
        fze30.setWidth(4);
        fze30.setX(109);
        fze30.setY(5);
        fkd_14.X(fze30);
        fze30.guy();
        fze30.onChildrenAdded();
        fkd_14.onChildrenAdded();
        fze fze31 = fze.checkOut();
        fze31.setElementMap(fhs_23);
        fze31.setHeight(6);
        fze31.setPosition(fzw_0.tLg);
        fze31.setRotation(asp_1.dad);
        fze31.setTexture(this.okR.uF("themePressed"));
        fze31.setWidth(4);
        fze31.setX(109);
        fze31.setY(9);
        fym_04.X(fze31);
        fze31.guy();
        fze31.onChildrenAdded();
        fym_04.onChildrenAdded();
    }
}

