/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from ecG
 */
public class ecg_2
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fzk fzk2 = (fzk)fes_23.getAppearance();
        fzk2.setElementMap(fhs_23);
        fzk2.setAlign(faa_2.tLR);
        fzk2.setState("default");
        fes_22.X(fzk2);
        fzk2.guy();
        fyW fyW2 = fyW.checkOut();
        fyW2.setRenderer(fyw_0.gqw().gqB().uG("fontTitle21Shadowed"));
        fyW2.setElementMap(fhs_23);
        fzk2.X(fyW2);
        fyW2.guy();
        fyW2.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("mainTextTitleColor"));
        fzk2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(40);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txExploitsBar"));
        fze2.setWidth(40);
        fze2.setX(0);
        fze2.setY(0);
        fzk2.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fzk2.onChildrenAdded();
        fes_2 fes_24 = fes_22;
        fzk fzk3 = (fzk)fes_24.getAppearance();
        fzk3.setElementMap(fhs_23);
        fzk3.setState("mouseHover");
        fes_22.X(fzk3);
        fzk3.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_23);
        fyp_03.setColor(new fhl_2("mainTextLightColor"));
        fzk3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(40);
        fze3.setPosition(fzw_0.tLg);
        fze3.setTexture(this.okR.uF("txExploitsBar"));
        fze3.setWidth(40);
        fze3.setX(0);
        fze3.setY(42);
        fzk3.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fzk3.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fzk fzk4 = (fzk)fes_25.getAppearance();
        fzk4.setElementMap(fhs_23);
        fzk4.setState("pressed");
        fes_22.X(fzk4);
        fzk4.guy();
        fyp_0 fyp_04 = fyp_0.checkOut();
        fyp_04.setElementMap(fhs_23);
        fyp_04.setColor(new fhl_2("mainTextLightColor"));
        fzk4.X(fyp_04);
        fyp_04.guy();
        fyp_04.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(40);
        fze4.setPosition(fzw_0.tLg);
        fze4.setTexture(this.okR.uF("txExploitsBar"));
        fze4.setWidth(40);
        fze4.setX(0);
        fze4.setY(84);
        fzk4.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fzk4.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fzk fzk5 = (fzk)fes_26.getAppearance();
        fzk5.setElementMap(fhs_23);
        fzk5.setState("disabled");
        fes_22.X(fzk5);
        fzk5.guy();
        fyp_0 fyp_05 = fyp_0.checkOut();
        fyp_05.setElementMap(fhs_23);
        fyp_05.setColor(new fhl_2("defaultDisabledColor"));
        fzk5.X(fyp_05);
        fyp_05.guy();
        fyp_05.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(40);
        fze5.setPosition(fzw_0.tLg);
        fze5.setTexture(this.okR.uF("txExploitsBar"));
        fze5.setWidth(40);
        fze5.setX(0);
        fze5.setY(126);
        fzk5.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fzk5.onChildrenAdded();
        fes_2 fes_27 = fes_22;
        fzk fzk6 = (fzk)fes_27.getAppearance();
        fzk6.setElementMap(fhs_23);
        fzk6.setState("selected");
        fes_22.X(fzk6);
        fzk6.guy();
        fyp_0 fyp_06 = fyp_0.checkOut();
        fyp_06.setElementMap(fhs_23);
        fyp_06.setColor(new fhl_2("mainTextLightColor"));
        fzk6.X(fyp_06);
        fyp_06.guy();
        fyp_06.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(40);
        fze6.setPosition(fzw_0.tLg);
        fze6.setTexture(this.okR.uF("txExploitsBar"));
        fze6.setWidth(40);
        fze6.setX(0);
        fze6.setY(168);
        fzk6.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fzk6.onChildrenAdded();
        fes_2 fes_28 = fes_22;
        fzk fzk7 = (fzk)fes_28.getAppearance();
        fzk7.setElementMap(fhs_23);
        fzk7.setState("mouseHoverSelected");
        fes_22.X(fzk7);
        fzk7.guy();
        fyp_0 fyp_07 = fyp_0.checkOut();
        fyp_07.setElementMap(fhs_23);
        fyp_07.setColor(new fhl_2("mainTextLightColor"));
        fzk7.X(fyp_07);
        fyp_07.guy();
        fyp_07.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(40);
        fze7.setPosition(fzw_0.tLg);
        fze7.setTexture(this.okR.uF("txExploitsBar"));
        fze7.setWidth(40);
        fze7.setX(0);
        fze7.setY(210);
        fzk7.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fzk7.onChildrenAdded();
        fes_2 fes_29 = fes_22;
        fzk fzk8 = (fzk)fes_29.getAppearance();
        fzk8.setElementMap(fhs_23);
        fzk8.setState("pressedSelected");
        fes_22.X(fzk8);
        fzk8.guy();
        fyp_0 fyp_08 = fyp_0.checkOut();
        fyp_08.setElementMap(fhs_23);
        fyp_08.setColor(new fhl_2("mainTextLightColor"));
        fzk8.X(fyp_08);
        fyp_08.guy();
        fyp_08.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setHeight(40);
        fze8.setPosition(fzw_0.tLg);
        fze8.setTexture(this.okR.uF("txExploitsBar"));
        fze8.setWidth(40);
        fze8.setX(0);
        fze8.setY(252);
        fzk8.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fzk8.onChildrenAdded();
        fes_2 fes_210 = fes_22;
        fzk fzk9 = (fzk)fes_210.getAppearance();
        fzk9.setElementMap(fhs_23);
        fzk9.setState("disabledSelected");
        fes_22.X(fzk9);
        fzk9.guy();
        fyp_0 fyp_09 = fyp_0.checkOut();
        fyp_09.setElementMap(fhs_23);
        fyp_09.setColor(new fhl_2("defaultDisabledColor"));
        fzk9.X(fyp_09);
        fyp_09.guy();
        fyp_09.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setHeight(40);
        fze9.setPosition(fzw_0.tLg);
        fze9.setTexture(this.okR.uF("txExploitsBar"));
        fze9.setWidth(40);
        fze9.setX(0);
        fze9.setY(294);
        fzk9.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fzk9.onChildrenAdded();
    }
}

