/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from ecv
 */
public class ecv_2
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fzk fzk2 = (fzk)fes_23.getAppearance();
        fzk2.setElementMap(fhs_23);
        fzk2.setAlignment(faa_2.tLN);
        fzk2.setState("default");
        fes_22.X(fzk2);
        fzk2.guy();
        fyW fyW2 = fyW.checkOut();
        fyW2.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10"));
        fyW2.setElementMap(fhs_23);
        fzk2.X(fyW2);
        fyW2.guy();
        fyW2.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("defaultLightColor"));
        fzk2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(20);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("themeDefault"));
        fze2.setWidth(20);
        fze2.setX(363);
        fze2.setY(61);
        fzk2.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fzk2.onChildrenAdded();
        fes_2 fes_24 = fes_22;
        fzk fzk3 = (fzk)fes_24.getAppearance();
        fzk3.setElementMap(fhs_23);
        fzk3.setAlignment(faa_2.tLN);
        fzk3.setState("mouseHover");
        fes_22.X(fzk3);
        fzk3.guy();
        fyW fyW3 = fyW.checkOut();
        fyW3.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10"));
        fyW3.setElementMap(fhs_23);
        fzk3.X(fyW3);
        fyW3.guy();
        fyW3.onChildrenAdded();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_23);
        fyp_03.setColor(new fhl_2("defaultLightColor"));
        fzk3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(20);
        fze3.setPosition(fzw_0.tLg);
        fze3.setTexture(this.okR.uF("themeOver"));
        fze3.setWidth(20);
        fze3.setX(363);
        fze3.setY(61);
        fzk3.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fzk3.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fzk fzk4 = (fzk)fes_25.getAppearance();
        fzk4.setElementMap(fhs_23);
        fzk4.setAlignment(faa_2.tLN);
        fzk4.setState("pressed");
        fes_22.X(fzk4);
        fzk4.guy();
        fyW fyW4 = fyW.checkOut();
        fyW4.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10"));
        fyW4.setElementMap(fhs_23);
        fzk4.X(fyW4);
        fyW4.guy();
        fyW4.onChildrenAdded();
        fyp_0 fyp_04 = fyp_0.checkOut();
        fyp_04.setElementMap(fhs_23);
        fyp_04.setColor(new fhl_2("defaultLightColor"));
        fzk4.X(fyp_04);
        fyp_04.guy();
        fyp_04.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(20);
        fze4.setPosition(fzw_0.tLg);
        fze4.setTexture(this.okR.uF("themePressed"));
        fze4.setWidth(20);
        fze4.setX(363);
        fze4.setY(61);
        fzk4.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fzk4.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fzk fzk5 = (fzk)fes_26.getAppearance();
        fzk5.setElementMap(fhs_23);
        fzk5.setAlignment(faa_2.tLN);
        fzk5.setState("selected");
        fes_22.X(fzk5);
        fzk5.guy();
        fyW fyW5 = fyW.checkOut();
        fyW5.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10"));
        fyW5.setElementMap(fhs_23);
        fzk5.X(fyW5);
        fyW5.guy();
        fyW5.onChildrenAdded();
        fyp_0 fyp_05 = fyp_0.checkOut();
        fyp_05.setElementMap(fhs_23);
        fyp_05.setColor(new fhl_2("defaultLightColor"));
        fzk5.X(fyp_05);
        fyp_05.guy();
        fyp_05.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(20);
        fze5.setPosition(fzw_0.tLg);
        fze5.setTexture(this.okR.uF("themeDefaultSelected"));
        fze5.setWidth(20);
        fze5.setX(363);
        fze5.setY(61);
        fzk5.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fzk5.onChildrenAdded();
        fes_2 fes_27 = fes_22;
        fzk fzk6 = (fzk)fes_27.getAppearance();
        fzk6.setElementMap(fhs_23);
        fzk6.setAlignment(faa_2.tLN);
        fzk6.setState("mouseHoverSelected");
        fes_22.X(fzk6);
        fzk6.guy();
        fyW fyW6 = fyW.checkOut();
        fyW6.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10"));
        fyW6.setElementMap(fhs_23);
        fzk6.X(fyW6);
        fyW6.guy();
        fyW6.onChildrenAdded();
        fyp_0 fyp_06 = fyp_0.checkOut();
        fyp_06.setElementMap(fhs_23);
        fyp_06.setColor(new fhl_2("defaultLightColor"));
        fzk6.X(fyp_06);
        fyp_06.guy();
        fyp_06.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(20);
        fze6.setPosition(fzw_0.tLg);
        fze6.setTexture(this.okR.uF("themeOverSelected"));
        fze6.setWidth(20);
        fze6.setX(363);
        fze6.setY(61);
        fzk6.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fzk6.onChildrenAdded();
        fes_2 fes_28 = fes_22;
        fzk fzk7 = (fzk)fes_28.getAppearance();
        fzk7.setElementMap(fhs_23);
        fzk7.setAlignment(faa_2.tLN);
        fzk7.setState("pressedSelected");
        fes_22.X(fzk7);
        fzk7.guy();
        fyW fyW7 = fyW.checkOut();
        fyW7.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10"));
        fyW7.setElementMap(fhs_23);
        fzk7.X(fyW7);
        fyW7.guy();
        fyW7.onChildrenAdded();
        fyp_0 fyp_07 = fyp_0.checkOut();
        fyp_07.setElementMap(fhs_23);
        fyp_07.setColor(new fhl_2("defaultLightColor"));
        fzk7.X(fyp_07);
        fyp_07.guy();
        fyp_07.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(20);
        fze7.setPosition(fzw_0.tLg);
        fze7.setTexture(this.okR.uF("themePressedSelected"));
        fze7.setWidth(20);
        fze7.setX(363);
        fze7.setY(61);
        fzk7.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fzk7.onChildrenAdded();
    }
}

