/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from eeU
 */
public class eeu_2
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        fhv_1 fhv_12;
        fha_2 fha_22;
        fhv_1 fhv_13;
        fhv_1 fhv_14;
        fha_2 fha_23;
        fhv_1 fhv_15;
        fhv_1 fhv_16;
        fhv_1 fhv_17;
        fes_2 fes_23;
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_24 = fes_22;
        fys_0 fys_02 = fes_24.getAppearance();
        fys_02.setElementMap(fhs_23);
        fes_22.X(fys_02);
        fys_02.guy();
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        fkd_12.setEnabled(true);
        fkd_12.setScaled(true);
        fys_02.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(2);
        fze2.setPosition(fzw_0.tKY);
        fze2.setTexture(this.okR.uF("themeSimple"));
        fze2.setWidth(3);
        fze2.setX(24);
        fze2.setY(176);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(2);
        fze3.setPosition(fzw_0.tLa);
        fze3.setTexture(this.okR.uF("themeSimple"));
        fze3.setWidth(1);
        fze3.setX(30);
        fze3.setY(176);
        fkd_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setFlipHorizontaly(true);
        fze4.setHeight(2);
        fze4.setPosition(fzw_0.tLc);
        fze4.setTexture(this.okR.uF("themeSimple"));
        fze4.setWidth(3);
        fze4.setX(24);
        fze4.setY(176);
        fkd_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(1);
        fze5.setPosition(fzw_0.tLf);
        fze5.setTexture(this.okR.uF("themeSimple"));
        fze5.setWidth(3);
        fze5.setX(24);
        fze5.setY(179);
        fkd_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(1);
        fze6.setPosition(fzw_0.tLg);
        fze6.setTexture(this.okR.uF("themeSimple"));
        fze6.setWidth(1);
        fze6.setX(30);
        fze6.setY(181);
        fkd_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setFlipHorizontaly(true);
        fze7.setHeight(1);
        fze7.setPosition(fzw_0.tLh);
        fze7.setTexture(this.okR.uF("themeSimple"));
        fze7.setWidth(3);
        fze7.setX(24);
        fze7.setY(179);
        fkd_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setFlipVerticaly(true);
        fze8.setHeight(2);
        fze8.setPosition(fzw_0.tLk);
        fze8.setTexture(this.okR.uF("themeSimple"));
        fze8.setWidth(3);
        fze8.setX(24);
        fze8.setY(176);
        fkd_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setFlipVerticaly(true);
        fze9.setHeight(2);
        fze9.setPosition(fzw_0.tLm);
        fze9.setTexture(this.okR.uF("themeSimple"));
        fze9.setWidth(1);
        fze9.setX(30);
        fze9.setY(176);
        fkd_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setFlipHorizontaly(true);
        fze10.setFlipVerticaly(true);
        fze10.setHeight(2);
        fze10.setPosition(fzw_0.tLo);
        fze10.setTexture(this.okR.uF("themeSimple"));
        fze10.setWidth(3);
        fze10.setX(24);
        fze10.setY(176);
        fkd_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkd_12.onChildrenAdded();
        fes_2 fes_25 = fys_02.getParentOfType(fes_2.class);
        fes_2 fes_26 = fes_25.getWidgetByThemeElementName("horizontalButton", false);
        if (fes_26 != null) {
            fes_23 = fes_26;
            fhv_17 = (fym_0)fes_23.getAppearance();
            fhv_17.setElementMap(fhs_23);
            ((fys_0)fhv_17).setState("default");
            fes_26.X(fhv_17);
            fhv_17.guy();
            fhv_16 = fze.checkOut();
            fhv_16.setElementMap(fhs_23);
            ((fze)fhv_16).setHeight(20);
            ((fze)fhv_16).setPosition(fzw_0.tLg);
            ((fze)fhv_16).setTexture(this.okR.uF("themeDefault"));
            ((fze)fhv_16).setWidth(20);
            ((fze)fhv_16).setX(486);
            ((fze)fhv_16).setY(559);
            fhv_17.X(fhv_16);
            fhv_16.guy();
            fhv_16.onChildrenAdded();
            fhv_17.onChildrenAdded();
            fhv_15 = fes_26;
            fha_23 = (fym_0)((fes_2)fhv_15).getAppearance();
            fha_23.setElementMap(fhs_23);
            ((fys_0)fha_23).setState("mouseHover");
            fes_26.X(fha_23);
            fha_23.guy();
            fhv_14 = fze.checkOut();
            fhv_14.setElementMap(fhs_23);
            ((fze)fhv_14).setHeight(20);
            ((fze)fhv_14).setPosition(fzw_0.tLg);
            ((fze)fhv_14).setTexture(this.okR.uF("themeOver"));
            ((fze)fhv_14).setWidth(20);
            ((fze)fhv_14).setX(486);
            ((fze)fhv_14).setY(559);
            fha_23.X(fhv_14);
            fhv_14.guy();
            fhv_14.onChildrenAdded();
            fha_23.onChildrenAdded();
            fhv_13 = fes_26;
            fha_22 = (fym_0)((fes_2)fhv_13).getAppearance();
            fha_22.setElementMap(fhs_23);
            ((fys_0)fha_22).setState("pressed");
            fes_26.X(fha_22);
            fha_22.guy();
            fhv_12 = fze.checkOut();
            fhv_12.setElementMap(fhs_23);
            ((fze)fhv_12).setHeight(20);
            ((fze)fhv_12).setPosition(fzw_0.tLg);
            ((fze)fhv_12).setTexture(this.okR.uF("themePressed"));
            ((fze)fhv_12).setWidth(20);
            ((fze)fhv_12).setX(486);
            ((fze)fhv_12).setY(559);
            fha_22.X(fhv_12);
            fhv_12.guy();
            fhv_12.onChildrenAdded();
            fha_22.onChildrenAdded();
        }
        if ((fhv_17 = (fes_23 = fys_02.getParentOfType(fes_2.class)).getWidgetByThemeElementName("verticalButton", false)) != null) {
            fhv_16 = (fes_2)fhv_17;
            fhv_15 = (fym_0)((fes_2)fhv_16).getAppearance();
            fhv_15.setElementMap(fhs_23);
            ((fys_0)fhv_15).setState("default");
            fhv_17.X(fhv_15);
            fhv_15.guy();
            fha_23 = fze.checkOut();
            fha_23.setElementMap(fhs_23);
            ((fze)fha_23).setHeight(20);
            ((fze)fha_23).setPosition(fzw_0.tLg);
            ((fze)fha_23).setTexture(this.okR.uF("themeDefault"));
            ((fze)fha_23).setWidth(20);
            ((fze)fha_23).setX(486);
            ((fze)fha_23).setY(559);
            fhv_15.X(fha_23);
            fha_23.guy();
            fha_23.onChildrenAdded();
            fhv_15.onChildrenAdded();
            fhv_14 = (fes_2)fhv_17;
            fhv_13 = (fym_0)((fes_2)fhv_14).getAppearance();
            fhv_13.setElementMap(fhs_23);
            ((fys_0)fhv_13).setState("mouseHover");
            fhv_17.X(fhv_13);
            fhv_13.guy();
            fha_22 = fze.checkOut();
            fha_22.setElementMap(fhs_23);
            ((fze)fha_22).setHeight(20);
            ((fze)fha_22).setPosition(fzw_0.tLg);
            ((fze)fha_22).setTexture(this.okR.uF("themeOver"));
            ((fze)fha_22).setWidth(20);
            ((fze)fha_22).setX(486);
            ((fze)fha_22).setY(559);
            fhv_13.X(fha_22);
            fha_22.guy();
            fha_22.onChildrenAdded();
            fhv_13.onChildrenAdded();
            fhv_12 = (fes_2)fhv_17;
            fym_0 fym_02 = (fym_0)((fes_2)fhv_12).getAppearance();
            fym_02.setElementMap(fhs_23);
            fym_02.setState("pressed");
            fhv_17.X(fym_02);
            fym_02.guy();
            fze fze11 = fze.checkOut();
            fze11.setElementMap(fhs_23);
            fze11.setHeight(20);
            fze11.setPosition(fzw_0.tLg);
            fze11.setTexture(this.okR.uF("themePressed"));
            fze11.setWidth(20);
            fze11.setX(486);
            fze11.setY(559);
            fym_02.X(fze11);
            fze11.guy();
            fze11.onChildrenAdded();
            fym_02.onChildrenAdded();
        }
        fhv_16 = fze.checkOut();
        fhv_16.setElementMap(fhs_23);
        ((fze)fhv_16).setHeight(12);
        ((fze)fhv_16).setPosition(fzw_0.tLg);
        ((fze)fhv_16).setTexture(this.okR.uF("themeSimple2"));
        ((fze)fhv_16).setWidth(1);
        ((fze)fhv_16).setX(299);
        ((fze)fhv_16).setY(254);
        fys_02.X(fhv_16);
        fhv_16.guy();
        fhv_16.onChildrenAdded();
        fys_02.onChildrenAdded();
    }
}

