/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from eeX
 */
public class eex_1
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        fhv_1 fhv_12;
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fys_0 fys_02 = fes_23.getAppearance();
        fys_02.setElementMap(fhs_23);
        fes_22.X(fys_02);
        fys_02.guy();
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_23);
        fkh_12.setEnabled(true);
        fys_02.X(fkh_12);
        fkh_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(2);
        fze2.setPosition(fzw_0.tKY);
        fze2.setTexture(this.okR.uF("themeSimple"));
        fze2.setWidth(3);
        fze2.setX(24);
        fze2.setY(176);
        fkh_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(2);
        fze3.setPosition(fzw_0.tLa);
        fze3.setTexture(this.okR.uF("themeSimple"));
        fze3.setWidth(1);
        fze3.setX(30);
        fze3.setY(176);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setFlipHorizontaly(true);
        fze4.setHeight(2);
        fze4.setPosition(fzw_0.tLc);
        fze4.setTexture(this.okR.uF("themeSimple"));
        fze4.setWidth(3);
        fze4.setX(24);
        fze4.setY(176);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(1);
        fze5.setPosition(fzw_0.tLf);
        fze5.setTexture(this.okR.uF("themeSimple"));
        fze5.setWidth(3);
        fze5.setX(24);
        fze5.setY(179);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(1);
        fze6.setPosition(fzw_0.tLg);
        fze6.setTexture(this.okR.uF("themeSimple"));
        fze6.setWidth(1);
        fze6.setX(30);
        fze6.setY(181);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setFlipHorizontaly(true);
        fze7.setHeight(1);
        fze7.setPosition(fzw_0.tLh);
        fze7.setTexture(this.okR.uF("themeSimple"));
        fze7.setWidth(3);
        fze7.setX(24);
        fze7.setY(179);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setFlipVerticaly(true);
        fze8.setHeight(2);
        fze8.setPosition(fzw_0.tLk);
        fze8.setTexture(this.okR.uF("themeSimple"));
        fze8.setWidth(3);
        fze8.setX(24);
        fze8.setY(176);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setFlipVerticaly(true);
        fze9.setHeight(2);
        fze9.setPosition(fzw_0.tLm);
        fze9.setTexture(this.okR.uF("themeSimple"));
        fze9.setWidth(1);
        fze9.setX(30);
        fze9.setY(176);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setFlipHorizontaly(true);
        fze10.setFlipVerticaly(true);
        fze10.setHeight(2);
        fze10.setPosition(fzw_0.tLo);
        fze10.setTexture(this.okR.uF("themeSimple"));
        fze10.setWidth(3);
        fze10.setX(24);
        fze10.setY(176);
        fkh_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkh_12.onChildrenAdded();
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        fkd_12.setEnabled(true);
        fkd_12.setScaled(true);
        fys_02.X(fkd_12);
        fkd_12.guy();
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        fze11.setHeight(1);
        fze11.setPosition(fzw_0.tLg);
        fze11.setTexture(this.okR.uF("themeSimple"));
        fze11.setWidth(1);
        fze11.setX(30);
        fze11.setY(181);
        fkd_12.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fkd_12.onChildrenAdded();
        fes_2 fes_24 = fys_02.getParentOfType(fes_2.class);
        fes_2 fes_25 = fes_24.getWidgetByThemeElementName("horizontalButton", false);
        if (fes_25 != null) {
            fhv_12 = fes_25;
            fym_0 fym_02 = (fym_0)((fes_2)fhv_12).getAppearance();
            fym_02.setElementMap(fhs_23);
            fym_02.setState("default");
            fes_25.X(fym_02);
            fym_02.guy();
            fze fze12 = fze.checkOut();
            fze12.setElementMap(fhs_23);
            fze12.setHeight(20);
            fze12.setPosition(fzw_0.tLg);
            fze12.setTexture(this.okR.uF("themeDefault"));
            fze12.setWidth(20);
            fze12.setX(486);
            fze12.setY(559);
            fym_02.X(fze12);
            fze12.guy();
            fze12.onChildrenAdded();
            fym_02.onChildrenAdded();
            fes_2 fes_26 = fes_25;
            fym_0 fym_03 = (fym_0)fes_26.getAppearance();
            fym_03.setElementMap(fhs_23);
            fym_03.setState("mouseHover");
            fes_25.X(fym_03);
            fym_03.guy();
            fze fze13 = fze.checkOut();
            fze13.setElementMap(fhs_23);
            fze13.setHeight(20);
            fze13.setPosition(fzw_0.tLg);
            fze13.setTexture(this.okR.uF("themeOver"));
            fze13.setWidth(20);
            fze13.setX(486);
            fze13.setY(559);
            fym_03.X(fze13);
            fze13.guy();
            fze13.onChildrenAdded();
            fym_03.onChildrenAdded();
            fes_2 fes_27 = fes_25;
            fym_0 fym_04 = (fym_0)fes_27.getAppearance();
            fym_04.setElementMap(fhs_23);
            fym_04.setState("pressed");
            fes_25.X(fym_04);
            fym_04.guy();
            fze fze14 = fze.checkOut();
            fze14.setElementMap(fhs_23);
            fze14.setHeight(20);
            fze14.setPosition(fzw_0.tLg);
            fze14.setTexture(this.okR.uF("themePressed"));
            fze14.setWidth(20);
            fze14.setX(486);
            fze14.setY(559);
            fym_04.X(fze14);
            fze14.guy();
            fze14.onChildrenAdded();
            fym_04.onChildrenAdded();
        }
        fhv_12 = fze.checkOut();
        fhv_12.setElementMap(fhs_23);
        ((fze)fhv_12).setHeight(12);
        ((fze)fhv_12).setPosition(fzw_0.tLg);
        ((fze)fhv_12).setTexture(this.okR.uF("themeSimple2"));
        ((fze)fhv_12).setWidth(1);
        ((fze)fhv_12).setX(299);
        ((fze)fhv_12).setY(254);
        fys_02.X(fhv_12);
        fhv_12.guy();
        fhv_12.onChildrenAdded();
        fys_02.onChildrenAdded();
    }
}

