/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from egg
 */
public class egg_2
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(2, 2, 2, 2));
        fes_22.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fes_2 fes_24 = fes_22;
        fzk fzk2 = (fzk)fes_24.getAppearance();
        fzk2.setElementMap(fhs_23);
        fzk2.setAlign(faa_2.tLO);
        fzk2.setState("default");
        fes_22.X(fzk2);
        fzk2.guy();
        fyW fyW2 = fyW.checkOut();
        fyW2.setRenderer(fyw_0.gqw().gqB().uG("fontDefault10Bold"));
        fyW2.setElementMap(fhs_23);
        fzk2.X(fyW2);
        fyW2.guy();
        fyW2.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("mecanicBlueColor"));
        fzk2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        String string = "tabDefaultBackground";
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fkd_12);
        }
        fkd_12.setScaled(true);
        fzk2.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(9);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("themeDefault"));
        fze2.setWidth(9);
        fze2.setX(460);
        fze2.setY(12);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fkd_12.onChildrenAdded();
        String string2 = "tabDefaultBorder";
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fkh_12);
        }
        fzk2.X(fkh_12);
        fkh_12.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(11);
        fze3.setPosition(fzw_0.tKY);
        fze3.setTexture(this.okR.uF("themeDefault"));
        fze3.setWidth(10);
        fze3.setX(449);
        fze3.setY(0);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(11);
        fze4.setPosition(fzw_0.tLa);
        fze4.setTexture(this.okR.uF("themeDefault"));
        fze4.setWidth(9);
        fze4.setX(460);
        fze4.setY(0);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(11);
        fze5.setPosition(fzw_0.tLc);
        fze5.setTexture(this.okR.uF("themeDefault"));
        fze5.setWidth(10);
        fze5.setX(470);
        fze5.setY(0);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(9);
        fze6.setPosition(fzw_0.tLh);
        fze6.setTexture(this.okR.uF("themeDefault"));
        fze6.setWidth(10);
        fze6.setX(470);
        fze6.setY(12);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(7);
        fze7.setPosition(fzw_0.tLo);
        fze7.setTexture(this.okR.uF("themeDefault"));
        fze7.setWidth(10);
        fze7.setX(470);
        fze7.setY(20);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setHeight(7);
        fze8.setPosition(fzw_0.tLm);
        fze8.setTexture(this.okR.uF("themeDefault"));
        fze8.setWidth(9);
        fze8.setX(460);
        fze8.setY(20);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setHeight(7);
        fze9.setPosition(fzw_0.tLk);
        fze9.setTexture(this.okR.uF("themeDefault"));
        fze9.setWidth(10);
        fze9.setX(449);
        fze9.setY(20);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setHeight(7);
        fze10.setPosition(fzw_0.tLf);
        fze10.setTexture(this.okR.uF("themeDefault"));
        fze10.setWidth(10);
        fze10.setX(449);
        fze10.setY(12);
        fkh_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkh_12.onChildrenAdded();
        fzk2.onChildrenAdded();
        fes_2 fes_25 = fes_22;
        fzk fzk3 = (fzk)fes_25.getAppearance();
        fzk3.setElementMap(fhs_23);
        fzk3.setAlign(faa_2.tLO);
        fzk3.setState("mouseHover");
        fes_22.X(fzk3);
        fzk3.guy();
        fyp_0 fyp_03 = fyp_0.checkOut();
        fyp_03.setElementMap(fhs_23);
        fyp_03.setColor(new fhl_2("blackColor"));
        fzk3.X(fyp_03);
        fyp_03.guy();
        fyp_03.onChildrenAdded();
        String string3 = "tabOverBackground";
        fkd_1 fkd_13 = fkd_1.checkOut();
        fkd_13.setElementMap(fhs_23);
        if (fhs_23 != null && string3 != null) {
            fhs_23.a(string3, fkd_13);
        }
        fkd_13.setScaled(true);
        fzk3.X(fkd_13);
        fkd_13.guy();
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        fze11.setHeight(9);
        fze11.setPosition(fzw_0.tLg);
        fze11.setTexture(this.okR.uF("themeOver"));
        fze11.setWidth(9);
        fze11.setX(460);
        fze11.setY(12);
        fkd_13.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fkd_13.onChildrenAdded();
        String string4 = "tabOverBorder";
        fkh_1 fkh_13 = new fkh_1();
        fkh_13.aVI();
        fkh_13.setElementMap(fhs_23);
        if (fhs_23 != null && string4 != null) {
            fhs_23.a(string4, fkh_13);
        }
        fzk3.X(fkh_13);
        fkh_13.guy();
        fze fze12 = fze.checkOut();
        fze12.setElementMap(fhs_23);
        fze12.setHeight(11);
        fze12.setPosition(fzw_0.tKY);
        fze12.setTexture(this.okR.uF("themeOver"));
        fze12.setWidth(10);
        fze12.setX(449);
        fze12.setY(0);
        fkh_13.X(fze12);
        fze12.guy();
        fze12.onChildrenAdded();
        fze fze13 = fze.checkOut();
        fze13.setElementMap(fhs_23);
        fze13.setHeight(11);
        fze13.setPosition(fzw_0.tLa);
        fze13.setTexture(this.okR.uF("themeOver"));
        fze13.setWidth(9);
        fze13.setX(460);
        fze13.setY(0);
        fkh_13.X(fze13);
        fze13.guy();
        fze13.onChildrenAdded();
        fze fze14 = fze.checkOut();
        fze14.setElementMap(fhs_23);
        fze14.setHeight(11);
        fze14.setPosition(fzw_0.tLc);
        fze14.setTexture(this.okR.uF("themeOver"));
        fze14.setWidth(10);
        fze14.setX(470);
        fze14.setY(0);
        fkh_13.X(fze14);
        fze14.guy();
        fze14.onChildrenAdded();
        fze fze15 = fze.checkOut();
        fze15.setElementMap(fhs_23);
        fze15.setHeight(9);
        fze15.setPosition(fzw_0.tLh);
        fze15.setTexture(this.okR.uF("themeOver"));
        fze15.setWidth(10);
        fze15.setX(470);
        fze15.setY(12);
        fkh_13.X(fze15);
        fze15.guy();
        fze15.onChildrenAdded();
        fze fze16 = fze.checkOut();
        fze16.setElementMap(fhs_23);
        fze16.setHeight(7);
        fze16.setPosition(fzw_0.tLo);
        fze16.setTexture(this.okR.uF("themeOver"));
        fze16.setWidth(10);
        fze16.setX(470);
        fze16.setY(20);
        fkh_13.X(fze16);
        fze16.guy();
        fze16.onChildrenAdded();
        fze fze17 = fze.checkOut();
        fze17.setElementMap(fhs_23);
        fze17.setHeight(7);
        fze17.setPosition(fzw_0.tLm);
        fze17.setTexture(this.okR.uF("themeOver"));
        fze17.setWidth(9);
        fze17.setX(460);
        fze17.setY(20);
        fkh_13.X(fze17);
        fze17.guy();
        fze17.onChildrenAdded();
        fze fze18 = fze.checkOut();
        fze18.setElementMap(fhs_23);
        fze18.setHeight(7);
        fze18.setPosition(fzw_0.tLk);
        fze18.setTexture(this.okR.uF("themeOver"));
        fze18.setWidth(10);
        fze18.setX(449);
        fze18.setY(20);
        fkh_13.X(fze18);
        fze18.guy();
        fze18.onChildrenAdded();
        fze fze19 = fze.checkOut();
        fze19.setElementMap(fhs_23);
        fze19.setHeight(7);
        fze19.setPosition(fzw_0.tLf);
        fze19.setTexture(this.okR.uF("themeOver"));
        fze19.setWidth(10);
        fze19.setX(449);
        fze19.setY(12);
        fkh_13.X(fze19);
        fze19.guy();
        fze19.onChildrenAdded();
        fkh_13.onChildrenAdded();
        fzk3.onChildrenAdded();
        fes_2 fes_26 = fes_22;
        fzk fzk4 = (fzk)fes_26.getAppearance();
        fzk4.setElementMap(fhs_23);
        fzk4.setAlign(faa_2.tLO);
        fzk4.setState("pressed");
        fes_22.X(fzk4);
        fzk4.guy();
        fyp_0 fyp_04 = fyp_0.checkOut();
        fyp_04.setElementMap(fhs_23);
        fyp_04.setColor(new fhl_2("mecanicBlueColor"));
        fzk4.X(fyp_04);
        fyp_04.guy();
        fyp_04.onChildrenAdded();
        String string5 = "tabPressedBackground";
        fkd_1 fkd_14 = fkd_1.checkOut();
        fkd_14.setElementMap(fhs_23);
        if (fhs_23 != null && string5 != null) {
            fhs_23.a(string5, fkd_14);
        }
        fkd_14.setScaled(true);
        fzk4.X(fkd_14);
        fkd_14.guy();
        fze fze20 = fze.checkOut();
        fze20.setElementMap(fhs_23);
        fze20.setHeight(9);
        fze20.setPosition(fzw_0.tLg);
        fze20.setTexture(this.okR.uF("themePressed"));
        fze20.setWidth(9);
        fze20.setX(460);
        fze20.setY(12);
        fkd_14.X(fze20);
        fze20.guy();
        fze20.onChildrenAdded();
        fkd_14.onChildrenAdded();
        String string6 = "tabPressedBorder";
        fkh_1 fkh_14 = new fkh_1();
        fkh_14.aVI();
        fkh_14.setElementMap(fhs_23);
        if (fhs_23 != null && string6 != null) {
            fhs_23.a(string6, fkh_14);
        }
        fzk4.X(fkh_14);
        fkh_14.guy();
        fze fze21 = fze.checkOut();
        fze21.setElementMap(fhs_23);
        fze21.setHeight(11);
        fze21.setPosition(fzw_0.tKY);
        fze21.setTexture(this.okR.uF("themePressed"));
        fze21.setWidth(10);
        fze21.setX(449);
        fze21.setY(0);
        fkh_14.X(fze21);
        fze21.guy();
        fze21.onChildrenAdded();
        fze fze22 = fze.checkOut();
        fze22.setElementMap(fhs_23);
        fze22.setHeight(11);
        fze22.setPosition(fzw_0.tLa);
        fze22.setTexture(this.okR.uF("themePressed"));
        fze22.setWidth(9);
        fze22.setX(460);
        fze22.setY(0);
        fkh_14.X(fze22);
        fze22.guy();
        fze22.onChildrenAdded();
        fze fze23 = fze.checkOut();
        fze23.setElementMap(fhs_23);
        fze23.setHeight(11);
        fze23.setPosition(fzw_0.tLc);
        fze23.setTexture(this.okR.uF("themePressed"));
        fze23.setWidth(10);
        fze23.setX(470);
        fze23.setY(0);
        fkh_14.X(fze23);
        fze23.guy();
        fze23.onChildrenAdded();
        fze fze24 = fze.checkOut();
        fze24.setElementMap(fhs_23);
        fze24.setHeight(9);
        fze24.setPosition(fzw_0.tLh);
        fze24.setTexture(this.okR.uF("themePressed"));
        fze24.setWidth(10);
        fze24.setX(470);
        fze24.setY(12);
        fkh_14.X(fze24);
        fze24.guy();
        fze24.onChildrenAdded();
        fze fze25 = fze.checkOut();
        fze25.setElementMap(fhs_23);
        fze25.setHeight(7);
        fze25.setPosition(fzw_0.tLo);
        fze25.setTexture(this.okR.uF("themePressed"));
        fze25.setWidth(10);
        fze25.setX(470);
        fze25.setY(20);
        fkh_14.X(fze25);
        fze25.guy();
        fze25.onChildrenAdded();
        fze fze26 = fze.checkOut();
        fze26.setElementMap(fhs_23);
        fze26.setHeight(7);
        fze26.setPosition(fzw_0.tLm);
        fze26.setTexture(this.okR.uF("themePressed"));
        fze26.setWidth(9);
        fze26.setX(460);
        fze26.setY(20);
        fkh_14.X(fze26);
        fze26.guy();
        fze26.onChildrenAdded();
        fze fze27 = fze.checkOut();
        fze27.setElementMap(fhs_23);
        fze27.setHeight(7);
        fze27.setPosition(fzw_0.tLk);
        fze27.setTexture(this.okR.uF("themePressed"));
        fze27.setWidth(10);
        fze27.setX(449);
        fze27.setY(20);
        fkh_14.X(fze27);
        fze27.guy();
        fze27.onChildrenAdded();
        fze fze28 = fze.checkOut();
        fze28.setElementMap(fhs_23);
        fze28.setHeight(7);
        fze28.setPosition(fzw_0.tLf);
        fze28.setTexture(this.okR.uF("themePressed"));
        fze28.setWidth(10);
        fze28.setX(449);
        fze28.setY(12);
        fkh_14.X(fze28);
        fze28.guy();
        fze28.onChildrenAdded();
        fkh_14.onChildrenAdded();
        fzk4.onChildrenAdded();
        fes_2 fes_27 = fes_22;
        fzk fzk5 = (fzk)fes_27.getAppearance();
        fzk5.setElementMap(fhs_23);
        fzk5.setAlign(faa_2.tLO);
        fzk5.setState("disabled");
        fes_22.X(fzk5);
        fzk5.guy();
        fyp_0 fyp_05 = fyp_0.checkOut();
        fyp_05.setElementMap(fhs_23);
        fyp_05.setColor(new fhl_2("defaultDarkGreyColor"));
        fzk5.X(fyp_05);
        fyp_05.guy();
        fyp_05.onChildrenAdded();
        String string7 = "tabDisabledBackground";
        fkd_1 fkd_15 = fkd_1.checkOut();
        fkd_15.setElementMap(fhs_23);
        if (fhs_23 != null && string7 != null) {
            fhs_23.a(string7, fkd_15);
        }
        fkd_15.setScaled(true);
        fzk5.X(fkd_15);
        fkd_15.guy();
        fze fze29 = fze.checkOut();
        fze29.setElementMap(fhs_23);
        fze29.setHeight(9);
        fze29.setPosition(fzw_0.tLg);
        fze29.setTexture(this.okR.uF("themeDisabled"));
        fze29.setWidth(9);
        fze29.setX(460);
        fze29.setY(12);
        fkd_15.X(fze29);
        fze29.guy();
        fze29.onChildrenAdded();
        fkd_15.onChildrenAdded();
        String string8 = "tabDisabledBorder";
        fkh_1 fkh_15 = new fkh_1();
        fkh_15.aVI();
        fkh_15.setElementMap(fhs_23);
        if (fhs_23 != null && string8 != null) {
            fhs_23.a(string8, fkh_15);
        }
        fzk5.X(fkh_15);
        fkh_15.guy();
        fze fze30 = fze.checkOut();
        fze30.setElementMap(fhs_23);
        fze30.setHeight(11);
        fze30.setPosition(fzw_0.tKY);
        fze30.setTexture(this.okR.uF("themeDisabled"));
        fze30.setWidth(10);
        fze30.setX(449);
        fze30.setY(0);
        fkh_15.X(fze30);
        fze30.guy();
        fze30.onChildrenAdded();
        fze fze31 = fze.checkOut();
        fze31.setElementMap(fhs_23);
        fze31.setHeight(11);
        fze31.setPosition(fzw_0.tLa);
        fze31.setTexture(this.okR.uF("themeDisabled"));
        fze31.setWidth(9);
        fze31.setX(460);
        fze31.setY(0);
        fkh_15.X(fze31);
        fze31.guy();
        fze31.onChildrenAdded();
        fze fze32 = fze.checkOut();
        fze32.setElementMap(fhs_23);
        fze32.setHeight(11);
        fze32.setPosition(fzw_0.tLc);
        fze32.setTexture(this.okR.uF("themeDisabled"));
        fze32.setWidth(10);
        fze32.setX(470);
        fze32.setY(0);
        fkh_15.X(fze32);
        fze32.guy();
        fze32.onChildrenAdded();
        fze fze33 = fze.checkOut();
        fze33.setElementMap(fhs_23);
        fze33.setHeight(9);
        fze33.setPosition(fzw_0.tLh);
        fze33.setTexture(this.okR.uF("themeDisabled"));
        fze33.setWidth(10);
        fze33.setX(470);
        fze33.setY(12);
        fkh_15.X(fze33);
        fze33.guy();
        fze33.onChildrenAdded();
        fze fze34 = fze.checkOut();
        fze34.setElementMap(fhs_23);
        fze34.setHeight(7);
        fze34.setPosition(fzw_0.tLo);
        fze34.setTexture(this.okR.uF("themeDisabled"));
        fze34.setWidth(10);
        fze34.setX(470);
        fze34.setY(20);
        fkh_15.X(fze34);
        fze34.guy();
        fze34.onChildrenAdded();
        this.b(fkh_15);
        this.c(fkh_15);
        this.d(fkh_15);
        fkh_15.onChildrenAdded();
        fzk5.onChildrenAdded();
        this.e(fes_22);
        this.f(fes_22);
        this.g(fes_22);
        this.h(fes_22);
    }

    public fhi_2 b(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(7);
        fze2.setPosition(fzw_0.tLm);
        fze2.setTexture(this.okR.uF("themeDisabled"));
        fze2.setWidth(9);
        fze2.setX(460);
        fze2.setY(20);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 c(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(7);
        fze2.setPosition(fzw_0.tLk);
        fze2.setTexture(this.okR.uF("themeDisabled"));
        fze2.setWidth(10);
        fze2.setX(449);
        fze2.setY(20);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 d(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(7);
        fze2.setPosition(fzw_0.tLf);
        fze2.setTexture(this.okR.uF("themeDisabled"));
        fze2.setWidth(10);
        fze2.setX(449);
        fze2.setY(12);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 e(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fzk fzk2 = (fzk)fes_22.getAppearance();
        fzk2.setElementMap(fhs_22);
        fzk2.setAlign(faa_2.tLO);
        fzk2.setState("selected");
        fhi_22.X(fzk2);
        fzk2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("blackColor"));
        fzk2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        String string = "tabDefaultSelectedBackground";
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fkd_12);
        }
        fkd_12.setScaled(true);
        fzk2.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(9);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("themeDefaultSelected"));
        fze2.setWidth(9);
        fze2.setX(460);
        fze2.setY(12);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fkd_12.onChildrenAdded();
        String string2 = "tabDefaultSelectedBorder";
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fkh_12);
        }
        fzk2.X(fkh_12);
        fkh_12.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fze3.setHeight(11);
        fze3.setPosition(fzw_0.tKY);
        fze3.setTexture(this.okR.uF("themeDefaultSelected"));
        fze3.setWidth(10);
        fze3.setX(449);
        fze3.setY(0);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_22);
        fze4.setHeight(11);
        fze4.setPosition(fzw_0.tLa);
        fze4.setTexture(this.okR.uF("themeDefaultSelected"));
        fze4.setWidth(9);
        fze4.setX(460);
        fze4.setY(0);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_22);
        fze5.setHeight(11);
        fze5.setPosition(fzw_0.tLc);
        fze5.setTexture(this.okR.uF("themeDefaultSelected"));
        fze5.setWidth(10);
        fze5.setX(470);
        fze5.setY(0);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_22);
        fze6.setHeight(9);
        fze6.setPosition(fzw_0.tLh);
        fze6.setTexture(this.okR.uF("themeDefaultSelected"));
        fze6.setWidth(10);
        fze6.setX(470);
        fze6.setY(12);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_22);
        fze7.setHeight(7);
        fze7.setPosition(fzw_0.tLo);
        fze7.setTexture(this.okR.uF("themeDefaultSelected"));
        fze7.setWidth(10);
        fze7.setX(470);
        fze7.setY(20);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_22);
        fze8.setHeight(7);
        fze8.setPosition(fzw_0.tLm);
        fze8.setTexture(this.okR.uF("themeDefaultSelected"));
        fze8.setWidth(9);
        fze8.setX(460);
        fze8.setY(20);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_22);
        fze9.setHeight(7);
        fze9.setPosition(fzw_0.tLk);
        fze9.setTexture(this.okR.uF("themeDefaultSelected"));
        fze9.setWidth(10);
        fze9.setX(449);
        fze9.setY(20);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_22);
        fze10.setHeight(7);
        fze10.setPosition(fzw_0.tLf);
        fze10.setTexture(this.okR.uF("themeDefaultSelected"));
        fze10.setWidth(10);
        fze10.setX(449);
        fze10.setY(12);
        fkh_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkh_12.onChildrenAdded();
        fzk2.onChildrenAdded();
        return fzk2;
    }

    public fhi_2 f(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fzk fzk2 = (fzk)fes_22.getAppearance();
        fzk2.setElementMap(fhs_22);
        fzk2.setAlign(faa_2.tLO);
        fzk2.setState("mouseHoverSelected");
        fhi_22.X(fzk2);
        fzk2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("mecanicBlueColor"));
        fzk2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        String string = "tabOverSelectedBackground";
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fkd_12);
        }
        fkd_12.setScaled(true);
        fzk2.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(9);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("themeOverSelected"));
        fze2.setWidth(9);
        fze2.setX(460);
        fze2.setY(12);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fkd_12.onChildrenAdded();
        String string2 = "tabOverSelectedBorder";
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fkh_12);
        }
        fzk2.X(fkh_12);
        fkh_12.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fze3.setHeight(11);
        fze3.setPosition(fzw_0.tKY);
        fze3.setTexture(this.okR.uF("themeOverSelected"));
        fze3.setWidth(10);
        fze3.setX(449);
        fze3.setY(0);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_22);
        fze4.setHeight(11);
        fze4.setPosition(fzw_0.tLa);
        fze4.setTexture(this.okR.uF("themeOverSelected"));
        fze4.setWidth(9);
        fze4.setX(460);
        fze4.setY(0);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_22);
        fze5.setHeight(11);
        fze5.setPosition(fzw_0.tLc);
        fze5.setTexture(this.okR.uF("themeOverSelected"));
        fze5.setWidth(10);
        fze5.setX(470);
        fze5.setY(0);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_22);
        fze6.setHeight(9);
        fze6.setPosition(fzw_0.tLh);
        fze6.setTexture(this.okR.uF("themeOverSelected"));
        fze6.setWidth(10);
        fze6.setX(470);
        fze6.setY(12);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_22);
        fze7.setHeight(7);
        fze7.setPosition(fzw_0.tLo);
        fze7.setTexture(this.okR.uF("themeOverSelected"));
        fze7.setWidth(10);
        fze7.setX(470);
        fze7.setY(20);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_22);
        fze8.setHeight(7);
        fze8.setPosition(fzw_0.tLm);
        fze8.setTexture(this.okR.uF("themeOverSelected"));
        fze8.setWidth(9);
        fze8.setX(460);
        fze8.setY(20);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_22);
        fze9.setHeight(7);
        fze9.setPosition(fzw_0.tLk);
        fze9.setTexture(this.okR.uF("themeOverSelected"));
        fze9.setWidth(10);
        fze9.setX(449);
        fze9.setY(20);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_22);
        fze10.setHeight(7);
        fze10.setPosition(fzw_0.tLf);
        fze10.setTexture(this.okR.uF("themeOverSelected"));
        fze10.setWidth(10);
        fze10.setX(449);
        fze10.setY(12);
        fkh_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkh_12.onChildrenAdded();
        fzk2.onChildrenAdded();
        return fzk2;
    }

    public fhi_2 g(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fzk fzk2 = (fzk)fes_22.getAppearance();
        fzk2.setElementMap(fhs_22);
        fzk2.setAlign(faa_2.tLO);
        fzk2.setState("pressedSelected");
        fhi_22.X(fzk2);
        fzk2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("blackColor"));
        fzk2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        String string = "tabPressedSelectedBackground";
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fkd_12);
        }
        fkd_12.setScaled(true);
        fzk2.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(9);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("themePressedSelected"));
        fze2.setWidth(9);
        fze2.setX(460);
        fze2.setY(12);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fkd_12.onChildrenAdded();
        String string2 = "tabPressedSelectedBorder";
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fkh_12);
        }
        fzk2.X(fkh_12);
        fkh_12.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fze3.setHeight(11);
        fze3.setPosition(fzw_0.tKY);
        fze3.setTexture(this.okR.uF("themePressedSelected"));
        fze3.setWidth(10);
        fze3.setX(449);
        fze3.setY(0);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_22);
        fze4.setHeight(11);
        fze4.setPosition(fzw_0.tLa);
        fze4.setTexture(this.okR.uF("themePressedSelected"));
        fze4.setWidth(9);
        fze4.setX(460);
        fze4.setY(0);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_22);
        fze5.setHeight(11);
        fze5.setPosition(fzw_0.tLc);
        fze5.setTexture(this.okR.uF("themePressedSelected"));
        fze5.setWidth(10);
        fze5.setX(470);
        fze5.setY(0);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_22);
        fze6.setHeight(9);
        fze6.setPosition(fzw_0.tLh);
        fze6.setTexture(this.okR.uF("themePressedSelected"));
        fze6.setWidth(10);
        fze6.setX(470);
        fze6.setY(12);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_22);
        fze7.setHeight(7);
        fze7.setPosition(fzw_0.tLo);
        fze7.setTexture(this.okR.uF("themePressedSelected"));
        fze7.setWidth(10);
        fze7.setX(470);
        fze7.setY(20);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_22);
        fze8.setHeight(7);
        fze8.setPosition(fzw_0.tLm);
        fze8.setTexture(this.okR.uF("themePressedSelected"));
        fze8.setWidth(9);
        fze8.setX(460);
        fze8.setY(20);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_22);
        fze9.setHeight(7);
        fze9.setPosition(fzw_0.tLk);
        fze9.setTexture(this.okR.uF("themePressedSelected"));
        fze9.setWidth(10);
        fze9.setX(449);
        fze9.setY(20);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_22);
        fze10.setHeight(7);
        fze10.setPosition(fzw_0.tLf);
        fze10.setTexture(this.okR.uF("themePressedSelected"));
        fze10.setWidth(10);
        fze10.setX(449);
        fze10.setY(12);
        fkh_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkh_12.onChildrenAdded();
        fzk2.onChildrenAdded();
        return fzk2;
    }

    public fhi_2 h(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fzk fzk2 = (fzk)fes_22.getAppearance();
        fzk2.setElementMap(fhs_22);
        fzk2.setAlign(faa_2.tLO);
        fzk2.setState("disabledSelected");
        fhi_22.X(fzk2);
        fzk2.guy();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_22);
        fyp_02.setColor(new fhl_2("blackColor"));
        fzk2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        String string = "tabDisabledSelectedBackground";
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_22);
        if (fhs_22 != null && string != null) {
            fhs_22.a(string, fkd_12);
        }
        fkd_12.setScaled(true);
        fzk2.X(fkd_12);
        fkd_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(9);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("themeDisabledSelected"));
        fze2.setWidth(9);
        fze2.setX(460);
        fze2.setY(12);
        fkd_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fkd_12.onChildrenAdded();
        String string2 = "tabDisabledSelectedBorder";
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_22);
        if (fhs_22 != null && string2 != null) {
            fhs_22.a(string2, fkh_12);
        }
        fzk2.X(fkh_12);
        fkh_12.guy();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_22);
        fze3.setHeight(11);
        fze3.setPosition(fzw_0.tKY);
        fze3.setTexture(this.okR.uF("themeDisabledSelected"));
        fze3.setWidth(10);
        fze3.setX(449);
        fze3.setY(0);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_22);
        fze4.setHeight(11);
        fze4.setPosition(fzw_0.tLa);
        fze4.setTexture(this.okR.uF("themeDisabledSelected"));
        fze4.setWidth(9);
        fze4.setX(460);
        fze4.setY(0);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_22);
        fze5.setHeight(11);
        fze5.setPosition(fzw_0.tLc);
        fze5.setTexture(this.okR.uF("themeDisabledSelected"));
        fze5.setWidth(10);
        fze5.setX(470);
        fze5.setY(0);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_22);
        fze6.setHeight(9);
        fze6.setPosition(fzw_0.tLh);
        fze6.setTexture(this.okR.uF("themeDisabledSelected"));
        fze6.setWidth(10);
        fze6.setX(470);
        fze6.setY(12);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_22);
        fze7.setHeight(7);
        fze7.setPosition(fzw_0.tLo);
        fze7.setTexture(this.okR.uF("themeDisabledSelected"));
        fze7.setWidth(10);
        fze7.setX(470);
        fze7.setY(20);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_22);
        fze8.setHeight(7);
        fze8.setPosition(fzw_0.tLm);
        fze8.setTexture(this.okR.uF("themeDisabledSelected"));
        fze8.setWidth(9);
        fze8.setX(460);
        fze8.setY(20);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_22);
        fze9.setHeight(7);
        fze9.setPosition(fzw_0.tLk);
        fze9.setTexture(this.okR.uF("themeDisabledSelected"));
        fze9.setWidth(10);
        fze9.setX(449);
        fze9.setY(20);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_22);
        fze10.setHeight(7);
        fze10.setPosition(fzw_0.tLf);
        fze10.setTexture(this.okR.uF("themeDisabledSelected"));
        fze10.setWidth(10);
        fze10.setX(449);
        fze10.setY(12);
        fkh_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fkh_12.onChildrenAdded();
        fzk2.onChildrenAdded();
        return fzk2;
    }
}

