/*
 * Decompiled with CFR 0.152.
 */
import java.awt.Insets;
import java.util.Stack;

/*
 * Renamed from ekf
 */
public class ekf_1
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        fze fze2;
        fha_2 fha_22;
        fhv_1 fhv_12;
        fha_2 fha_23;
        fhv_1 fhv_13;
        fhv_1 fhv_14;
        Object object;
        fhv_1 fhv_15;
        fhv_1 fhv_16;
        fhv_1 fhv_17;
        fhv_1 fhv_18;
        fhv_1 fhv_19;
        fhv_1 fhv_110;
        fes_2 fes_23;
        fkq_2 fkq_22;
        fkq_2 fkq_23;
        fkq_2 fkq_24;
        fkq_2 fkq_25;
        fkq_2 fkq_26;
        fkq_2 fkq_27;
        fha_2 fha_24;
        Object object2;
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_24 = fes_22;
        fzp fzp2 = (fzp)fes_24.getAppearance();
        fzp2.setElementMap(fhs_23);
        fzp2.setClearButtonDisplaySize(new fsm_1(18, 18));
        fzp2.setSearchButtonDisplaySize(new fsm_1(18, 18));
        fes_22.X(fzp2);
        fzp2.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_23);
        fzx2.setInsets(new Insets(3, 6, 3, 6));
        fzp2.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fes_2 fes_25 = fzp2.getParentOfType(fes_2.class);
        fes_2 fes_26 = fes_25.getWidgetByThemeElementName("textEditor", false);
        if (fes_26 != null) {
            object2 = fes_26;
            fha_24 = (fzq)((fes_2)object2).getAppearance();
            fha_24.setElementMap(fhs_23);
            ((fzq)fha_24).setAlign(faa_2.tLN);
            ((fzm)fha_24).setPadding(new Insets(0, 4, 0, 4));
            ((fys_0)fha_24).setState("default");
            fes_26.X(fha_24);
            fha_24.guy();
            fkq_27 = fyW.checkOut();
            ((fyW)fkq_27).setRenderer(fyw_0.gqw().gqB().uG("fontDefault16"));
            fkq_27.setElementMap(fhs_23);
            fha_24.X(fkq_27);
            fkq_27.guy();
            fkq_27.onChildrenAdded();
            fkq_26 = fyp_0.checkOut();
            fkq_26.setElementMap(fhs_23);
            ((fyp_0)fkq_26).setColor(new fhl_2("mainTextLightColor"));
            fha_24.X(fkq_26);
            fkq_26.guy();
            fkq_26.onChildrenAdded();
            fkq_25 = fyp_0.checkOut();
            fkq_25.setElementMap(fhs_23);
            ((fyp_0)fkq_25).setColor(new fhl_2("mainTextTitleColor"));
            ((fyp_0)fkq_25).setName("text");
            fha_24.X(fkq_25);
            fkq_25.guy();
            fkq_25.onChildrenAdded();
            fkq_24 = fyp_0.checkOut();
            fkq_24.setElementMap(fhs_23);
            ((fyp_0)fkq_24).setColor(new fhl_2("mainTextTitleColor", 0.5f));
            ((fyp_0)fkq_24).setName("ghostText");
            fha_24.X(fkq_24);
            fkq_24.guy();
            fkq_24.onChildrenAdded();
            fkq_23 = fyp_0.checkOut();
            fkq_23.setElementMap(fhs_23);
            ((fyp_0)fkq_23).setColor(new fhl_2("mainTextTitleColor"));
            ((fyp_0)fkq_23).setName("selection");
            fha_24.X(fkq_23);
            fkq_23.guy();
            fkq_23.onChildrenAdded();
            fkq_22 = fyp_0.checkOut();
            fkq_22.setElementMap(fhs_23);
            ((fyp_0)fkq_22).setColor(new fhl_2("mainTextTitleColor"));
            ((fyp_0)fkq_22).setName("cursor");
            fha_24.X(fkq_22);
            fkq_22.guy();
            fkq_22.onChildrenAdded();
            fha_24.onChildrenAdded();
        }
        object2 = "pmbNewTextEditor";
        fha_24 = fkd_1.checkOut();
        fha_24.setElementMap(fhs_23);
        if (fhs_23 != null && object2 != null) {
            fhs_23.a((String)object2, fha_24);
        }
        ((fkd_1)fha_24).setScaled(true);
        fzp2.X(fha_24);
        fha_24.guy();
        fkq_27 = fze.checkOut();
        fkq_27.setElementMap(fhs_23);
        ((fze)fkq_27).setFlipHorizontaly(true);
        ((fze)fkq_27).setHeight(7);
        ((fze)fkq_27).setPosition(fzw_0.tKY);
        ((fze)fkq_27).setTexture(this.okR.uF("txChatTextEditor"));
        ((fze)fkq_27).setWidth(7);
        ((fze)fkq_27).setX(21);
        ((fze)fkq_27).setY(0);
        fha_24.X(fkq_27);
        fkq_27.guy();
        fkq_27.onChildrenAdded();
        fkq_26 = fze.checkOut();
        fkq_26.setElementMap(fhs_23);
        ((fze)fkq_26).setFlipHorizontaly(true);
        ((fze)fkq_26).setHeight(1);
        ((fze)fkq_26).setPosition(fzw_0.tLf);
        ((fze)fkq_26).setTexture(this.okR.uF("txChatTextEditor"));
        ((fze)fkq_26).setWidth(7);
        ((fze)fkq_26).setX(21);
        ((fze)fkq_26).setY(8);
        fha_24.X(fkq_26);
        fkq_26.guy();
        fkq_26.onChildrenAdded();
        fkq_25 = fze.checkOut();
        fkq_25.setElementMap(fhs_23);
        ((fze)fkq_25).setFlipHorizontaly(true);
        ((fze)fkq_25).setHeight(7);
        ((fze)fkq_25).setPosition(fzw_0.tLk);
        ((fze)fkq_25).setTexture(this.okR.uF("txChatTextEditor"));
        ((fze)fkq_25).setWidth(7);
        ((fze)fkq_25).setX(21);
        ((fze)fkq_25).setY(21);
        fha_24.X(fkq_25);
        fkq_25.guy();
        fkq_25.onChildrenAdded();
        fkq_24 = fze.checkOut();
        fkq_24.setElementMap(fhs_23);
        ((fze)fkq_24).setHeight(7);
        ((fze)fkq_24).setPosition(fzw_0.tLa);
        ((fze)fkq_24).setTexture(this.okR.uF("txChatTextEditor"));
        ((fze)fkq_24).setWidth(1);
        ((fze)fkq_24).setX(8);
        ((fze)fkq_24).setY(0);
        fha_24.X(fkq_24);
        fkq_24.guy();
        fkq_24.onChildrenAdded();
        fkq_23 = fze.checkOut();
        fkq_23.setElementMap(fhs_23);
        ((fze)fkq_23).setHeight(1);
        ((fze)fkq_23).setPosition(fzw_0.tLg);
        ((fze)fkq_23).setTexture(this.okR.uF("txChatTextEditor"));
        ((fze)fkq_23).setWidth(1);
        ((fze)fkq_23).setX(8);
        ((fze)fkq_23).setY(8);
        fha_24.X(fkq_23);
        fkq_23.guy();
        fkq_23.onChildrenAdded();
        fkq_22 = fze.checkOut();
        fkq_22.setElementMap(fhs_23);
        ((fze)fkq_22).setHeight(7);
        ((fze)fkq_22).setPosition(fzw_0.tLm);
        ((fze)fkq_22).setTexture(this.okR.uF("txChatTextEditor"));
        ((fze)fkq_22).setWidth(1);
        ((fze)fkq_22).setX(8);
        ((fze)fkq_22).setY(21);
        fha_24.X(fkq_22);
        fkq_22.guy();
        fkq_22.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(7);
        fze3.setPosition(fzw_0.tLc);
        fze3.setTexture(this.okR.uF("txChatTextEditor"));
        fze3.setWidth(7);
        fze3.setX(21);
        fze3.setY(0);
        fha_24.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(1);
        fze4.setPosition(fzw_0.tLh);
        fze4.setTexture(this.okR.uF("txChatTextEditor"));
        fze4.setWidth(7);
        fze4.setX(21);
        fze4.setY(8);
        fha_24.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(7);
        fze5.setPosition(fzw_0.tLo);
        fze5.setTexture(this.okR.uF("txChatTextEditor"));
        fze5.setWidth(7);
        fze5.setX(21);
        fze5.setY(21);
        fha_24.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fha_24.onChildrenAdded();
        fes_2 fes_27 = fzp2.getParentOfType(fes_2.class);
        fes_2 fes_28 = fes_27.getWidgetByThemeElementName("searchButton", false);
        if (fes_28 != null) {
            fes_23 = fes_28;
            fhv_110 = (fym_0)fes_23.getAppearance();
            fhv_110.setElementMap(fhs_23);
            ((fys_0)fhv_110).setState("default");
            fes_28.X(fhv_110);
            fhv_110.guy();
            fhv_19 = fze.checkOut();
            fhv_19.setElementMap(fhs_23);
            ((fze)fhv_19).setHeight(18);
            ((fze)fhv_19).setPosition(fzw_0.tLg);
            ((fze)fhv_19).setTexture(this.okR.uF("txMagnifyingGlass"));
            ((fze)fhv_19).setWidth(18);
            ((fze)fhv_19).setX(0);
            ((fze)fhv_19).setY(0);
            fhv_110.X(fhv_19);
            fhv_19.guy();
            fhv_19.onChildrenAdded();
            fhv_110.onChildrenAdded();
            fhv_18 = fes_28;
            fhv_17 = (fym_0)((fes_2)fhv_18).getAppearance();
            fhv_17.setElementMap(fhs_23);
            ((fys_0)fhv_17).setState("mouseHover");
            fes_28.X(fhv_17);
            fhv_17.guy();
            fhv_16 = fze.checkOut();
            fhv_16.setElementMap(fhs_23);
            ((fze)fhv_16).setHeight(18);
            ((fze)fhv_16).setPosition(fzw_0.tLg);
            ((fze)fhv_16).setTexture(this.okR.uF("txMagnifyingGlass"));
            ((fze)fhv_16).setWidth(18);
            ((fze)fhv_16).setX(0);
            ((fze)fhv_16).setY(22);
            fhv_17.X(fhv_16);
            fhv_16.guy();
            fhv_16.onChildrenAdded();
            fhv_17.onChildrenAdded();
            fhv_15 = fes_28;
            object = (fym_0)((fes_2)fhv_15).getAppearance();
            ((fhv_1)object).setElementMap(fhs_23);
            ((fys_0)object).setState("pressed");
            fes_28.X((fhi_2)object);
            ((fhi_2)object).guy();
            fhv_14 = fze.checkOut();
            fhv_14.setElementMap(fhs_23);
            ((fze)fhv_14).setHeight(18);
            ((fze)fhv_14).setPosition(fzw_0.tLg);
            ((fze)fhv_14).setTexture(this.okR.uF("txMagnifyingGlass"));
            ((fze)fhv_14).setWidth(18);
            ((fze)fhv_14).setX(0);
            ((fze)fhv_14).setY(44);
            ((fhi_2)object).X(fhv_14);
            fhv_14.guy();
            fhv_14.onChildrenAdded();
            ((fhv_1)object).onChildrenAdded();
            fhv_13 = fes_28;
            fha_23 = (fym_0)((fes_2)fhv_13).getAppearance();
            fha_23.setElementMap(fhs_23);
            ((fzq)fha_23).setAlign(faa_2.tLO);
            ((fys_0)fha_23).setState("disabled");
            fes_28.X(fha_23);
            fha_23.guy();
            fhv_12 = fze.checkOut();
            fhv_12.setElementMap(fhs_23);
            ((fze)fhv_12).setHeight(18);
            ((fze)fhv_12).setPosition(fzw_0.tLg);
            ((fze)fhv_12).setTexture(this.okR.uF("txMagnifyingGlass"));
            ((fze)fhv_12).setWidth(18);
            ((fze)fhv_12).setX(0);
            ((fze)fhv_12).setY(66);
            fha_23.X(fhv_12);
            fhv_12.guy();
            fhv_12.onChildrenAdded();
            fha_23.onChildrenAdded();
        }
        if ((fhv_110 = (fes_23 = fzp2.getParentOfType(fes_2.class)).getWidgetByThemeElementName("clearButton", false)) != null) {
            fhv_19 = (fes_2)fhv_110;
            fhv_18 = (fym_0)((fes_2)fhv_19).getAppearance();
            fhv_18.setElementMap(fhs_23);
            ((fys_0)fhv_18).setState("default");
            fhv_110.X(fhv_18);
            fhv_18.guy();
            fhv_17 = fze.checkOut();
            fhv_17.setElementMap(fhs_23);
            ((fze)fhv_17).setHeight(18);
            ((fze)fhv_17).setPosition(fzw_0.tLg);
            ((fze)fhv_17).setTexture(this.okR.uF("txCloseCross"));
            ((fze)fhv_17).setWidth(18);
            ((fze)fhv_17).setX(0);
            ((fze)fhv_17).setY(0);
            fhv_18.X(fhv_17);
            fhv_17.guy();
            fhv_17.onChildrenAdded();
            fhv_18.onChildrenAdded();
            fhv_16 = (fes_2)fhv_110;
            fhv_15 = (fym_0)((fes_2)fhv_16).getAppearance();
            fhv_15.setElementMap(fhs_23);
            ((fys_0)fhv_15).setState("mouseHover");
            fhv_110.X(fhv_15);
            fhv_15.guy();
            object = fze.checkOut();
            ((fhv_1)object).setElementMap(fhs_23);
            ((fze)object).setHeight(18);
            ((fze)object).setPosition(fzw_0.tLg);
            ((fze)object).setTexture(this.okR.uF("txCloseCross"));
            ((fze)object).setWidth(18);
            ((fze)object).setX(0);
            ((fze)object).setY(20);
            fhv_15.X((fhi_2)object);
            ((fhi_2)object).guy();
            ((fhv_1)object).onChildrenAdded();
            fhv_15.onChildrenAdded();
            fhv_14 = (fes_2)fhv_110;
            fhv_13 = (fym_0)((fes_2)fhv_14).getAppearance();
            fhv_13.setElementMap(fhs_23);
            ((fys_0)fhv_13).setState("pressed");
            fhv_110.X(fhv_13);
            fhv_13.guy();
            fha_23 = fze.checkOut();
            fha_23.setElementMap(fhs_23);
            ((fze)fha_23).setHeight(18);
            ((fze)fha_23).setPosition(fzw_0.tLg);
            ((fze)fha_23).setTexture(this.okR.uF("txCloseCross"));
            ((fze)fha_23).setWidth(18);
            ((fze)fha_23).setX(0);
            ((fze)fha_23).setY(40);
            fhv_13.X(fha_23);
            fha_23.guy();
            fha_23.onChildrenAdded();
            fhv_13.onChildrenAdded();
            fhv_12 = (fes_2)fhv_110;
            fha_22 = (fym_0)((fes_2)fhv_12).getAppearance();
            fha_22.setElementMap(fhs_23);
            ((fzq)fha_22).setAlign(faa_2.tLO);
            ((fys_0)fha_22).setState("disabled");
            fhv_110.X(fha_22);
            fha_22.guy();
            fze2 = fze.checkOut();
            fze2.setElementMap(fhs_23);
            fze2.setHeight(18);
            fze2.setPosition(fzw_0.tLg);
            fze2.setTexture(this.okR.uF("txCloseCross"));
            fze2.setWidth(18);
            fze2.setX(0);
            fze2.setY(60);
            fha_22.X(fze2);
            fze2.guy();
            fze2.onChildrenAdded();
            fha_22.onChildrenAdded();
        }
        if ((fhv_18 = ((fes_2)(fhv_19 = fzp2.getParentOfType(fes_2.class))).getWidgetByThemeElementName("list", false)) != null) {
            fhv_17 = (fes_2)fhv_18;
            fhv_16 = (fza)((fes_2)fhv_17).getAppearance();
            fhv_16.setElementMap(fhs_23);
            fhv_18.X(fhv_16);
            fhv_16.guy();
            fhv_15 = new fzx();
            ((fzu)fhv_15).aVI();
            fhv_15.setElementMap(fhs_23);
            ((fzu)fhv_15).setInsets(new Insets(8, 8, 0, 8));
            fhv_16.X(fhv_15);
            fhv_15.guy();
            fhv_15.onChildrenAdded();
            object = "pmbSearchBackground";
            fhv_14 = fkd_1.checkOut();
            fhv_14.setElementMap(fhs_23);
            if (fhs_23 != null && object != null) {
                fhs_23.a((String)object, fhv_14);
            }
            ((fkd_1)fhv_14).setScaled(true);
            fhv_16.X(fhv_14);
            fhv_14.guy();
            fhv_13 = fze.checkOut();
            fhv_13.setElementMap(fhs_23);
            ((fze)fhv_13).setHeight(3);
            ((fze)fhv_13).setPosition(fzw_0.tKY);
            ((fze)fhv_13).setTexture(this.okR.uF("txSearchBackground"));
            ((fze)fhv_13).setWidth(3);
            ((fze)fhv_13).setX(0);
            ((fze)fhv_13).setY(0);
            fhv_14.X(fhv_13);
            fhv_13.guy();
            fhv_13.onChildrenAdded();
            fha_23 = fze.checkOut();
            fha_23.setElementMap(fhs_23);
            ((fze)fha_23).setHeight(1);
            ((fze)fha_23).setPosition(fzw_0.tLf);
            ((fze)fha_23).setTexture(this.okR.uF("txSearchBackground"));
            ((fze)fha_23).setWidth(3);
            ((fze)fha_23).setX(0);
            ((fze)fha_23).setY(16);
            fhv_14.X(fha_23);
            fha_23.guy();
            fha_23.onChildrenAdded();
            fhv_12 = fze.checkOut();
            fhv_12.setElementMap(fhs_23);
            ((fze)fhv_12).setHeight(3);
            ((fze)fhv_12).setPosition(fzw_0.tLk);
            ((fze)fhv_12).setTexture(this.okR.uF("txSearchBackground"));
            ((fze)fhv_12).setWidth(3);
            ((fze)fhv_12).setX(0);
            ((fze)fhv_12).setY(29);
            fhv_14.X(fhv_12);
            fhv_12.guy();
            fhv_12.onChildrenAdded();
            fha_22 = fze.checkOut();
            fha_22.setElementMap(fhs_23);
            ((fze)fha_22).setHeight(3);
            ((fze)fha_22).setPosition(fzw_0.tLa);
            ((fze)fha_22).setTexture(this.okR.uF("txSearchBackground"));
            ((fze)fha_22).setWidth(1);
            ((fze)fha_22).setX(16);
            ((fze)fha_22).setY(0);
            fhv_14.X(fha_22);
            fha_22.guy();
            fha_22.onChildrenAdded();
            fze2 = fze.checkOut();
            fze2.setElementMap(fhs_23);
            fze2.setHeight(1);
            fze2.setPosition(fzw_0.tLg);
            fze2.setTexture(this.okR.uF("txSearchBackground"));
            fze2.setWidth(1);
            fze2.setX(16);
            fze2.setY(16);
            fhv_14.X(fze2);
            fze2.guy();
            fze2.onChildrenAdded();
            fze fze6 = fze.checkOut();
            fze6.setElementMap(fhs_23);
            fze6.setHeight(3);
            fze6.setPosition(fzw_0.tLm);
            fze6.setTexture(this.okR.uF("txSearchBackground"));
            fze6.setWidth(1);
            fze6.setX(16);
            fze6.setY(29);
            fhv_14.X(fze6);
            fze6.guy();
            fze6.onChildrenAdded();
            fze fze7 = fze.checkOut();
            fze7.setElementMap(fhs_23);
            fze7.setHeight(3);
            fze7.setPosition(fzw_0.tLc);
            fze7.setTexture(this.okR.uF("txSearchBackground"));
            fze7.setWidth(3);
            fze7.setX(29);
            fze7.setY(0);
            fhv_14.X(fze7);
            fze7.guy();
            fze7.onChildrenAdded();
            fze fze8 = fze.checkOut();
            fze8.setElementMap(fhs_23);
            fze8.setHeight(1);
            fze8.setPosition(fzw_0.tLh);
            fze8.setTexture(this.okR.uF("txSearchBackground"));
            fze8.setWidth(3);
            fze8.setX(29);
            fze8.setY(16);
            fhv_14.X(fze8);
            fze8.guy();
            fze8.onChildrenAdded();
            fze fze9 = fze.checkOut();
            fze9.setElementMap(fhs_23);
            fze9.setHeight(3);
            fze9.setPosition(fzw_0.tLo);
            fze9.setTexture(this.okR.uF("txSearchBackground"));
            fze9.setWidth(3);
            fze9.setX(29);
            fze9.setY(29);
            fhv_14.X(fze9);
            fze9.guy();
            fze9.onChildrenAdded();
            fhv_14.onChildrenAdded();
            fyp_0 fyp_02 = fyp_0.checkOut();
            fyp_02.setElementMap(fhs_23);
            fyp_02.setColor(new awx_2(0.0f, 0.0f, 0.0f, 0.0f));
            fhv_16.X(fyp_02);
            fyp_02.guy();
            fyp_02.onChildrenAdded();
            fes_2 fes_29 = fhv_16.getParentOfType(fes_2.class);
            fes_2 fes_210 = fes_29.getWidgetByThemeElementName("verticalScrollbar", false);
            if (fes_210 != null) {
                fes_2 fes_211 = fes_210;
                fys_0 fys_02 = fes_211.getAppearance();
                fys_02.setElementMap(fhs_23);
                fes_210.X(fys_02);
                fys_02.guy();
                fes_2 fes_212 = fys_02.getParentOfType(fes_2.class);
                fes_2 fes_213 = fes_212.getWidgetByThemeElementName("verticalIncreaseButton", false);
                if (fes_213 != null) {
                    fzx fzx3 = new fzx();
                    fzx3.aVI();
                    fzx3.setElementMap(fhs_23);
                    fzx3.setInsets(new Insets(1, 1, 1, 1));
                    fes_213.X(fzx3);
                    fzx3.guy();
                    fzx3.onChildrenAdded();
                    fes_2 fes_214 = fes_213;
                    fym_0 fym_02 = (fym_0)fes_214.getAppearance();
                    fym_02.setElementMap(fhs_23);
                    fym_02.setState("default");
                    fes_213.X(fym_02);
                    fym_02.guy();
                    fze fze10 = fze.checkOut();
                    fze10.setElementMap(fhs_23);
                    fze10.setHeight(6);
                    fze10.setPosition(fzw_0.tLg);
                    fze10.setTexture(this.okR.uF("txScrollbarButton"));
                    fze10.setWidth(8);
                    fze10.setX(0);
                    fze10.setY(0);
                    fym_02.X(fze10);
                    fze10.guy();
                    fze10.onChildrenAdded();
                    fym_02.onChildrenAdded();
                    this.b(fes_213);
                    this.c(fes_213);
                    this.d(fes_213);
                }
                this.e(fys_02);
                this.f(fys_02);
                fys_02.onChildrenAdded();
                this.n(fes_210);
            }
            this.o(fhv_16);
            fhv_16.onChildrenAdded();
        }
        fzp2.onChildrenAdded();
    }

    public fhi_2 b(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fym_0 fym_02 = (fym_0)fes_22.getAppearance();
        fym_02.setElementMap(fhs_22);
        fym_02.setState("mouseHover");
        fhi_22.X(fym_02);
        fym_02.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(6);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txScrollbarButton"));
        fze2.setWidth(8);
        fze2.setX(0);
        fze2.setY(8);
        fym_02.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fym_02.onChildrenAdded();
        return fym_02;
    }

    public fhi_2 c(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fym_0 fym_02 = (fym_0)fes_22.getAppearance();
        fym_02.setElementMap(fhs_22);
        fym_02.setState("pressed");
        fhi_22.X(fym_02);
        fym_02.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(6);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txScrollbarButton"));
        fze2.setWidth(8);
        fze2.setX(0);
        fze2.setY(16);
        fym_02.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fym_02.onChildrenAdded();
        return fym_02;
    }

    public fhi_2 d(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fym_0 fym_02 = (fym_0)fes_22.getAppearance();
        fym_02.setElementMap(fhs_22);
        fym_02.setState("disabled");
        fhi_22.X(fym_02);
        fym_02.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(6);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txScrollbarButton"));
        fze2.setWidth(8);
        fze2.setX(0);
        fze2.setY(24);
        fym_02.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fym_02.onChildrenAdded();
        return fym_02;
    }

    public fhi_2 e(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = fhi_22.getParentOfType(fes_2.class);
        fes_2 fes_23 = fes_22.getWidgetByThemeElementName("verticalDecreaseButton", false);
        if (fes_23 != null) {
            fzx fzx2 = new fzx();
            fzx2.aVI();
            fzx2.setElementMap(fhs_22);
            fzx2.setInsets(new Insets(1, 1, 1, 1));
            fes_23.X(fzx2);
            fzx2.guy();
            fzx2.onChildrenAdded();
            fes_2 fes_24 = fes_23;
            fym_0 fym_02 = (fym_0)fes_24.getAppearance();
            fym_02.setElementMap(fhs_22);
            fym_02.setState("default");
            fes_23.X(fym_02);
            fym_02.guy();
            fze fze2 = fze.checkOut();
            fze2.setElementMap(fhs_22);
            fze2.setFlipVerticaly(true);
            fze2.setHeight(6);
            fze2.setPosition(fzw_0.tLg);
            fze2.setTexture(this.okR.uF("txScrollbarButton"));
            fze2.setWidth(8);
            fze2.setX(0);
            fze2.setY(0);
            fym_02.X(fze2);
            fze2.guy();
            fze2.onChildrenAdded();
            fym_02.onChildrenAdded();
            fes_2 fes_25 = fes_23;
            fym_0 fym_03 = (fym_0)fes_25.getAppearance();
            fym_03.setElementMap(fhs_22);
            fym_03.setState("mouseHover");
            fes_23.X(fym_03);
            fym_03.guy();
            fze fze3 = fze.checkOut();
            fze3.setElementMap(fhs_22);
            fze3.setFlipVerticaly(true);
            fze3.setHeight(6);
            fze3.setPosition(fzw_0.tLg);
            fze3.setTexture(this.okR.uF("txScrollbarButton"));
            fze3.setWidth(8);
            fze3.setX(0);
            fze3.setY(8);
            fym_03.X(fze3);
            fze3.guy();
            fze3.onChildrenAdded();
            fym_03.onChildrenAdded();
            fes_2 fes_26 = fes_23;
            fym_0 fym_04 = (fym_0)fes_26.getAppearance();
            fym_04.setElementMap(fhs_22);
            fym_04.setState("pressed");
            fes_23.X(fym_04);
            fym_04.guy();
            fze fze4 = fze.checkOut();
            fze4.setElementMap(fhs_22);
            fze4.setFlipVerticaly(true);
            fze4.setHeight(6);
            fze4.setPosition(fzw_0.tLg);
            fze4.setTexture(this.okR.uF("txScrollbarButton"));
            fze4.setWidth(8);
            fze4.setX(0);
            fze4.setY(16);
            fym_04.X(fze4);
            fze4.guy();
            fze4.onChildrenAdded();
            fym_04.onChildrenAdded();
            fes_2 fes_27 = fes_23;
            fym_0 fym_05 = (fym_0)fes_27.getAppearance();
            fym_05.setElementMap(fhs_22);
            fym_05.setState("disabled");
            fes_23.X(fym_05);
            fym_05.guy();
            fze fze5 = fze.checkOut();
            fze5.setElementMap(fhs_22);
            fze5.setFlipVerticaly(true);
            fze5.setHeight(6);
            fze5.setPosition(fzw_0.tLg);
            fze5.setTexture(this.okR.uF("txScrollbarButton"));
            fze5.setWidth(8);
            fze5.setX(0);
            fze5.setY(24);
            fym_05.X(fze5);
            fze5.guy();
            fze5.onChildrenAdded();
            fym_05.onChildrenAdded();
        }
        return fes_23;
    }

    public fhi_2 f(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = fhi_22.getParentOfType(fes_2.class);
        fes_2 fes_23 = fes_22.getWidgetByThemeElementName("verticalSlider", false);
        if (fes_23 != null) {
            fkp_2 fkp_22;
            fha_2 fha_22;
            fhv_1 fhv_12;
            fes_2 fes_24 = fes_23;
            fys_0 fys_02 = fes_24.getAppearance();
            fys_02.setElementMap(fhs_22);
            fes_23.X(fys_02);
            fys_02.guy();
            fes_2 fes_25 = fys_02.getParentOfType(fes_2.class);
            fes_2 fes_26 = fes_25.getWidgetByThemeElementName("verticalButton", false);
            if (fes_26 != null) {
                fhv_12 = fes_26;
                fha_22 = (fym_0)((fes_2)fhv_12).getAppearance();
                fha_22.setElementMap(fhs_22);
                ((fys_0)fha_22).setState("default");
                fes_26.X(fha_22);
                fha_22.guy();
                fkp_22 = fkd_1.checkOut();
                fkp_22.setElementMap(fhs_22);
                fkp_22.setEnabled(true);
                ((fkd_1)fkp_22).setScaled(true);
                fha_22.X(fkp_22);
                fkp_22.guy();
                fze fze2 = fze.checkOut();
                fze2.setElementMap(fhs_22);
                fze2.setHeight(4);
                fze2.setPosition(fzw_0.tKY);
                fze2.setTexture(this.okR.uF("txScrollbarSlider"));
                fze2.setWidth(4);
                fze2.setX(0);
                fze2.setY(0);
                fkp_22.X(fze2);
                fze2.guy();
                fze2.onChildrenAdded();
                fze fze3 = fze.checkOut();
                fze3.setElementMap(fhs_22);
                fze3.setHeight(1);
                fze3.setPosition(fzw_0.tLf);
                fze3.setTexture(this.okR.uF("txScrollbarSlider"));
                fze3.setWidth(4);
                fze3.setX(0);
                fze3.setY(4);
                fkp_22.X(fze3);
                fze3.guy();
                fze3.onChildrenAdded();
                fze fze4 = fze.checkOut();
                fze4.setElementMap(fhs_22);
                fze4.setHeight(4);
                fze4.setPosition(fzw_0.tLk);
                fze4.setTexture(this.okR.uF("txScrollbarSlider"));
                fze4.setWidth(4);
                fze4.setX(0);
                fze4.setY(12);
                fkp_22.X(fze4);
                fze4.guy();
                fze4.onChildrenAdded();
                fze fze5 = fze.checkOut();
                fze5.setElementMap(fhs_22);
                fze5.setHeight(4);
                fze5.setPosition(fzw_0.tLa);
                fze5.setTexture(this.okR.uF("txScrollbarSlider"));
                fze5.setWidth(1);
                fze5.setX(3);
                fze5.setY(0);
                fkp_22.X(fze5);
                fze5.guy();
                fze5.onChildrenAdded();
                fze fze6 = fze.checkOut();
                fze6.setElementMap(fhs_22);
                fze6.setHeight(1);
                fze6.setPosition(fzw_0.tLg);
                fze6.setTexture(this.okR.uF("txScrollbarSlider"));
                fze6.setWidth(1);
                fze6.setX(3);
                fze6.setY(4);
                fkp_22.X(fze6);
                fze6.guy();
                fze6.onChildrenAdded();
                fze fze7 = fze.checkOut();
                fze7.setElementMap(fhs_22);
                fze7.setHeight(4);
                fze7.setPosition(fzw_0.tLm);
                fze7.setTexture(this.okR.uF("txScrollbarSlider"));
                fze7.setWidth(1);
                fze7.setX(3);
                fze7.setY(12);
                fkp_22.X(fze7);
                fze7.guy();
                fze7.onChildrenAdded();
                fze fze8 = fze.checkOut();
                fze8.setElementMap(fhs_22);
                fze8.setHeight(4);
                fze8.setPosition(fzw_0.tLc);
                fze8.setTexture(this.okR.uF("txScrollbarSlider"));
                fze8.setWidth(4);
                fze8.setX(4);
                fze8.setY(0);
                fkp_22.X(fze8);
                fze8.guy();
                fze8.onChildrenAdded();
                fze fze9 = fze.checkOut();
                fze9.setElementMap(fhs_22);
                fze9.setHeight(1);
                fze9.setPosition(fzw_0.tLh);
                fze9.setTexture(this.okR.uF("txScrollbarSlider"));
                fze9.setWidth(4);
                fze9.setX(4);
                fze9.setY(4);
                fkp_22.X(fze9);
                fze9.guy();
                fze9.onChildrenAdded();
                fze fze10 = fze.checkOut();
                fze10.setElementMap(fhs_22);
                fze10.setHeight(4);
                fze10.setPosition(fzw_0.tLo);
                fze10.setTexture(this.okR.uF("txScrollbarSlider"));
                fze10.setWidth(4);
                fze10.setX(4);
                fze10.setY(12);
                fkp_22.X(fze10);
                fze10.guy();
                fze10.onChildrenAdded();
                fkp_22.onChildrenAdded();
                fze fze11 = fze.checkOut();
                fze11.setElementMap(fhs_22);
                fze11.setHeight(0);
                fze11.setPosition(fzw_0.tLg);
                fze11.setTexture(this.okR.uF("txScrollbarSlider"));
                fze11.setWidth(0);
                fze11.setX(0);
                fze11.setY(16);
                fha_22.X(fze11);
                fze11.guy();
                fze11.onChildrenAdded();
                fha_22.onChildrenAdded();
                fes_2 fes_27 = fes_26;
                fym_0 fym_02 = (fym_0)fes_27.getAppearance();
                fym_02.setElementMap(fhs_22);
                fym_02.setState("mouseHover");
                fes_26.X(fym_02);
                fym_02.guy();
                fkd_1 fkd_12 = fkd_1.checkOut();
                fkd_12.setElementMap(fhs_22);
                fkd_12.setScaled(true);
                fym_02.X(fkd_12);
                fkd_12.guy();
                fze fze12 = fze.checkOut();
                fze12.setElementMap(fhs_22);
                fze12.setHeight(4);
                fze12.setPosition(fzw_0.tKY);
                fze12.setTexture(this.okR.uF("txScrollbarSlider"));
                fze12.setWidth(4);
                fze12.setX(0);
                fze12.setY(18);
                fkd_12.X(fze12);
                fze12.guy();
                fze12.onChildrenAdded();
                fze fze13 = fze.checkOut();
                fze13.setElementMap(fhs_22);
                fze13.setHeight(1);
                fze13.setPosition(fzw_0.tLf);
                fze13.setTexture(this.okR.uF("txScrollbarSlider"));
                fze13.setWidth(4);
                fze13.setX(0);
                fze13.setY(22);
                fkd_12.X(fze13);
                fze13.guy();
                fze13.onChildrenAdded();
                fze fze14 = fze.checkOut();
                fze14.setElementMap(fhs_22);
                fze14.setHeight(4);
                fze14.setPosition(fzw_0.tLk);
                fze14.setTexture(this.okR.uF("txScrollbarSlider"));
                fze14.setWidth(4);
                fze14.setX(0);
                fze14.setY(30);
                fkd_12.X(fze14);
                fze14.guy();
                fze14.onChildrenAdded();
                fze fze15 = fze.checkOut();
                fze15.setElementMap(fhs_22);
                fze15.setHeight(4);
                fze15.setPosition(fzw_0.tLa);
                fze15.setTexture(this.okR.uF("txScrollbarSlider"));
                fze15.setWidth(1);
                fze15.setX(3);
                fze15.setY(18);
                fkd_12.X(fze15);
                fze15.guy();
                fze15.onChildrenAdded();
                fze fze16 = fze.checkOut();
                fze16.setElementMap(fhs_22);
                fze16.setHeight(1);
                fze16.setPosition(fzw_0.tLg);
                fze16.setTexture(this.okR.uF("txScrollbarSlider"));
                fze16.setWidth(1);
                fze16.setX(3);
                fze16.setY(22);
                fkd_12.X(fze16);
                fze16.guy();
                fze16.onChildrenAdded();
                fze fze17 = fze.checkOut();
                fze17.setElementMap(fhs_22);
                fze17.setHeight(4);
                fze17.setPosition(fzw_0.tLm);
                fze17.setTexture(this.okR.uF("txScrollbarSlider"));
                fze17.setWidth(1);
                fze17.setX(3);
                fze17.setY(30);
                fkd_12.X(fze17);
                fze17.guy();
                fze17.onChildrenAdded();
                fze fze18 = fze.checkOut();
                fze18.setElementMap(fhs_22);
                fze18.setHeight(4);
                fze18.setPosition(fzw_0.tLc);
                fze18.setTexture(this.okR.uF("txScrollbarSlider"));
                fze18.setWidth(4);
                fze18.setX(4);
                fze18.setY(18);
                fkd_12.X(fze18);
                fze18.guy();
                fze18.onChildrenAdded();
                fze fze19 = fze.checkOut();
                fze19.setElementMap(fhs_22);
                fze19.setHeight(1);
                fze19.setPosition(fzw_0.tLh);
                fze19.setTexture(this.okR.uF("txScrollbarSlider"));
                fze19.setWidth(4);
                fze19.setX(4);
                fze19.setY(22);
                fkd_12.X(fze19);
                fze19.guy();
                fze19.onChildrenAdded();
                fze fze20 = fze.checkOut();
                fze20.setElementMap(fhs_22);
                fze20.setHeight(4);
                fze20.setPosition(fzw_0.tLo);
                fze20.setTexture(this.okR.uF("txScrollbarSlider"));
                fze20.setWidth(4);
                fze20.setX(4);
                fze20.setY(30);
                fkd_12.X(fze20);
                fze20.guy();
                fze20.onChildrenAdded();
                fkd_12.onChildrenAdded();
                fym_02.onChildrenAdded();
                fes_2 fes_28 = fes_26;
                fym_0 fym_03 = (fym_0)fes_28.getAppearance();
                fym_03.setElementMap(fhs_22);
                fym_03.setState("pressed");
                fes_26.X(fym_03);
                fym_03.guy();
                fkd_1 fkd_13 = fkd_1.checkOut();
                fkd_13.setElementMap(fhs_22);
                fkd_13.setScaled(true);
                fym_03.X(fkd_13);
                fkd_13.guy();
                fze fze21 = fze.checkOut();
                fze21.setElementMap(fhs_22);
                fze21.setHeight(4);
                fze21.setPosition(fzw_0.tKY);
                fze21.setTexture(this.okR.uF("txScrollbarSlider"));
                fze21.setWidth(4);
                fze21.setX(0);
                fze21.setY(36);
                fkd_13.X(fze21);
                fze21.guy();
                fze21.onChildrenAdded();
                fze fze22 = fze.checkOut();
                fze22.setElementMap(fhs_22);
                fze22.setHeight(1);
                fze22.setPosition(fzw_0.tLf);
                fze22.setTexture(this.okR.uF("txScrollbarSlider"));
                fze22.setWidth(4);
                fze22.setX(0);
                fze22.setY(40);
                fkd_13.X(fze22);
                fze22.guy();
                fze22.onChildrenAdded();
                fze fze23 = fze.checkOut();
                fze23.setElementMap(fhs_22);
                fze23.setHeight(4);
                fze23.setPosition(fzw_0.tLk);
                fze23.setTexture(this.okR.uF("txScrollbarSlider"));
                fze23.setWidth(4);
                fze23.setX(0);
                fze23.setY(48);
                fkd_13.X(fze23);
                fze23.guy();
                fze23.onChildrenAdded();
                fze fze24 = fze.checkOut();
                fze24.setElementMap(fhs_22);
                fze24.setHeight(4);
                fze24.setPosition(fzw_0.tLa);
                fze24.setTexture(this.okR.uF("txScrollbarSlider"));
                fze24.setWidth(1);
                fze24.setX(3);
                fze24.setY(36);
                fkd_13.X(fze24);
                fze24.guy();
                fze24.onChildrenAdded();
                fze fze25 = fze.checkOut();
                fze25.setElementMap(fhs_22);
                fze25.setHeight(1);
                fze25.setPosition(fzw_0.tLg);
                fze25.setTexture(this.okR.uF("txScrollbarSlider"));
                fze25.setWidth(1);
                fze25.setX(3);
                fze25.setY(40);
                fkd_13.X(fze25);
                fze25.guy();
                fze25.onChildrenAdded();
                fze fze26 = fze.checkOut();
                fze26.setElementMap(fhs_22);
                fze26.setHeight(4);
                fze26.setPosition(fzw_0.tLm);
                fze26.setTexture(this.okR.uF("txScrollbarSlider"));
                fze26.setWidth(1);
                fze26.setX(3);
                fze26.setY(48);
                fkd_13.X(fze26);
                fze26.guy();
                fze26.onChildrenAdded();
                fze fze27 = fze.checkOut();
                fze27.setElementMap(fhs_22);
                fze27.setHeight(4);
                fze27.setPosition(fzw_0.tLc);
                fze27.setTexture(this.okR.uF("txScrollbarSlider"));
                fze27.setWidth(4);
                fze27.setX(4);
                fze27.setY(36);
                fkd_13.X(fze27);
                fze27.guy();
                fze27.onChildrenAdded();
                fze fze28 = fze.checkOut();
                fze28.setElementMap(fhs_22);
                fze28.setHeight(1);
                fze28.setPosition(fzw_0.tLh);
                fze28.setTexture(this.okR.uF("txScrollbarSlider"));
                fze28.setWidth(4);
                fze28.setX(4);
                fze28.setY(40);
                fkd_13.X(fze28);
                fze28.guy();
                fze28.onChildrenAdded();
                fze fze29 = fze.checkOut();
                fze29.setElementMap(fhs_22);
                fze29.setHeight(4);
                fze29.setPosition(fzw_0.tLo);
                fze29.setTexture(this.okR.uF("txScrollbarSlider"));
                fze29.setWidth(4);
                fze29.setX(4);
                fze29.setY(48);
                fkd_13.X(fze29);
                fze29.guy();
                fze29.onChildrenAdded();
                fkd_13.onChildrenAdded();
                fym_03.onChildrenAdded();
                fes_2 fes_29 = fes_26;
                fym_0 fym_04 = (fym_0)fes_29.getAppearance();
                fym_04.setElementMap(fhs_22);
                fym_04.setState("disabled");
                fes_26.X(fym_04);
                fym_04.guy();
                fkd_1 fkd_14 = fkd_1.checkOut();
                fkd_14.setElementMap(fhs_22);
                fkd_14.setScaled(true);
                fym_04.X(fkd_14);
                fkd_14.guy();
                fze fze30 = fze.checkOut();
                fze30.setElementMap(fhs_22);
                fze30.setHeight(4);
                fze30.setPosition(fzw_0.tKY);
                fze30.setTexture(this.okR.uF("txScrollbarSlider"));
                fze30.setWidth(4);
                fze30.setX(0);
                fze30.setY(54);
                fkd_14.X(fze30);
                fze30.guy();
                fze30.onChildrenAdded();
                fze fze31 = fze.checkOut();
                fze31.setElementMap(fhs_22);
                fze31.setHeight(1);
                fze31.setPosition(fzw_0.tLf);
                fze31.setTexture(this.okR.uF("txScrollbarSlider"));
                fze31.setWidth(4);
                fze31.setX(0);
                fze31.setY(58);
                fkd_14.X(fze31);
                fze31.guy();
                fze31.onChildrenAdded();
                fze fze32 = fze.checkOut();
                fze32.setElementMap(fhs_22);
                fze32.setHeight(4);
                fze32.setPosition(fzw_0.tLk);
                fze32.setTexture(this.okR.uF("txScrollbarSlider"));
                fze32.setWidth(4);
                fze32.setX(0);
                fze32.setY(66);
                fkd_14.X(fze32);
                fze32.guy();
                fze32.onChildrenAdded();
                fze fze33 = fze.checkOut();
                fze33.setElementMap(fhs_22);
                fze33.setHeight(4);
                fze33.setPosition(fzw_0.tLa);
                fze33.setTexture(this.okR.uF("txScrollbarSlider"));
                fze33.setWidth(1);
                fze33.setX(3);
                fze33.setY(54);
                fkd_14.X(fze33);
                fze33.guy();
                fze33.onChildrenAdded();
                fze fze34 = fze.checkOut();
                fze34.setElementMap(fhs_22);
                fze34.setHeight(1);
                fze34.setPosition(fzw_0.tLg);
                fze34.setTexture(this.okR.uF("txScrollbarSlider"));
                fze34.setWidth(1);
                fze34.setX(3);
                fze34.setY(58);
                fkd_14.X(fze34);
                fze34.guy();
                fze34.onChildrenAdded();
                fze fze35 = fze.checkOut();
                fze35.setElementMap(fhs_22);
                fze35.setHeight(4);
                fze35.setPosition(fzw_0.tLm);
                fze35.setTexture(this.okR.uF("txScrollbarSlider"));
                fze35.setWidth(1);
                fze35.setX(3);
                fze35.setY(66);
                fkd_14.X(fze35);
                fze35.guy();
                fze35.onChildrenAdded();
                fze fze36 = fze.checkOut();
                fze36.setElementMap(fhs_22);
                fze36.setHeight(4);
                fze36.setPosition(fzw_0.tLc);
                fze36.setTexture(this.okR.uF("txScrollbarSlider"));
                fze36.setWidth(4);
                fze36.setX(4);
                fze36.setY(54);
                fkd_14.X(fze36);
                fze36.guy();
                fze36.onChildrenAdded();
                fze fze37 = fze.checkOut();
                fze37.setElementMap(fhs_22);
                fze37.setHeight(1);
                fze37.setPosition(fzw_0.tLh);
                fze37.setTexture(this.okR.uF("txScrollbarSlider"));
                fze37.setWidth(4);
                fze37.setX(4);
                fze37.setY(58);
                fkd_14.X(fze37);
                fze37.guy();
                fze37.onChildrenAdded();
                fze fze38 = fze.checkOut();
                fze38.setElementMap(fhs_22);
                fze38.setHeight(4);
                fze38.setPosition(fzw_0.tLo);
                fze38.setTexture(this.okR.uF("txScrollbarSlider"));
                fze38.setWidth(4);
                fze38.setX(4);
                fze38.setY(66);
                fkd_14.X(fze38);
                fze38.guy();
                fze38.onChildrenAdded();
                fkd_14.onChildrenAdded();
                fym_04.onChildrenAdded();
            }
            fhv_12 = fkd_1.checkOut();
            fhv_12.setElementMap(fhs_22);
            ((fkn_2)fhv_12).setEnabled(true);
            ((fkd_1)fhv_12).setScaled(true);
            fys_02.X(fhv_12);
            fhv_12.guy();
            fha_22 = fze.checkOut();
            fha_22.setElementMap(fhs_22);
            ((fze)fha_22).setHeight(3);
            ((fze)fha_22).setPosition(fzw_0.tKY);
            ((fze)fha_22).setTexture(this.okR.uF("txScrollbarBackground"));
            ((fze)fha_22).setWidth(3);
            ((fze)fha_22).setX(0);
            ((fze)fha_22).setY(0);
            fhv_12.X(fha_22);
            fha_22.guy();
            fha_22.onChildrenAdded();
            fkp_22 = fze.checkOut();
            fkp_22.setElementMap(fhs_22);
            ((fze)fkp_22).setHeight(0);
            ((fze)fkp_22).setPosition(fzw_0.tLf);
            ((fze)fkp_22).setTexture(this.okR.uF("txScrollbarBackground"));
            ((fze)fkp_22).setWidth(3);
            ((fze)fkp_22).setX(0);
            ((fze)fkp_22).setY(4);
            fhv_12.X(fkp_22);
            fkp_22.guy();
            fkp_22.onChildrenAdded();
            this.g(fhv_12);
            this.h(fhv_12);
            this.i(fhv_12);
            this.j(fhv_12);
            this.k(fhv_12);
            this.l(fhv_12);
            this.m(fhv_12);
            fhv_12.onChildrenAdded();
            fys_02.onChildrenAdded();
        }
        return fes_23;
    }

    public fhi_2 g(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(3);
        fze2.setPosition(fzw_0.tLk);
        fze2.setTexture(this.okR.uF("txScrollbarBackground"));
        fze2.setWidth(3);
        fze2.setX(0);
        fze2.setY(13);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 h(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(3);
        fze2.setPosition(fzw_0.tLa);
        fze2.setTexture(this.okR.uF("txScrollbarBackground"));
        fze2.setWidth(1);
        fze2.setX(2);
        fze2.setY(0);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 i(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(0);
        fze2.setPosition(fzw_0.tLg);
        fze2.setTexture(this.okR.uF("txScrollbarBackground"));
        fze2.setWidth(1);
        fze2.setX(2);
        fze2.setY(4);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 j(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(3);
        fze2.setPosition(fzw_0.tLm);
        fze2.setTexture(this.okR.uF("txScrollbarBackground"));
        fze2.setWidth(1);
        fze2.setX(2);
        fze2.setY(13);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 k(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(3);
        fze2.setPosition(fzw_0.tLc);
        fze2.setTexture(this.okR.uF("txScrollbarBackground"));
        fze2.setWidth(3);
        fze2.setX(3);
        fze2.setY(0);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 l(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(0);
        fze2.setPosition(fzw_0.tLh);
        fze2.setTexture(this.okR.uF("txScrollbarBackground"));
        fze2.setWidth(3);
        fze2.setX(3);
        fze2.setY(4);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 m(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_22);
        fze2.setHeight(3);
        fze2.setPosition(fzw_0.tLo);
        fze2.setTexture(this.okR.uF("txScrollbarBackground"));
        fze2.setWidth(3);
        fze2.setX(3);
        fze2.setY(13);
        fhi_22.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        return fze2;
    }

    public fhi_2 n(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = (fes_2)fhi_22;
        fys_0 fys_02 = fes_22.getAppearance();
        fys_02.setElementMap(fhs_22);
        fhi_22.X(fys_02);
        fys_02.guy();
        fzx fzx2 = new fzx();
        fzx2.aVI();
        fzx2.setElementMap(fhs_22);
        fzx2.setInsets(new Insets(0, 2, 8, 0));
        fys_02.X(fzx2);
        fzx2.guy();
        fzx2.onChildrenAdded();
        fys_02.onChildrenAdded();
        return fys_02;
    }

    public fhi_2 o(fhi_2 fhi_22) {
        fhs_2 fhs_22 = this.nei.peek();
        fes_2 fes_22 = fhi_22.getParentOfType(fes_2.class);
        fes_2 fes_23 = fes_22.getWidgetByThemeElementName("renderableTemplate", false);
        if (fes_23 != null) {
            fes_2 fes_24 = fes_23;
            fys_0 fys_02 = fes_24.getAppearance();
            fys_02.setElementMap(fhs_22);
            fys_02.setState("default");
            fes_23.X(fys_02);
            fys_02.guy();
            fzv fzv2 = fzv.checkOut();
            fzv2.setElementMap(fhs_22);
            fzv2.setInsets(new Insets(0, 0, 8, 0));
            fys_02.X(fzv2);
            fzv2.guy();
            fzv2.onChildrenAdded();
            String string = "pmbWhite10";
            fkd_1 fkd_12 = fkd_1.checkOut();
            fkd_12.setElementMap(fhs_22);
            if (fhs_22 != null && string != null) {
                fhs_22.a(string, fkd_12);
            }
            fkd_12.setScaled(true);
            fys_02.X(fkd_12);
            fkd_12.guy();
            fze fze2 = fze.checkOut();
            fze2.setElementMap(fhs_22);
            fze2.setHeight(3);
            fze2.setPosition(fzw_0.tKY);
            fze2.setTexture(this.okR.uF("txWhite10Background"));
            fze2.setWidth(3);
            fze2.setX(0);
            fze2.setY(0);
            fkd_12.X(fze2);
            fze2.guy();
            fze2.onChildrenAdded();
            fze fze3 = fze.checkOut();
            fze3.setElementMap(fhs_22);
            fze3.setHeight(1);
            fze3.setPosition(fzw_0.tLf);
            fze3.setTexture(this.okR.uF("txWhite10Background"));
            fze3.setWidth(3);
            fze3.setX(0);
            fze3.setY(16);
            fkd_12.X(fze3);
            fze3.guy();
            fze3.onChildrenAdded();
            fze fze4 = fze.checkOut();
            fze4.setElementMap(fhs_22);
            fze4.setHeight(3);
            fze4.setPosition(fzw_0.tLk);
            fze4.setTexture(this.okR.uF("txWhite10Background"));
            fze4.setWidth(3);
            fze4.setX(0);
            fze4.setY(29);
            fkd_12.X(fze4);
            fze4.guy();
            fze4.onChildrenAdded();
            fze fze5 = fze.checkOut();
            fze5.setElementMap(fhs_22);
            fze5.setHeight(3);
            fze5.setPosition(fzw_0.tLa);
            fze5.setTexture(this.okR.uF("txWhite10Background"));
            fze5.setWidth(1);
            fze5.setX(16);
            fze5.setY(0);
            fkd_12.X(fze5);
            fze5.guy();
            fze5.onChildrenAdded();
            fze fze6 = fze.checkOut();
            fze6.setElementMap(fhs_22);
            fze6.setHeight(1);
            fze6.setPosition(fzw_0.tLg);
            fze6.setTexture(this.okR.uF("txWhite10Background"));
            fze6.setWidth(1);
            fze6.setX(16);
            fze6.setY(16);
            fkd_12.X(fze6);
            fze6.guy();
            fze6.onChildrenAdded();
            fze fze7 = fze.checkOut();
            fze7.setElementMap(fhs_22);
            fze7.setHeight(3);
            fze7.setPosition(fzw_0.tLm);
            fze7.setTexture(this.okR.uF("txWhite10Background"));
            fze7.setWidth(1);
            fze7.setX(16);
            fze7.setY(29);
            fkd_12.X(fze7);
            fze7.guy();
            fze7.onChildrenAdded();
            fze fze8 = fze.checkOut();
            fze8.setElementMap(fhs_22);
            fze8.setHeight(3);
            fze8.setPosition(fzw_0.tLc);
            fze8.setTexture(this.okR.uF("txWhite10Background"));
            fze8.setWidth(3);
            fze8.setX(29);
            fze8.setY(0);
            fkd_12.X(fze8);
            fze8.guy();
            fze8.onChildrenAdded();
            fze fze9 = fze.checkOut();
            fze9.setElementMap(fhs_22);
            fze9.setHeight(1);
            fze9.setPosition(fzw_0.tLh);
            fze9.setTexture(this.okR.uF("txWhite10Background"));
            fze9.setWidth(3);
            fze9.setX(29);
            fze9.setY(16);
            fkd_12.X(fze9);
            fze9.guy();
            fze9.onChildrenAdded();
            fze fze10 = fze.checkOut();
            fze10.setElementMap(fhs_22);
            fze10.setHeight(3);
            fze10.setPosition(fzw_0.tLo);
            fze10.setTexture(this.okR.uF("txWhite10Background"));
            fze10.setWidth(3);
            fze10.setX(29);
            fze10.setY(29);
            fkd_12.X(fze10);
            fze10.guy();
            fze10.onChildrenAdded();
            fkd_12.onChildrenAdded();
            fys_02.onChildrenAdded();
            fes_2 fes_25 = fes_23;
            fys_0 fys_03 = fes_25.getAppearance();
            fys_03.setElementMap(fhs_22);
            fys_03.setState("mouseHover");
            fes_23.X(fys_03);
            fys_03.guy();
            String string2 = "pmbWhite25";
            fkd_1 fkd_13 = fkd_1.checkOut();
            fkd_13.setElementMap(fhs_22);
            if (fhs_22 != null && string2 != null) {
                fhs_22.a(string2, fkd_13);
            }
            fkd_13.setScaled(true);
            fys_03.X(fkd_13);
            fkd_13.guy();
            fze fze11 = fze.checkOut();
            fze11.setElementMap(fhs_22);
            fze11.setHeight(3);
            fze11.setPosition(fzw_0.tKY);
            fze11.setTexture(this.okR.uF("txWhite25Background"));
            fze11.setWidth(3);
            fze11.setX(0);
            fze11.setY(0);
            fkd_13.X(fze11);
            fze11.guy();
            fze11.onChildrenAdded();
            fze fze12 = fze.checkOut();
            fze12.setElementMap(fhs_22);
            fze12.setHeight(1);
            fze12.setPosition(fzw_0.tLf);
            fze12.setTexture(this.okR.uF("txWhite25Background"));
            fze12.setWidth(3);
            fze12.setX(0);
            fze12.setY(16);
            fkd_13.X(fze12);
            fze12.guy();
            fze12.onChildrenAdded();
            fze fze13 = fze.checkOut();
            fze13.setElementMap(fhs_22);
            fze13.setHeight(3);
            fze13.setPosition(fzw_0.tLk);
            fze13.setTexture(this.okR.uF("txWhite25Background"));
            fze13.setWidth(3);
            fze13.setX(0);
            fze13.setY(29);
            fkd_13.X(fze13);
            fze13.guy();
            fze13.onChildrenAdded();
            fze fze14 = fze.checkOut();
            fze14.setElementMap(fhs_22);
            fze14.setHeight(3);
            fze14.setPosition(fzw_0.tLa);
            fze14.setTexture(this.okR.uF("txWhite25Background"));
            fze14.setWidth(1);
            fze14.setX(16);
            fze14.setY(0);
            fkd_13.X(fze14);
            fze14.guy();
            fze14.onChildrenAdded();
            fze fze15 = fze.checkOut();
            fze15.setElementMap(fhs_22);
            fze15.setHeight(1);
            fze15.setPosition(fzw_0.tLg);
            fze15.setTexture(this.okR.uF("txWhite25Background"));
            fze15.setWidth(1);
            fze15.setX(16);
            fze15.setY(16);
            fkd_13.X(fze15);
            fze15.guy();
            fze15.onChildrenAdded();
            fze fze16 = fze.checkOut();
            fze16.setElementMap(fhs_22);
            fze16.setHeight(3);
            fze16.setPosition(fzw_0.tLm);
            fze16.setTexture(this.okR.uF("txWhite25Background"));
            fze16.setWidth(1);
            fze16.setX(16);
            fze16.setY(29);
            fkd_13.X(fze16);
            fze16.guy();
            fze16.onChildrenAdded();
            fze fze17 = fze.checkOut();
            fze17.setElementMap(fhs_22);
            fze17.setHeight(3);
            fze17.setPosition(fzw_0.tLc);
            fze17.setTexture(this.okR.uF("txWhite25Background"));
            fze17.setWidth(3);
            fze17.setX(29);
            fze17.setY(0);
            fkd_13.X(fze17);
            fze17.guy();
            fze17.onChildrenAdded();
            fze fze18 = fze.checkOut();
            fze18.setElementMap(fhs_22);
            fze18.setHeight(1);
            fze18.setPosition(fzw_0.tLh);
            fze18.setTexture(this.okR.uF("txWhite25Background"));
            fze18.setWidth(3);
            fze18.setX(29);
            fze18.setY(16);
            fkd_13.X(fze18);
            fze18.guy();
            fze18.onChildrenAdded();
            fze fze19 = fze.checkOut();
            fze19.setElementMap(fhs_22);
            fze19.setHeight(3);
            fze19.setPosition(fzw_0.tLo);
            fze19.setTexture(this.okR.uF("txWhite25Background"));
            fze19.setWidth(3);
            fze19.setX(29);
            fze19.setY(29);
            fkd_13.X(fze19);
            fze19.guy();
            fze19.onChildrenAdded();
            fkd_13.onChildrenAdded();
            fys_03.onChildrenAdded();
        }
        return fes_23;
    }
}

