/*
 * Decompiled with CFR 0.152.
 */
import java.util.Stack;

/*
 * Renamed from eld
 */
public class eld_1
implements fhh_2 {
    private fhq_2 okR;
    private Stack<fhs_2> nei = new Stack();

    @Override
    public void a(fhs_2 fhs_22, fhq_2 fhq_22, fes_2 fes_22) {
        this.okR = fhq_22;
        this.nei.push(fhs_22);
        fhs_2 fhs_23 = this.nei.peek();
        fes_2 fes_23 = fes_22;
        fzq fzq2 = (fzq)fes_23.getAppearance();
        fzq2.setElementMap(fhs_23);
        fzq2.setAlign(faa_2.tLN);
        fzq2.setState("default");
        fes_22.X(fzq2);
        fzq2.guy();
        fyW fyW2 = fyW.checkOut();
        fyW2.setRenderer(fyw_0.gqw().gqB().uG("fontDefault14Bold"));
        fyW2.setElementMap(fhs_23);
        fzq2.X(fyW2);
        fyW2.guy();
        fyW2.onChildrenAdded();
        fyp_0 fyp_02 = fyp_0.checkOut();
        fyp_02.setElementMap(fhs_23);
        fyp_02.setColor(new fhl_2("defaultDarkGreyColor"));
        fzq2.X(fyp_02);
        fyp_02.guy();
        fyp_02.onChildrenAdded();
        String string = "textEditorLightBorder";
        fkh_1 fkh_12 = new fkh_1();
        fkh_12.aVI();
        fkh_12.setElementMap(fhs_23);
        if (fhs_23 != null && string != null) {
            fhs_23.a(string, fkh_12);
        }
        fzq2.X(fkh_12);
        fkh_12.guy();
        fze fze2 = fze.checkOut();
        fze2.setElementMap(fhs_23);
        fze2.setHeight(4);
        fze2.setPosition(fzw_0.tKY);
        fze2.setTexture(this.okR.uF("themeSimple"));
        fze2.setWidth(4);
        fze2.setX(396);
        fze2.setY(153);
        fkh_12.X(fze2);
        fze2.guy();
        fze2.onChildrenAdded();
        fze fze3 = fze.checkOut();
        fze3.setElementMap(fhs_23);
        fze3.setHeight(4);
        fze3.setPosition(fzw_0.tLa);
        fze3.setTexture(this.okR.uF("themeSimple"));
        fze3.setWidth(20);
        fze3.setX(400);
        fze3.setY(153);
        fkh_12.X(fze3);
        fze3.guy();
        fze3.onChildrenAdded();
        fze fze4 = fze.checkOut();
        fze4.setElementMap(fhs_23);
        fze4.setHeight(4);
        fze4.setPosition(fzw_0.tLc);
        fze4.setTexture(this.okR.uF("themeSimple"));
        fze4.setWidth(4);
        fze4.setX(420);
        fze4.setY(153);
        fkh_12.X(fze4);
        fze4.guy();
        fze4.onChildrenAdded();
        fze fze5 = fze.checkOut();
        fze5.setElementMap(fhs_23);
        fze5.setHeight(7);
        fze5.setPosition(fzw_0.tLh);
        fze5.setTexture(this.okR.uF("themeSimple"));
        fze5.setWidth(4);
        fze5.setX(420);
        fze5.setY(157);
        fkh_12.X(fze5);
        fze5.guy();
        fze5.onChildrenAdded();
        fze fze6 = fze.checkOut();
        fze6.setElementMap(fhs_23);
        fze6.setHeight(3);
        fze6.setPosition(fzw_0.tLo);
        fze6.setTexture(this.okR.uF("themeSimple"));
        fze6.setWidth(4);
        fze6.setX(420);
        fze6.setY(164);
        fkh_12.X(fze6);
        fze6.guy();
        fze6.onChildrenAdded();
        fze fze7 = fze.checkOut();
        fze7.setElementMap(fhs_23);
        fze7.setHeight(3);
        fze7.setPosition(fzw_0.tLm);
        fze7.setTexture(this.okR.uF("themeSimple"));
        fze7.setWidth(20);
        fze7.setX(400);
        fze7.setY(164);
        fkh_12.X(fze7);
        fze7.guy();
        fze7.onChildrenAdded();
        fze fze8 = fze.checkOut();
        fze8.setElementMap(fhs_23);
        fze8.setHeight(3);
        fze8.setPosition(fzw_0.tLk);
        fze8.setTexture(this.okR.uF("themeSimple"));
        fze8.setWidth(4);
        fze8.setX(396);
        fze8.setY(164);
        fkh_12.X(fze8);
        fze8.guy();
        fze8.onChildrenAdded();
        fze fze9 = fze.checkOut();
        fze9.setElementMap(fhs_23);
        fze9.setHeight(7);
        fze9.setPosition(fzw_0.tLf);
        fze9.setTexture(this.okR.uF("themeSimple"));
        fze9.setWidth(4);
        fze9.setX(396);
        fze9.setY(157);
        fkh_12.X(fze9);
        fze9.guy();
        fze9.onChildrenAdded();
        fkh_12.onChildrenAdded();
        String string2 = "shortcutRowFullBackground";
        fkd_1 fkd_12 = fkd_1.checkOut();
        fkd_12.setElementMap(fhs_23);
        if (fhs_23 != null && string2 != null) {
            fhs_23.a(string2, fkd_12);
        }
        fkd_12.setScaled(true);
        fzq2.X(fkd_12);
        fkd_12.guy();
        fze fze10 = fze.checkOut();
        fze10.setElementMap(fhs_23);
        fze10.setHeight(2);
        fze10.setPosition(fzw_0.tKY);
        fze10.setTexture(this.okR.uF("themeSimple"));
        fze10.setWidth(2);
        fze10.setX(2);
        fze10.setY(175);
        fkd_12.X(fze10);
        fze10.guy();
        fze10.onChildrenAdded();
        fze fze11 = fze.checkOut();
        fze11.setElementMap(fhs_23);
        fze11.setHeight(2);
        fze11.setPosition(fzw_0.tLa);
        fze11.setTexture(this.okR.uF("themeSimple"));
        fze11.setWidth(14);
        fze11.setX(4);
        fze11.setY(175);
        fkd_12.X(fze11);
        fze11.guy();
        fze11.onChildrenAdded();
        fze fze12 = fze.checkOut();
        fze12.setElementMap(fhs_23);
        fze12.setHeight(2);
        fze12.setPosition(fzw_0.tLc);
        fze12.setTexture(this.okR.uF("themeSimple"));
        fze12.setWidth(2);
        fze12.setX(18);
        fze12.setY(175);
        fkd_12.X(fze12);
        fze12.guy();
        fze12.onChildrenAdded();
        fze fze13 = fze.checkOut();
        fze13.setElementMap(fhs_23);
        fze13.setHeight(14);
        fze13.setPosition(fzw_0.tLf);
        fze13.setTexture(this.okR.uF("themeSimple"));
        fze13.setWidth(2);
        fze13.setX(2);
        fze13.setY(178);
        fkd_12.X(fze13);
        fze13.guy();
        fze13.onChildrenAdded();
        fze fze14 = fze.checkOut();
        fze14.setElementMap(fhs_23);
        fze14.setHeight(14);
        fze14.setPosition(fzw_0.tLg);
        fze14.setTexture(this.okR.uF("themeSimple"));
        fze14.setWidth(14);
        fze14.setX(4);
        fze14.setY(178);
        fkd_12.X(fze14);
        fze14.guy();
        fze14.onChildrenAdded();
        fze fze15 = fze.checkOut();
        fze15.setElementMap(fhs_23);
        fze15.setHeight(14);
        fze15.setPosition(fzw_0.tLh);
        fze15.setTexture(this.okR.uF("themeSimple"));
        fze15.setWidth(2);
        fze15.setX(18);
        fze15.setY(178);
        fkd_12.X(fze15);
        fze15.guy();
        fze15.onChildrenAdded();
        fze fze16 = fze.checkOut();
        fze16.setElementMap(fhs_23);
        fze16.setHeight(2);
        fze16.setPosition(fzw_0.tLk);
        fze16.setTexture(this.okR.uF("themeSimple"));
        fze16.setWidth(2);
        fze16.setX(2);
        fze16.setY(191);
        fkd_12.X(fze16);
        fze16.guy();
        fze16.onChildrenAdded();
        fze fze17 = fze.checkOut();
        fze17.setElementMap(fhs_23);
        fze17.setHeight(2);
        fze17.setPosition(fzw_0.tLm);
        fze17.setTexture(this.okR.uF("themeSimple"));
        fze17.setWidth(14);
        fze17.setX(4);
        fze17.setY(191);
        fkd_12.X(fze17);
        fze17.guy();
        fze17.onChildrenAdded();
        fze fze18 = fze.checkOut();
        fze18.setElementMap(fhs_23);
        fze18.setHeight(2);
        fze18.setPosition(fzw_0.tLo);
        fze18.setTexture(this.okR.uF("themeSimple"));
        fze18.setWidth(2);
        fze18.setX(18);
        fze18.setY(191);
        fkd_12.X(fze18);
        fze18.guy();
        fze18.onChildrenAdded();
        fkd_12.onChildrenAdded();
        fzq2.onChildrenAdded();
    }
}

