/*
 * Decompiled with CFR 0.152.
 */
public final class WN {
    public static final String bPJ = "themes";
    public static final String bPK = "selectedTheme";
    public static final String bPL = "selectedThemeBaseDirectory";
    public static final String bPM = "useNoTheme";
    public static final String bPN = "themes/config.properties";
    public static final String bPO = "theme.xml";
    public static final String bPP = "theme";
    public static final String bPQ = "theme/colors/colors.xml";
    public static final String bPR = "theme_autoGenerated";
    public static final String bPS = "theme/appSkin/";
    public static final String bPT = "^theme_[\\w-]{1,20}$";
    public static final String bPU = "-";
    public static final String bPV = "theme";
    public static final String bPW = "name";
    public static final String bPX = "author";
    public static final String bPY = "version";
    public static final String bPZ = "wakfuVersion";
    public static final String bQa = "date";
    public static final String bQb = "description";
    public static final int bQc = 30;
    public static final int bQd = 300;

    private WN() {
    }
}

